app/src/main/res/layout/audioplayer_fragment.xml

make layout clickable to intercept touch

---

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/SkipPreferenceDialog.java

Ideally we should inspect all the String.valueOf, these were I could see right now.

Replace some of String.valueOf uses with to String.format to get locale's digits

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Restore ExternalPlayer visibility when restoring instance state

---

app/build.gradle
build.gradle
core/build.gradle

Update WorkManager to latest version

Don't mix android.arch & androidx dependencies

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java
app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java
core/src/main/java/de/danoeh/antennapod/core/service/FeedUpdateWorker.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/java/de/danoeh/antennapod/core/util/download/AutoUpdateManager.java

WorkManager.getInstance() without context is deprecated

---

core/src/main/assets/shownotes-style.css

change webview margin styling to padding

---

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java

Delete crash report on upgrade

---

app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

added media to queue when playing

---

app/src/main/res/layout/feed_item_list_fragment.xml
app/src/main/res/layout/feedinfo.xml
app/src/main/res/layout/nav_listitem.xml
core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java

Closes #4064
- Smaller height of header
- Faster transition
- More blurred background (clear cache to see this)

Theme tweaks

---

.github/ISSUE_TEMPLATE/bug_report.md

Prestissimo is really old. I don't think many people still use it.

Removed mention of Prestissimo from issue template

---

app/src/main/res/layout/external_player_fragment.xml

set max width on external player image

---

app/src/main/res/anim/fade_in.xml
app/src/main/res/anim/fade_out.xml
app/src/main/res/anim/slide_left_in.xml
app/src/main/res/anim/slide_left_out.xml
app/src/main/res/anim/slide_right_in.xml
app/src/main/res/anim/slide_right_out.xml
core/src/main/res/values/integers.xml

Made fragment transition a bit faster

---

core/build.gradle

(cherry picked from commit 356927188738a9d80dfa41e667406f69a744a26f)

fix a lint error

---

app/src/androidTest/java/de/test/antennapod/handler/FeedHandlerTest.java
core/src/play/java/de/danoeh/antennapod/core/cast/CastUtils.java

Fixed feed image tests

---

app/src/main/java/de/danoeh/antennapod/view/PagerIndicatorView.java

In RTL languages such as Persian فارسی this turns
to
(note the disabled dot position which is used for chapter's page)

Fix PagerIndicatorView disabled dot in RTL languages

---

.github/workflows/runTests.sh

Fixed passing CI on AndroidTest failure

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java

Fixed Snackbars being covered by audio player

---

core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java

Do not ANR when calling SyncService.enqueue during sync

---

app/src/androidTest/java/de/test/antennapod/util/FilenameGeneratorTest.java
core/src/main/java/de/danoeh/antennapod/core/util/FileNameGenerator.java

Fixed adding feeds with long filename

---

app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
app/src/main/res/layout/about_teaser.xml
app/src/main/res/layout/audioplayer_fragment.xml
app/src/main/res/layout/cover_fragment.xml
app/src/main/res/layout/episodes_apply_action_fragment.xml
app/src/main/res/layout/external_player_fragment.xml
app/src/main/res/layout/feeditem_fragment.xml
app/src/main/res/layout/feeditemlist_header.xml
app/src/main/res/layout/feeditemlist_item.xml
app/src/main/res/layout/gpodnet_podcast_listitem.xml
app/src/main/res/layout/itunes_podcast_listitem.xml
app/src/main/res/layout/nav_list.xml
app/src/main/res/layout/nav_listitem.xml
app/src/main/res/layout/nav_section_item.xml
app/src/main/res/layout/onlinefeedview_activity.xml
app/src/main/res/layout/searchlist_item.xml
app/src/main/res/layout/simplechapter_item.xml
app/src/main/res/layout/statistics_listitem.xml
core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
core/src/main/res/values/strings.xml

Before:
https://drive.google.com/file/d/12j6tl8AoWRr9AAT4S3I51HYAgLik2gNh/view?usp=sharing
After:
https://drive.google.com/file/d/1CAhv5WTxBwvsY_ibNJ6nJfw2B89WVns7/view?usp=sharing

Improved TalkBack accessibility

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java

Fix http search

---

app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
app/src/main/res/layout/audioplayer_fragment.xml
app/src/main/res/layout/external_player_fragment.xml
app/src/main/res/layout/statistics_listitem.xml
core/src/main/res/values/attrs.xml
core/src/main/res/values/colors.xml
core/src/main/res/values/styles.xml

Also, changed background of miniplayer to separate from list entries.
Closes #4065
Before/After:

Made dark theme darker

---

.github/workflows/android-emulator.yml

This hopefully fixes the retry button for the emulator tests

Updated to checkout/v2

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java

Fixed crash when switching theme

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
CONTRIBUTING.md
app/build.gradle
build.gradle
core/build.gradle
createTranslatorsList.py

I'm terrible at pull request titles, bear with me here.
- Fixed up CONTRIBUTING.md with better English and wording
- Updated links and linked to templates
- Updated templates with some stuff from CONTRIBUTING.md
- Added 1.8.1 to CHANGLOG.md
- Deleted trailing semicolon in python file
- Replace echo with printf in shell script
- Added applicationId to app
- Deleted unused def STRING
- Reorganized versions

Clean up some non-code files

---

app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Various fixes for feeds that do not specify duration

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Fixed enqueueing wrong items on playback

---

core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java

Retry gpodder sync before notifying

---

app/src/main/res/layout/audioplayer_fragment.xml
core/src/main/res/drawable/bg_gradient.xml

I liked the look of the old layout more but it is obviously more important that the seek bar can be grabbed easily.
Closes #4166

Do not resize seekbar to make it easier to grab

---

core/src/main/java/de/danoeh/antennapod/core/util/URLChecker.java

URL schemes are case insensitive

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java
app/src/main/res/layout/itemdescription_listitem.xml
app/src/main/res/layout/onlinefeedview_activity.xml
core/src/main/res/values/strings.xml

Added button to stop previewed episode

---

app/src/main/res/layout/audio_controls.xml
core/src/main/res/values/strings.xml

Fixed wrong translation

---

app/src/main/res/layout/feeditemlist_item.xml
core/src/main/res/values/styles.xml

Fixed new label

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java
core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/res/values/ids.xml

Fixes an issue where the player notification sometimes opened the downloads page
Closes #4201

Unique intents

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java

This is a bit risky but I am running this since a few days and did not notice problems. Because this should fix the phantom notification, I think that it is worth a try
Closes #3398
Closes #2716

Playback service optimizations

---

app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java

Increase contrast of played items

---

app/src/main/res/layout/subscription_item.xml

Increase contrast for missing cover images

---

app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

I hope that this closes #4215 and closes #4085

Send play intent if service state is unknown

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java

Fixed crash when loading chapters fails

---

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java

Detected with LeakCanary:
```
debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.3'
```

Fixed leaking fragments

---

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java

Fixed events delivering to background thread and modifying Views

---

core/src/main/res/values/strings.xml

Rename "Headphones Disconnect" option 

---

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java

This speeds up feed refresh but it is confusing to users if new episodes do not appear instantly.
Closes #4257

Do not cache feeds

---

core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java

Fixed file not found exception after database import

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Users keep ignoring the issue template. This PR tries to make it better by adding checkboxes and reducing the amount of text.

Updated issue templates

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Adds a seekbar which is scrubbable for the media player notification in Android 10 
Closes #3657

Add seekbar to notification

---

app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java

Fixed clicking timecodes

---

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
app/src/androidTest/java/de/test/antennapod/ui/SpeedChangeTest.java
app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java
app/src/main/java/de/danoeh/antennapod/view/ItemOffsetDecoration.java
app/src/main/java/de/danoeh/antennapod/view/PlaybackSpeedSeekBar.java
app/src/main/res/layout/audio_controls.xml
app/src/main/res/layout/audioplayer_fragment.xml
app/src/main/res/layout/playback_speed_seek_bar.xml
app/src/main/res/layout/speed_select_dialog.xml
app/src/main/res/xml/preferences_playback.xml
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
core/src/main/res/values/strings.xml

New playback speed dialog

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
core/src/main/java/de/danoeh/antennapod/core/service/ProviderInstallerInterceptor.java
core/src/main/java/de/danoeh/antennapod/core/service/UserAgentInterceptor.java
core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java

This is pretty ugly but it prevents crashes and issues when streaming (I hope).
Closes #4170 
Related: #4077
cc @Slinger

Install provider in any case

---

app/src/main/res/menu/episodes_apply_action_options.xml
core/src/main/res/values/strings.xml

There is a difference between filter/none and select/none in German. Make it more clear which one this refers to.

Made string name more clear

---

app/src/androidTest/java/de/test/antennapod/handler/RssParserTest.java
core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java

Fixed mime type in media:content

---

app/src/androidTest/java/de/test/antennapod/EspressoTestUtils.java
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/dialog/IconPollDialog.java
core/src/main/res/values/strings.xml

Note: The strings will not be pushed to Transifex.

Added new icon poll

---

app/src/main/java/de/danoeh/antennapod/activity/DownloadAuthenticationActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
core/src/main/java/de/danoeh/antennapod/core/event/DownloadEvent.java
core/src/main/java/de/danoeh/antennapod/core/event/DownloadLogEvent.java
core/src/main/java/de/danoeh/antennapod/core/event/DownloaderUpdate.java
core/src/main/java/de/danoeh/antennapod/core/event/FavoritesEvent.java
core/src/main/java/de/danoeh/antennapod/core/event/FeedItemEvent.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedEvent.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
core/src/main/java/de/danoeh/antennapod/core/glide/ChapterImageModelLoader.java
core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java
core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
core/src/main/java/de/danoeh/antennapod/core/sync/model/EpisodeAction.java
core/src/main/java/de/danoeh/antennapod/core/sync/model/EpisodeActionChanges.java

- I took the effort to add some of the missing annotations (`androidx.annotation.NonNull`, `androidx.annotation.Nullable`) where indicated by Lint. Please note, this does not cover the whole code base.

Add missing @NonNull and @Nullable annotations.

---

app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java

Make mobile streaming dialog easier to understand

---

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java

Dispose loaders before setting controller to null

---

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java

Changes the away that sleep timer reduces the volume so it changes gradually, the minimum volume is still the same and the time needed are still the same so maybe the default values could be revised.
Closes #4295

Smoothier sleep timer

---

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/RunningDownloadsFragment.java
app/src/main/res/menu/downloads_completed.xml
app/src/main/res/menu/downloads_log.xml
app/src/main/res/menu/downloads_running.xml

This adds the refresh button to all three download fragments.
Closes #4055

Add the "Refresh" button on the "Download" page

---

app/src/main/java/de/danoeh/antennapod/fragment/OnlineSearchFragment.java
app/src/main/res/layout/fragment_itunes_search.xml
app/src/main/res/layout/quick_feed_discovery.xml
core/src/main/res/values/strings.xml

Showing "powered by" for search and suggestions

---

app/src/main/java/de/danoeh/antennapod/dialog/FeedFilterDialog.java
app/src/main/java/de/danoeh/antennapod/dialog/FeedSortDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/UserInterfacePreferencesFragment.java
app/src/main/res/menu/subscriptions.xml
app/src/main/res/xml/preferences_user_interface.xml
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/res/values/strings.xml

Add 'sort' to subscriptions view

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

Hide locked message if queue is empty

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java

Continuation of #4409 
Closes #4402

Update skip/forward TextViews of AudioPlayerFragment

---

build.gradle

Upgraded AppCompat to fix WebView crashes

---

app/src/main/java/de/danoeh/antennapod/fragment/DownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java

Fixed pages forgetting scroll position when switching tabs

---

app/src/main/assets/special_thanks.csv
app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/AboutFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/ContributorsPagerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/DevelopersFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/LicensesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/SpecialThanksFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/TranslatorsFragment.java
app/src/main/res/xml/preferences_about.xml
core/src/main/res/values/strings.xml

Provides a way to thank active users who do not code or translate (for example: website design, forum moderators, etc).

Added 'special thanks' screen

---

core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
core/src/main/java/de/danoeh/antennapod/core/service/download/handler/FeedParserTask.java
core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
core/src/main/java/de/danoeh/antennapod/core/util/comparator/FeedItemPubdateComparator.java

Fixed items without pubdate getting assigned the current date on every single refresh

---

app/src/main/res/layout/feeditemlist_item.xml

Fix cropped covers on API <20

---

.circleci/config.yml
app/build.gradle
build.gradle

Target API30

---

core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java

AntennaPod currently checks if a network is metered.
> Cellular networks may be unmetered, or Wi-Fi networks may be metered, so this isn't a good way of selecting a specific transport
> https://developer.android.com/reference/android/app/job/JobInfo#NETWORK_TYPE_METERED
It now checks if a network is metered OR uses cellular.
Closes #4393

Detect network cellular instead of network metered

---

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java

Fixes #4470. Splits up the search query into keywords, so searches are improved.

Improve search feature by using keywords instead of full match

---

app/src/main/res/layout/addfeed.xml
app/src/main/res/layout/audioplayer_fragment.xml
core/src/main/res/values/styles.xml

Fixes #4476. Grouped styling attributes for TextViews in Add Podcast screen into an app style to optimize code.

Added Style for TextViews in Add Podcast screen

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Auto-add label to bug template, expand FR template description, small changes

Improve templates

---

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/res/layout/all_episodes_fragment.xml
app/src/main/res/layout/feed_item_list_fragment.xml
app/src/main/res/layout/fragment_subscriptions.xml
app/src/main/res/values/integers.xml

This adds a swipe to refresh ability to the subscriptions screen.
This is just a sample, how this would work.
The swipe to refresh ability could be added to all ListViews and GridViews, which should be the next step, if this implementation looks fine.
Closes #1797

Use swipe to refresh

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/OnlineSearchFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java

Allow to go back to search results list

---

app/src/main/AndroidManifest.xml

Closes #4371 
I tested it with sndcpy and it works.
I already worked on this some weeks ago without success and I do not know why, the same changes now work.

add allow audio capture

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java

Fixes #4506
The loop takes less than 10 ms, even when reproducing the behavior many times.

Generate unique view IDs

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
core/src/main/res/values/strings.xml

Closes [#4538 ](https://github.com/AntennaPod/AntennaPod/issues/4538)

Style 'Import successful' dialog

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Closes #3398 (hopefully for real, this time)

Load queue in background thread

---

.github/workflows/android-emulator.yml

Looks like emulator tests currently fail regularly. Maybe upgrading helps.

Upgrade Android emulator action

---

app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/res/layout/nav_list.xml

Closes [#4523](https://github.com/AntennaPod/AntennaPod/issues/4523#issuecomment-708601410)

Add progress bar when loading feeds in sidebar

---

app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/res/xml/preferences_user_interface.xml

Fixes for CI failures introduced in recent PRs

---

core/src/main/java/de/danoeh/antennapod/core/storage/DatabaseExporter.java

Add error message when database export does not have enough space

---

core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/java/de/danoeh/antennapod/core/util/gui/NotificationUtils.java
core/src/main/res/values/strings.xml

New channel for synchronization errors

---

core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java

Remove episode from queue when gpodder notifies as played

---

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
app/src/main/res/layout/feeditemlist_item.xml

Fixed played state sometimes not being displayed

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java

Reuse audiofocus request object

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

This prevents crashes when the service is the first entry point after an
update that needs a database upgrade.
Needed for #3974
Maybe even fixes a few ANR errors.

Ensure that first DB query is executed in background thread

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java

Fixed NPEs in bottom sheet

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Only accept media control buttons while actually playing

---

app/src/main/java/de/danoeh/antennapod/view/EmptyViewHandler.java
app/src/main/res/layout/all_episodes_fragment.xml

@ByteHamster  Fixed Issue - 4550. Please review.
Closes #4550

FIXED: Issue - 4550 Episodes page no longer shows empty view

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java

Considers date in metadata or else date in file. Test added.
Fixes #4598

Local feeds: honor file creation date

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java

Sorry if you see repeated commits, i had some trouble with my fork's branches

Local feeds, add successful download log entry

---

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java

Closes [#4599 ](https://github.com/AntennaPod/AntennaPod/issues/4599)

Remove enable autodownload from local feed

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java

Cancel notification updater future before shutting down executor

---

app/src/main/java/de/danoeh/antennapod/fragment/OnlineSearchFragment.java

Fixed crash when searching

---

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/res/menu/subscriptions.xml

Use radio buttons for column number on subscriptions screen

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/res/layout/onlinefeedview_activity.xml
core/src/main/res/values/strings.xml

Continuation of #4504
Closes #4504
Closes #1915

Show "include in auto downloads" checkbox on adding podcast

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
core/src/main/res/values/strings.xml

Apparently, users delete essential system apps.

Add error message when system file manager is not available

---

app/src/main/res/xml/preferences_playback.xml
core/src/main/res/values/arrays.xml
core/src/main/res/values/strings.xml

Add 'recommended' text to ExoPlayer setting

---

app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java

Fixed clear download log menu item

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Fixes a bug introduced in #4591
Fixes #4649
Fixes #4650

Fix using wrong playable object

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java

Hide share link on feed info page for local feeds

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
core/src/main/res/values/strings.xml

Update local folder properties on refresh

---

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java

Use lazy singleton instead of Bill Pugh singleton

---

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java

Added support for showing feed item images on Android Auto

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java

Fixed file size statistics

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java

Stop foreground in DownloadService before calling stop

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java

The expanded media style notification has a higher resolution than
normal large icons
Closes #4694

Increased resolution of notification icon

---

app/src/main/res/layout/quick_feed_discovery.xml

text button at 48dp

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/res/values/strings.xml

Add a nice icon to the queue selection also show the number of episodes

add an icon to the Android Auto queue

---

app/src/main/java/de/danoeh/antennapod/activity/BugReportActivity.java
app/src/main/res/layout/bug_report.xml
app/src/main/res/menu/bug_report_options.xml
core/src/main/res/values/strings.xml

fix #4653 removed button to export logs and reimplemented as a menu option of BugReportActivity. Included confirmation dialog.

Moved export log function to menu and added confirm dialog

---

LICENSE
README.md
app/src/main/assets/licenses.xml
app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java

The issue was opened for two weeks. 10 developers expressed their approval, no one voted against it.
Closes #4685
The license file still needs to include the MIT license.

Relicense under the GPL

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

show pause button, thanks to this question will fix #4707
https://stackoverflow.com/questions/29022062/mediasession-stop-button-vs-pause-button-displayed

pause button for autos

---

app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
app/src/main/java/de/danoeh/antennapod/view/CircularProgressBar.java

Show progress of current chapter

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/AboutFragment.java
app/src/main/res/xml/preferences.xml
app/src/main/res/xml/preferences_about.xml
core/src/main/res/values/strings.xml

With our new website, some of the links have changed. Also, the FAQ is no more.

Correct website links

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java
core/src/main/res/values/strings.xml

Added number to parallel downloads string

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java

Removed unused import

---

core/src/test/java/de/danoeh/antennapod/core/service/download/DownloadRequestTest.java

Run `DownloadRequestTest` with Robolectric outside of emulator.

Run DownloadRequestTest with Robolectric

---

app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java
app/src/main/res/layout/time_dialog.xml
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
core/src/main/res/values/strings.xml

This is a draft PR to add 5 and 10 min sleep timer extend buttons
I haven't done Android development in a while, so please let me know what needs changing.
And also please tell me how you handle translations e.g. on the button. I haven't added the `+5 min` to the strings yet, as I'm not sure how you handle that.

feat: add five, ten and twenty minutes sleep timer extend buttons

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbTasksTest.java

Run `DbTasksTest` with Robolectric outside of the Android emulator.

Run DbTasksTest with Robolectric

---

app/src/main/java/de/danoeh/antennapod/adapter/DownloadlistAdapter.java
core/src/main/res/values/strings.xml

Added content description for download cancel button 

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbNullCleanupAlgorithmTest.java

Tear down database after db cleanup test

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java

Run `DbWriterTest` with Robolectric outside of the Android emulator,
small code changes to make Checkstyle happy

Run DbWriterTest with Robolectric

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java

Will resolve #4830
Details:
When the User Setting for auto downloading of podcasts is enabled, the OnlineFeedView's Include in Auto Downloads checkbox always defaults to true. This change stores the state of the checkbox when we subscribe to a feed, and then uses this as the default value the next time we load the OnlineFeedView.

Include in Auto Downloads checkbox remembers the last used checked state

---

app/src/main/AndroidManifest.xml
app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java

Removed support for opening external video

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
core/src/main/java/de/danoeh/antennapod/core/util/DownloadError.java
core/src/main/res/values/strings.xml

fix #2953 
handle errors with SSL and HTTP Connection errors during download

handle ssl and connection error

---

app/src/main/java/de/danoeh/antennapod/activity/DownloadAuthenticationActivity.java
app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java

I have read somewhere that users have trouble setting the password in feed settings. When entering because of a download, remember the password now.

Remember entered password

---

CONTRIBUTING.md
app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java

When I run `./gradlew :core:testPlayDebugUnitTest`, I'm seeing these errors on my Mac
```
de.danoeh.antennapod.core.storage.DbTasksTest > testAddQueueItemsInDownload_EnqueueEnabled FAILED
java.lang.IllegalArgumentException: resource sqlite4java/osx/libsqlite4java.jnilib not found.
```

tips on running tests when contributing

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/res/layout/feeditemlist_header.xml

Fixes a ClassCastException in FeedItemlistFragment if a FeedItemFilter is set and the last feed update has failed.
I just removed some lines of code causing the cast error that don't seem necessary to me.
**Affected versions:** 2.1.1 and develop branch
**Steps to reproduce:**
1. Add a feed
2. Turn off the internet connection (Wifi + Mobile)
3. Go to the subscriptions page and press the feed update button
4. Go to feed item list, you will see the red message "Last Refresh failed"
5. Set a feed item filter, e.g. "Not played"
6. The activity crashes with a ClassCastException, see below. It's not possible to show the feed item list any more unless the feed update was successful again.
**Stack trace:**
```Java
2021-01-13 21:50:39.449 2903-2903/de.danoeh.antennapod.debug E/ItemlistFragment: …
```

Fix ClassCastException in FeedItemlistFragment

---

core/src/main/res/values/arrays.xml
core/src/main/res/values/strings.xml

close #345 
Built-in Android player and Sonic Media Player no longer supported

Added indication for unsupported players

---

core/src/main/java/de/danoeh/antennapod/core/service/download/NewEpisodesNotification.java

adding forgoten setGroupAlertBehavior as mentioned in https://github.com/AntennaPod/AntennaPod/pull/4646#issuecomment-765544983

add setGroupAlertBehavior to episode notifications.

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/util/ImageResourceUtils.java
core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java

Fixes #4788 
Add error handling for glide image loading

Use podcast image as fallback when episode image returns 404

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java
core/src/main/res/values/strings.xml

According to a translator, the word `hours` is translated differently in `Every x hours` and `Duration: x hours`.

Added new string for 'every x hours'

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbCleanupTests.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbQueueCleanupAlgorithmTest.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbTestUtils.java

Run the following test classes with Robolectric outside of the Android emulator:
- DbReaderTest
- DbCleanupTests
- DbQueueCleanupAlgorithmTest
- DbTestUtils

Run DbReaderTest etc. with Robolectric

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Close #4863
Android auto skip button should always skip regardless of what preferences says because fast forward button is available in the UI

Android auto skip button

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java

Show the publish date next to the title. Based on this [mock](https://github.com/AntennaPod/AntennaPod/issues/1672#issuecomment-743033806) from @keunes 
Closes #1672

Show publish date for podcasts and file creation date for local feeds

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java

Fixed local folder name being set to null

---

app/src/main/java/de/danoeh/antennapod/adapter/DownloadlistAdapter.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java

Related: #4556
Does not fix the issue but apparently makes it appear less often. Also, makes queueing downloads more efficient and cleans up the code a bit.

Clean up DownloadService

---

app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
app/src/androidTest/java/de/test/antennapod/ui/SpeedChangeTest.java
app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java
app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

Reduces probability of #4879 but there is still some duplication going on

More reliable chapter loading

---

core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java
core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3Reader.java
core/src/main/java/de/danoeh/antennapod/core/util/id3reader/model/FrameHeader.java
core/src/main/java/de/danoeh/antennapod/core/util/id3reader/model/TagHeader.java
core/src/test/java/de/danoeh/antennapod/core/util/id3reader/ChapterReaderTest.java
core/src/test/java/de/danoeh/antennapod/core/util/id3reader/Id3ReaderTest.java

Rewrite chapter parser for testability

---

app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java

Don't flicker with nav drawer loading indicator when refreshing

---

core/src/main/res/values/strings.xml

Fixed typo

---

core/src/test/java/de/danoeh/antennapod/core/util/id3reader/ChapterReaderTest.java

Thanks to the Sendegate community!
https://sendegate.de/t/gesucht-beispieldateien-mit-kapitelmarken/13228

Added a real file to test chapter parser with

---

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java

Don't flicker progress bar while refreshing

---

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java

Improve FeedItem class documentation as discussed in #4911.

Improve FeedItem class documentation

---

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

The `getPlayLastPlayedMediaIntent` method was originally added in 2013
to avoid starting the service without a media file. The bind method
should actually never need to start the service in the first place,
though.
This definitely fixes #4835 because it eliminates the code path that triggers the error message but I still need a few more tests to be convinced that it does not break anything. Actually, in the long run, I want to get rid of `PlaybackController` as it couples UI and service too strongly (see #4661).

Fixed rare 'file not found' errors when starting playback

---

app/src/main/AndroidManifest.xml

https://developer.android.com/about/versions/12/behavior-changes-12#exported

Explicitly specify exported attribute for Android 12 compatibility

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java

Removed DbWriter dependency from model

---

app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagListFragment.java

Remove deprecated asynctask from gpodder fragments

---

app/src/main/res/layout/feeditemlist_item.xml

Mark separator icons as not important for talkback #4758

---

build.gradle
core/build.gradle
core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
net/README.md
net/ssl/README.md
net/ssl/build.gradle
net/ssl/src/free/java/de/danoeh/antennapod/net/ssl/SslProviderInstaller.java
net/ssl/src/main/AndroidManifest.xml
net/ssl/src/main/java/de/danoeh/antennapod/net/ssl/BackportCaCerts.java
net/ssl/src/main/java/de/danoeh/antennapod/net/ssl/BackportTrustManager.java
net/ssl/src/main/java/de/danoeh/antennapod/net/ssl/CompositeX509TrustManager.java
net/ssl/src/main/java/de/danoeh/antennapod/net/ssl/NoV1SslSocketFactory.java
net/ssl/src/main/java/de/danoeh/antennapod/net/ssl/SslClientSetup.java
net/ssl/src/play/java/de/danoeh/antennapod/net/ssl/SslProviderInstaller.java
settings.gradle
ui/app-start-intent/build.gradle
ui/common/build.gradle

Moved SSL providers to new module

---

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/RemoteMedia.java

Removed chapter loader from model

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java

More efficient and needs less code :)
Replaces #4969
Contributes to #4661

Replace Java-based feed filtering with SQL-based

---

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
core/src/main/res/values/strings.xml

This is a new request and replaces the old request by the same name.
Fixes #4919

Show podcast-specific settings in preferences search

---

app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java

Fix regression: flashing progress bar

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java

Fixed download service regressions

---

app/src/main/java/de/danoeh/antennapod/view/ChapterSeekBar.java

Make buffering indicator a bit less visible

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java

Stop playback of deleted podcast even if it is just streaming

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/res/layout/audioplayer_fragment.xml

Fixed clicks going through the player

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Clear temporary playback speed when switching to another episode

---

app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagFragment.java

Stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
at de.danoeh.antennapod.fragment.gpodnet.TagFragment.onActivityCreated(TagFragment.java:49)
at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
at …

Fix crash when selecting gpodder.net category

---

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
core/src/main/java/de/danoeh/antennapod/core/storage/NavDrawerData.java

Fixed animation when hiding drawer items

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Minor template updates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Reverts AntennaPod/AntennaPod#5021
The syntax is not actually a comment syntax.

Revert "Minor template updates"

---

CONTRIBUTING.md

Address this forum post https://forum.antennapod.org/t/facing-issues-while-building-antennapod-in-android-studio/754/3

how to build from source

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java

Fix crash when resuming while there is no playable

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/RemoteMedia.java
core/src/play/java/de/danoeh/antennapod/core/cast/CastUtils.java

Better metadata for previewed episodes

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Fixed miniplayer state sometimes being wrong

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
core/src/main/res/values/strings.xml

Rename audio player tabs

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
app/src/main/res/xml/preferences.xml
core/src/main/res/drawable/ic_contribute_black.xml
core/src/main/res/drawable/ic_contribute_white.xml
core/src/main/res/values/attrs.xml
core/src/main/res/values/strings.xml
core/src/main/res/values/styles.xml

Fixes #4975, Add Contribute entry to settings screen under 'Project'

Add Contribute entry to settings screen under 'Project'

---

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

Update play icon when service is stopped

---

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java

Backport: Add missing synchronized keyword

---

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
core/src/main/res/values/strings.xml

Add link to relevant settings screen in 'Episode cache full' dialog 

---

core/src/main/java/de/danoeh/antennapod/core/feed/SubscriptionsFilter.java
core/src/main/java/de/danoeh/antennapod/core/feed/SubscriptionsFilterGroup.java
core/src/main/res/values/strings.xml

Add filtering subscriptions based on new episodes notification setting

---

app/src/main/res/layout/audioplayer_fragment.xml

Fixed tab flickering

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
app/src/main/res/layout/queue_fragment.xml

Fixes #5022 
Added swipe/pull to refresh functionality to the Queue screen. 
**Changes made**: `SwipeRefreshLayout` listener added in the method `onCreateView()` of class `QueueFragment.java`. Additionally, layout changes done in file `queue_fragment.xml`.

Adds pull to refresh functionality on Queue screen

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/view/ChapterSeekBar.java
app/src/main/res/layout/audioplayer_fragment.xml

This adds the possibility to change the current chapter by tapping on the corresponding area on the seek bar as proposed in #4898. In addition, the current chapter title will be shown in the popup for the current playback time while seeking.

Chapter controls for the seek bar

---

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/view/PlayButton.java
app/src/main/res/drawable/ic_animate_pause_play.xml
app/src/main/res/drawable/ic_animate_play.xml
app/src/main/res/drawable/ic_animate_play_pause.xml
app/src/main/res/layout/audioplayer_fragment.xml
app/src/main/res/layout/external_player_fragment.xml
app/src/main/res/layout/videoplayer_activity.xml
app/src/main/res/values/svg.xml
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

I spent too many hours getting this useless animation to work. See gif below :D
Also, closes #5091

Play button animation

---

app/src/main/java/de/danoeh/antennapod/view/ChapterSeekBar.java

This should fix the issue with the height of the seek bar, mentioned in #5017. As far as I can tell, it occurs with SDK versions < 23.

Fix for the height issue of the seek bar

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/res/layout/alternate_urls_dropdown_item.xml
app/src/main/res/layout/alternate_urls_item.xml
app/src/main/res/layout/onlinefeedview_activity.xml

Wrap long text in alternate version dropdown

---

.circleci/config.yml
app/build.gradle
app/lint.xml
core/build.gradle
core/src/main/res/drawable/ic_fab_edit_black.xml
core/src/main/res/values-large/dimens.xml
core/src/main/res/values/dimens.xml
core/src/main/res/values/strings.xml
net/ssl/build.gradle
ui/app-start-intent/build.gradle
ui/common/build.gradle

- Fixed not linting everything on CI
- Fixed commit hash in new Android Studio
- Removed unused translations and resources

Lint fixes

---

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/java/de/danoeh/antennapod/core/util/FeedItemUtil.java

Reduce dependencies of model to UserPreferences

---

core/src/main/java/de/danoeh/antennapod/core/feed/Chapter.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/mapper/ChapterCursorMapper.java
core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedCursorMapper.java
core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedItemCursorMapper.java
core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedMediaCursorMapper.java
core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedPreferencesCursorMapper.java

Moved cursor related code out of model

---

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java

Decouple FeedMedia and sync service

---

app/src/main/java/de/danoeh/antennapod/dialog/TagSettingsDialog.java

Especially when creating multiple tags manually, I often forgot to press the "plus" button for the last one.

Automatically add tag when pressing OK

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java

While seeking and holding a bit on one point with a playing episode, the thumb tries to jump back to its original position. This should fix it.

Jumping thumb while seeking

---

app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java

Fixed NPE in ExternalPlayerFragment

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/view/ChapterSeekBar.java

This fixes issues of the seek bar, mentioned in #4915
I'm not sure about the third one. In my testing, the seeking worked every time (the same as via the chapters page). The only thing that was a bit strange is the highlighting, but I'm not sure (yet) how to solve that.

Seek bar issues

---

app/src/main/java/de/danoeh/antennapod/dialog/ProxyDialog.java
core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java

Fixed proxy support

---

app/build.gradle
build.gradle
common.gradle
core/build.gradle
model/build.gradle
net/ssl/build.gradle
net/sync/gpoddernet/build.gradle
net/sync/model/build.gradle
playFlavor.gradle
ui/app-start-intent/build.gradle
ui/common/build.gradle
ui/png-icons/build.gradle

Original idea by @TacoTheDank, see #5110

Move common gradle setup to a single file

---

core/src/test/java/de/danoeh/antennapod/core/service/download/DownloadRequestTest.java

Test case that covers the previously untested DownloadRequest.equals method.

Add new test for Download Request equals

---

core/src/test/java/de/danoeh/antennapod/core/util/FeedItemUtilTest.java

Added new test case for FeedItemUtil.java. Tested the getIds() method to ensure the ids were printed out along with the edge cases.

Added new test case for FeedItemUtil.java to test getIds() method

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java

Add a unit test testRemoveAllNewFlags to cover the method removeAllNewFlags() under DBWriter.java to improve the code coverage.

Add a unit test under DbWriterTest.java

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java

Let test wait until database operation is completed

---

app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java

fixes https://github.com/AntennaPod/AntennaPod/issues/5218

copy e-mail

---

core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java
core/src/main/res/layout/player_widget.xml
ui/png-icons/src/main/res/drawable/ic_widget_fast_forward.xml
ui/png-icons/src/main/res/drawable/ic_widget_fast_rewind.xml
ui/png-icons/src/main/res/drawable/ic_widget_pause.xml
ui/png-icons/src/main/res/drawable/ic_widget_play.xml
ui/png-icons/src/main/res/drawable/ic_widget_skip.xml

Widgets don't work with vector drawables. Create a copy in `ui/png-icons`, so they are converted at compile time.

Fix widget not showing icons

---

app/src/main/java/de/danoeh/antennapod/dialog/TagSettingsDialog.java
app/src/main/res/layout/edit_tags_dialog.xml
app/src/main/res/layout/single_tag_text_view.xml

Allow to choose from existing tags/folders in folder settings dialog

---

core/src/main/java/de/danoeh/antennapod/core/util/download/AutoUpdateManager.java

Ignore refresh when there is no network

---

core/src/main/res/drawable/ic_web.xml

Updated website icon

---

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

End select mode when page is closed

---

app/src/main/res/menu/feeditemlist_context.xml

Removed 'visit website' context menu item

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java

close #5273
Be more careful validating whether an item has non-NULL `getmedia()`

watch for empty getMedia() while checking for duplicates

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

Fix swipe refresh not working on empty queue

---

.github/workflows/android-emulator.yml

See https://github.com/ReactiveCircus/android-emulator-runner/issues/168

Fix Emulator CI

---

core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java

Fix crash when a server returns a null location

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
core/src/main/res/values/strings.xml

See https://twitter.com/Quietlyhere123/status/1419016750813773824

Updated service shutting down text because it could be scary

---

app/src/main/res/layout/episode_filter_dialog.xml
app/src/main/res/layout/subscription_item.xml

- [Notes](https://developer.android.com/reference/android/view/ViewGroup.LayoutParams#FILL_PARENT)

Fix deprecated fill_parent attributes

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/StoragePreferencesFragment.java
app/src/main/res/xml/preferences_storage.xml
core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/res/values/arrays.xml
core/src/main/res/values/strings.xml

Remove image cache size setting and choose size automatically

---

app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
app/src/main/res/layout/audio_controls.xml
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
core/src/main/res/values/strings.xml

The setting does not work in our default player anyway and just
clutters the interface with yet another setting that nobody uses.

Removed left/right volume controls

---

app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java

Fix crash when setting sleep timer to zero

---

.github/ISSUE_TEMPLATE/bug_report.md

So automatic tagging works again

Update bug tag

---

app/src/main/AndroidManifest.xml
core/src/main/java/de/danoeh/antennapod/core/util/URLChecker.java
core/src/test/java/de/danoeh/antennapod/core/util/URLCheckerTest.java

Support subscribing with links like https://antennapod.org/deeplink/subscribe/?url=abc
See also https://forum.antennapod.org/t/how-do-i-give-a-link-to-my-podcast-on-antennapod/1199/

Add subscription deeplink

---

core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3Reader.java

See https://forum.antennapod.org/t/chapter-marks-documentation/1193

Skip id3 extended header if available

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java

Old behavior was to still show the old one but still start the next one when pressing play.

When continuous playback is disabled, show next episode in notification

---

core/src/main/res/values/styles.xml

Disable multi-touch

---

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/res/values/integers.xml

Make Accidental Pull Down Refresh less likely

---

app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/res/menu/nav_feed_context.xml
core/src/main/res/values/strings.xml

Fix: #5298 "Add to folder" in podcast contextual side menu

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
core/src/main/java/de/danoeh/antennapod/core/sync/EpisodeActionFilter.java
core/src/main/java/de/danoeh/antennapod/core/sync/GuidValidator.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/play/java/de/danoeh/antennapod/core/cast/CastUtils.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java
core/src/test/java/de/danoeh/antennapod/core/sync/EpisodeActionFilterTest.java
core/src/test/java/de/danoeh/antennapod/core/sync/GuidValidatorTest.java
net/sync/model/src/main/java/de/danoeh/antennapod/net/sync/model/EpisodeAction.java

Identify episodes by guid

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java

Fix NPE in duplicate detection

---

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/res/menu/nav_feed_context.xml

Multi-select fixes

---

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java

Fix wrong fragment receiving context menu event

---

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java

This is a bit hacky but it fixes #5401

End select mode when the number of items got smaller

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

Allow connecting to pages signed with user CA

---

app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/gpoddernet/GpodnetService.java

Human-readable gpodder error message

---

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java

Fix seeking while paused

---

app/src/main/AndroidManifest.xml
app/src/main/java/de/danoeh/antennapod/discovery/ItunesPodcastSearcher.java

Open Apple podcast urls

---

core/src/main/java/de/danoeh/antennapod/core/util/FeedItemPermutors.java

Sort queue in dictionary order

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java

Use data folder for initial subscriptions

---

.github/workflows/android-emulator.yml
app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java
common.gradle
core/src/main/java/de/danoeh/antennapod/core/service/download/NewEpisodesNotification.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java
ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/MainActivityStarter.java
ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/VideoPlayerActivityStarter.java

Declare intent mutability for Android 12 compatibility

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

Queue lock now no longer influences swiping

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/res/drawable/ic_download_black.xml

Show list of downloads on Android Auto

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java

Remember password when adding new feed

---

app/src/main/AndroidManifest.xml

Make opml intent filter more strict

---

app/src/main/java/de/danoeh/antennapod/receiver/ConnectivityActionReceiver.java
core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java

Don't use metered networks for auto download

---

core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java
core/src/main/java/de/danoeh/antennapod/core/glide/NoHttpStringLoader.java

Fix loading cover images on mobile when not allowed

---

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java
parser/feed/src/test/java/de/danoeh/antennapod/parser/feed/element/namespace/RssParserTest.java
parser/feed/src/test/resources/feed-rss-testUnsupportedElements.xml

Ignore item tags that are not inside a channel

---

app/src/main/AndroidManifest.xml

Register as music app

---

core/src/main/java/de/danoeh/antennapod/core/util/URLChecker.java
core/src/test/java/de/danoeh/antennapod/core/util/URLCheckerTest.java

Support subscribe links that have a slash before the argument

---

core/build.gradle
core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java

Use OkHttp as backend for ExoPlayer

---

app/src/main/java/de/danoeh/antennapod/adapter/PlaybackStatisticsListAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedStatisticsDialogFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedStatisticsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackStatisticsFragment.java
app/src/main/res/layout/feed_statistics.xml
app/src/main/res/layout/feed_statistics_dialog.xml
app/src/main/res/layout/feedinfo.xml
core/src/main/res/values/strings.xml

Show more detailed feed statistics

---

app/src/main/AndroidManifest.xml
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/activity/SelectSubscriptionActivity.java
app/src/main/res/layout/subscription_selection_activity.xml
core/src/main/res/values/strings.xml

Add subscription to home screen

---

app/src/main/res/xml/provider_paths.xml
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/TypeGetter.java

Two small possible fixes for crashes shown on Google Play. See commit messages for details.

Mini fixes

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java

Possible fix for #5446. Might even help against #4458

Remove all media listeners and end audio focus when shutting down playback service

---

build.gradle

Upgrade Conscrypt

---

core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java

Respect remaining time setting in widget

---

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java

Fix CoverFragment crashing when showing RemoteMedia

---

app/src/main/res/layout/fragment_subscriptions.xml
app/src/main/res/layout/subscription_selection_activity.xml
app/src/main/res/layout/time_dialog.xml

Fixed a few paddings

---

app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/SwipeActions.java

Fix #4844
See references to the values I'm changing
https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/ItemTouchHelper.Callback#getswipeescapevelocity

Make it slightly harder to swipe episodes

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java

Don't reload image when download status changes

---

core/src/main/java/de/danoeh/antennapod/core/sync/GuidValidator.java

Was already fixed on the develop branch but is worth a backport to 2.4
Closes #5561

Backport null guid sync errors

---

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java
app/src/main/res/layout/subscription_item.xml

https://forum.antennapod.org/t/app-crashed/1511

Fix crash on API 21 when showing subscriptions screen

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java

Do not crash when opening chapter dialog twice

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Remove new flag when streaming

---

app/src/main/java/de/danoeh/antennapod/dialog/TagSettingsDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/actions/FeedMultiSelectActionHandler.java
app/src/main/res/layout/edit_tags_dialog.xml
app/src/main/res/menu/nav_feed_action_speeddial.xml
core/src/main/res/values/strings.xml

Add 'add to tag' option to multiselect menu

---

app/src/main/AndroidManifest.xml
app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
common.gradle
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/util/StorageUtils.java
core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java
core/src/main/res/layout/player_widget.xml
core/src/main/res/values/strings.xml

This PR removes support for old Android versions (released more than 8 years ago). Affects about 0.4% of our Google Play users.
The change is necessary for #5518, which is in turn necessary for continuing to develop the app starting next year (see #4930).

Bump to minimum SDK version 19 (Android 4.4)

---

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java

When deleting a feed, instead of deleting all its items and media files one-by-one, execute a single database call that deletes all of them. This reduces the database stress significantly because it now only needs one pass over the file.
Test case: Debug version, database export with 126 subscriptions. Using multi-select to delete all subscriptions.
Before: 3 minutes, 36 seconds
After: 1 minute, 16 seconds

Make feed deletions 3 times faster

---

core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java

I regularly have to restart the CI because of this test

Make queue removal test more stable

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java

Don't try to sync local folders

---

app/src/main/java/de/danoeh/antennapod/fragment/actions/EpisodeMultiSelectActionHandler.java
core/src/main/res/values/strings.xml

Simplify confusing string with two plurals

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java

Related: https://forum.antennapod.org/t/whos-wrong-antenna-or-guardian/1573

Print more episode details in error message

---

app/src/main/java/de/danoeh/antennapod/dialog/ShareDialog.java
app/src/main/res/layout/share_episode_dialog.xml
core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
core/src/main/res/values/strings.xml

Combine 'Episode webpage' & 'Media file address' share options

---

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackServiceStarter.java
model/src/main/java/de/danoeh/antennapod/model/playback/Playable.java

Fix crash when share dialog tries to serialize FeedMedia

---

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java
core/src/main/java/de/danoeh/antennapod/core/util/InputUtils.java

fix #5574 
Handle mouse right click for Android M and up, otherwise, protect for null

handle mouse right click

---

app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
config/checkstyle/checkstyle.xml
config/checkstyle/suppressions.xml
core/src/main/java/de/danoeh/antennapod/core/backup/OpmlBackupAgent.java
core/src/main/java/de/danoeh/antennapod/core/export/CommonSymbols.java
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/test/java/android/util/Log.java

Since the rules were created, most of the occurrences have been fixed in other PRs

Move more checkstyle checks from 'new code' style to main style

---

.github/workflows/checks.yml
.github/workflows/runEmulatorTests.sh
app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java
parser/media/build.gradle
parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentReader.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/id3/ChapterReaderTest.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/id3/Id3ReaderTest.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentChapterReaderTest.java

Apparently, we have been skipping some unit tests since a few months. Make sure that all are actually run and fix the problems the tests were supposed to catch.

Actually run all tests on CI

---

.github/workflows/close-if-no-reply.yml

Awaiting https://github.com/actions/stale/issues/654

Close issues & PRs if no reply when requested

---

core/src/main/java/de/danoeh/antennapod/core/feed/ChapterMerger.java
parser/media/src/main/java/de/danoeh/antennapod/parser/media/id3/ChapterReader.java

See https://forum.antennapod.org/t/episode-picture-not-shown/1650

Improvements to chapter merging

---

parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentReader.java

Do not hang trying to parse ogg/vorbis chapters

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
model/src/main/java/de/danoeh/antennapod/model/playback/MediaType.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Atom.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Media.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/MimeTypeUtils.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/SyndTypeUtils.java

See https://github.com/AntennaPod/AntennaPod/issues/4404#issuecomment-1020563275

When mime type is octet-stream, guess from the file name

---

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/MimeTypeUtils.java

See https://forum.antennapod.org/t/add-support-for-m4b-files/1669

Manually detect m4b on devices that don't do it

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java

Tested. Behavior is the same as before.

Fix clipboard deprecation in AddFeedFragment

---

.github/workflows/close-if-no-reply.yml

I also changed the time to 30 days instead of 20 to not stress people too much

Send message to stale issues/PRs

---

app/src/main/java/de/danoeh/antennapod/dialog/ProxyDialog.java
core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
core/src/main/java/de/danoeh/antennapod/core/service/download/ProxyConfig.java

And if it gets null, just ignore the setting.
I guess this was caused by #5471
Fixes #5697 and probably also #5693

Make sure that proxy host name does not get null

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java

Otherwise, it can happen that a task in one executor still tries to
submit something to a stopped executor.

Shutdown download executors properly

---

app/build.gradle
common.gradle
core/build.gradle
event/build.gradle
model/build.gradle
net/ssl/build.gradle
net/sync/gpoddernet/build.gradle
net/sync/model/build.gradle
parser/feed/build.gradle
parser/media/build.gradle
playback/base/build.gradle
playback/cast/build.gradle
ui/app-start-intent/build.gradle
ui/common/build.gradle
ui/png-icons/build.gradle

Companion PR to https://github.com/AntennaPod/AntennaPod/pull/5655 to make that one smaller. These are deprecations that already exist under 4.2, so they can be fixed right now.

Fix some gradle deprecations

---

app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
app/src/main/res/layout/audio_controls.xml

…_controls.xml
I think I got it this time, I removed ONLY the speed thing from the audio controls.
Closes #5686

Removed the speed indicator from the PlaybackControlsDialog

---

app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java

Shrink discovery section when hidden

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/actions/FeedMultiSelectActionHandler.java
app/src/main/res/menu/feedlist.xml
app/src/main/res/menu/nav_feed_action_speeddial.xml

remove_item referred to both, feeds and media files. Sometimes the wrong
fragment receives the context menu click event.
Closes #5730

Fix side drawer detecting click on 'remove item'

---

app/src/androidTest/java/de/test/antennapod/storage/AutoDownloadTest.java
app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java
app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayActionButton.java
app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayLocalActionButton.java
app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java
app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackServiceStarter.java

They are always `true` anyway.

Remove startWhenPrepared and prepareImmediately

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Reset position when skipping and 'smart mark as played'

---

app/src/main/java/de/danoeh/antennapod/dialog/DownloadLogDetailsDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java

Show feed error in dialog instead of opening download log screen

---

app/src/main/java/de/danoeh/antennapod/adapter/YearStatisticsListAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/StatisticsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/SubscriptionStatisticsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/YearsStatisticsFragment.java
app/src/main/java/de/danoeh/antennapod/view/LineChartView.java
app/src/main/res/layout/statistics_listitem_linechart.xml
app/src/main/res/layout/statistics_year_listitem.xml
core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
core/src/main/res/values/strings.xml

Add line graph to statistics screen

---

core/src/main/res/values/styles.xml

Fix subscribe button being transparent on some devices

---

net/sync/gpoddernet/build.gradle
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/HostnameParser.java
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudLoginFlow.java
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudSyncService.java
net/sync/gpoddernet/src/test/java/de/danoeh/antennapod/net/sync/HostnameParserTest.java

Thanks for the test account @markcs! This will either land in 2.5.1 (if there are additional bugs that make an update necessary) or in 2.6.0
Closes #5748

Support Nextcloud installations in subfolders

---

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java

Do not jump chapter screen when switching to new chapter

---

app/build.gradle

Use AndroidX version of MultiDex

---

event/src/main/java/de/danoeh/antennapod/event/StatisticsEvent.java
ui/common/src/main/java/de/danoeh/antennapod/ui/common/PagedToolbarFragment.java
ui/i18n/src/main/res/values/strings.xml
ui/statistics/build.gradle
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/StatisticsFragment.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/PlaybackStatisticsListAdapter.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/StatisticsFilterDialog.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/SubscriptionStatisticsFragment.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/years/YearsStatisticsFragment.java
ui/statistics/src/main/res/layout/statistics_filter_dialog.xml

Suggestion by @keunes in #5734

Make 'to' filter of statistics inclusive

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
parser/media/src/main/java/de/danoeh/antennapod/parser/media/id3/Id3MetadataReader.java

Extract shownotes from id3 comment field

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java

I noticed this while working on #5780.

Small change to improve code readability

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentChapterReader.java
parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentMetadataReader.java
parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentReader.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/id3/MetadataReaderTest.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentChapterReaderTest.java
parser/media/src/test/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentMetadataReaderTest.java

Second half of #5256
cc @DrMcCoy

Read vorbis description of local files

---

app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java

Don't cancel download on click

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java

Previously "OPML export" was used as subject in the Share Intent, even when "HTML export" or "Favorites export" was selected. This change fixes that and also changes the Share Intent to use the proper content type (either `text/x-opml` or `text/html`).

Use proper content type and subject when sharing exported HTML/Favorites

---

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java
app/src/main/res/menu/nav_feed_context.xml
core/src/main/java/de/danoeh/antennapod/core/menuhandler/MenuItemUtils.java

Fix context menu handling

---

core/src/main/res/values-v23/styles.xml

This should effectively close #5797.

Fix navigation bar theming on Nougat (closes #5797)

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java

Updating local files takes long. Show progress.

---

core/src/main/java/de/danoeh/antennapod/core/util/download/AutoUpdateManager.java
core/src/main/res/values/strings.xml

Maybe that makes it easier for some users.
Closes #5790

Add button to always refresh over mobile data

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java

Fix full sync trying to handle local feeds

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Fix UI not updating when forwarding while paused

---

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java

- Make code easier to read
- Fall back to internal memory when folder is not writable

Rewrite data folder creation

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/res/layout-sw720dp/main.xml
app/src/main/res/layout/audioplayer_fragment.xml
app/src/main/res/layout/main.xml

I found some more things that should be replaced with FragmentContainerView.
Tested on an Android 10 device.

Use more FragmentContainerView

---

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java

Upgrade feed url to https if possible

---

README.md

As discussed at the latest community call.

Add link to community call in readme

---

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java

Fix 'loading more' getting stuck

---

app/src/main/java/de/danoeh/antennapod/view/TimePicker.java
app/src/main/res/layout/feed_refresh_dialog.xml

https://forum.antennapod.org/t/app-crashes-network/1922

Work around Samsung having messed up the TimePicker

---

app/src/androidTest/java/de/test/antennapod/dialogs/ShareDialogTest.java
app/src/main/java/de/danoeh/antennapod/dialog/ShareDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
app/src/main/res/layout/share_episode_dialog.xml
app/src/main/res/menu/feedinfo.xml
app/src/main/res/menu/feeditem_options.xml
app/src/main/res/menu/feedlist.xml
app/src/main/res/menu/mediaplayer.xml
core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
ui/i18n/src/main/res/values/strings.xml

Restore episode sharing that only includes a media URL

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
app/src/main/res/layout/feed_item_list_fragment.xml
app/src/main/res/layout/feedinfo.xml
app/src/main/res/layout/feeditemlist_header.xml
app/src/main/res/menu/feedlist.xml
core/src/main/res/drawable/ic_filter_white.xml
core/src/main/res/drawable/ic_rounded_corner_left.xml
core/src/main/res/drawable/ic_rounded_corner_right.xml
core/src/main/res/drawable/ic_sort.xml
core/src/main/res/values/attrs.xml
core/src/main/res/values/styles.xml

See https://forum.antennapod.org/t/make-podcast-specific-settings-easier-to-discover/1720
Before/After:

Podcast page re-design

---

.github/workflows/checks.yml
.github/workflows/close-if-no-reply.yml

Changelogs:
- https://github.com/actions/checkout/releases
- https://github.com/actions/cache/releases
- https://github.com/actions/upload-artifact/releases
- https://github.com/actions/setup-java/releases
- https://github.com/actions/stale/releases

Update action dependencies in workflows

---

app/src/main/res/layout/activity_widget_config.xml

Somehow we ended up having hard coded strings here...

Translate widget config screen

---

app/src/main/java/de/danoeh/antennapod/dialog/ProxyDialog.java
core/src/main/java/de/danoeh/antennapod/core/ClientConfig.java
core/src/main/java/de/danoeh/antennapod/core/service/BasicAuthorizationInterceptor.java
core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpCredentialEncoder.java
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java

Remove dependencies:
- HttpClient->Preferences
- AuthorizationInterceptor->Download Service
- ExoPlayer->Download Service
Contributes to #4661

Decouple HttpClient

---

app/src/main/java/de/danoeh/antennapod/dialog/SwipeActionsDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/SwipeAction.java
app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/SwipeActions.java
app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/TogglePlaybackStateSwipeAction.java
ui/i18n/src/main/res/values/strings.xml

See https://forum.antennapod.org/t/change-swipe-gestures-remove-new-tag-then-mark-as-played-then-unplayed/1953

Invert behavior of playback state swipe action to first remove from inbox

---

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java

Before, it sometimes resized the grid but not the actual covers

Fix column change on subscriptions screen

---

ui/i18n/src/main/res/values/strings.xml
ui/statistics/build.gradle
ui/statistics/src/main/res/layout/feed_statistics.xml

Show spinner while loading statistics

---

app/src/main/java/de/danoeh/antennapod/activity/SplashActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java
app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java

I fixed some deprecations. That's all, really.

Fix some deprecations

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java

Fix 'load more' not detecting next page

---

app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
app/src/main/res/menu/mediaplayer.xml

It got lost when removing the speed bar from the audio controls dialog

Add speed dialog to video player

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Don't recreate activity when a result is pending

---

build.gradle
common.gradle
core/src/main/java/de/danoeh/antennapod/core/util/syndication/FeedDiscoverer.java
core/src/main/java/de/danoeh/antennapod/core/util/syndication/HtmlToPlainText.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/TypeGetter.java

From here: https://github.com/AntennaPod/AntennaPod/pull/5655
Updated jsoup 1.11.2 -> 1.15.1 ([changelog](https://jsoup.org/news/))
Tested on an Android 10 device. Feed loading and discovery works.

Update jsoup library

---

app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java

Fix placeholder image sometimes missing

---

app/src/main/res/layout/feeditemlist_header.xml

See https://forum.antennapod.org/t/app-crash-android-4-4-4/2086

Fix crash on Android 4.4

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/synchronization/GpodderAuthenticationFragment.java
app/src/main/res/layout/gpodnetauth_credentials.xml
app/src/main/res/layout/gpodnetauth_host.xml
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/gpoddernet/GpodnetService.java
ui/i18n/src/main/res/values/strings.xml

You can still type in the url of the official server if you somehow manage to register.
Closes #5944

Remove default gpodder sync server

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java

See https://forum.antennapod.org/t/protected-feed-not-working/2080

Do not forget feed password when subscribing

---

app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java

Fix importing multiple authenticated feeds

---

app/build.gradle
app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java
app/src/main/res/layout/subscription_item.xml
ui/common/src/main/java/de/danoeh/antennapod/ui/common/TriangleLabelView.java
ui/common/src/main/res/values/attrs.xml

Part of #5925.
I also cleaned up a bunch of stuff in TriangleLabelView we don't use (like the secondary text, bottom corners, etc.).
Installed and tested. Visually identical.

Integrate TriangleLabelView library locally into project

---

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java

Supports all lists except "all episodes" list because that one still
displays tabs. Can be added as soon as the tabs are no longer required.
Contributes to #5934

Scroll to top by long-pressing toolbar

---

app/src/debug/res/values/strings.xml
app/src/main/res/values/strings.xml
common.gradle
ui/i18n/src/main/res/values/strings.xml

Resolve app_name in common.gradle

---

core/src/main/java/de/danoeh/antennapod/core/receiver/PlayerWidget.java

Work around widget flickering

---

app/src/main/res/layout/feeditemlist_item.xml

Remove empty space next to inbox icon

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
app/src/main/res/xml/preferences.xml
ui/i18n/src/main/res/values/strings.xml

Add statistics moved message

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
app/src/main/res/layout/feeditem_fragment.xml

Use circular progress bar on ItemFragment

---

app/src/main/res/xml/preferences.xml

Fix chart icon having been renamed

---

net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudLoginFlow.java

Fix NextCloud retrying without delay

---

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
app/src/main/res/layout/episodes_list_fragment.xml
model/src/main/java/de/danoeh/antennapod/model/feed/FeedItemFilter.java

- Allow all multi-select actions
- Update star icon and let it toggle only one aspect of the filter
- Make filter info bar clickable

Tweak 'all episodes' screen

---

app/src/main/res/layout/audioplayer_fragment.xml
core/src/main/res/drawable/ic_arrow_down.xml

Use downwards arrow icon to close player screen

---

app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java

When multiple funding tags reference the same URL, display the one with longer title

---

.github/workflows/runEmulatorTests.sh
app/src/main/AndroidManifest.xml
app/src/main/java/de/danoeh/antennapod/activity/SelectSubscriptionActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
app/src/main/res/xml/shortcuts.xml
core/src/main/res/drawable-anydpi-v26/ic_subscriptions_shortcut.xml
core/src/main/res/drawable/ic_folder_black.xml
core/src/main/res/drawable/ic_subscriptions.xml
core/src/main/res/drawable/ic_subscriptions_black.xml
core/src/main/res/drawable/ic_subscriptions_shortcut.xml

Change subscriptions icon from folder to grid view

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/ChapterCursorMapper.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/DownloadStatusCursorMapper.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedCursorMapper.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedPreferencesCursorMapper.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/years/YearStatisticsListAdapter.java

Instead of loading every single episode and then calculating the statistics in Java, let the database calculate all the statistics. The database is much better at loading large amounts of data and filtering it. This is especially important since we will use the statistics feature for deciding which feeds we show on the home screen (see #5864).
I have a huge test database with about 26k episodes.
Calculating the statistics before took 3300 ms. With this PR, it takes only 700 ms, so it is about **4-5 times faster**.
I think this is one of the longest SQL queries I ever wrote...
```sql
SELECT
Feeds.id AS feed_id,
Feeds.title,
Feeds.custom_title,
Feeds.file_url,
Feeds.download_url,
Feeds.downloaded,
Feeds.link,
Feeds.description,
Feeds.payment_link,
Feeds.last_update,
Feeds.language, …
```

Make statistics loading more efficient

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Fix miniplayer sometimes showing toolbar

---

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java

Clear search box when coming back from search

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
app/src/main/res/layout/cover_fragment.xml

Fix player screen on some screen dimensions

---

app/build.gradle
build.gradle
core/build.gradle

Remove robotium-solo library

---

core/src/main/res/values/arrays.xml
model/src/main/java/de/danoeh/antennapod/model/feed/FeedCounter.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
ui/i18n/src/main/res/values/strings.xml

Implement "Downloaded and unplayed" subscription counter option

---

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java

Fix loading views inconsistently showing cover

---

app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/TogglePlaybackStateSwipeAction.java

Don't remove feed item from screen after "toggle played", if filter setting includes "not played"

---

app/src/main/res/layout/horizontal_itemlist_item.xml

Decrease margin around button in episode card

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

Initialize swipe actions before using them

---

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java

Fix chapters dialog crashing

---

app/src/main/java/de/danoeh/antennapod/ui/home/sections/QueueSection.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/HorizontalItemViewHolder.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java

Tweak Queue section on home screen

---

app/src/main/res/layout/horizontal_feed_item.xml
app/src/main/res/layout/horizontal_itemlist_item.xml

adding margin on inner cardview
Fix #6104 
Hi @keunes, @ByteHamster 
I do mistake to my PR, so my PR accidentaly closed, please to review again my PR from #6114

remove card elevation

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java
core/src/main/java/de/danoeh/antennapod/core/util/gui/ShownotesCleaner.java
core/src/test/java/de/danoeh/antennapod/core/util/gui/ShownotesCleanerTest.java

Let's hope that this does not break too many valid use cases of css in shownotes. The regex is quite fragile.
Closes #6127

Remove text colors from shownotes

---

app/src/main/res/layout/time_dialog.xml

Select all when focusing time in sleep timer

---

app/src/main/java/de/danoeh/antennapod/dialog/ItemFilterDialog.java

Fix #5977
Hi @ByteHamster 
This PR fixed for the bottomsheet not expanded properly when orientation landscape
Before 
https://user-images.githubusercontent.com/32972299/196888701-1510befe-3261-44f2-bfa2-7c7ded3c4b67.mp4
After Fix
https://user-images.githubusercontent.com/32972299/196889005-b655b885-e729-43e3-ac9d-9838144b98ff.mp4

add default state expanded filter dialog

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java

Got broken by c42ed1d1874142f52385ad1c7ce45bffa17e4981

Fix queue sort order not being displayed

---

app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
ui/i18n/src/main/res/values/strings.xml

Add confirmation dialog for clearing history

---

app/src/main/java/de/danoeh/antennapod/ui/home/HomeFragment.java
app/src/main/res/layout/home_fragment.xml

I just pulled down on the home screen, expecting it to refresh. Now it does.

Add pull-to-refresh to home screen

---

app/src/main/res/layout/home_section.xml

This made the layout more complex than I expected...

Support for multi-line home section titles

---

net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/HostnameParser.java

Convert nextcloud domains to Punycode

---

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
app/src/main/res/layout/feeditemlist_item.xml

Also, this finally gets rid of the jumping when entering multi-select mode.
Closes #6202

Multi-select using background instead of checkbox

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

https://forum.antennapod.org/t/alpha-3-0-feedback/2569/16

Use exactly those insets that we mark as consumed

---

ui/i18n/src/main/res/values/strings.xml

Make description of tinted theme more clear

---

app/src/main/java/de/danoeh/antennapod/ui/home/sections/EpisodesSurpriseSection.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/QueueSection.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/SubscriptionsSection.java

Reduce padding of horizontal home sections to better align them with the titles

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/handler/FeedSyncTask.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/FeedHandler.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/FeedHandlerResult.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/HandlerState.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Itunes.java

Update feed url when server returns itunes:new-feed-url

---

app/src/main/res/layout/audioplayer_fragment.xml

Avoid icons leaking below the miniplayer

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/res/layout/audioplayer_fragment.xml

Use nicer animation when sliding up player

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

When playback is started from MediaSessionCompat.Callback:
- The service does not go through onStartCommand, so it does not go to foreground state.
- The media session is already destroyed.
Now, create a new media session and definitely start foreground service when something is playing.
Fixes a regression in #6293

Fix when playback is started from MediaSessionCompat.Callback

---

ui/common/src/main/res/layout/pager_fragment.xml

Don't break tab labels into multiple lines on small devices

---

app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java

Fix current chapter having the same color as the dialog background

---

model/src/main/java/de/danoeh/antennapod/model/feed/FeedMedia.java

https://forum.antennapod.org/t/automatic-episode-info-updating-for-episosdes-with-changed-data-duration-file-size-title-etc/2733

Update duration from feed if there is none yet

---

playback/cast/build.gradle
playback/cast/src/play/java/de/danoeh/antennapod/playback/cast/CastOptionsProvider.java

Fixes #6317.
Also, now uses a styled cast receiver app that I registered with Google :) See pictures below
Before:
After:

Fix Chromecast on Android 12, use styled receiver

---

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java

Ensure that the context is non-null when loading the shownotes

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceInterfaceImpl.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterface.java
net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterfaceStub.java
ui/app-start-intent/src/main/res/values/pending_intent.xml

Add retry button to download failed notifications

---

net/discovery/src/main/java/de/danoeh/antennapod/net/discovery/ItunesTopListLoader.java

Fix crash in iTunes loader

---

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/main/res/values/arrays.xml
storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java

Add mobile sync setting

---

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java

Always add feeds from opml, even if download fails

---

app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
app/src/main/res/menu/mediaplayer.xml
ui/i18n/src/main/res/values/strings.xml

Add chapters button to video player

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
ui/app-start-intent/src/main/res/values/pending_intent.xml
ui/png-icons/src/main/res/drawable/ic_notification_cancel.xml

Add cancel action to download notification

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
ui/i18n/src/main/res/values/strings.xml

https://developer.android.com/guide/topics/media/media-controls
Fixes #4448 
Fixes #6049

Support media resumption

---

app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/DownloadsSection.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/InboxSection.java
core/src/main/java/de/danoeh/antennapod/core/export/favorites/FavoritesWriter.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/storage/APCleanupAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/storage/APQueueCleanupAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/EpisodeCleanupAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/storage/ExceptFavoriteCleanupAlgorithm.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java

Makes two of our longest classes a bit shorter
Also closes #6222

Instead of specialized methods, use the global 'getEpisodes' method with a filter

---

playback/cast/src/play/java/de/danoeh/antennapod/playback/cast/CastEnabledActivity.java

Workaround for yet another place where Huawei messed up the Android system.
Closes #6364

Fix crash on Huawei devices

---

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java
core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java

Issue #6363 was since "deleted" by the author.

Warn when local folder is empty instead of silently ignoring

---

storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/StatisticsFilterDialog.java

Make statistics filter start at 00:00

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Notify Android Auto that the queue changed

---

ui/i18n/src/main/res/values/strings.xml

Mention in statistics to warning when deleting podcast(s)

---

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
core/src/main/java/de/danoeh/antennapod/core/storage/ItemEnqueuePositionCalculator.java
core/src/main/res/values/arrays.xml
storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
ui/i18n/src/main/res/values-pl/strings.xml
ui/i18n/src/main/res/values/strings.xml

Random enqueue location

---

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java

https://forum.antennapod.org/t/episode-list-involuntarily-moves-down/2910/

Avoid scrolling screen on refresh

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Don't crash when Chromecast media is not loaded yet

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java

Support longer transient pause

---

app/src/main/java/de/danoeh/antennapod/ui/home/HomeSection.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/SubscriptionsSection.java

Problem was introduced in #6267

Fix long-pressing subscription on home screen

---

app/src/main/java/de/danoeh/antennapod/ui/home/sections/SubscriptionsSection.java

Respect 'include marked as played' on home screen

---

core/src/main/res/values/styles.xml

Add onPrimary color

---

app/src/main/assets/special_thanks.csv

Adding some folks that contribute to AntennaPod, and updating some descriptions.
Order updated also, with the logic being: users currently active on top, no longer contributing below, sorted based on estimated time contribution.

Update 'Special thanks' list in the About screen

---

app/src/main/res/xml/preferences.xml

Correctly theme download icon in settings

---

app/src/main/java/de/danoeh/antennapod/dialog/ItemFilterDialog.java
app/src/main/java/de/danoeh/antennapod/dialog/SubscriptionsFilterDialog.java
app/src/main/res/layout/filter_dialog_row.xml
core/src/main/res/color/button_bg_selector.xml
core/src/main/res/values/styles.xml

Also, make it easier to see what option is selected
Closes #6452

Let filter button height grow

---

app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java
app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java

gilde leaking by activity's referrence

---

app/src/main/java/de/danoeh/antennapod/activity/WidgetConfigActivity.java
core/src/main/java/de/danoeh/antennapod/core/receiver/PlayerWidget.java

#6410 made the widget 100% transparent by default. Change it to 100% opaque again.

Fix default widget background

---

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/SimpleChapters.java

Fix NullPointerException when chapter does not have start time

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Fixed #6512 - Mini player in landscape mode missing the Play button

Fix mini player in landscape mode missing the Play button

---

app/build.gradle
app/src/main/java/com/google/android/material/bottomsheet/ViewPagerBottomSheetBehavior.java
app/src/main/java/de/danoeh/antennapod/PodcastApp.java
app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/dialog/SwipeActionsDialog.java
app/src/main/java/de/danoeh/antennapod/ui/home/HomeSection.java
app/src/main/java/de/danoeh/antennapod/view/LiftOnScrollListener.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java
build.gradle
common.gradle
core/build.gradle
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java
core/src/main/res/layout/player_widget.xml

Like #5581 but for minSdk 21.
Also centralized the stream library version.

Remove no longer needed Compat stuff

---

app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/EditUrlSettingsDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
core/src/main/java/de/danoeh/antennapod/core/service/FeedUpdateWorker.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
core/src/main/java/de/danoeh/antennapod/core/util/download/FeedUpdateManager.java
ui/i18n/src/main/res/values/strings.xml

The download service rewrite broke this feature

Fix 'allow once' for feed update on mobile networks

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java

Don't allow adding items without media to the queue

---

app/src/androidTest/java/de/test/antennapod/service/download/HttpDownloaderTest.java
core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequestCreator.java
core/src/main/java/de/danoeh/antennapod/core/service/download/EpisodeDownloadWorker.java
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadRequest.java
net/download/service-interface/src/test/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadRequestTest.java

Unfortunately, this removes the feature to resume downloads later manually. Closes #6460.

Delete partially downloaded file when giving up to retry

---

playback/cast/src/play/java/de/danoeh/antennapod/playback/cast/MediaInfoCreator.java

Fix Chromecast crash if FeedItem does not have a feed

---

app/src/main/java/de/danoeh/antennapod/PodcastApp.java
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java

Upgrade preferences before using them

---

app/src/main/java/de/danoeh/antennapod/view/NoRelayoutTextView.java

Relayout NoRelayoutTextView if text gets longer

---

core/src/main/java/de/danoeh/antennapod/core/service/download/EpisodeDownloadWorker.java

Avoid race conditions when updating download notification

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
core/src/main/java/de/danoeh/antennapod/core/sync/queue/SynchronizationQueueSink.java

Sync on app start

---

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequestCreator.java

See https://forum.antennapod.org/t/feed-download-completed-but-size-does-not-equal-expected-size/3288

Do not try to resume download of feeds

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/synchronization/NextcloudAuthenticationFragment.java
net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudLoginFlow.java

Restore Nextcloud login state when recreated

---

core/src/main/java/de/danoeh/antennapod/core/service/download/NewEpisodesNotification.java

Open inbox instead of 'all episodes' when pressing 'new episodes' summary

---

core/src/main/res/values/styles.xml

Make preference switch background less prominent

---

app/src/main/java/de/danoeh/antennapod/fragment/actions/FeedMultiSelectActionHandler.java
app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
app/src/main/res/menu/nav_feed_action_speeddial.xml
app/src/main/res/xml/preferences_notifications.xml
core/src/main/java/de/danoeh/antennapod/core/util/gui/NotificationUtils.java
storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
ui/i18n/src/main/res/values/strings.xml

Remove auto-download notification setting & add episode notifications to multi select options

---

ui/i18n/src/main/res/values/strings.xml

Improve wording

---

core/src/main/java/de/danoeh/antennapod/core/service/FeedUpdateWorker.java
core/src/main/java/de/danoeh/antennapod/core/util/download/FeedUpdateManager.java

Refresh local feeds even if there is no internet

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java

Apply username and password when subscribing

---

parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentReader.java

Posted in #6666, but actually unrelated to the issue there

Fix crash if vorbis exception does not have message

---

app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
app/src/main/java/de/danoeh/antennapod/view/viewholder/HorizontalItemViewHolder.java
app/src/main/res/layout/addfeed.xml
app/src/main/res/layout/episodes_list_fragment.xml
app/src/main/res/layout/feed_item_list_fragment.xml
app/src/main/res/layout/feeditemlist_header.xml
app/src/main/res/layout/fragment_itunes_search.xml
app/src/main/res/layout/fragment_subscriptions.xml
app/src/main/res/layout/home_section.xml
app/src/main/res/layout/queue_fragment.xml
app/src/main/res/layout/search_fragment.xml
app/src/main/res/layout/simple_list_fragment.xml
app/src/main/res/layout/subscription_item.xml
ui/common/build.gradle
ui/common/src/main/res/layout/pager_fragment.xml
ui/i18n/src/main/res/values/strings.xml

Better content descriptions for TalkBack

---

app/src/main/res/layout/horizontal_itemlist_item.xml

Might lead to bad contrast in dark theme when applying dynamic colors
Closes #6696

Remove ProgressBar background

---

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/res/layout/addfeed.xml
app/src/main/res/layout/feeditemlist_header.xml
app/src/main/res/layout/home_section.xml
app/src/main/res/layout/quick_feed_discovery.xml
ui/i18n/src/main/res/values/strings.xml

I discovered that text fields can be marked as headings for accessibility. Doing that to make navigation (especially on the home screen) easier.

Some more accessibility tweaks

---

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
core/src/main/java/de/danoeh/antennapod/core/sync/queue/SynchronizationQueueSink.java

Do not try to sync local feeds

---

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
app/src/main/java/de/danoeh/antennapod/ui/home/HomeFragment.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/AllowNotificationsSection.java
app/src/main/res/layout/home_section_notification.xml
core/src/main/java/de/danoeh/antennapod/core/service/download/EpisodeDownloadWorker.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
ui/i18n/src/main/res/values/strings.xml

- Support showing most error messages as a snackbar
- Ask for notification permission when enabling episode notifications
- Clarify what we use notifications for

Allow hiding notification permission nag

---

app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
ui/i18n/src/main/res/values/strings.xml

See https://forum.antennapod.org/t/episodes-marked-as-played/3635

Announce played/unplayed in TalkBack

---

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/AboutFragment.java
app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java

#6481 hid it starting with Android 12L instead of Android 13

Show 'copied to clipboard' message on Android 12L

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
ui/i18n/src/main/res/values/strings.xml

Also hide path, is not accessible on recent Android versions anyway.
Closes #6741

Add button to share exported database export

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java

This is a possible fix for #6748
I can't reproduce the crash, but I think this might fix the crash. Should we just merge it or somehow send the build for testing first?

Only set target gain when enhancer was enabled

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java

- When deleting local folders, don't delete files
- Don't try to delete files twice
- Fix deleting non-local feeds
Closes #6757

Fix file deletion

---

app/src/main/res/layout/time_dialog.xml

Add ScrollView to sleep timer dialog

---

app/src/main/java/de/danoeh/antennapod/ui/home/HomeFragment.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/EchoSection.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screens/FinalShareScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screens/WavesScreen.java

- Make it show every year automatically, without having to change code manually (getting out the update on time was too stressful, I don't want that next year)
- New screen background with expanding circles (waves) from the bottom, replacing one of the 2 stripes screens

Make it easier to migrate Echo to a new year 

---

app/build.gradle

Update preference search library

---

ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java

Fix Echo using wrong number of days in a year

---

app/src/main/res/layout/home_section.xml

See https://github.com/AntennaPod/AntennaPod/pull/6230#issuecomment-1850948501, cc @loucasal

Better center number in 'new' pill

---

core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java
core/src/test/java/de/danoeh/antennapod/core/feed/FeedItemTest.java
model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBUpgrader.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemCursorMapper.java

This should not change any behavior.
The retry count and timing are now managed by WorkManager.

Remove unnecessary autodownload code

---

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java

If feed url was typed manually, show edit url button on error

---

app/src/main/java/de/danoeh/antennapod/dialog/ItemFilterDialog.java
app/src/main/res/layout/filter_dialog.xml

this adds only the reset button but maybe it would also make sense to add the icons, i'm just not sure designwise how to do it @keunes ? Any thoughts?
Closes #6383

Add reset button to episodes filter

---

app/src/main/res/layout/nextcloud_auth_dialog.xml

fix #6806 
Add a nested scrollbar so the user can scroll for `Proceed to login`

Add scrollbar to Nextcloud login dialog

---

ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/PlaybackStatisticsListAdapter.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/StatisticsFilterDialog.java

Use localized date format

---

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java

Print duration as number of days only on Echo

---

app/src/main/res/menu/mediaplayer.xml

Improve toolbar in player: always show share

---

app/src/main/java/de/danoeh/antennapod/ui/home/sections/EchoSection.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screens/FinalShareScreen.java

Tweaks to Echo

---

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java
ui/i18n/src/main/res/values/strings.xml

- Only request storage permission when ContentResolver fails
- Easier to read error message

Tweak OPML import

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

Rewind when sleep timer pauses playback

---

app/src/main/java/de/danoeh/antennapod/fragment/preferences/UserInterfacePreferencesFragment.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
core/src/main/res/values/arrays.xml
storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
ui/png-icons/src/main/res/drawable/ic_notification_sleep.xml
ui/png-icons/src/main/res/drawable/ic_notification_sleep_off.xml

Toggle sleep timer from notification

---

core/src/main/AndroidManifest.xml

Needed for future Android 14 support

Specify foreground service type

---

.github/workflows/checks.yml
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
app/src/main/java/de/danoeh/antennapod/dialog/TimeRangeDialog.java
app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
build.gradle
common.gradle
config/spotbugs/exclude.xml
core/src/main/java/de/danoeh/antennapod/core/backup/OpmlBackupAgent.java
core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
core/src/main/java/de/danoeh/antennapod/core/storage/NavDrawerData.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java
ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/FastBlurTransformation.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/years/BarChartView.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/years/YearStatisticsListAdapter.java

Closes #6941. After trying a whole bunch of stuff, the only solution I found was to just print everything normally. I think the problem was that the error was being piped to grep instead of the CI itself (stupid). This should be a dirty solution until something else is found. (I have an idea which is to configure output from the task in common.gradle, but I'll try that another time.)
Also not all modules use the build flavors, and therefore not all modules were generating `playDebug.xml` (some only generated `debug.xml`). The XmlSlurper was only checking for `playDebug.xml`. I updated it to do both.
It was not possible for me to fix SpotBugs without updating it. I had to update SpotBugs from 4.2.1 to [4.2.3](https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#423---2021-04-12), …

Update and fix SpotBugs

---

build.gradle
core/build.gradle
core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
core/src/main/java/de/danoeh/antennapod/core/util/download/NetworkConnectionChangeHandler.java

Upgrade ExoPlayer version.
First step towards #6608

Upgrade ExoPlayer to media3 version

---

app/build.gradle
app/proguard.cfg
app/src/main/assets/licenses.xml
build.gradle
core/build.gradle
core/src/main/java/de/danoeh/antennapod/core/service/download/HttpCredentialEncoder.java

The library is only used in one single line that can also be done with the Android framework

Remove okio library

---

build.gradle

Closes #6601. Well, that was easier than I expected :D

Upgrade OkHttp

---

build.gradle
core/build.gradle
core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java

- Fix some Media3 deprecations

Fix some Media3 deprecations

---

app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PauseActionButton.java
app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
core/src/main/java/de/danoeh/antennapod/core/receiver/MediaButtonReceiver.java
core/src/main/java/de/danoeh/antennapod/core/service/QuickSettingsTileService.java
core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java
ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/MediaButtonStarter.java

Contributes to https://github.com/AntennaPod/AntennaPod/issues/4661

Decouple media button sender and receiver

---

common.gradle

Suppress outdated dependency Lint

---

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
core/src/test/java/de/danoeh/antennapod/core/feed/FeedTest.java
core/src/test/java/de/danoeh/antennapod/core/util/FeedItemUtilTest.java
model/src/main/java/de/danoeh/antennapod/model/feed/Feed.java
model/src/main/java/de/danoeh/antennapod/model/feed/FeedPreferences.java

Remove check for updated attributes, just update them. This code is not necessary and complicates adding new attributes.

Remove check for updated attributes, just update them

---

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java

See https://forum.antennapod.org/t/abo-episodes-listing-bug-in-android-auto/4266

Fix missing episodes on Android Auto

---

scripts/generateModuleDiagram.sh

Add script to generate module diagram. Output available on the Wiki: https://github.com/AntennaPod/AntennaPod/wiki/Code-structure

Add script to generate module diagram

---

app/src/main/java/de/danoeh/antennapod/ui/home/HomeFragment.java
app/src/main/java/de/danoeh/antennapod/ui/home/sections/EchoSection.java
config/spotbugs/exclude.xml
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoActivity.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoConfig.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/BaseBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/BubbleBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/FinalShareBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/RotatingSquaresBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/StripesBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/WaveformBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/background/WavesBackground.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/EchoScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/FinalShareScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/HoarderScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/HoursPlayedScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/IntroScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/QueueScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/ThanksScreen.java
ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/TimeReleasePlayScreen.java
ui/echo/src/main/res/layout/echo_activity.xml
ui/echo/src/main/res/layout/simple_echo_screen.xml
ui/echo/src/main/res/values/echo-strings.xml
ui/statistics/build.gradle
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/StatisticsFragment.java
ui/statistics/src/main/res/menu/statistics.xml

Each screen is its own file, which makes it easier to add interactive elements.

Restructure Echo to be more flexible

---

app/build.gradle
app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
ui/preferences/build.gradle
ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/about/AboutFragment.java
ui/preferences/src/main/res/layout/settings_activity.xml

Move about screen to :ui:preferences
Contributes to https://github.com/AntennaPod/AntennaPod/issues/4661

Move about screen to :ui:preferences

---

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java
app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java

Fix search button not working on some screens

Fix search button not working on some screens

---

ui/i18n/src/main/res/values/strings.xml

This one was left behind when most strings were converted to sentence case.

Update remaining string to sentence case

---

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
app/src/main/java/de/danoeh/antennapod/activity/SelectSubscriptionActivity.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemListRecyclerView.java
app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/feed/RenameFeedDialog.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java
config/spotbugs/exclude.xml
playback/base/src/main/java/de/danoeh/antennapod/playback/base/PlaybackServiceMediaPlayer.java
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackController.java
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/NavDrawerData.java
storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/OpmlBackupAgent.java
ui/common/src/main/java/de/danoeh/antennapod/ui/common/Converter.java
ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/PieChartView.java

Cleaned up unused SpotBugs rules and fixed a bunch of existing ones.
(I've already completed the full SpotBugs upgrade (not including the plugin) in another branch. This one should be merged first, and then I'll make that PR.)

Spotbugs cleanup

---

app/src/main/AndroidManifest.xml
build.gradle
common.gradle
playback/service/src/main/AndroidManifest.xml
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackController.java
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
ui/echo/build.gradle

Target SDK 34

---

app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java

Show feed search results as soon as they are available without waiting for episode search results
Closes #6889

Show feed search results as soon as they are available

---

net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudSyncService.java

Nextcloud Gpodder sync using wrong url

---

playback/service/build.gradle
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java

playback: do not enable sleep mode in Android Auto

---

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java
app/src/main/res/layout/feedinfo.xml

Show statistics above description on feed info page

---

ui/common/src/main/res/values/styles.xml

See https://github.com/AntennaPod/AntennaPod/pull/7163#issuecomment-2097606828

Fix settings toolbar having color

---

app/src/main/res/layout/feeditemlist_header.xml
ui/common/src/main/res/drawable/bg_message_error.xml

Suggested by  @keunes in #7098

Update error message design

---

app/src/main/res/layout/swipeactions_dialog.xml

Make it possible to scroll swipe actions dialog. Fixes problems when using a very small screen.

Make it possible to scroll swipe actions dialog

---

ui/i18n/src/main/res/values/strings.xml
ui/preferences/src/main/res/xml/preferences_playback.xml
ui/preferences/src/main/res/xml/preferences_user_interface.xml

Reorganize settings in the user interface

---

app/build.gradle
app/src/main/res/resources.properties

Option to switch app language

---

app/src/main/java/de/danoeh/antennapod/ui/screen/download/CompletedDownloadsFragment.java
app/src/main/res/layout/simple_list_fragment.xml

Add pull to refresh to Downloads screen

---

app/src/main/java/de/danoeh/antennapod/PreferenceUpgrader.java
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/FeedSettingsFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/AutomaticDeletionPreferencesFragment.java
config/spotbugs/exclude.xml
playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackController.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java
storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/FavoritesWriter.java

Per https://github.com/AntennaPod/AntennaPod/pull/6968#issuecomment-2029266134
- [N/A] If it is a core feature, I have added automated tests

Spotbugs cleanup part 2

---

.github/ISSUE_TEMPLATE/feature_request.yml

Almost nobody used the problem/solution scheme we requested. Users want to write their feature first before thinking about reasons.

Make issue template easier to use

---

ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoConfig.java

Echo 2024 bringup. Still mostly the same as the 2023 version because no designer volunteered.

Echo 2024 bringup

---

app/src/main/AndroidManifest.xml
ui/common/src/main/res/values/styles.xml

To be honest, I am not 100% sure why this works. But apparently it does work.
Closes #7290

Fix blue theme sometimes showing partially dynamic

---

app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java
app/src/main/java/de/danoeh/antennapod/ui/share/ShareUtils.java
net/common/src/main/java/de/danoeh/antennapod/net/common/UrlChecker.java
net/common/src/test/java/de/danoeh/antennapod/net/common/UrlCheckerTest.java

- Properly extract url parameter
- Remove prefix before looking it up in the database

Fix subscription deeplink

---

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java
app/src/main/res/layout/feeditemlist_header.xml

Hide 'Not subscribed' message the first time we show preview

Hide 'Not subscribed' message the first time we show preview

---

ui/preferences/src/main/res/layout/theme_preference.xml

Otherwise the buttons fill the entire screen

Maximum height of user interface settings for tablet users

---

storage/database/src/main/java/de/danoeh/antennapod/storage/database/FeedDatabaseWriter.java

Ignore new episodes action for non-subscribed feeds
Closes #7333

Ignore new episodes action for non-subscribed feeds

---

app/src/main/res/layout/onlinefeedview_activity.xml
ui/common/src/main/res/values/styles.xml

Fix paddings in online feed preview

---

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java
net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdater.java

Support new episodes notification on local feeds
Closes #7307

Support new episodes notification on local feeds

---

ui/i18n/src/main/res/values/strings.xml

Be more detailed with what is deleted when unsubscribing
Closes #7355

Be more detailed about what is deleted when unsubscribing

---

app/src/main/res/layout/swipeactions_picker.xml

Closes #7283
- [.] I have read the contribution guidelines: https://github.com/AntennaPod/AntennaPod/blob/develop/CONTRIBUTING.md#submit-a-pull-request
- [.] I have performed a self-review of my code
- [.] I have run the automated code checks using `./gradlew checkstyle spotbugsPlayDebug spotbugsDebug :app:lintPlayDebug`
- [.] My code follows the style guidelines of the AntennaPod project: https://github.com/AntennaPod/AntennaPod/wiki/Code-style
- [.] I have mentioned the corresponding issue and the relevant keyword (e.g., "Closes: #xy") in the description (see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [.] If it is a core feature, I have added automated tests

Fixed Scrolling issues in Swipe Actions

---

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java
model/src/main/java/de/danoeh/antennapod/model/feed/Feed.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/NonSubscribedFeedsCleaner.java

Show subscribe nag only after interacting with episode
Closes #7341

Show subscribe nag only after interacting with episode

---

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/video/VideoplayerActivity.java

Don't show transcript icon for videos when there is none

---

app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java

Fix subscribing with discovery dialog

Fix subscribing with discovery dialog

---

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/TimeRangeDialog.java

Multi-line sleep timer time range for 12 hour locales

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Update bottom navigation inbox badge when inbox changes

Update bottom navigation inbox badge when inbox changes

---

app/src/main/java/de/danoeh/antennapod/ui/screen/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionViewHolder.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionsRecyclerAdapter.java
app/src/main/res/layout/subscription_grid_item.xml
ui/common/src/main/res/drawable/ic_checkbox_background.xml

Use theme color for subscription card background

Use theme color for subscription card background

---

app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavDrawerFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/FeedMenuHandler.java
app/src/main/res/menu/feedlist.xml
app/src/main/res/menu/nav_feed_context.xml

Allow sharing feeds from the subscriptions page. We want more users to share feeds, so that they spread the word about AntennaPod using our deeplink :)

Allow sharing feeds from subscriptions page

---

app/src/main/java/de/danoeh/antennapod/ui/SelectableAdapter.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeMultiSelectActionHandler.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/HorizontalItemListAdapter.java
app/src/main/java/de/danoeh/antennapod/ui/screen/InboxFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/download/CompletedDownloadsFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/episode/ItemPagerFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/AudioPlayerFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/playback/video/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/ui/swipeactions/DeleteSwipeAction.java
app/src/main/java/de/danoeh/antennapod/ui/view/LocalDeleteModal.java
app/src/main/res/layout/floating_select_menu.xml
app/src/main/res/layout/floating_select_menu_item.xml
app/src/main/res/menu/episodes_apply_action_speeddial.xml
ui/i18n/src/main/res/values/strings.xml

Only show relevant actions on multi-select
Closes #7157

Only show relevant actions on multi-select

---

net/discovery/src/main/java/de/danoeh/antennapod/net/discovery/ItunesTopListLoader.java
net/discovery/src/main/java/de/danoeh/antennapod/net/discovery/PodcastSearchResult.java

Do not print toplist authors twice

Do not print toplist authors twice

---

ui/i18n/src/main/res/values/strings.xml
ui/preferences/src/main/res/xml/preferences_playback.xml

Closes #7200.
Note: I found the summary proposed in the ticket read a bit clunky, so I am suggesting a hopefully improved one.

Make enqueue location setting easier to understand

---

storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemSortQuery.java

fix: sorting episodes by file name doesn't work

---

README.md

The cool projects now use badges
[![GitHub check runs](https://img.shields.io/github/check-runs/AntennaPod/AntennaPod/develop)](https://github.com/AntennaPod/AntennaPod/actions/workflows/checks.yml?query=branch%3Adevelop) [![License: GPL v3](https://img.shields.io/github/license/AntennaPod/AntennaPod)](https://www.gnu.org/licenses/gpl-3.0) [![GitHub Release](https://img.shields.io/github/v/release/AntennaPod/AntennaPod)](https://github.com/AntennaPod/AntennaPod/releases) [![https://img.shields.io/github/commits-since/AntennaPod/AntennaPod/latest/develop](https://img.shields.io/github/commits-since/AntennaPod/AntennaPod/latest/develop)](https://github.com/AntennaPod/AntennaPod/commits/develop/) [![Translations on Weblate](https://hosted.weblate.org/widget/antennapod/app/svg-badge.svg?native …

The cool projects now use badges

---

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java
app/src/main/res/layout/episodes_list_fragment.xml
app/src/main/res/layout/fragment_subscriptions.xml
app/src/main/res/layout/nav_section_item.xml
app/src/main/res/layout/queue_fragment.xml
ui/i18n/src/main/res/values/strings.xml

Fix alignment issue under the title and remove extra padding

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java

Fix inbox counter not always updating
Closes #7516

Fix inbox counter not always updating

---

ui/i18n/src/main/res/values/strings.xml

Update subscriptions list label in settings
Closes #7515

Update subscriptions list label in settings

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Version code now shows which version was used and is more reliable than the memory of users.

Remove app source from issue template

---

net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SyncService.java

Fix sync getting stuck in endless loop
Closes #7531

Fix sync getting stuck in endless loop

---

app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/ProxyDialog.java
ui/i18n/src/main/res/values/strings.xml
ui/preferences/src/main/res/layout/proxy_settings.xml

Update proxy dialog to Material 3. Google Play complained about the dialog not having proper accessibility descriptions.

Update proxy dialog to Material 3

---

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/PlaybackSpeedSeekBar.java
app/src/main/java/de/danoeh/antennapod/ui/view/EmptyViewHandler.java
app/src/main/res/layout/addfeed.xml
app/src/main/res/layout/edit_tags_dialog.xml
app/src/main/res/layout/feeditemlist_header.xml
app/src/main/res/layout/playback_speed_feed_setting_dialog.xml
app/src/main/res/layout/playback_speed_seek_bar.xml
app/src/main/res/layout/speed_select_dialog.xml
ui/common/src/main/res/drawable/ic_minus.xml
ui/common/src/main/res/values/styles.xml

Accessibility tweaks reported by Google Play. Mainly touch target sizes.

Accessibility tweaks reported by Google Play

---

playback/cast/build.gradle
playback/cast/src/play/java/de/danoeh/antennapod/playback/cast/CastPsmp.java

Restore playback speed on Chromecast
Closes #6493

Restore playback speed on Chromecast

---

app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeFragment.java
app/src/main/res/layout/home_fragment.xml
ui/i18n/src/main/res/values/strings.xml

Prepare empty home screen for bottom navigation

Prepare empty home screen for bottom navigation

---

app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/UserInterfacePreferencesFragment.java

Fixes #7585 
Hope everything's ok, thought I'd try a "good first issue"

Disable 'Back button opens drawer' if Bottom menu is enabled

---

README.md

Update translation link in readme

Update translation link in readme

---

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java
app/src/main/res/layout/feedinfo.xml
app/src/main/res/layout/feeditemlist_header.xml
ui/common/src/main/res/values/styles.xml

Make feed info page more similar to main list
Closes #7576

Make feed info page more similar to main list

---

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/playback/video/VideoplayerActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/BugReportActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/PreferenceActivity.java
build.gradle
common.gradle
gradle/wrapper/gradle-wrapper.properties
net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdaterTest.java
ui/common/src/main/java/de/danoeh/antennapod/ui/common/ThemeSwitcher.java
ui/common/src/main/java/de/danoeh/antennapod/ui/common/ToolbarActivity.java
ui/common/src/main/res/layout/toolbar_activity.xml
ui/widget/src/main/java/de/danoeh/antennapod/ui/widget/WidgetConfigActivity.java

Target Android 15

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavigationNames.java
app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java
ui/i18n/src/main/res/values/strings.xml

Shorter names for bottom navigation items.

Shorter names for bottom navigation items

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
settings.gradle
ui/i18n/src/main/res/values/strings.xml
ui/preferences/build.gradle
ui/preferences/src/main/res/xml/preferences.xml

Upgrade SearchPreference and use our own 'more' string
Closes #7654

Upgrade SearchPreference and use our own 'more' string

---

app/src/main/java/de/danoeh/antennapod/PreferenceUpgrader.java

Enable bottom navigation for beta users. Now that most critical bugs are probably solved, we can start rolling it out to a larger number of users. This gives us more feedback before we roll it out for all users.

Enable bottom navigation for beta users

---

app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavDrawerFragment.java
model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Atom.java
parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java
storage/database/src/main/java/de/danoeh/antennapod/storage/database/FeedDatabaseWriter.java

Reduce log spam during feed update

Reduce log spam during feed update

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/BottomNavigation.java
app/src/main/res/values/ids.xml

Code cleanup: Move bottom navigation handling out of MainActivity

Move bottom navigation handling out of MainActivity

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
ui/i18n/src/main/res/values/strings.xml

Enable bottom navigation by default for new users

Enable bottom navigation by default for new users

---

ui/i18n/src/main/res/values/strings.xml

Clarify headset disconnected string
CC @keunes

Clarify headset disconnected string

---

storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/DatabaseExporter.java

Write database exports without seeking export file
This can lead to problems with WebDAV because the file does not exist yet.
Closes #7721

Write database exports without seeking export file

---

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/TranscriptAdapter.java
model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java
model/src/main/java/de/danoeh/antennapod/model/feed/TranscriptSegment.java
model/src/main/java/de/danoeh/antennapod/model/feed/TranscriptType.java
net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/episode/MediaDownloadedHandler.java
net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java
parser/transcript/src/main/java/de/danoeh/antennapod/parser/transcript/TranscriptParser.java
parser/transcript/src/main/java/de/danoeh/antennapod/parser/transcript/VttTranscriptParser.java
parser/transcript/src/test/java/de/danoeh/antennapod/parser/transcript/VttTranscriptParserTest.java

This PR adds VTT support for transcripts (in addition to existing SRT and JSON).
Closes #7431

Vtt support for transcripts

---

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemListRecyclerView.java
app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodesListFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/AllEpisodesFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/InboxFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/PlaybackHistoryFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java
app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java

Remember scroll positions
See also #7800 and #7766
Closes #7697

Remember scroll positions

---

net/common/src/main/java/de/danoeh/antennapod/net/common/AntennapodHttpClient.java
ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/ApOkHttpUrlLoader.java

Fix user-agent not always being sent
Extracted from #7739
Closes #7743 
CC @tonytamsf

Fix user-agent not always being sent

---

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java

Fixes #7853 by removing the subtitle value, leaving just the preferred title (the custom title if set, or else the feed title).
- <details>
<summary>Checkstyle and spotbugs seem to fail to run (lint passes)</summary>
```
> Task :checkstyle FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':checkstyle'.
> Cannot access input property 'source' of task ':checkstyle'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). For more information, please refer to https://docs.gradle.org/8.10.2/userguide/incremental_build.html#sec:disable-state-tracking in the Gradle documentation.
> Failed to create MD5 hash for file content.
```
```
> Task :ui:echo:spotbugsPlayDebug FAILED
> Task …
```

Remove duplicate custom feed title in subtitle field

---

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java

Fix some deprecations and warnings

Fix some deprecations and warnings

---

app/build.gradle
app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
settings.gradle
storage/database-maintenance-service/README.md
storage/database-maintenance-service/build.gradle
storage/database-maintenance-service/src/main/AndroidManifest.xml
storage/database-maintenance-service/src/main/java/de/danoeh/antennapod/storage/databasemaintenanceservice/DatabaseMaintenanceWorker.java
storage/database-maintenance-service/src/main/res/values/ids.xml
storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java

Run download log cleaner regularly
See https://github.com/AntennaPod/AntennaPod/issues/7664

Run download log cleaner regularly
