core/src/main/res/values/strings.xml
Closes #4472.
Removed the unused navigate_upwards_label string from the English strings.xml file.
=> Removed navigate_upwards_label from strings.xml

app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
Since the single SearchFragment is used for searching items at both within a podcast fragment and at Episode Fragment, only difference arises is the passage of feed, episode page pushes 0 and the podcast page pushes the particular value)
Hence, A check is placed when retrieving search results for the feed value and The Feed recycler Data is appropriately handled
Closes #4488
=> Fixed "Searching within single podcast shows other podcasts #4488"

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
`MainAcitvity` uses default Handler constructor which is deprecated. 
[Handler docs](https://developer.android.com/reference/android/os/Handler#Handler())
It is better to replace it with best constructor matching  situation and for here I had replaced It with Looper accepting one. More specifically providing it `mainLooper()` as it is performing UI operation.
Their are multiple places where this deprecated constructor is being used but for now I had made changes on `MainAcitvity` only, was thinking that first this changes get accepted than it is better to do on remaining ones.
=> Replacing deprecated default constructor of handler with constructor that accepts Looper

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/VisitWebsiteActionButton.java
Changed VisitWebsiteActionButton onClick method to use IntentUtils class.
=> Fix 'Visit website' button crashes app if there is no browser installed

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
The previous value, no-store, did not allow CDNs to do their work.
Closes #4527
=> Set cache-control to no-cache

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
Closes #3337 
| Key | Action |
| -- | -- |
|`P` <del>`Space`/`Enter`</del>(Conflicting with dpad navigation) | Play/Pause|
| `J`/`A`/`,` | Rewind media |
| `K`/`D`/`.` | Forward media |
| `+`/`W` | Raise media volume (channel) |
| `-`/`S` | Lower media volume (channel) |
| `M` | Mute/unmute (toggle) media (volume channel; only on API > 23) |
| Key | Action |
| -- | -- |
| `P`/`Space`<del>/`Enter`</del>(Just to be save) | Play/Pause |
| `J`/`A`/`,` | Rewind media |
| `K`/`D`/`.` | Forward media |
| `F`/`Esc` | Exit video player |
| `i` | Enter picture-in-picture mode |
| `0`-`9` | Go to 0-90% of the video |
| `+`/`W` | Raise media volume (channel) |
| `-`/`S` | Lower media volume (channel) |
| `M` | Mute/unmute (toggle) media (volume channel; only on API > 23) |
=> Hardware keyboard support 

core/src/main/res/values/strings.xml
"Total size of downloaded podcasts" might be interpreted as the total cumulative size of all episodes ever downloaded. This is to improve the string so it's clear that it's about the episodes currently on the device.
=> Clarify 'downloads' statistic

README.md
- Improve readability: The words I added make it easier to read the sentence or phrase.
- Use consistent capitalization: `wiki` is spelled in lower case before, also I see no reason to capitalize it.
=> Improve readability. Use consistent capitalization.

app/src/main/res/values-sw360dp/resource-overrides.xml
Makes settings look more aesthetically pleasing and symmetrical (margin and padding-wise).
Here's an APK for your example.
[antennapod-reserved-space.zip](https://github.com/AntennaPod/AntennaPod/files/5299652/antennapod-reserved-space.zip)
=> Don't reserve icon space for settings without icons

app/src/main/java/de/danoeh/antennapod/activity/BugReportActivity.java
This stack trace regularly catches my eye, even though it is completely harmless.
=> Don't spam stacktrace when there is no crash report

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Closes #2312
With 126 feeds, this reduces the time for loading the feed list from 10 seconds to 6 seconds (measured in debug version, which is slower than release). It also reduces the memory usage significantly.
=> Improve performance and memory usage of 'recent pubdate' feed sort option

app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/res/values/strings.xml
Resolves #4320. As I understand it, the translations for all languages except the default language (English) are provided by volunteers via Transifex.
=> Edit streaming confirmation dialog labels

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
close #4276
* Smart Mark As Played -> 30 secs
* Keep Skip Episodes -> on
* Auto Skip -> on
* Delete removes from Queue -> on
* Skip End for podcast -> 31 secs
1) The item will be removed from the queue
2) The playback location history will be retain where the item was autoSkip at
3) Instead of pretending to 'end' the episode, we will stop playing, pretend we skipped, mark item as played
Also fixed a bug that was using media.getId(), media.getItem.get() - which both are wrong. Using the string from `getIdentifyingValue()` instead
=> When doing Auto Skip to End, do the right thing

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
`onCreate()` should only ever be called once, where the tables and
indices are created. Any other changes need to happen via `onUpgrade()`,
so we can safely remove `IF NOT EXISTS`.
When importing any database into the app (e.g. if it gets corrupted and
is recreated with `sqlite3 old-database.db ".dump"`), it first needs to
be set back to the correct version. This can be done in sqlite with:
$ sqlite3 old-database.db "PRAGMA user_version"
<old-db-version>
$ sqlite3 new-database.db "PRAGMA user_version = <old-db-version>"
For more context, see this PR: https://github.com/AntennaPod/AntennaPod/pull/4585
=> Remove IF NOT EXISTS from index create statements

app/src/main/res/xml/preferences_user_interface.xml
I believe this fixes #4640 .  Tested and "High Notification Priority" no longer appears in the search results.
Hopefully I did this correctly, I'm new to both open source and android dev, so if a change needs to be made just let me know.
=> prefExpandNotify search result bug fix

app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java, app/src/main/res/layout/quick_feed_discovery.xml
close #4669 
When the user choose 'Hide' in the Discover drop down, remove the 'Suggestion by iTunes' in quick discovery.
=> hide suggestion by iTunes when the user hides suggestions

core/src/main/java/de/danoeh/antennapod/core/util/comparator/FeedItemPubdateComparator.java
Perfect example where one bug fix (#4440) breaks two other things (this, #4672)
=> Fixed comparator method contract when date is null

app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java, app/src/main/java/de/danoeh/antennapod/config/PlaybackServiceCallbacksImpl.java, core/src/main/java/de/danoeh/antennapod/core/DownloadServiceCallbacks.java, core/src/main/java/de/danoeh/antennapod/core/PlaybackServiceCallbacks.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Just a small refactoring: Remove callback functions with constant return value:
* `DownloadServiceCallbacksImpl.shouldCreateReport()`
* `PlaybackServiceCallbacksImpl.useQueue()`
Contributes to #4661.
=> Refactoring: Remove callback functions with constant value

core/src/main/res/values/colors.xml, core/src/main/res/values/styles.xml
fix #4701
I used the Accessibility scanner and pick the lowest contrast to hit the 4.5 scale
=> higher contrast color for search bar

core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Some problems with wrong dates might be caused by the
static date parser no longer being thread safe.
This partially reverts commit 77ef2393365e0ff7621321f725a18ac858e50cbf.
Might cause #4648 but I can not reproduce the bug, so this is just a wild guess.
=> Partially revert "Performance improvements"

app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/androidTest/java/de/test/antennapod/ui/NavigationDrawerTest.java, app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- Replace getSystemService(Context.LAYOUT_INFLATER_SERVICE) with LayoutInflater.from
- Fix usage of obsolete junit.framework.Assert method (called new method internally, no testing needed)
=> LayoutInflater and JUnit improvements

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
fix #4217
Move the `PlaybackPreferences.clearCurrentlyPlayingTemporaryPlaybackSpeed()` to the synchronous part of the code when the episode ends, reset the speed for the next episode to pick up. 
I think this problem of the podcast speed setting not working when the phone is locked is because of this timing issue.
=> timing issue with speed settings per podcast  when moving to the next episode when phone is locked

core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
fix #2012 
A simple to fix to allow to jump to a timecode when sharing the URL of a feed item with this [SHA](https://github.com/AntennaPod/AntennaPod/commit/afb151eb3f8a83663169d0f1fcce3686be1b53f5)
Then I change TABS to spaces
=> share by timecode

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/res/layout/feeditem_fragment.xml, core/src/main/res/values/strings.xml
fix #2682 I add a TextView to the feeditem_fragment with a read-only message and set the visibility in ItemFragment.updateButtons() based on if media is null or not.
as this is my first pull request, any suggestions you can offer in the process is appreciated. thanks
=> added readonly message for feed items w/o media

core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java
Fixes #4765: Automatic download feature needs to be disabled for local podcasts
Provides a careful fix for the master branch as suggested in #4777.
=> Fix #4765: Disable autoDownload for local feeds (master branch)

app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
As requested in #4784 the same fix for the master branch:
Fixes #4776: Mark played/unplayed status should update immediately in playback history
=> Update played/unplayed status in playback history (master branch)

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java
Fixes #4775: Illegal connection pointer in Robolectric tests
Wait for all asynchronous DBWriter methods to be finished before the next unit test method starts:
```java
dbExec.awaitTermination(1, TimeUnit.SECONDS);
```
=> Fix #4775: Illegal connection pointer in Robolectric tests (awaitTermination)

core/src/main/res/values/strings.xml
Fix translations
1. Fixed wrong attribute translate to translatable in strings.xml
2. Fixed wrong key parallel_downloads_suffix in strings.xml
3. Fixed plurals in russian translation
4. Replaced triple dots with ellipses
=> Fix translations

core/src/test/java/de/danoeh/antennapod/core/util/playback/ExternalMediaTest.java
Run `ExternalMediaTest` as a unit test outside of the emulator.
=> Run ExternalMediaTest with Robolectric

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
Fixes #4757: On the "add podcast" page, pressing the search button does not use search term
=> Fix search button to forward the search query

core/src/test/java/de/danoeh/antennapod/core/storage/DbNullCleanupAlgorithmTest.java
Run `DbNullCleanupAlgorithmTest` with Robolectric outside of the Android emulator.
=> Run DbNullCleanupAlgorithmTest with Robolectric

core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java, core/src/test/java/de/danoeh/antennapod/core/util/DateUtilsTest.java
Run `DateUtilsTest` as a unit test outside of the emulator.
Important to say that I had to do some changes in the `DateUtils` class because Android ships a modified version of `SimpleDateFormat` that is not fully compatible with the JDK version. Unfortunately, Robolectric hasn't implemented an Android compatible version yet (see https://github.com/robolectric/robolectric/issues/5220).
Contributes to #4569 as it saves CPU resources even if it doesn't use Robolectric.
=> Run DateUtilsTest as Unit Test

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java, core/src/main/java/de/danoeh/antennapod/core/util/FileNameGenerator.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java, core/src/test/java/de/danoeh/antennapod/core/util/FilenameGeneratorTest.java, core/src/test/java/de/danoeh/antennapod/core/util/URLCheckerTest.java, core/src/test/java/de/danoeh/antennapod/core/util/playback/TimelineTest.java, core/src/test/java/de/danoeh/antennapod/core/util/syndication/FeedDiscovererTest.java
Run more util test classes with Robolectric outside of the Android emulator (replaces #4808):
- `FeedDiscovererTest`
- `FilenameGeneratorTest`
- `TimelineTest`
- `URLCheckerTest`
Additionally, it sets the maximum file name length in `FileNameGenerator` to 242 as CircleCI has a limitation there. (See discussion in #4808.)
=> Run more util tests with Robolectric (2)

app/src/androidTest/java/de/test/antennapod/EspressoTestUtils.java, app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
On CircleCI the following UI test fails frequently:
```
de.test.antennapod.ui.MainActivityTest > testAddFeed[test(AVD) - 9] FAILED 
androidx.test.espresso.PerformException: Error performing 'wait for a specific view for5000 millis.' on view 'is a root view.'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
```
As the feed download seems to be very slow the code has to reliably wait until the target view becomes visible. For this I introduced the helper method `EspressoTestUtils.waitForViewGlobally()` that doesn't stick to the current view root.
Also I made some small code changes to satisfy Checkstyle.
Contributes to #4194.
=> Fix MainActivityTest.testAddFeed() timeout failure

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/IPlayer.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/VideoPlayer.java
fix #2268
Adding basic auth during streaming
These pages helped me figure out ExoPlayer and Http headers
* https://stackoverflow.com/questions/31162441/setting-headers-for-streaming-mp4-video-and-playing-files-with-exoplayer
* https://stackoverflow.com/questions/28700391/using-cache-in-exoplayer
* https://stackoverflow.com/questions/21906749/stream-authenticated-video-with-mediaplayer-on-android
* https://github.com/google/ExoPlayer/issues/5371
=> send Authorization header to be able to stream password protected media

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java, core/src/test/java/de/danoeh/antennapod/core/feed/LocalFeedUpdaterTest.java
Accepts any local folder file of MIME type `image/jpeg` or `image/png` as the local feed image.
If the local folder contains an image with file name `folder.jpg`, `Folder.jpg`, `folder.png`, or `Folder.png` it is taken with preference.
If there is no image file the default local feed image (`res/raw/local_feed_default_icon.png`) is used.
Resolves #4804.
=> Use any image for local folders

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
After the larger tab navigation, the landscape mode is cutting off the image in the playing mode.
related to my fav fix :D https://github.com/AntennaPod/AntennaPod/pull/4292/files
See before
and after my fix
=> Fix cover image cut off in landscape mode

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
fix #2965 
squash version of  https://github.com/AntennaPod/AntennaPod/pull/4720
This was a hard one to track down.  Once the player is set to `PlayerStatus.INDETERMINATE` or `PlayerStatus.INITIALIZED`, the car player will not come back.  Remove those 2 lines and it works.
Using Skip
Using fast forward or wait for the episode to finish (BTW, there is a bug with the number of minutes it's showing.
=> Fix Android Auto next episode

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java, app/src/main/java/de/danoeh/antennapod/activity/WidgetConfigActivity.java, core/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/receiver/PlayerWidget.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java, core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java, core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdaterJobService.java
Instead of binding to the service, pass the required data. This also
ensures that the widget is updated instantly. JobService had the problem
that the OS sometimes took some seconds before actually executing the
job.
=> Reduce coupling between widget and playback service

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/AutoDownloadPreferencesFragment.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/ExceptFavoriteCleanupAlgorithm.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml, core/src/test/java/de/danoeh/antennapod/core/storage/ExceptFavoriteCleanupAlgorithmTest.java
This is another way of solving #2077.
The root issue is that queued episodes are never auto-deleted
currently which means that if you automatically add episodes to the
queue you will eventually end up with AntennaPod refusing to auto
download more episodes because the cache is full and it can't make
space.
This option will only refuse to delete favorited items. Otherwise it
will simply delete the oldest episodes.
=> Added new cleanup option: when not favorited

app/build.gradle, app/src/main/assets/licenses.xml, app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java, app/src/main/java/de/danoeh/antennapod/view/EpisodeItemListRecyclerView.java, build.gradle
Migrate 
- recyclerview-flexibledivider (unmaintained, replaced the library)
- leinardi speed-dial (Available on [Jitpack](https://github.com/leinardi/FloatingActionButtonSpeedDial/issues/159))
Contributes to #4930
=> Migrate away from jcenter

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java, core/src/main/java/de/danoeh/antennapod/core/service/download/handler/MediaDownloadedHandler.java, core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/RemoteMedia.java
No longer uses code duplication for opening local and remote streams.
Also, switched to OkHttp to handle redirects.
Fixes https://forum.antennapod.org/t/fehlende-kapitelmarken/673
=> Simplified chapter reader

core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java, core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3Reader.java, core/src/main/java/de/danoeh/antennapod/core/util/id3reader/model/FrameHeader.java
Previously, we relied on the string to fill the complete frame.
Some podcasts terminate the string early and leave some garbage in
the frame data. Skip that garbage, so that the reader is at a valid
frame header position when starting the next iteration.
Closes #4938
We should really add unit tests for chapter parsing. Dealing with octet-counting is pretty mind-twisting (at least to me).
=> Fix parsing chapters with multiple null bytes

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
When the activity is recreated after it was stopped in background,
the BackStackEntryCount is the same for all fragments. The one that
should display the toggle therefore thinks it shouldn't. This change
saves the button state now. This is only needed for top-level fragments.
Closes #4853
=> Fixed disappearing drawer toggle

.circleci/config.yml, app/build.gradle, build.gradle, core/build.gradle
The F-Droid build fails because they do not like the line `implementation 'com.google.android.play:core:1.8.0'`, even if it's surrounded by a check. See https://forum.antennapod.org/t/version-2-1-3-on-f-droid/703/
Also closes #4457
=> Remove free build hack

app/src/main/java/de/danoeh/antennapod/discovery/GpodnetPodcastSearcher.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/GpodderAuthenticationFragment.java, app/src/main/res/layout/gpodnetauth_credentials.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/GpodnetPreferences.java, core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java, core/src/main/java/de/danoeh/antennapod/core/sync/gpoddernet/GpodnetService.java, core/src/main/res/values-de/strings.xml, core/src/main/res/values/strings.xml
It is possible to select a custom sync server for AntennaPod.  However AntennaPod ignores the schema and port number in that URL and uses `https:` and port 443 for all servers.
This is fine for the default server (https://gpodder.net) but it prevents any server in a LAN to take over from gpodder.net as that site seems to be very busy lately and synchronization fails more often than not.
The software behind gpodder.net is open source and available at https://github.com/gpodder/mygpo.  
I managed to set it up, but failed to point AntennaPod to my server.  The reasons being:
- A normal user can only access ports >= 1024.
- On a LAN server you could only use self-signed certificates for https - which will most likely fail Androids certificate checks (as it does with other software).
- The …
=> use full URL for custom gpodder server

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlayableException.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlayableUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdaterJobService.java, core/src/play/java/de/danoeh/antennapod/core/cast/CastUtils.java, core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
Refactoring: Move inner classes `PlayableUtils` and `PlayableException` out of `Playable`.
This was discussed in https://github.com/AntennaPod/AntennaPod/pull/4911#discussion_r568122621.
=> Playable Refactoring

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java, core/src/main/res/values/strings.xml
Cancel the periodic updater before calling stopForeground so
that the notification can't come back after it has been closed.
Remove the workaround for API 30 slow notification closing because
it can cause a stuck notification. However, in order to avoid misleading
text being left on the notification if it closes slowly, ensure that
the "0 downloads" text is written to the notification when shutting down.
Fixes #4556
=> Avoid the stuck download notification

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java, config/checkstyle/checkstyle-new-code.xml, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java, core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBUpgrader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSContent.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java, core/src/test/java/de/danoeh/antennapod/core/feed/FeedItemTest.java, core/src/test/java/de/danoeh/antennapod/core/syndication/handler/AtomParserTest.java, core/src/test/java/de/danoeh/antennapod/core/syndication/handler/RssParserTest.java, core/src/test/java/de/danoeh/antennapod/core/util/playback/TimelineTest.java
- For existing episodes, moves the longer text to `description` and sets `content_encoded` to `NULL`.
- For new episodes, only stores the longer text.
- The freed up space will not be available immediately. It will be used later when adding new data to the database. We can not simply execute `VACUUM` after upgrading because `onUpgrade` is called in a transaction.
- After executing `VACUUM` on my PC, the database from #3932 decreased its size from 71.2MB to 52.8MB. This does not match the old measurements because in the experiment, I just deleted one of the columns instead of the one with the shorter text. This is still a decrease of around 25%.
- Upgrade takes around 5-10 seconds. User stays on splash screen with spinning circle. We should probably add a text "Upgrading database".
**Needs …
=> Database size: Only store content_encoded or description

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- moving while downloading sometimes caused ArrayIndexOutOfBoundsException
- Long-pressing and then swiping out leaves the screen empty and the
context menu open. Pressing items crashed the app.
Closes #4994
=> Fixed 2 little bugs related to queue movement

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
I've tested it and it works great. I've refactored to eliminate code duplication. Hope it's fine with you.
Fixes #4918
=> Exclude non-functional notification settings screen from settings search for android versions 26+

core/src/main/java/de/danoeh/antennapod/core/service/download/handler/FeedSyncTask.java
Apparently, the feature was never actually working since it was introduced in 2014...
=> Fixed getting next page of feed

app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java
Fixes #4799 and PR #4856, display full podcast title on podcast info screen.
=> Increase podcast title max lines to 6 in info fragment.

core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java, core/src/main/java/de/danoeh/antennapod/core/feed/MediaType.java
This fixes #4802 which, as was mentioned by @damoasda, is a result of incorrect mimetypes being returned for opus (and others) in Android 9 and before (maybe Android 10 too). For example, an opus file would return a mime type of `application/octet-stream`.
The PR provided here should also solve this problem for multiple other file types, by instead using the suffix (file extension) in cases where the mime type was of no help.
Screenshot:
=> Fixed certain file types not being recognized in local feeds (Closes #4802)

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Otherwise, we can see a misleading state in the miniplayer.
=> Stop service properly when playback ends

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java, core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
rebased #5037 to master
Fixes this UI issue https://forum.antennapod.org/t/beta-version-2-2-0/751/10?u=tonytamsf
- don't show double negative remain time
=> Safer remain time - default to zero when the media duration is wrong

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/AboutFragment.java, app/src/main/res/layout/feedsettings.xml, app/src/main/res/layout/settings_activity.xml
See https://github.com/TeamNewPipe/NewPipe/pull/5882. As stated in that PR, you should read over the [reasons](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0-alpha02) for the class's creation to understand why this change was made.
This doesn't close any issues that I'm aware of.
However, you should update https://github.com/ByteHamster/SearchPreference's preference dependency to [1.1.1](https://developer.android.com/jetpack/androidx/releases/preference#1.1.1) so it can take advantage of the bugfixes between 1.1.0 and 1.2.4 that pertain to FragmentContainerView.
=> Use FragmentContainerView in settings

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
The lock button controls whether tracks in the queue can be reordered and swiped. Since swipe works regardless of the "keep sorted" setting, the button to disable swipe should always be available.
Without this change, you have to disable "keep sorted", lock/unlock the queue and then activate "keep sorted" again if you want to enable/disable the swipe feature. I didn't even know that the lock function existed because I always have keep sorted active.
Slightly related to #4844
=> Show queue lock button even if "keep sorted" is active

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/main/java/de/danoeh/antennapod/dialog/FeedRefreshIntervalDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java, app/src/main/res/layout/feed_refresh_dialog.xml, app/src/main/res/xml/preferences_network.xml, core/lint.xml, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
I think i've included everything that you've requested. The tests have been updated and are passing. I think we are missing tests for setting the time, but that can be done in another PR.
Please check it out.
Closes #4708
=> New feed update interval or time dialog

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
Happens when pressing play on another episode without pausing the previous one.
=> Fix miniplayer sometimes showing old media file

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, core/src/main/res/values/strings.xml
Was introduced in 67d2287323260e0bcbfcd644a33da5402c29b383 but I
am not sure why. It is not really logical to do - removing from the
queue just means that one is no longer interested in the episode - not
that it was actually played.
=> Don't mark episodes as played when removing from queue

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
Malformed audio files can cause a crash in ExoPlayer. We have our own
id3 extractor and don't use the data of ExoPlayer, so we can just
disable parsing in ExoPlayer. This reduces the number locations where
something can go wrong that prevents playback.
https://forum.antennapod.org/t/error-unable-to-access-media-file-1000/953
=> Disable ExoPlayer id3 extraction

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
I assume we want to sync the current position if playback is being paused.
The implementation in **develop** always syncs the end position of the track being paused.
=> sync paused position on playback pause

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java, app/src/main/java/de/danoeh/antennapod/view/EmptyViewHandler.java
ViewPager2 does not play nice with SwipeRefreshLayout if the wrapped
RecyclerView is hidden. This commit removes the show/hide logic from
EmptyViewHandler, so that the RecyclerView is always displayed, even
when empty. This prevents you from swiping left/right while pulling down
the swipe refresh indicator.
The RecyclerViews will now always remain visible. This did not cause any regressions in my tests, because empty RecyclerViews do not draw anything anyway and additional Views (such as the empty list message) are absolutely positioned inside Frame or RelativeLayouts and are added after the ReyclerView, so they are still shown on top. I hope I did not miss anything :)
Fixes #5132
=> Fix stuck swipe refresh indicator

.circleci/config.yml
Contributors (including myself) will hate me for this one but it will finally avoid having xml whitespace changes in nearly every PR.
=> Add CI check that enforces layout xml file formatting

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
I'm not sure if this is intended, but for an episode without chapters, the bar gets highlighted while seeking (as with the chapters). This should fix it.
=> Highlighted seek bar while seeking on episode without chapters

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/view/ChapterSeekBar.java
Loading chapters can take around 5-10 seconds, depending on the media
type. During that time, the player screen shows nothing or the old media
file. Instead, load the chapters afterwards.
In my case, a podcast uses a 400kb image that takes ages for the parser to skip. Not sure why it takes so long - 400kb is not insanely big.
=> Speed up loading media info

core/src/main/res/drawable/ic_download.xml
The download icon is updated based on the #5137 issue.
(@mchoi8, @gregoryjtom, @mengshi24)
Closes #5137
Dark Theme             |  Light Theme
:-------------------------:|:-------------------------:
=> Update download icon

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/CancelDownloadActionButton.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/res/menu/feeditem_options.xml, app/src/main/res/menu/feeditemlist_context.xml, core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
AutoDownlaoding previously assumed that the filters had been initialised, which is not necessarily the case now that users can disable "Include in Auto Downloads" before subscribing to a new feed. This created the following problem (only present in the  develop branch):
1. Enable Auto Downloads in the Global User Preferences.
2. View a new feed (e.g. from discovery or online search).
2. Uncheck "Include in Auto Downloads".
3. Tap "Subscribe".
The "Include in Auto Download" setting is correctly set in the feed preferences (to not auto download this feed), but the newest episode of the podcast begins to automatically download.
This could be related to issue #4800
It may be preferable to instead (or also) initialise the filters when subscribing to a new feed.
(I did not know whether or not …
=> Check Auto Download preference on the feed before auto downloading

app/src/main/res/xml/preferences.xml, core/src/main/res/drawable/ic_cloud.xml
I did a user test yesterday and got the feedback that a star for the synchronization icon is weird. Replaced it with a cloud icon.
cc @thrillfall
=> Add sync icon

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/res/layout/cover_fragment.xml
I did a user test yesterday and it was the second person who wondered what clicking the title does. This is not clear if the titles have a normal length. To avoid confusion, I just removed the ripple effect.
(also, fixed scrolling too far for 3-line titles)
=> Removed highlighting of episode title

core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java
I found the root cause of the second problem metioned in #5092, where a big image is repeatedly decoded multiple times.
The root cause of the problem lies in that the class `de.danoeh.antennapod.core.glide.FastBlurTransformation` fails to provided an implementation of the method hashcode().
The `com.bumptech.glide.load.engine.EnginKey` class, used by Glide as key for indexing cached image, calculates hashcode as this:
Here, `transformations `is a `SimpleArrayMap `whose hashcode is calculated by:
Each default `Transformation `provided by Glide provides a `hashcode()` method, which usually only depends on a static `String `to identify the class of the `Transformation`. For example, the `com.bumptech.glide.load.resource.bitmap.CenterCrop`:
However, when the `transformations `array contains a …
=> Fix bug  leading to cache miss in de.danoeh.antennapod.core.glide.FastBlurTransformation

ui/png-icons/build.gradle
Subscribing otherwise crashes on Android 4.4, see https://forum.antennapod.org/t/android-4-4-2-support/1168
=> Fix png icons on Android 4.4

core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java, core/src/main/java/de/danoeh/antennapod/core/glide/ResizingOkHttpStreamFetcher.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java
All images <= 1 MB are not touched at all. All images > 1 MB are scaled down to at most 2000 px and converted to webp format. Then we iteratively decrease the quality until we are below 1 MB. Only the scaled version is saved as the "original" image in Glide. Glide might then also store possible transformations for different sizes but these are small.
If you want to try, you can use this feed: https://tools.bytehamster.com/podcast/rss.xml. It has an episode (called "Huge image") with a huge (20 MB) image. Here, the image is so large that even 5% quality produces more than 1 MB, so we just stop there and use the 1.6 MB file. I don't think an image can get much larger than RGB noise, so this should be the absolute minimum an image will ever have.
Review request @pc-bert
Related: #5057
=> Recode images to save cache space

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
When the queue is extremely long, it blocked loading the playable and therefore made playback slow to start. Closes #5024.
=> Delay loading queue until media is loaded

app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java
I noticed a bug where the wrong cover-art would be show in some cases. It seems to be related to a race condition where the load of the folder-image is almost instant and could then be replaced by an earlier triggered cover-art load by Glide. Probably also related to how GridView is recycling views when scrolling!
By explicitly calling the clear, we can remove any resources that are waiting to be loaded into the specific view/ViewTarget. 
Steps to reproduce:
1. Have at least one podcast with a folder/tag.
2. Navigate to the subscription page
3. Press the FAB/+ to add a new subscription
4. Search and add a new subscription
5. Use the android back button to navigate back all the way to the subscription page (3 steps back)
6. See that the last folder now has the cover art for the first …
=> Clear cover target when setting folder image in CoverLoader

core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java, core/src/test/java/de/danoeh/antennapod/core/syndication/handler/AtomParserTest.java, core/src/test/resources/feed-atom-testEmptyRelLinks.xml
src: https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.7.2
If the "rel" attribute is not present, the link element MUST
be interpreted as if the link relation type is
"alternate".
Fixes: #5346
=> Treat link without rel as rel=alternate

app/src/main/java/de/danoeh/antennapod/dialog/FilterDialog.java
No idea how someone could end up with that invalid value but it was reported by a user.
https://forum.antennapod.org/t/filter-option-causes-app-to-crash-on-one-podcast-broken-database/1229
=> Fix filter dialog crashing if someone has a non-supported filter value set

app/src/androidTest/java/de/test/antennapod/ui/QueueFragmentTest.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml, core/src/main/res/drawable/ic_lock_closed.xml, core/src/main/res/drawable/ic_lock_open.xml, core/src/main/res/values/strings.xml
Even though this option now has a warning dialog, it still seems to confuse users. I think there are now quite a few reasons to no longer display that option as prominently.
- Users can see the title text (and a checkbox), so they do not have to guess what the icon means
- The queue screen is more consistent with other screens (search+refresh icon)
- Swiping (which was a use-case for the lock feature) can now be disabled (and will be made slightly harder in #4844)
- By selecting "keep sorted", even reordering can be disabled
- It is an extremely specific option that is likely only used by very few users
The option is still available in the overflow menu for now but I actually would like to remove it completely in the future.
Any opinions about this change? Pinging some users who have …
=> Move queue lock feature to the overflow menu

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceStateManager.java
See [here](https://developer.android.com/reference/androidx/core/app/ServiceCompat#stopForeground(android.app.Service,%20int)).
The internal code is this:
```
public static void stopForeground(@NonNull Service service, @StopForegroundFlags int flags) {
if (Build.VERSION.SDK_INT >= 24) {
service.stopForeground(flags);
} else {
service.stopForeground((flags & ServiceCompat.STOP_FOREGROUND_REMOVE) != 0);
}
}
```
=> Use ServiceCompat.stopForeground

app/build.gradle
This contributes to https://github.com/AntennaPod/AntennaPod/issues/4930 and checks off one of the checkboxes. Version 1.2.3 does not exist on JitPack, so we must upgrade to the new release that does away with jcenter.
See https://github.com/xabaras/RecyclerViewSwipeDecorator and https://github.com/xabaras/RecyclerViewSwipeDecorator/releases.
=> Bump RecyclerViewSwipeDecorator to 1.3

CONTRIBUTING.md
Added a link directly to the Feature Request template, just like there is for the Bug Report template, so that new contributors can more easily find it. Previously, even contributors who had read through the contributing guidelines were unaware that a specific template existed for Feature Requests and would submit poorly formatted requests as a result, which then would get flagged by antennapod-bot and need to be edited.
=> Add Feature Request template link to Contributing.md

app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/RemoveFromInboxSwipeAction.java
Otherwise, setting the filter to "unplayed" wrongly removes the episode. Review request: @ueen
=> Only remove new swipe action when showing only new episodes

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/UserInterfacePreferencesFragment.java, build.gradle, core/build.gradle, core/src/main/java/de/danoeh/antennapod/core/util/gui/NotificationUtils.java, model/build.gradle, parser/feed/build.gradle, ui/app-start-intent/build.gradle, ui/png-icons/build.gradle
Reference: https://github.com/AntennaPod/AntennaPod/pull/5201#issuecomment-907605489
I even included a few compatibility improvements to, y'know, sweeten the pot a little ;)
- Remove AndroidX libraries from modules where they aren't used.
- Update AppCompat 1.2.0 -> 1.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat)) (Be sure to read the changelogs in AppCompat's internally updated dependencies as well. They'll be listed in the AppCompat changelog.)
- This includes Fragment 1.3.6, which is dealt with in the original PR I made.
- This also includes Annotation 1.2.0 and Core 1.5.0.
- Fix missing super call (this is rendered obsolete by my Fragment PR, but this must be done for now for lint to pass).
- Use an AndroidX Core feature: …
=> Update AppCompat to 1.3.x

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/WidgetConfigActivity.java, build.gradle, core/lint.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedMediaCursorMapper.java
IntelliJ's IDEA 2021.2 has been released, which [adds support for AGP 4.2.x](https://www.jetbrains.com/idea/whatsnew/#:~:text=The%20Android%20plugin%20was%20upgraded%20to%20v4.2.0.).
- Update gradle wrapper to 7.2 using git bash
- Update Triplet 3.4.0 -> 3.6.0-agp4.2 ([changelog](https://github.com/Triple-T/gradle-play-publisher/releases))
- Update Android Studio 4.1.3 -> 4.2.2 ([changelog](https://developer.android.com/studio/releases/gradle-plugin#4-2-0))
- Update dexcount-gradle-plugin 1.0.4 -> 3.0.0 ([changelog](https://github.com/KeepSafe/dexcount-gradle-plugin/releases))
- Update resourceplaceholders 0.3 -> 0.4 ([changelog](https://github.com/timfreiheit/ResourcePlaceholdersPlugin/releases))
- Fix
```
...\AntennaPod\core\src\main\java\de\danoeh\antennapod\core\preferences\UserPrefere …
```
=> Update plugins and Gradle (4.2.2)

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, build.gradle, core/build.gradle
This fixes many internal issues with Fragments that can manifest in app behavior (this includes some FragmentContainerView bugfixes as well).
Be sure to read every [version changelog](https://developer.android.com/jetpack/androidx/releases/fragment#version_135_3) from 1.2.4 (a transitive version that was used) to 1.3.6.
As onActivityResult and onRequestPermissionsResult were deprecated with Fragment [1.3.0](https://developer.android.com/jetpack/androidx/releases/fragment#version_130_3), I have replaced them with the new Activity Result APIs.
The only other deprecations that came with this update is the deprecation of setRetainInstance(boolean), and fixing that would entail a rather significant rewrite of AntennaPod to use ViewModel objects and AndroidX Lifecycle. This deprecation doesn't …
=> Update AndroidX Fragment to 1.3.6

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
We use the same ID for each overlay layout. The speed dial searches
everywhere, even in invisible fragments, so it sometimes shows/hides the
wrong overlay layout.
Fixes #5421
=> Fix FAB overlay sometimes not showing

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Otherwise, pressing the download button, pausing and coming back
shows the wrong action buttons.
Fixes #5419
=> Refresh item state on start

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java, app/src/main/res/xml/preferences_playback.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
As discussed, this also changes the default for existing users. When no one complains, we can probably simply remove the setting later.
Closes #4787
=> Pause on focus loss by default

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/CancelDownloadActionButton.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, core/src/main/java/de/danoeh/antennapod/core/feed/LocalFeedUpdater.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/handler/MediaDownloadedHandler.java, core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBUpgrader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedItemCursorMapper.java, core/src/main/java/de/danoeh/antennapod/core/storage/mapper/FeedPreferencesCursorMapper.java, core/src/test/java/de/danoeh/antennapod/core/feed/FeedItemTest.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java
The new value never got stored in the database. Also, it only got
increased by certain types of errors - all other errors could be retried
indefinitely. Also added a unit test.
Closes #5491
=> Fix auto-download retry backoff

app/src/main/java/de/danoeh/antennapod/dialog/RemoveFeedDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/actions/FeedMultiSelectActionHandler.java
When the database is huge, loading the subscription item list takes
a long time. Redirecting to the episodes screen after deleting
sometimes results in the item list starting to update before. If the
screen is then hidden before the Callable returns, the app crashes.
Closes #5319
=> Fix crash when deleting feed

app/src/main/java/de/danoeh/antennapod/activity/BugReportActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
Fixes the following lines appearing in exported logs:
```
11-13 11:37:30.293  1088  3430 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://de.danoeh.antennapod.provider/external_storage/Android/data/de.danoeh.antennapod/files/full-logs.txt from pid=4587, uid=1000 requires the provider be exported, or grantUriPermission()
11-13 11:37:30.293  1088  3430 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
11-13 11:37:30.293  1088  3430 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
11-13 11:37:30.293  1088  3430 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239) …
```
=> Fix Permission Denial when sharing files

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Do not warn if the duplicate detection did not even find the item itself,
which means that the item does not have enough metadata to be identified
correctly.
=> Reduce duplicate warnings

core/src/main/res/values-v21/styles.xml, core/src/main/res/values-v23/styles.xml, core/src/main/res/values-v27/styles.xml, core/src/main/res/values/colors.xml
Because I am more than tired of seeing that horrid bright white navbar on my otherwise completely dark screen.
During the switching process from AppCompat (1.x.x) to MaterialComponents (2.x.x) for theming, that navbar tinting for the dark modes was removed for some reason. Here's to adding it back ~~at least for API 27+ devices for now. I might add API 21-26 support in another PR~~.
This closes https://github.com/AntennaPod/AntennaPod/issues/4559 / https://github.com/AntennaPod/AntennaPod/issues/4570 (paging @hmilgraum and @xylo, cause you guys opened those two issues).
Tested on my Android 10 device.
OUTDATED SCREENSHOTS, SEE NEW ONES [HERE](https://github.com/AntennaPod/AntennaPod/pull/5422#issuecomment-950400644).
| UI changes | Before | After |
| ------------- | ------------- | …
=> Make navigation bar color match theming

core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
- Use convenience builder provided by `androidx.core.app.ShareCompat`.
- Add nullability annotations to method parameters.
=> Use ShareCompat.IntentBuilder to compose share intent.

app/build.gradle, app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java, app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java, app/src/main/res/xml/preferences_user_interface.xml, core/build.gradle, core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java, core/src/main/java/de/danoeh/antennapod/core/glide/PaletteBitmap.java, core/src/main/java/de/danoeh/antennapod/core/glide/PaletteBitmapResource.java, core/src/main/java/de/danoeh/antennapod/core/glide/PaletteBitmapTranscoder.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/res/values/strings.xml, ui/common/src/main/java/de/danoeh/antennapod/ui/common/ThemeUtils.java
Closes #5415 
Added a preference to display subscription title and changed the title `TextView` background to the dominant color in the subscription cover image instead of transparent background.
=> Add preference to show subscription title

app/build.gradle, build.gradle, core/build.gradle, net/sync/gpoddernet/build.gradle, parser/feed/build.gradle, parser/media/build.gradle, playback/base/build.gradle
This is just for easier readability.
=> Centralize library versions used in multiple modules

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java, build.gradle, core/src/main/java/de/danoeh/antennapod/core/glide/ResizingOkHttpStreamFetcher.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
This will have to be done sooner or later due to https://github.com/AntennaPod/AntennaPod/issues/4930. February 2022 is coming, whether we like it or not, and the ExoPlayer team only seems to want to host versions 2.13.3 and up on the new Maven repo. We want to do this now so that we are prepared and have ample time to fix any potential bugs. Due to Jcenter's sunsetting, it isn't just a "bigger version number somewhere in the code," it's actually integral to the continued maintenance of AntennaPod as an app.
I've merged together the ExoPlayer changes from https://github.com/AntennaPod/AntennaPod/pull/5085 and https://github.com/AntennaPod/AntennaPod/pull/4752.
I am willing to debug the hell out of this and do any testing necessary to get this merged. Feel free to ask questions regarding …
=> Update AndroidX Media and ExoPlayer

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedItemDuplicateGuesser.java, core/src/test/java/de/danoeh/antennapod/core/storage/FeedItemDuplicateGuesserTest.java
While this causes fewer false-positives for some feeds, it also prevents detecting actual duplicates for some other feeds. Maybe this is a better trade-off now.
Closes #5598
=> Only mark items as duplicates if duration and date are similar

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/receiver/ConnectivityActionReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/download/ConnectionStateMonitor.java
fix #2220 
Alternatives ways to detect network changes.  This changes has 2 subtle fixes
1) For Lollipop, there is a new way to detect network changes
2) The suggestion [here](https://stackoverflow.com/questions/36421930/connectivitymanager-connectivity-action-deprecated) to use `onAvailable()` doesn't work because some wifi is available but not active, I had to put a Thread.wait(1000) in a `Runnable()` for it work work, so I ended up using this instead https://developer.android.com/reference/android/net/ConnectivityManager.OnNetworkActiveListener
To test this change
1) Enable mobile and wifi on Android 12
2) Turn off wifi, you should see this
```
1640302894.109 31595-31633/de.danoeh.antennapod.debug D/ConnectionStateMonitor: ConnectionStateMonitor::onNetworkActive network connection …
```
=> Detect network changes with > Lollipop of Android

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
fix #5559
retarget to `master`, same as https://github.com/AntennaPod/AntennaPod/pull/5609](https://github.com/AntennaPod/AntennaPod/pull/5610)
A user playing an episode pauses it.  disconnect headset (wired and bluetooth) and reconnect again.  The episode should *NOT* be playing, but it currently starts playing incorrectly.
Looks like we are currently not detecting whether a user unplug when an episode was playing.  This broke Bluetooth and a wired headset.
=> resume playing only if the user unplugs via wired headset or bluetooth while episode in progress

core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
Here is the crash log and a simple fix
```
Android version: 12
OS version: 4.19.202-g319182f6dff7-ab7793572
AntennaPod version: 2.4.1
Model: Pixel 5a
Device: barbet
Product: barbet
Time: 02-01-2022 00:43:24
AntennaPod version: 2.4.1
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasTransport(int)' on a null object reference
at de.danoeh.antennapod.core.util.NetworkUtils.isNetworkMetered(NetworkUtils.java:107)
at de.danoeh.antennapod.core.util.NetworkUtils.isNetworkRestricted(NetworkUtils.java:96)
at de.danoeh.antennapod.core.util.NetworkUtils.isEpisodeDownloadAllowed(NetworkUtils.java:74)
at de.danoeh.antennapod.adapter.actionbutton.DownloadActionButton.onClick(DownloadActionButton.java:55)
at …
```
=> fix crash when not on network

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
Fixes the issue that the playing notification doesn't disappear when deleting the currently playing episode. This closes #3704.
=> Remove playing notification when deleting currently playing episode

app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java
Fixes a bug not yet mentioned in the issues that the sleep timer dialog in the current develop branch (3656ddc) shows too many buttons and labels (see screenshot below).
Bug occurs due to the switching to the event bus. By default, everything is shown and only if the bus reports a change, some buttons will be hidden. This change fixes this behaviour by hiding the 'disable SleepTimer' buttons by default and only enabling them if necessary.
This does not fix the problem that after opening the sleep timer dialog, it can take up to 1 second (next sleep timer tick) to load whether the sleep timer is active or not. Fixing this could be possible by using sticky events for the sleep timer - because then the sleep timer dialog would get the latest state of the sleep timer at setup and not after …
=> Don't show 'Set SleepTimer' and 'Disable SleepTimer' at the same time

app/build.gradle, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/res/layout/popup_bubble_view.xml
- Update Balloon 1.1.5 -> 1.4.0 ([changelog](https://github.com/skydoves/Balloon/releases))
- Context: https://github.com/skydoves/Balloon/releases/tag/1.2.2
- Let me know if you'd like the margins changed any (e.g. back to their margins in the "before" screenshot, etc.)
- Context: https://github.com/skydoves/Balloon/releases/tag/1.3.1
- I fixed the problem with the arrow being in the wrong place in newer versions that was mentioned [here](https://github.com/AntennaPod/AntennaPod/pull/5085).
I tested this hard. RTL also works just like before. Horizontally works fine too.
| Before | After |
| ------------- | ------------- |
| ![Screenshot_20211204-181802_AntennaPod Debug](https://user-images.githubusercontent.com/32376686/144727664-b7fc843a-048c-4ede-8776-1cbb65f7b9ff.png) | …
=> Update Balloon library

core/src/main/java/de/danoeh/antennapod/core/service/BasicAuthorizationInterceptor.java
fix #5214
This code works while testing this [feed](https://tools.bytehamster.com/podcast/passwordProtectedMedia.xml) (1st item), I'm not sure if this is the right place to fix it.  
Another way to fix this would be in the redirect interceptor but that didn't work, any ideas @ByteHamster ?
I would have rather have this fixed in [AntennapodHttpClient.java](https://github.com/AntennaPod/AntennaPod/blob/32ac7f7f7140e5d837fbe9090c4f934ee0dba1c4/core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java#L95)
```
response = response.newBuilder().request(request.newBuilder().url(location).build()).build();
```
=> follow 301 for authorization headers during download

core/src/main/java/de/danoeh/antennapod/core/service/BasicAuthorizationInterceptor.java
@tonytamsf found a fix for downloads with password+redirect not working in #5612. While streaming actually worked when that issue got created, it got broken when we switched to the OkHTTP backend for ExoPlayer in #5510. This PR fixes streaming again.
=> Fix streaming password protected media with http redirect

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
fix #3892
Explaining the fix
- Add 2 episodes never played before into the queue
- Play the 2nd episode for 10+ seconds
- Don't hit pause, play the 1st episode
- Hit next
- Before this fix, the episode starts at 0:00.  This is because getting the next item from the queue does NOT load the saved position from the DB
Note for troubleshooting for future
- I first thought it was a bug in [LocalPSMP.java](https://github.com/AntennaPod/AntennaPod/blob/f0100e61ac633516082ea112363132c99f7c0b7a/core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java#L961) in `endPlayback()`
- I started the trace through the code in [PlaybackService.java](https://github.com/AntennaPod/AntennaPod/blob/31d76b5aaec95cba01a67e28f87b799bae67a41a/core/src/main/java/de/danoeh/antennapod/core/service/pl …
=> load Media info from DB in order to grab last saved position

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
This just causes problems with keeping the preloaded list up-to-date.
We only call the method from background threads anyway.
One more step towards removing that weird `PlaybackServiceTaskManager` class.
=> Remove queue loading logic from PlaybackServiceTaskManager

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequestCreator.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/LocalFeedStubDownloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/test/java/de/danoeh/antennapod/core/service/download/DownloadRequestTest.java
This allows displaying the refresh state. Also, it is faster because
multiple local feeds can be refreshed in parallel.
Closes #5607
=> Refresh local feeds in DownloadService

app/build.gradle
Updates FloatingActionButtonSpeedDial 3.1.1 -> 3.2.0 ([changelog](https://github.com/leinardi/FloatingActionButtonSpeedDial/releases))
This brings accessibility improvements that I think could benefit some AntennaPod users.
The library now uses Maven Central as well.
Linked issues are in the changelog.
Tested APK worked fine.
=> Update SpeedDial library

.github/workflows/checks.yml, config/checkstyle/suppressions.xml
Using the checkstyle binary instead of executing it with Gradle. This makes the check significantly faster and also no longer requires restoring the gradle cache on each run.
Before: ~40-50 seconds
After: ~20-25 seconds
=> Make checkstyle CI faster

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java
Workaround was added for publishers misbehaving but the current
implementation breaks valid feeds
=> Fix line breaks in plain-text descriptions

CONTRIBUTING.md
The template files had been renamed in commit 5bef7c73.
=> CONTRIBUTING.md: fix issue template links

app/src/androidTest/java/de/test/antennapod/storage/AutoDownloadTest.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayLocalActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java, app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java, core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackServiceStarter.java, core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java, core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdaterJobService.java
Fixes a bug where local folders sometimes did not start because AntennaPod
thought it needed to play locally. Also avoids situations in which it
streams even though a local file is available. Simplifies the
PlaybackService slightly.
Closes #5723
=> Decide whether or not to stream on demand

build.gradle
Update Material Components 1.1.0 -> 1.4.0 ([changelog](https://github.com/material-components/material-components-android/releases))
Discussion about the size increase was [here](https://github.com/AntennaPod/AntennaPod/pull/5201) and was found to be very minimal. My own APK analyzation comparisons showed only tiny increases.
Tested APK worked fine.
By the way, what do you think about migrating the currently used Material design over to Material 3? Support will be official in 1.5.0. I think it'd make AntennaPod look pretty good.
=> Update Material Components library

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/DownloadStatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/StatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/about/ContributorsPagerFragment.java
I found some super calls that weren't doing anything. They can be removed with no consequence.
=> Remove unused overridden super calls

app/build.gradle, app/src/main/java/de/danoeh/antennapod/PodcastApp.java, common.gradle
=> Enable MultiDex

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadStatus.java, core/src/main/java/de/danoeh/antennapod/core/service/download/Downloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/mapper/DownloadStatusCursorMapper.java, core/src/main/java/de/danoeh/antennapod/core/util/DownloadError.java, core/src/main/java/de/danoeh/antennapod/core/util/DownloadErrorLabel.java
This is needed to separate the database handling from the `core` module without adding dependencies to the UI. The database should not depend on the UI.
Contributes to #4661
=> Simplify DownloadStatus

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Itunes.java
=> Ignore itunes:author when not child of channel

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/BugReportActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, core/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
Using `ShareCompat.IntentBuilder` takes care of all the subtleties associated with Android's share mechanism.
The `PackageManager.queryIntentActivities()` code is unnecessary. See https://issuetracker.google.com/issues/173137936
=> Use ShareCompat.IntentBuilder for all share actions

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
This was already implemented in 31c0f90d0720518705da6a86b2541c2b38b054b8
but apparently got overwritten by a merge conflict with the download
service rewrite.
Closes #5763
=> Use data folder for initial subscriptions

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java, ui/i18n/src/main/res/values/strings.xml
- Before: "Downloading podcast data"
- After:
- Only feeds are downloaded: "Refreshing podcasts"
- Only episodes are downloaded: "Downloading episodes"
- Mixed: "Downloading podcast data"
=> Simplify download notification title

app/src/main/java/de/danoeh/antennapod/asynctask/DocumentFileExportWorker.java, core/src/main/java/de/danoeh/antennapod/core/storage/DatabaseExporter.java
Use "truncate mode" so there's no chance we end up with data from the old file when overwriting and existing file.
Fixes #5819
=> Truncate existing file when exporting OPML/HTML/Favorites

core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/Downloader.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
- Only redirects when feed was parsed successfully (for misbehaving captive portals, closes #5324)
- Decouple http client from database (contributes to #4661)
=> Rewrite feed redirect handling

.github/workflows/checks.yml
Apparently, the Emulator job sometimes hangs and then uses CPU
resources for the default timeout of 6 hours.
This changes the timeout to 45 minutes.
=> Timeout CI after 45 minutes

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UsageStatistics.java, core/src/main/res/layout/popup_bubble_view.xml, ui/i18n/src/main/res/values/strings.xml
Although I mostly stream podcasts, I prefer the download button in episode lists, which allows me to quickly download multiple episodes, e.g., before traveling. This usage pattern, however, causes the on-demand configuration popup for stream vs download (added in #4121) to open infrequently. This PR adds a 'Do not ask again' button to this popup, honoring the decision of users who like to keep the Download button.
In the screenshot, the bottom of the letter __g__ is cut off. This cutoff seems unrelated to the proposed changes and also appears when only __No__ and __Yes__ are present (visible with a larger screen size).
Thank you for this great app!
=> Show on-demand configuration popup for stream vs download only once

app/build.gradle, app/src/main/res/xml/shortcuts.xml, build.gradle
- We use MultiDex now, so we no longer need dexcount
- We can use a resValue instead of a resourcePlaceholder
- Simplify getting default value of properties
=> Remove Gradle plugins that are no longer needed

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/SelectableAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/actions/EpisodeMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, app/src/main/res/layout/all_episodes_fragment.xml, app/src/main/res/menu/episodes.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemFilterQuery.java, ui/i18n/src/main/res/values/strings.xml
Closes #4971
Todo: Handle lazy loading
=> Multi-Select on 'All episodes' screen

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Not only that spares resources but it also
avoid resetting the web view and its scroll.
Closes #5917
=> Do not reload item description if not needed

app/proguard.cfg
I removed some old redundant rules from proguard. Explanations are below. No differences when decompiling APKs with APKTool.
---
The following OkHttp rules are consumed by the library itself internally as part of its own proguard file (as of [3.11.0](https://square.github.io/okhttp//changelogs/changelog_3x/#:~:text=New%3A%20Embed%20R8/ProGuard%20rules%20in%20the%20jar.%20These%20will%20be%20applied%20automatically%20by%20R8.)) (These rules were added [before](https://github.com/AntennaPod/AntennaPod/pull/2963/files) the [upgrade to that version](https://github.com/AntennaPod/AntennaPod/commit/e8be5cb8ec18d49c66abd6898a6a55d9f246c7e4).)
```
-dontwarn javax.annotation.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
-dontwarn org.codehaus.mojo.animal_sniffer.*
```
This …
=> Remove old redundant rules from proguard

app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/res/layout/list_container_fragment.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Although this roughly shares behavior with `EpisodesListFragment`, since `PlaylistHistoryFragment` already has its own separate implementation, I did not factor out lazy loading into an interface, or try to unify the implementations — that can be done in a later refactoring if deemed desirable.
I'm also not a super expert in Android or anything, so I figured I'd push a draft PR up early in case I'm way off base in how to accomplish this.
To do:
- <strike>Add new tests for the lazy loading behavior.</strike>
- <strike>Add changelog entry?</strike>
Fixes #5788.
=> Convert playback history fragment to lazy loading

app/proguard.cfg, build.gradle
I was doing some more research regarding #5903 for more ProGuard rules to clean up, and I found that the EventBus library also embeds the [ProGuard rules](https://github.com/greenrobot/EventBus/blob/master/eventbus-android/consumer-rules.pro) into itself as of 3.3.0.
See the releases: https://github.com/greenrobot/EventBus/releases
Of course, like last time, I decompiled the APKs with APKTool and diffed them with WinMerge. There was nothing missing.
I also tested it on my device and playback, navigation, etc. all worked normally.
=> Update EventBus library

app/proguard.cfg
A follow-up to #5903.
I looked at the default settings in `proguard-android.txt` provided by the SDK tools and found that these lines were duplicates. We use the `proguard-android.txt` file as the default in `common.gradle`. The file itself states:
```
```
The lines I removed in this PR were added around 2012-2013 according to the git blame. They may not have existed in the `proguard-android.txt` file at the time, and were likely meant to be a temporary bugfix until it was added upstream or something.
As with 5903, I decompiled the release APKs with APKTool and diffed them with WinMerge. There were NO differences.
=> Remove more old rules from proguard

core/src/main/java/de/danoeh/antennapod/core/preferences/SleepTimerPreferences.java
Requested on the forum (twice by the same person)
https://forum.antennapod.org/t/sleep-timer-vibrate-default-setting/2147
https://forum.antennapod.org/t/suggested-change-to-default-settings/1411
Opinions? In the last 7 years since #1072 was implemented, nobody else complained about the vibration being on by default. Still, I see that this could be a bit unexpected to have it vibrate.
=> Disable sleep timer vibration by default

.github/workflows/checks.yml, build.gradle
- Updated Checkstyle to 10.3.1 ([changelog](https://checkstyle.org/releasenotes.html)) and ran the Checkstyle task
- Replace unmaintained [diff-checkstyle](https://github.com/yangziwen/diff-checkstyle/blob/master/README.md) with [diff-check](https://github.com/yangziwen/diff-check) (by the same person)
- AdoptJDK has moved to Temurin (also known as Adoptium)
=> Update Checkstyle, use Temurin distribution

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/AddToQueueSwipeAction.java, app/src/main/res/layout/feeditemlist_item.xml, app/src/main/res/menu/episodes_apply_action_speeddial.xml, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/res/drawable-anydpi-v26/ic_playlist_shortcut.xml, core/src/main/res/drawable/ic_playlist.xml, core/src/main/res/drawable/ic_playlist_black.xml, core/src/main/res/drawable/ic_playlist_play.xml, core/src/main/res/drawable/ic_playlist_play_black.xml, core/src/main/res/drawable/ic_playlist_remove.xml, core/src/main/res/drawable/ic_playlist_shortcut.xml
I noticed that the spacing of the old drawables were inconsistent with each other. The old `playlist_play` bars are much longer and the top two are full-length. Meanwhile, the old `playlist_remove` bars were shorter and only the first top bar was full length.
The newer Material icons by Google no longer have these discrepancies.
The `playlist_play` drawable currently used is a design from 2015 (gotten from [materialdesignicons.com](https://materialdesignicons.com/icon/playlist-play), whose Google icons are pretty outdated). This drawable has had several redesigns since then, but has not been updated in AntennaPod.
There originally wasn't a `playlist_remove` drawable by Google, so we had to get a custom-made one from [materialdesignicons.com](https://materialdesignicons.com/icon/playlist-re …
=> Use new material playlist drawables

.github/workflows/checks.yml
The Espresso tests have been failing a lot lately (and then succeeded without changing anything on the fifth try). This takes a screenshot of the failed test and stores it in an artifact, so we are able to see what is going on.
=> Use atd emulator image

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, core/src/main/java/de/danoeh/antennapod/core/menuhandler/MenuItemUtils.java
With the migration in #6001, flickering of the refresh menu got more. This PR reworks the menu, so that the flicker can simply no longer happen because the spinner is not set when it is already there.
Closes #3842
=> Simplify updating refresh menu

core/src/main/java/de/danoeh/antennapod/core/util/FeedItemPermutors.java
The current smart shuffle algorithm does not work well in cases when you have one podcast with many episodes in your queue. Currently, it calculates a "spread" value for each podcast, depending on how many episodes it has, and scales each episode index with the spread. It then places all episodes of all feeds ordered by their spread value.
In the situation that your queue looks like this `A B C DD EEEEEEEEEE`, all the single-episode podcasts (`ABC`) get the same spread value. Sorting by the spread value therefore already "consumes" all single-episode feeds and puts them on top: `ABCDE_________`. It then places the ones from `E` with a spread, mixed with the second episode from `D`. This ends up with `A B C D EEEEE D EEEEE`, and does not really look shuffled. There are 5 episodes from `E` …
=> Rework smart shuffle

core/src/main/java/de/danoeh/antennapod/core/export/favorites/FavoritesWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
I noticed that queue loading takes a long time when people have ridiculously long queues. This PR makes it a little faster.
Note how getting the list of favorite episodes (to display the star icons) takes quite a significant percentage of the queue loading time. This is because instead of loading only the IDs of favorite episodes, we actually ask the database for all the items' information, and then only use the IDs. In the first commit, I change it to only load the IDs.
Notice how the favorites list (red arrow) is now only barely visible in the profiling result. The nice thing is that this favorite list is loaded for every single list, so this change makes *all* lists about 10% faster. The other thing that takes a lot of time is loading the queue itself (see the large orange block on the …
=> Database optimizations

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java, app/src/main/res/layout/episodes_list_fragment.xml, app/src/main/res/layout/feed_item_list_fragment.xml, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/layout/queue_fragment.xml, app/src/main/res/layout/quick_feed_discovery.xml, ui/i18n/src/main/res/values/strings.xml
Contributes to #5101, removing 2 of the 4 different spinners that we use
=> Use dummy items instead of loading progress bar

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/res/values/arrays.xml, model/src/main/java/de/danoeh/antennapod/model/feed/FeedCounter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, ui/i18n/src/main/res/values/strings.xml
Fixes #6011
Note that I had to leave the old value in the `FeedCounter` enum, because with that value removed, running `UserPreferences.getFeedCounterSetting()` when the pref is set to `"0"` will result in no match being found (`FeedCounter.fromOrdinal()` will find no item matching `0`).
I'm almost certain there is a better/more elegant way of doing this, so please let me know and I'll make the necessary changes.
=> Remove "inbox and unplayed" feed counter option

.github/workflows/checks.yml
Should fix failing CI on PRs targeted to `master`
Backport of #6032
=> Backport: Use atd emulator image

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportActivity.java, app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/RenameItemDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/ShareDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java
I thought I would clean up some things first before I start working on migrating the rest of the codebase over.
[Here](https://developer.android.com/topic/libraries/view-binding#fragments:~:text=Make%20sure%20you%20clean%20up%20any%20references)'s the context for declaring binding as null in `onDestroyView`.
Built and tested on my device, everything works fine.
=> Clean up some existing viewbinding stuff

build.gradle
Git blame tells me this is from 7 years ago, and seems to only be related to CircleCI. I think we can get rid of this.
=> Remove old preDexLibs code in build.gradle

app/build.gradle, app/src/main/res/xml/shortcuts.xml
New AGP versions no longer use resValues in the shortcuts file. We also cannot use the previous resourceplaceholders plugin (see bfb811d29e611146855f77df5dd97b9fb664cf25) because that plugin does not support recent AGP versions either.
Side-effect:
The shortcuts of the debug version now start the release version.
Fixes #6093
=> Fix shortcuts showing 'app not installed'

app/src/main/res/xml/provider_paths.xml
Sharing crashes on some devices with
"Failed to find configured root that contains
/storage/XXXX-XXXX/Android/data/de.danoeh.antennapod/files/media/x/y.mp3"
Might fix #6106
=> Add external-files-path to share provider

app/src/main/res/layout/cover_fragment.xml
#6067 made the cover larger than before. This restores the original size.
=> Make cover on player screen slightly smaller

app/src/main/java/de/danoeh/antennapod/fragment/InboxFragment.java, core/src/main/res/values/arrays.xml
This PR closes #6167.
* Fixed the tag name of InboxFragment in accordance with its name in ListPreference so that InboxFragment could be named matched with its Preference Name and loaded in `MainActivity::onCreate()`
=> Fix Inbox not default screen when set as such

parser/media/src/main/java/de/danoeh/antennapod/parser/media/vorbis/VorbisCommentReader.java
Could be understood as a crash, see #6162
=> Don't print full stack trace when there is no vorbis comment

.github/workflows/checks.yml, net/discovery/build.gradle, parser/feed/build.gradle, ui/glide/build.gradle, ui/statistics/build.gradle
instead of checking every module individually. This avoids having to re-state all disabled Lint checks in all parent modules.
=> Check Lint recursively from the :app module

build.gradle, common.gradle, core/build.gradle, gradle.properties
Espresso needs to be updated because it adds activities without android:exported attribute otherwise, preventing build.
We need to upgrade in order to still upload to Google Play.
=> Target API 31

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
This PR is an attempt to fix a bug (#5863) that causes the "skip" button to be unresponsive if the player is paused. Previously, the player would be **stopped** (in `PlaybackService`) if the podcast was previously paused, thus not responding to subsequent "skip" operations. I could be wrong, but I think that "stopping" the player is only necessary if the current podcast is the last podcast in your queue.
Unfortunately, the tests in `PlaybackTest `are 'flaky', so adding new tests is not really possible on my machine.
This is my first contribution to AntennaPod. So if there is anything I can improve, just let me know.
=> Fixed bug that causes "skip" button to be unresponsive

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/layout/episodes_list_fragment.xml, app/src/main/res/layout/feed_item_list_fragment.xml, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/layout/queue_fragment.xml
Dummies are slower on some devices, even when disabling their animations.
Closes #5101
=> Revert back to showing progress bars while loading

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
Instead of pausing the entire service, only pause media playback without telling the service. This has the following advantages:
- It's faster
- The position does not change (because it does not need to seek)
- We can definitely resume (because we still have a foreground service)
Especially the last point is important on Android 12, where we couldn't restart after an interruption because the service cannot be started.
Closes #6227
Closes #5803
=> Rework audio focus handling

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
Fixes #6284
(The timer sometimes still needs some time to start, so the situation can still happen. It's just a bit less likely)
=> Send first sleep timer tick earlier

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceStateManager.java
Probably closes #6250
Might even close #6049 because we then no longer go through a Start->Stop->Start state when clicking the notification
=> Don't stop service between episodes

app/src/main/res/layout/cover_fragment.xml
When text of shownotes-button are longer then the default min-with it runs in to the button border. This improoves that, please see screenshorts.
shownotes and chapters
original | fixed
--------|------
(only) shownotes
short copy for ref | original | fixed
---|--------|------
=> Fix shownotes-button text border overlap for long translations

app/src/main/res/layout/edit_tags_dialog.xml, ui/i18n/src/main/res/values/strings.xml
People regularly don't understand tags/folders. I'm still convinced that this is because "tag" is harder to understand than "folder", because tags don't have a clear mental model. For now, changing the checkbox text to be a bit more explicit. If this does not help and users are still confused, we might have to rename "tag" back to "folder".
See https://github.com/AntennaPod/AntennaPod/issues/6323#issuecomment-1434953262
=> Clarify "show in main list" checkbox title

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Apparently some servers return "Not Modified", even though a broken feed was fixed in the meantime. When refreshing all feeds, now force-refresh the feeds that previously failed.
Closes #6300
=> Force-refresh feeds that failed before

app/src/main/play/listings/en-US/full-description.txt
Based on suggestion in the forum here: https://forum.antennapod.org/t/itunes-referred-to-throughout-the-app-doesnt-exist/2725
=> Update iTunes to Apple Podcasts in Google Play

ui/i18n/src/main/res/values/strings.xml
Following up on https://github.com/AntennaPod/AntennaPod/pull/6326#discussion_r1110387894
I have a few arguments for this change:
* the main point of confusion for the user was that we didn't specify the entity (the 'what'), and that the setting was unlogically placed (making it seem to refer to 'tag' instead of 'podcast')
* 'Subscription' is actually a rather technical term. In the non-technical sense of the word, it is understood by some users as a 'paid' thing (which is why Apple [moved away](https://podnews.net/update/follow-not-subscribe) from the term).
* 'Subscription' is not used more frequently across AntennaPod than 'Podcast'
In terms of meaning, I would follow these guidelines:
* Subscriptions: refers to the collectivity of podcasts that users added in AntennPod
* Podcast: …
=> Update 'show in main list' string

app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/view/NoRelayoutTextView.java, app/src/main/res/layout/audioplayer_fragment.xml
Whenever some view calls requestLayout(), the bottom view jumps. This happens during slide when setting the player from GONE to VISIBLE. Also, it happens every time the position changes because the TextView has a dynamic width. We are not actually interested in the dynamic width and can simply keep the initial width. This avoids requestLayout() calls every time the position is updated.
Closes #5673
=> Do not jump bottom sheet when playing

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Fixes https://github.com/AntennaPod/AntennaPod/issues/5936 : Resume playback does not work when streaming after data connection drops
https://www.loom.com/share/18d918fb17f04839a90b9ab7ece8e1dc
https://www.loom.com/share/c0daf78f182f4f2aa777a6df591eb39d
=> Resume playback does not work when streaming after data connection drops

app/src/main/java/de/danoeh/antennapod/dialog/SwipeActionsDialog.java, app/src/main/res/xml/preferences_swipe.xml, ui/i18n/src/main/res/values/strings.xml
"Individual podcast" would be ambiguous here (could be misunderstood as "individual episode").
Closes #6339
=> Use more clear swipe action label

app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/MediaPlayerErrorDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java, ui/i18n/src/main/res/values/strings.xml
Closes #6302
I shortened the proposed text in #6302 significantly because it filled more than a full screen. The human readable message then looked way more scary than the actual error message (usually it's just something like "unable to connect to podcastserver.com").
=> More human readable player error message

app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java, app/src/main/res/xml/preferences_playback.xml, core/src/main/java/de/danoeh/antennapod/core/receiver/MediaButtonReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml
Android 12+ doesn't let us start the foreground service from an event like "headset reconnected". Hide the corresponding settings and avoid crashing.
=> Hide 'reconnect' settings

app/src/main/res/xml/preferences_user_interface.xml, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml
Users disable the setting and then wonder why other apps (like Android Auto) do not display the cover image, even though it says so in the setting summary.
Closes #6320
=> Remove 'set lockscreen background' setting

app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java
I have no idea what code path could pass a negative number there, but apparently there are users who experience a crash when trying to show a negative position.
Closes #6337
=> Don't crash trying to show item at negative position

core/src/main/java/de/danoeh/antennapod/core/sync/EpisodeActionFilter.java, core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
We never want to overwrite the local playback state.
Closes #5908
=> Ignore 'new' action during sync

core/src/main/java/de/danoeh/antennapod/core/sync/EpisodeActionFilter.java, core/src/test/java/de/danoeh/antennapod/core/sync/EpisodeActionFilterTest.java
I noticed an exception and stack trace on pointing AntennaPod at my home server, where the local/first episode action would have a null timestamp - we check the second/remote action's timestamp, but not the local's.
I don't believe this is a misbehaving server, although am happy to be corrected.
=> Handle a null timestamp in local/first actions

storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Apparently some devices do not support the SQLite IIF function.
Closes #6439
=> Fix queue section not loading

core/src/main/AndroidManifest.xml
This removes the arrow that is currently displayed in the tile. That arrow is only shown on tiles that open a dialog or activity.
=> Mark quick settings tile as toggleable

app/src/main/java/de/danoeh/antennapod/activity/SelectSubscriptionActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/TagSettingsDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/ui/home/HomeFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java
I have the following setup:
* A tag 'Done' with fully listened podcasts
* The subscription filter "counter greater 0"
* The subscription counter "downloaded episodes"
This way all done podcasts aren't visible in the drawer. When I want to tag another podcast as done, 'Done' isn't auto-completed. With this change all tags will be auto-completed.
=> Ignore subscription filter when suggesting tags

app/src/main/res/xml/provider_paths.xml
The library only looks at one of the external storage devices. If the exported log file doesn't happen to be stored on the first device, sharing it doesn't work.
This is a known issue in the Android libraries:
https://issuetracker.google.com/issues/37125252
This commit works around it by using an undocumented element that covers the entire file system.
Closes #6440
=> Fix file provider not being able to share all files

app/src/main/java/de/danoeh/antennapod/dialog/SubscriptionsFilterDialog.java, app/src/main/res/layout/filter_dialog_row.xml
Fixes at least the 'Counter greater 0' button in #6452 which is the same behavior as in v2.7.1
=> Make single filter button full-width

core/src/main/java/de/danoeh/antennapod/core/widget/WidgetUpdater.java, core/src/main/res/values-v31/dimens.xml, core/src/main/res/values/dimens.xml
Use 4dp like on many other places as corner radius. For Android 12+ use the launcher-chosen radius: https://developer.android.com/develop/ui/views/appwidgets#rounded-corner
=> Rounded corners of cover in widget

app/src/free/java/de/danoeh/antennapod/dialog/RatingDialog.java, ui/i18n/src/main/res/values/strings.xml
This pull request deletes the ReviewDialog class in the free build so that F-Droid users are no longer asked to do a review on Google Play. Also deleting strings that would otherwise be obsolete. Closes #6492.
=> Disable f-droid rating dialog

app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java
There should be no code path for feedItemPos to still be -1, but the crash reports indicate that it does. So this is now the dirty fix to avoid app crashes.
=> Fix crash in item pager

.github/workflows/checks.yml
This causes tons of hard-to-reproduce bugs on CI.
=> Do not cache AVD

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DownloadActionButton.java, core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/download/FeedUpdateManager.java, ui/i18n/src/main/res/values/strings.xml
WorkManager doesn't do the workaround either.
So we would launch a download that then never starts.
Closes #6631
=> No longer use 'metered' work-around for VPNs

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/CancelDownloadActionButton.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceInterfaceImpl.java, core/src/main/java/de/danoeh/antennapod/core/service/download/EpisodeDownloadWorker.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterface.java, net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterfaceStub.java
WorkManager does not tell us whether it was cancelled by the user (not retried) or by the system (retried later). So we need to delete the file and remove from queue when we know that it was actually the user. Also makes sure to always delete the file when the download fails.
Also, don't show "will retry" message on last retry attempt.
Closes #6596
=> Fix file deletion and queueing after download

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/layout/nav_section_item.xml
Part of #5925
Icon sized to be consistent with #6578
Existing "subscriptions are filtered" screenshot
New subscriptions are filtered screenshot (larger in order to use multiples of '4', but consistent with #6587)
=> Remove Iconify from SubscriptionFragment

core/src/main/java/de/danoeh/antennapod/core/service/FeedUpdateWorker.java
Updating a singletonList throws an UnsupportedOperationException, so the worker does not remove the notification
Closes #6649
=> Fix stuck notification when refreshing single feed

playback/base/src/main/java/de/danoeh/antennapod/playback/base/PlaybackServiceMediaPlayer.java
Users complained that they wanted to skip the ending of an episode and accidentally skipped the next one that started while their finger was moving.
Closes #6480
=> Ignore skip in first second of playback

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsRecyclerAdapter.java, app/src/main/res/layout/nav_listitem.xml, app/src/main/res/layout/subscription_item.xml, core/src/main/res/drawable/ic_error.xml
The icon does not have a dedicated click action, but clicking it opens the podcast page and there is a large banner with more information.
Closes #6653
cc @keunes
=> Add error icon on subscriptions screen

ui/i18n/src/main/res/values/strings.xml
Bring consistency into the punctuation of the settings, following up on [a forum comment by one of our translators](https://forum.antennapod.org/t/moving-to-title-case-for-the-app/2872/10?u=keunes).
In line with the Material Design style guide on [grammar and punctuation](https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation) (via @loucasal).
=> Remove periods for single sentences

app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java, app/src/main/res/layout/search_fragment.xml
Multi-select feature is added in the search fragment for search results.
limited context menu options for the fab button are added considering the most useful for the search result page.
if needed more features that can be done by simply changing some lines of onStartSelectMode() function of SearchFragment.java file.
For the search result page focus for searchView is handled properly to close and open the keyboard on right times.
Also, this is my first pull request. Please help if anything is wrong. This will help me a lot.
Closes #6398
=> Multi-select actions on search results

app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java, app/src/main/res/layout/time_dialog.xml
Users didn't scroll down to find the button. Now it is next to the checkbox, so it is harder to overlook.
Closes #6706
=> Make 'change times' button a settings icon

app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
Fixes #6728 
VariableSpeedDialog uses setPlaybackSpeed(float speed) method of PlaybackController to set the playback speed in the media player and also in preferences.
The major setback in the above code is that whenever the user opens the application and directly goes to change the playback speed( whether in the player fragment or global playback settings ) without trying to play any audio/video podcast it keeps the PlaybackService uninitiated NULL state.
According to the above code, it only signals the fragments to update the UI of playback speed without actually updating them into the preferences.
While adding the current playback speed to selectedSpeeds ( saved chips of speeds ), VariableSpeedDialog uses getCurrentPlaybackSpeedMultiplier() method of PlaybackController 
Due to …
=> Fix adding new playback speed preset when service is not running

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Fix #6533
The bug is on this line [#145](https://github.com/AntennaPod/AntennaPod/blob/f7a13065a9c92ba26d3686aeb18269f2313bd0b6/core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java#L145) - the call to `PlaybackPreferences.getCurrentlyPlayingFeedMediaId()` returns the episode that was playing and deinf deleted, hence it stops playing the next episode like it is supposed to.  Because it's called in a Thread, the next episode already started playing for 1 second or so and then stops
The fix will now save into the preference the correct episode that is playing on the PREPARE stage.
=> Fix sometimes stopping at the end of each episode

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
Merging #6074 has caused a new edge case for VBR audio files, in which using the seek bar to seek to the end of an episode sometimes hits the new code path, and the `skip()` function is called.
Because `skip()` invokes `endPlayback()` with `hasEnded` set to `false`, post-processing tasks are not executed unless the pre-seek position falls within the "Smart mark as played" range. If "Smart mark as played" is set to `Disabled`, or the pre-seek position is outside that range, then the episode is not marked as played, and not removed from queue.
This commit fixes that edge case by replacing `skip()` with a direct call to `endPlayback()`, with `hasEnded` set to `true`.
=> [3.2.0-beta1] Fix seeking to end using seek bar

app/build.gradle, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
Fix #6752
Honor sort order in all episode list as well as episode list per feed view in Android Auto
This is the new preference for the AllEpisodesFragment in order for this preference to be shared
`/data/data/de.danoeh.antennapod.debug/shared_prefs/de.danoeh.antennapod.debug_preferences.xml`
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<string name="prefEpisodesSort">2</string>
<string name="prefEpisodeFilter">unplayed</string>
</map>
```
=> Honor sort in episode list view in Android Auto

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
As described in #6777, when an external contoller play button is clicked, an arbitrary episode is started. It happens because on a call to the `onPlayFromSearch` method with an empty query, when, according to the [android documentation](https://developer.android.com/reference/android/media/session/MediaSession.Callback#onPlayFromSearch(java.lang.String,%20android.os.Bundle)), the app should make a decision what to play, a database search with this empty query is performed. Continuing from the last position appears more logical when just a play button is hit, so this pull requests makes the `onPlayFromSearch` method  do that when it is called with an empty query.
=> Play last episode on empty search query

app/src/main/assets/licenses.xml
We no longer use the external project, no need to keep the license
=> Remove audio player license

model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/PodcastIndex.java, parser/feed/src/test/java/de/danoeh/antennapod/parser/feed/element/namespace/RssParserTest.java, parser/feed/src/test/resources/feed-rss-testPodcastIndexTranscript.xml, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBUpgrader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemCursorMapper.java
Fix #4935 
@keunes , @ByteHamster mentioned that for the big feature for transcript, we will use the `transcript` branch and target many small PR's
This PR parses the `<podcast:transcript>` tag from a feed and store the URL of most preferred format (JSON and then SRT)
It's ready for review
Validation using the `Podnews Daily` podcast and `No Agenda`
```
sqlite> .schema
CREATE TABLE FeedItems (id INTEGER PRIMARY KEY AUTOINCREMENT ,title TEXT,pubDate INTEGER,read INTEGER,link TEXT,description TEXT,payment_link TEXT,media INTEGER,feed INTEGER,has_simple_chapters INTEGER,item_identifier TEXT,image_url TEXT,auto_download INTEGER,podcastindex_chapter_url TEXT,podcastindex_transcript_type TEXT,podcastindex_transcript_url TEXT);
sqlite> select podcastindex_transcript_type, …
```
=> Parse podcast:transcript url and store in SQLite

.github/workflows/close-if-no-reply.yml
We had this before and I thought it's maybe a bit quick. Lately, I regularly went through the issues list and saw some that are still open because of the 30 days but I don't think the authors will ever reply. So 2 weeks is probably enough.
=> Close unresponsive tickets earlier

app/src/main/java/de/danoeh/antennapod/preferences/VolumeAdaptationPreference.java, app/src/main/res/xml/feed_settings.xml, core/build.gradle, core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java, core/src/test/java/de/danoeh/antennapod/core/feed/VolumeAdaptionSettingTest.java, model/src/main/java/de/danoeh/antennapod/model/feed/VolumeAdaptionSetting.java
This is an attempt to fix #6802. I have no idea if it works (I cannot reproduce the issue on my device).
=> Check if volume boost effect is supported on the device

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, ui/i18n/src/main/res/values/strings.xml
fix #6698
(This is not a long term fix, just a patch until I can figure out why we are not getting BrowserRoot.EXTRA_RECENT)
To test this 
* Play an episode while *not* connected a car
* Plug in phone to car
* open AP
* There is a 'Current' tab that shows the current episode playing
2nd test
* Play an episode while *not* connected a car
* Delete the episode
* Plug in phone to car
* There should not be a 'current' tab
=> Show currently playing episode in Android Auto

core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java, ui/i18n/src/main/res/values/strings.xml
Apparently users are confused by RSS links. Because of https://github.com/AntennaPod/antennapod.github.io/pull/303, we can now add a title.
=> Share AntennaPod subscribe link instead of RSS url

app/build.gradle, build.gradle, common.gradle
Fixed some Gradle deprecations.
They want us to use tasks.register now, with configureEach.
Also beforeTask isn't a thing anymore, so I switched to the closest replacement.
=> Fix Gradle deprecations

app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/res/values/arrays.xml, model/src/main/java/de/danoeh/antennapod/model/feed/FeedPreferences.java, ui/i18n/src/main/res/values/strings.xml
Added extra option to "New episodes action" to add all new episodes of a subscription to the queue. This is mostly useful for local feeds where there is no downloading.
I was not sure whether to include inbox or not (setting is radio-style, so user cannot choose one or another) and I decided to include it whenever user uses queue. Not sure if that is correct or not, please advise.
This fixes #5246
=> Add option to add new episodes to queue

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/DownloadsPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/receiver/PowerConnectionReceiver.java, app/src/main/java/de/danoeh/antennapod/view/LocalDeleteModal.java, build.gradle, config/checkstyle/checkstyle.xml, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlElement.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlReader.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlSymbols.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/util/comparator/ChapterStartTimeComparator.java, core/src/main/java/de/danoeh/antennapod/core/util/comparator/PlaybackCompletionDateComparator.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Atom.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/DublinCore.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
Most files already fulfill these rules. Fix the last few remaining ones and move the rules to the main configuration file.
Some day in the future, we can then get rid of the diff-checkstyle check and do everything with the normal checkstyle. However, I want to avoid doing a large "re-format everything" commit, so we wait until almost all files comply with a rule before moving it to the main file.
=> Move some Checkstyle rules from new-code file to main file

core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlReader.java
Fix importing opml file with empty url and title
Closes #6896
=>  Fix importing opml file with empty url and title

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/view/LiftOnScrollListener.java, build.gradle, playback/cast/build.gradle
If you take the AntennaPod v3.2.0 APK, disassemble it, and look at the metadata, you'll find that most of these newer library versions were already being compiled, despite the lower versions in gradle. Basically it's #5474 again. There's no reason not to update these, since they were already being used anyway. Any possible bugs would have been evident and fixed already.
- Annotation was not 1.2.0, but actually 1.4.0. ~~I updated further to [1.7.1](https://developer.android.com/jetpack/androidx/releases/annotation).~~
- AppCompat was not 1.3.1, but 1.5.1.
- Core was not 1.5.0, but 1.8.0.
- Fragment was not 1.3.6, but 1.5.5. ~~I updated further to [1.5.7](https://developer.android.com/jetpack/androidx/releases/fragment#version_15_2).~~
- Media was not 1.4.3, but 1.6.0.
- Mediarouter was not …
=> Update AndroidX libraries

app/proguard.cfg, core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java, net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/gpoddernet/GpodnetService.java, net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudLoginFlow.java, net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/nextcloud/NextcloudSyncService.java, ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/ApOkHttpUrlLoader.java
- Fix OkHttp deprecations
- Remove [no longer needed ProGuard rule](https://square.github.io/okhttp/changelogs/changelog_4x/#version-401:~:text=Fix%3A%20Embed%20Proguard%20rules%20to%20prevent%20warnings%20from%20tools%20like%20DexGuard%20and%20R8.%20These%20warnings%20were%20triggered%20by%20OkHttp%E2%80%99s%20feature%20detection%20for%20TLS%20packages%20like%20org.conscrypt%2C%20org.bouncycastle%2C%20and%20org.openjsse.).
=> Fix OkHttp deprecations

gradle.properties
All the dependencies we use now support androidx
Closes https://github.com/AntennaPod/AntennaPod/issues/5925.
=> Remove Jetifier

app/src/main/java/de/danoeh/antennapod/fragment/preferences/dialog/PreferenceSwitchDialog.java, app/src/main/res/layout/dialog_switch_preference.xml, app/src/main/res/layout/swipeactions_dialog.xml
- Replaces the old SwitchCompat with MaterialSwitch in multi-select and swipeactions preferences. This updates the switches to the [new look](https://github.com/material-components/material-components-android/blob/master/docs/components/Switch.md).
=> Replace SwitchCompat with MaterialSwitch

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
Taken from #6944.
- Fixed a UI problem where the "add podcast" FAB was still visible underneath the SpeedDial main FAB. It should be gone when the "multi select" option is active.
~~- Fixed the SpeedDial main FAB being unlabeled in TalkBack. I used the workaround provided in https://github.com/leinardi/FloatingActionButtonSpeedDial/issues/192#issuecomment-1966084071.~~
=> Fix "add podcast" FAB still visible under SpeedDial main FAB

build.gradle, core/build.gradle, core/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/service/FeedUpdateWorker.java, core/src/main/java/de/danoeh/antennapod/core/service/download/EpisodeDownloadWorker.java, core/src/main/java/de/danoeh/antennapod/core/service/download/NewEpisodesNotification.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/sync/SyncService.java
Taken from #6940.
- Updated AndroidX Core 1.8.0 -> 1.9.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_190_2))
- Added POST_NOTIFICATIONS checks (requires the above).
=> Add POST_NOTIFICATIONS permission checks

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, app/src/main/res/xml/preferences_import_export.xml, storage/importexport/build.gradle, storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/AutomaticDatabaseExportWorker.java, storage/importexport/src/main/res/values/ids.xml, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml
Optional automatic daily database backup. Supports Nextcloud (which I haven't tested) but not Google Drive because Google did not implement support for accessing folders through the Storage Access Framework yet.
Closes #4850
=> Optional automatic daily database backup

app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/SwipeActions.java
Make swipe gestures less slippery. The sine function made the item move faster than the finger. Note that the reason for using the sine function is that the item comes to a stop gracefully instead of just stopping immediately.
See #7000
Before / After (blue=finger position, yellow=item position)
It stops a bit earlier now but the difference is not really noticeable in practice. Making it visually the same again (eg larger) would require more finger movement, making it harder to swipe.
=> Make swipe gestures less slippery

storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/AutomaticDatabaseExportWorker.java
Only consider backup files with the exact same filename pattern for deletion
See https://github.com/AntennaPod/AntennaPod/pull/6994#pullrequestreview-1944024809
=> Only consider backup files with the exact same filename pattern for deletion

storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/AutomaticDatabaseExportWorker.java, ui/i18n/src/main/res/values/strings.xml
Create automatic backups only every 3 days, update summary to include deletion of old ones
=> Create automatic backups only every 3 days, update summary

common.gradle, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Catch quick settings tile exceptions. The exception gets thrown if AntennaPod is installed in a work profile.
Closes #7001
=> Catch quick settings tile exceptions

app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java, core/src/main/java/de/danoeh/antennapod/core/feed/util/PlaybackSpeedUtils.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java
- Remove video-specific playback speed (no longer needed now that we have per-podcast speed)
- Respect changed speed setting on settings page even if the service is not running
- Do not change global speed when feed setting is updated
Closes #6916
=> Playback speed fixes

app/src/main/AndroidManifest.xml
Fix android:pathPattern not starting with a slash.
Reported through Google Play Console.
=> Fix android:pathPattern not starting with a slash

ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/ApGlideModule.java, ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/ChapterImageModelLoader.java
Fix loading chapter images in local feeds
Closes #6871
=> Fix loading chapter images in local feeds

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
The old method would sometimes crash
=> Launch splash activity after restoring backup

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DeleteActionButton.java, app/src/main/java/de/danoeh/antennapod/fragment/actions/EpisodeMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/fragment/swipeactions/DeleteSwipeAction.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceInterfaceImpl.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/APCleanupAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/APQueueCleanupAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/ExceptFavoriteCleanupAlgorithm.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedMedia.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Deleting feeds is now about 10 times faster for large databases
=> Faster feed deletion

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedItemDuplicateGuesser.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Itunes.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Media.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/DateUtils.java
Speed up feed parsing. AntennaPod is quite slow with huge feeds. The reason is that we have a bunch of workarounds for misbehaving feeds that also make it slower to work with feeds that do not misbehave.
Changes:
- Only start guessing duplicate episodes when no "proper" match is found
- Only parse non-html as HTML for attributes that really need it
- Do not log failed Long parsing when size is not specified
- Try to parse dates with RFC822 first before falling back to workarounds for other formats
I ran a benchmark with "Stuff you should know" (for which the workarounds are not needed) containing 2k episodes. Includes download of 8MB of feed XML (~5 seconds), debug build.
Before: 44 seconds, after: 13 seconds ==> **3.4 times faster feed refresh**
=> Speed up feed parsing

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/PlaybackPreferences.java
Fix playback state not being updated
Closes #7049
=> Fix playback state not being updated

core/src/test/java/de/danoeh/antennapod/core/storage/DbReaderTest.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdaterTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/FeedDatabaseWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemSortQuery.java
Remove unneeded methods from DbReader that just relay to a private method
=> Remove methods from DbReader that just call a private method

app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/DownloadsSection.java, core/src/test/java/de/danoeh/antennapod/core/storage/DbWriterTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Small database efficiency tweaks
- When checking whether there is a subscription, there is no need to create feed objects (plus counters etc). Just the number of episodes is enough.
- Downloads section only needs to load the items it actually displays.
- No need to load FeedMedia, just to load FeedItem including the same FeedMedia afterwards.
- No need to convert columns to Strings and back to Longs.
- No need to join favorites when we are only interested in the list of IDs anyway.
=> Small database efficiency tweaks

app/src/main/java/de/danoeh/antennapod/ui/screen/chapter/ChaptersFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/CoverFragment.java
Do not crash if an event comes in before the media is loaded.
Was introduced during the restructuring
=> Do not crash if an event comes in before the media is loaded

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeMultiSelectActionHandler.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/DownloadServiceInterfaceImpl.java
Don't allow downloading already downloaded episdoes again
Closes #6974
=> Don't allow downloading already downloaded episdoes again

app/src/main/java/de/danoeh/antennapod/PodcastApp.java
The message is not really relevant but almost fills a full screen. Now it just prints one line.
=> Don't spam the logs when doing unit tests

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java
Fix detection of local-only refresh. In the rare case that you have updates disabled for all feeds except local folders, AntennaPod would require a mobile data connection even though it doesn't actually need mobile data.
=> Fix detection of local-only refresh

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java, app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java, app/src/main/java/de/danoeh/antennapod/actionbutton/PlayActionButton.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedMedia.java, model/src/test/java/de/danoeh/antennapod/model/feed/FeedMediaTest.java, net/download/service-interface/src/test/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadRequestBuilderTest.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/episode/MediaDownloadedHandler.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdater.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbCleanupTests.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbNullCleanupAlgorithmTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbReaderTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbWriterTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBUpgrader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedItemFilterQuery.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/mapper/FeedMediaCursor.java, storage/database/src/test/java/de/danoeh/antennapod/storage/database/FeedItemPermutorsTest.java
Store download date database. It re-purposes the "is downloaded" column of the database to store a date instead of just 0/1, so it does not need new database columns :)
Prepares for #6716 and for automatic deletion X days after downloading, even if not played.
=> Store download date in database

app/src/main/java/de/danoeh/antennapod/ui/screen/download/DownloadLogAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/download/DownloadLogDetailsDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/SingleFeedSortDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/FeedSettingsFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbReaderTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbTasksTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbWriterTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdaterTest.java, playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/FeedDatabaseWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/feed/FeedStatisticsFragment.java
Add lazy loading to feed item list (like we already have on all other pages). This makes showing the feed page faster when the feed has a lot of episodes.
Benchmark in release mode, just the database calls. Before: 45ms, After: 9ms. ==> 5 times faster. (saving 36ms is not too much in practice. But things like these add up I guess)
=> Add lazy loading to feed item list

app/src/main/java/de/danoeh/antennapod/ui/SelectableAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java
Still not perfect because the toolbar is visible behind the action menu. However, it fixes the jumping when entering multi-select mode.
=> Hide info views in multi-select

app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionViewHolder.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionsRecyclerAdapter.java, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/layout/subscription_grid_item.xml, app/src/main/res/layout/subscription_list_item.xml, app/src/main/res/menu/subscriptions.xml, app/src/main/res/values/ids.xml, ui/i18n/src/main/res/values/strings.xml
Optionally display subscriptions as a simple list. I was mainly thinking of giving a fallback for the navigation drawer when we switch to bottom navigation. However, I quite like the list myself now because it is very clean.
Users requesting this on the forum:
https://forum.antennapod.org/t/how-to-change-subscription-view-into-list/2189
https://forum.antennapod.org/t/text-only-view-for-subscriptions/1991
https://forum.antennapod.org/t/display-subscriptions-as-list-in-addition-to-tiles/2723
=> Optionally display subscriptions as a simple list

model/src/main/java/de/danoeh/antennapod/model/feed/FeedPreferences.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBUpgrader.java
Fix default per-feed skip silence setting
Closes #7099
=> Fix default per-feed skip silence setting

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
When the position saver ticks while the service is just about to be stopped, it might happen that we first reset the position and then set it to the end again. This works around this.
Closes #7092 
Closes #5029
=> Work around race condition where position reset might be undone

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemViewHolder.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
Currently the podcast page is the only page that does not show covers. This makes the read/unread state more visible. Also, it shows the episode covers if the podcast supports that. The screen ignores the "show episode covers in lists" setting and always shows them.
Disadvantage: For podcasts that do not support episode specific covers, it now shows the cover redundantly.
Before / After (podcast not supporting episode specific covers) / After (podcast supporting episode specific covers)
Closes #7002
Closes #5148
=> Show covers on podcast page

model/src/main/java/de/danoeh/antennapod/model/feed/Chapter.java, model/src/main/java/de/danoeh/antennapod/model/feed/Feed.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedMedia.java
Closes: #7108 
The episodes were never removed from the Queue screen or the queue segment on the homescreen because no `QueueEvent`was emitted.
However, after closer inspection I found that there was already code in `DBWriter` to remove all such items:
https://github.com/AntennaPod/AntennaPod/blob/c56facd141a34d33ef38c0bdbee04a9944de8de7/storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java#L197
With more debugging I discovered that the `queue.remove` always returned false and never removed any items even if they were structurally equal. Since `FeedItem` doesn't override equal the two identical items are only equal if they are the same instance which is here never the case and therefore this never finds the matching items in the queue.
By adding the equals …
=> Implement missing equals and hashcode methods for feeditem

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateManagerImpl.java
Closes: #7136
Before when refreshing any feed(s) without network the refresh indicator stayed indefinitely.
This was also the case if you were on mobile, trying to refresh a need and in the popup selected "don't update over mobile".
I am not completely sure if this is how the fix should be implemented, maybe there is a cleaner version.
=> Fix infinite refresh indicator

.github/workflows/checks.yml, .github/workflows/runEmulatorTests.sh
GitHub switched their MacOS runners to ARM, which makes the Android emulator fail to start. Since we introduced the CI workflow, GitHub upgraded the Ubuntu runners as well, now supporting hardware acceleration. This means we no longer need MacOS. The Ubuntu runner is also about 2 times faster.
=> Switch Emulator CI to Ubuntu

app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java, app/src/main/res/menu/subscriptions.xml, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/res/xml/preferences_user_interface.xml
Move 'show subscription title' setting to subscription page. Previously, the setting was buried on the settings page. To see what it actually does, one would need to leave the settings again and go back to the subscriptions page -- just to then navigate to the settings again if one does not like the setting.
Now the setting is directly on the page that it affects.
=> Move 'show subscription title' setting to subscription page

app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/episode/ItemFragment.java, ui/common/src/main/java/de/danoeh/antennapod/ui/common/ImagePlaceholder.java, ui/discovery/src/main/java/de/danoeh/antennapod/ui/discovery/FeedDiscoverAdapter.java, ui/discovery/src/main/java/de/danoeh/antennapod/ui/discovery/OnlineSearchAdapter.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/about/SimpleIconListAdapter.java
All placeholder now have round corners matching the corner radius of the image that will eventually load.
I also added placeholder to the avatars on the contributor screen.
**Screenshots (now/earlier):**
I am quite interested in hearing some feedback about my code here. Like, I know that the GradientDrawable I used here seems somewhat questionable since we don't need a gradient. However, I couldn't get ColorDrawable to round the cornors and the ShapeDrawable and PaintDrawable were always transparent :/ 
Also another question, I initially used quite a few type inference assignments with `var x = new SomeClass()`. However, after double checking I discovered that the rest of the codebase isn't written in that style so I removed them again. So I wanted to ask again if there is a special …
=> Fix sharp corners on placeholders

app/src/androidTest/java/de/test/antennapod/ui/TextOnlyFeedsTest.java, app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
Fix tests creating FeedItems just once because of duplicate IDs
No idea why we only see the test failures now... Found them while implementing #7147 but they affect `master` as well
=> Fix tests creating FeedItems just once because of duplicate IDs

storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBWriter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Before 5218e06904e489f77da4078de775dd0a63b94ef4, deleting an item loaded its state from the database again. Now it stores the state of that object. markItemPlayed() did not reset the object's playback position, so when auto-delete was enabled, the position was overwritten again.
Closes #7092
=> Fix sometimes not resetting media position

model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java, model/src/main/java/de/danoeh/antennapod/model/feed/FeedMedia.java
Closes: #7150 
The problem was that `FeedMedia.item.id` and `FeedMedia.itemID` were able to get out of sync.
This PR now forces them to stay in sync. However, this begs the question why the `FeedMedia` class even stores the item id itself and not simply calls the item itself?
=> Fix deleting downloaded episode removes from queue

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
This was introduced in 5105cdd7 to prevent crashes on Huawei phones[1]. However, it seems this has already regressed in 376ffed5, where the setActive call was moved outside of the try-catch block.
Additionally, the problem is now 9 years old, and hopefully fixed for the users already.
[1] https://stackoverflow.com/questions/31556679/android-huawei-mediassessioncompat
=> playback: remove special handling for Huawei

net/common/src/main/java/de/danoeh/antennapod/net/common/BasicAuthorizationInterceptor.java
https://github.com/AntennaPod/AntennaPod/commit/755ccc42ece9fe30ebc989d80e9a846fa8e814f7 is the first bad commit. Yet another case of a dependency update breaking some completely unrelated part of the app. Probably because it also upgrades OkHttp with it.
=> Fix password protected feeds

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/audioplayer_fragment.xml, app/src/main/res/layout/download_log_fragment.xml, app/src/main/res/layout/feedinfo.xml, app/src/main/res/layout/feeditem_pager_fragment.xml, app/src/main/res/layout/feedsettings.xml, app/src/main/res/layout/search_fragment.xml, app/src/main/res/layout/subscription_selection_activity.xml, ui/common/src/main/res/values/styles.xml, ui/discovery/src/main/res/layout/fragment_online_search.xml
**Closes:** #7128
The problem was that the icons have their own color they use (`attr/action_icon_color`) which is fine, except in the toolbar where they should use a different color.
The fix applies a style to all toolbars where in the style only adds a theme for the surface which remaps the `attr/action_icon_color` to the color the other icons in the toolbar use.
=> Fix inconsistent icons in the app toolbar.

app/src/main/java/de/danoeh/antennapod/ui/screen/chapter/ChaptersListAdapter.java
If only some chapters have images the other chapters don't display anything but reserve space for the image.
Now those chapters display the image of the episode. If no chapters have images no images will be displayed (just like before).
**Alternative Implementation:**
We could also just remove the reserved space if the chapter has no image. This means that the items wouldn't be aligned but chapters without images would have more space to display information.
This is not my preferred solution but I am happy to hear your feedback.
**Screenshots:**
left: current, 
middle: preferred solution (this PR)
right: alternative implementation
=> Improve layout for missing chapter images

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/NoRelayoutTextView.java
NoRelayoutTextView: Enable requestLayout in more cases
=> NoRelayoutTextView: Enable requestLayout in more cases

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
Previously this was accomplished by manually subscribing to the Android Auto state. This was prone to failure, since it would only work as long as the service is running.
The correct way of handling this according to Android Auto docs[1] is to provide a valid PlaybackState when the service is bound. We accomplish this here by filling out the media session object whenever the media player is recreated.
Fixes #6698
[1] https://developer.android.com/training/cars/media/#initial-playback-state
=> Fix android auto resume on reconnect issues

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/DateUtils.java, parser/feed/src/test/java/de/danoeh/antennapod/parser/feed/element/util/DateUtilsTest.java
Reported on https://forum.antennapod.org/t/display-published-updated-dates-in-newly-imported-podcasts-list-of-episodes-instead-of-import-date/4679
=> Add new date format

net/common/src/main/java/de/danoeh/antennapod/net/common/UrlChecker.java, net/common/src/test/java/de/danoeh/antennapod/net/common/UrlCheckerTest.java
Fix UrlChecker on antennapod_local urls
=> Fix UrlChecker on antennapod_local urls

app/src/androidTest/java/de/test/antennapod/EspressoTestUtils.java, app/src/androidTest/java/de/test/antennapod/ui/TextOnlyFeedsTest.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Closes #7188
Apparently our test for exactly this did not catch this 🤔 might need to update the test: https://stackoverflow.com/a/68528795
=> Fix marking as played when there is no media

app/src/androidTest/java/de/test/antennapod/ui/FeedSettingsTest.java, app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/AutomaticDeletionPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/DownloadsPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/FeedMultiSelectActionHandler.java, app/src/main/res/menu/nav_feed_action_speeddial.xml, app/src/main/res/xml/feed_settings.xml, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/AutoDownloadPreferencesFragment.java, ui/preferences/src/main/res/xml/preferences_auto_deletion.xml, ui/preferences/src/main/res/xml/preferences_autodownload.xml, ui/preferences/src/main/res/xml/preferences_downloads.xml
Users had a hard time understanding that automatic deletion and episode cleanup are two different things. Maybe that is because in German, both got translated to the exact same string. Now both are next to each other and the titles are updated, so that it hopefully causes less confusion.
ToDo: Make strings a bit more consistent
Closes #4795
=> Move auto-delete settings

app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java, app/src/main/java/de/danoeh/antennapod/ui/view/EmptyViewHandler.java
On the search screen there was always the message "no results found" even before anything was ever searched and the message was repeated beneath it if really nothing was found by the app.
**Screenshot (Left two Before, Right ones After):**
In the `EmptyViewHandler.java` file many (but not all) private field names are prepended with the type they are of. Like the  TextView for the title is called `tvTitle`. I haven't seen such [Hungarian Notation](https://en.wikipedia.org/wiki/Hungarian_notation) in other parts of the app, so I assume they are a relict of the past. Should I also remove them since this PR already touches the file?
=> Fix redundant hints on search screen

app/src/main/java/de/danoeh/antennapod/ui/swipeactions/SwipeActions.java
Make swiping out easier. Going back to Google's default value for slow swipes. Partially reverts #5135
Closes #7000
=> Make swiping out easier

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/ToolbarIconTintManager.java
The original API used a callback where the caller needed to specify the icons of the menu items. However, the manager can find them on it's own.
Since the callback was never used for anything else, I also removed it, which now means the ToolbarIconTintManager can be used on it's own instead of instantiating an anonymous class that only overwrites the callback.
I originally stumbled upon this code when I fixed the app bar icon colors in #7163 and since then wanted to tidy it up a bit.
=> Refactor ToolbarIconTintManager to a simpler API

app/src/main/assets/shownotes-style.css
The problem has been described at length in #7139, but the links are now easier to distinguish from the other text, especially on dynamic themes.
Now all links are underlined (what the webview does per default) to better distinguish them.
Closes: #7139
=> Fix show notes link color

app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeFragment.java
If the user hasn't subscribed to any podcasts a welcome segment is shown on the homescreen. However, the scrollview with a refresh below was still there which was not only useless but could trigger an refresh at the wrong position and also tint the app bar.
**Screencast of the old behaivor:**
https://github.com/AntennaPod/AntennaPod/assets/21206831/d6aeaf4f-29d0-472c-8eb5-0a1a42e7cb42
=> Fix useless refresh on welcome home screen

app/src/main/java/de/danoeh/antennapod/ui/screen/AddFeedFragment.java, app/src/main/res/layout/addfeed.xml, ui/common/src/main/res/values/styles.xml
The search bar now looks more up to date with modern android styles. I tried to get it as close to the official documentation for [Search](https://m3.material.io/components/search/specs) as possible.
Eventually, we could update the MDC library to 1.8 and use the [SearchBar component](https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#search-bar) from there but, it is not quite easy and in two separate attempts I never got all aspects of the search to work.
For now I think this is a visual improvement.
**Screenshot (left: before, right: this PR):**
=> Improve search bar design on add podcast screen

app/src/main/res/layout/search_fragment.xml, ui/discovery/src/main/res/layout/fragment_online_search.xml
The problem was already described in #7235. This fixes that issues ~~but unfortunately now the navigation icon and all other toolbar icons on the search view have the wrong color again.~~
~~This is still better than before where many screens had the wrong icon colors, often even next to each other.~~
Edit: I since found a fix and it looks now correct everywhere 🎉
Closes: #7235
=> Fix search view regression

playback/service/build.gradle, playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ExoPlayerWrapper.java
Related PR: #5510
Basically reverts 186de76d95631bbdcd3cc4a2057321855b5a69aa
The OkHttp backend sometimes causes issues when servers cut the connection.
We had this happen after 1000s (about 17 minutes) for many users after upgrading OkHttp.
Removes proxy support for streaming.
=> Revert ExoPlayer back to default http backend

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/ToolbarIconTintManager.java, app/src/main/res/layout/feed_item_list_fragment.xml, ui/common/src/main/java/de/danoeh/antennapod/ui/common/OnCollapseChangeListener.java
First this commit improves the threshold at which the toolbar icon color is changed. We now ask the collapsing toolbar at which size it will be collapsed instead of guessing.
Second, this commit also sets the appbar title (when collapsed) to the podcast name in the podcast episode view.
I expect some pushback on this, since I implemented the updating title without asking for design first, but it was easy to implement and personally I quite like it.
I am excited to hear what you have to say about it. 😅 
**Before:**
https://github.com/AntennaPod/AntennaPod/assets/21206831/10ba3a37-b3f3-420a-ae7d-ab4158af457f 
**After:**
https://github.com/AntennaPod/AntennaPod/assets/21206831/51892589-d64e-412d-82fa-06c7e671f720 
Since we now use the correct threshold you can see that the icon color now …
=> Improve collapsing toolbar collapse state

app/src/main/assets/shownotes-style.css, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/episode/DownloadAnnouncer.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/episode/EpisodeDownloadWorker.java, ui/i18n/src/main/res/values/strings.xml
resolves (partially) #7070 
I added Talkback announcements at the start and end of download of an episode.
I'm not confident about code organization here - as far as I was able to tell, that's the only ACCESSIBILITY_SERVICE-related code in the codebase. Given how limited it is, I just placed it nearby relevant episode download code, but it could just as well be part of some accessibility component, but then again accessibility as a whole is abstracted by Android itself. That choice feels to me somewhat arbitrary and I'm new to the project.
I made a choice to announce full episode name. From what I understand, announcement can happen in a moment not directly related to user expressing their intent to download given episode, and so it seems reasonable to provide minimal (no podcast title) …
=> Announce episode download start/end with Talkback

app/src/main/AndroidManifest.xml
Remove support for deeplinking apple podcasts and SubscribeOnAndroid
See https://forum.antennapod.org/t/web-links-to-deeplink-search-and-deeplink-main-inside-the-app-dont-seem-to-be-working/5029
Google doesn't let us do that anymore if we can't verify that we own these domains.
Google Play Console:
antennapod.org: This domain passed ownership verification, but other domains in your app are failing. For users on Android 11 or older, one failing domain causes all other domains to fail. Once you have fixed or removed failing domains, users need to update their app before the links will work.
=> Remove support for deeplinking apple podcasts and SubscribeOnAndroid

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemViewHolder.java
Fix crash when accessing feed of dummy item
Closes #7269
=> Fix crash when accessing feed of dummy item

app/src/main/AndroidManifest.xml
Now that https://www.subscribeonandroid.com/.well-known/assetlinks.json exists, we can add back support for SubscribeOnAndroid.com. Removed two hosts and support for http (they have server-side redirects, which is [not supported](https://developer.android.com/training/app-links/verify-android-applinks#fix-errors))
Relates to #7286.
=> Add back SubscribeOnAndroid deeplinking

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ExoPlayerWrapper.java
Android 14 on Lenovo tablets does not intialize this AudioEffect. Catch this exception and continue playback. Closes Issue #7256
=> Android 14 on Lenovo tablets does not intialize this AudioEffect.

ui/i18n/src/main/res/values/strings.xml
Some languages use the quantity 'one' also for 11, 21, etc
Reported on Transifex
=> Some languages use the quantity 'one' also for 11, 21, etc

app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/ImportExportPreferencesFragment.java
Catch people disabling system file manager
Closes #7313
=> Catch people disabling system file manager

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/FeedSettingsFragment.java
Directly enable notifications when permission was granted. Otherwise one needs to click the setting twice
=> Directly enable notifications when permission was granted

storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Fix feed counters including non-subscribed podcasts
Closes #7331
=> Fix feed counters including non-subscribed podcasts

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java
=> Fix snackbar crash when on old Android version

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ExoPlayerWrapper.java
When podcasts use dynamic ad insertion and the media file changes between different network requests, users might experience jumps. Now, try to basically download the whole episode as soon as one hits the play button. That should avoid most of the jumps.
https://forum.antennapod.org/t/podcasts-skipping-back-and-over-content-during-stream/4911
https://forum.antennapod.org/t/player-sometimes-jumps-back-30-seconds/4601
https://forum.antennapod.org/t/podcasts-spontaneously-replay-the-last-few-seconds/4846
=> Increase buffer duration

app/src/main/res/layout/feed_item_list_fragment.xml, app/src/main/res/layout/feedinfo.xml
If the header got long (warning messages, preview description, etc), the image moved down. This created inconsistencies between feed fragment and feed info fragment.
Closes #7343
=> Keep the feed background image at the top

app/src/main/java/de/danoeh/antennapod/actionbutton/ItemActionButton.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
This makes it more clear that the podcast is not subscribed yet. It is still possible to stream or download by clicking the episodes.
Closes #7385
=> Hide play button on episode preview list

app/src/main/res/layout/simple_list_fragment.xml
Fix alignment on downloads screen
Closes #7383
=> Fix alignment on downloads screen

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/LocalPSMP.java
Check if media player is null before accessing tracks
Closes #7205
=> Check if media player is null before accessing tracks

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ExoPlayerWrapper.java
Catch crash when device does not support LoudnessEnhancer properly
=> Catch crash when device does not support LoudnessEnhancer properly

app/src/main/AndroidManifest.xml, playback/service/src/main/AndroidManifest.xml
Remove external files permission
Android documentation:
> If your app is on a device that runs API level 19 or higher,
> you don't need to declare this permission to read and write files
> in your application-specific directories.
AntennaPod supports API 21+, so the permission is completely irrelevant.
Removing it to "clean up" our permissions list on F-Droid.
=> Remove external files permission

net/common/src/main/java/de/danoeh/antennapod/net/common/NetworkUtils.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/AutoDownloadPreferencesFragment.java, ui/preferences/src/main/res/xml/preferences_autodownload.xml
Remove WiFi filter setting. 93% of our users have an Android version modern enough that the setting is not available there anyway. From the remaining 7%, probably only a tiny percentage use that setting. Removing simplifies our code and makes it easier to maintain.
=> Remove WiFi filter setting

ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/synchronization/NextcloudAuthenticationFragment.java, ui/preferences/src/main/res/layout/nextcloud_auth_dialog.xml
Better error message when nextcloud could not be reached
Closes #7244
=> Better error message when nextcloud could not be reached

ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/downloads/DataFolderAdapter.java
Allow selecting external media dirs as data directory
In addition to `/sdcard/Android/data/de.danoeh.antennapod`, this now enables `/sdcard/Android/media/de.danoeh.antennapod`. The folder is readable by other applications that have the "read storage" permission. At the same time, AntennaPod does not need the permission to write the folder.
=> Allow selecting external media dirs as data directory

storage/database/src/main/java/de/danoeh/antennapod/storage/database/NonSubscribedFeedsCleaner.java, storage/database/src/test/java/de/danoeh/antennapod/storage/database/NonSubscribedFeedsCleanerTest.java
Delete non-subscribed, non-interacted feeds earlier
=> Delete non-subscribed, non-interacted feeds earlier

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/res/layout/feedinfo.xml, ui/i18n/src/main/res/values/strings.xml, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/downloads/DownloadStatisticsListAdapter.java, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/feed/FeedStatisticsFragment.java, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/subscriptions/PlaybackStatisticsListAdapter.java, ui/statistics/src/main/res/layout/feed_statistics.xml, ui/statistics/src/main/res/layout/feed_statistics_card.xml
Modernize feed details design. Inspired by #6677. Note that the second row of statistics is new.
Closes #6677
Before/After:
ToDo:
- First line: time played, episodes started, space taken
- Click opens full dialog
- keep cards
- left aligned, 8dp padding
- look into alignment with heading
=> Modernize feed details design

app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/home_section.xml, ui/common/src/main/res/values/styles.xml, ui/discovery/src/main/java/de/danoeh/antennapod/ui/discovery/QuickFeedDiscoveryFragment.java, ui/discovery/src/main/res/layout/quick_feed_discovery.xml, ui/i18n/src/main/res/values/strings.xml
Use Material3 font styles on add podcast page. Subtle difference, but I think it looks a bit more modern.
Before/After:
ToDo:
- Move more button below
- Change label to "discover more"
- Remove headings
- Same line with "suggestions by", breaking "suggestions by"
=> Remove headings on add podcast page

storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Fix random episodes section not being random. We used "GROUP BY" without specifying which item in the group to take. Apparently, SQLite then takes a deterministic item instead of the first (randomly sorted) item.
=> Fix random episodes section not being random

app/src/main/AndroidManifest.xml
Our domain is still not verified because SubscribeOnAndroid has a redirect to www subdomain...
=> SubscribeOnAndroid has a redirect to www subdomain

ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/feed/FeedStatisticsFragment.java
Do not show estimated episode release for local folder
=> Do not show estimated episode release for local folder

app/src/main/java/de/danoeh/antennapod/ui/share/ShareDialog.java, app/src/main/java/de/danoeh/antennapod/ui/share/ShareUtils.java, app/src/main/res/layout/share_episode_dialog.xml
Show preview on share dialog. Now you can share immediately instead of having to select the radio button first.
Before/After:
=> Show preview on share dialog

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
Fix crash when opening local feed
=> Fix crash when opening local feed

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdater.java
Work around Android 5 returning 'null' duration for opus files.
Closes #7438
=> Work around Android 5 returning 'null' duration for opus files

app/src/main/java/de/danoeh/antennapod/actionbutton/DownloadActionButton.java, ui/i18n/src/main/res/values/strings.xml
Closes #6686
If a user clicks on Download Anyway, or Download Later 3 consecutive times, then remember that choice for 10 minutes and do not continue to ask the user.
- warn the user that Download over mobile is enabled for 30 minutes via a long Toast message
=> Remember choice again in mobile download anyway prompt

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/AutomaticDeletionPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/DownloadsPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/ImportExportPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/MainPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/PlaybackPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/SwipePreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/UserInterfacePreferencesFragment.java, build.gradle, common.gradle, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/AnimatedPreferenceFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/AutoDownloadPreferencesFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/NotificationPreferencesFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/about/AboutFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/about/ContributorsPagerFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/about/LicensesFragment.java, ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/synchronization/SynchronizationPreferencesFragment.java
Add predictive back gestures to settings screen.
Based on #7257, but just the settings screen for now.
=> Add predictive back gestures to settings screen

app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, net/common/src/main/java/de/danoeh/antennapod/net/common/UrlChecker.java, ui/i18n/src/main/res/values/strings.xml
=> Fix crash when opening deeplink that does not have a url

config/checkstyle/checkstyle.xml, net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/gpoddernet/model/GpodnetUploadChangesResponse.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/ItemEnqueuePositionCalculator.java
I noticed some unused imports. This PR removes them. I did not create an issue for such _small_ change, but obviously I will if really needed.
=> Remove imports only used in JavaDoc

CONTRIBUTING.md
Explain why there needs to be an issue first
Posted in some other PR:
> I did not create an issue for such small change, but obviously I will if really needed.
Creating the issue after the PR was not the point of this sentence in the documentation. Maybe this new sentence makes it a bit more clear why the issue should be first.
=> Explain why there needs to be an issue first

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java, net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SyncService.java, ui/i18n/src/main/res/values/strings.xml
- Enables users to manually trigger sync
- Makes sure that we actually refresh when a new feed arrives:
Previously, we might request the feed to be refreshed but then don't
actually wait for it to be completed because the refresh service
wouldn't start up quickly enough.
This makes sure that we do not try to sync again before the refresh
actually went through, even if the sync service is called multiple times.
Closes: #7184
ToDo later:
- When coming across an episode action that we cannot find, make sure that feeds were refreshed after that action 
- Do not upload copy of actions on full sync. This just floods servers unnecessarily and might mess up "last played" statistics
=> Sync service rework

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/LocalPSMP.java
Closes #7441
Detect whether we are using Android Auto using the code from @hades [here](https://github.com/AntennaPod/AntennaPod/pull/7053/files) 
- this fixes showing the now playing screen when users skip to next or when a podcast finishes and move to the next episode automatically
https://github.com/user-attachments/assets/f846448c-e4e6-407b-8f6b-e86686340ef6
=> new way to detect car mode to fix skip to next episode

ui/glide/src/main/java/de/danoeh/antennapod/ui/glide/FastBlurTransformation.java
Always top-align blurred image
Closes (again) #7343
CC @loucasal
=> Always top-align blurred image

storage/preferences/src/main/res/values/arrays.xml
Change default drawer order to better fit bottom navigation.
As discussed in the community call yesterday, this should be mentioned in the changelog. The changelog should also mention that one can re-order the drawer.
=> Change default drawer order to better fit bottom navigation

net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbCleanupTests.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbQueueCleanupAlgorithmTest.java
Fix autodownload tests not initializing sync service
=> Fix autodownload tests sometimes crashing because sync service is not initialized

app/src/main/java/de/danoeh/antennapod/ui/cleaner/ShownotesCleaner.java
This matches what Android does automatically for most native text views. Not perfect but good enough.
Fixes partially #7497
=> Set show notes direction to auto

app/src/main/java/de/danoeh/antennapod/actionbutton/DownloadActionButton.java, ui/i18n/src/main/res/values/strings.xml, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/feed/FeedStatisticsFragment.java
Support plurals for strings reported on Weblate
=> Support plurals for strings reported on Weblate

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, ui/common/src/main/res/drawable/ic_delete_auto.xml
- Fix auto-delete icon being black in dark theme
- Fix select menu not showing on podcast page
Closes #7514
Closes #7513
=> Select menu fixes

app/src/main/AndroidManifest.xml, build.gradle, common.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, ui/i18n/src/main/res/values-ja/strings.xml
Upgrade AGP and Gradle for Java 23 support. Tested to still support Java 17. AGP is upgraded as well but not to the latest version to keep support for IntelliJ Idea 2024.2.
Closes #7499
=> Upgrade AGP and Gradle for Java 23 support

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java
fix #7541
Do not display 'Show transcript' for episodes that do not have transcripts
=> fix bug with transcript showing up for all episodes

app/src/main/java/de/danoeh/antennapod/ui/screen/download/DownloadLogDetailsDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, ui/i18n/src/main/res/values/strings.xml
More human-readable error when feed is invalid
=> More human-readable error when feed is invalid

net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SyncService.java
Apparently requesting to run the manager cancels the already running one on some devices. This leads to an endless loop trying to refresh over and over again.
=> Wait in SyncService before enqueueing subscriptions refresh

app/src/main/res/layout/share_episode_dialog.xml
Otherwise devices with large font sizes would
push one of the items off the screen
Closes #7540
=> Limit share preview length

app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeFragment.java, ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/EchoConfig.java, ui/echo/src/main/res/values/echo-strings.xml, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/StatisticsFragment.java, ui/statistics/src/main/res/menu/statistics.xml
Add menu on statistics screen to bring back Echo
Closes #7543
=> Add menu on statistics screen to bring back Echo

app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeSection.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/DownloadsSection.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/EpisodesSurpriseSection.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/InboxSection.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/QueueSection.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/SubscriptionsSection.java, ui/i18n/src/main/res/values/strings.xml
Concatenation does not work with real translations because Android reverses the arrow symbol automatically.
=> Fix arrow direction of home more links on RTL languages

app/src/main/res/layout/external_player_fragment.xml, app/src/main/res/layout/feeditem_fragment.xml, app/src/main/res/layout/feeditemlist_item.xml
More consistent display on RTL languages
Closes #7497
=> More consistent display on RTL languages

app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java
Remember 'keep sorted' when selecting random sort
Closes #7518
=> Remember 'keep sorted' when selecting random sort

storage/database/src/main/java/de/danoeh/antennapod/storage/database/NonSubscribedFeedsCleaner.java, storage/database/src/test/java/de/danoeh/antennapod/storage/database/NonSubscribedFeedsCleanerTest.java
Fix non-subscribed feed cleaner removing feed even when episode is queued
See https://forum.antennapod.org/t/downloaded-podcasts-disappear/5881/5
=> Fix non-subscribed feed cleaner removing feed even when episode is queued

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java
Fix missing delete item for local feeds.
Also fix search fragment always showing all multi-select options.
See https://forum.antennapod.org/t/deleting-episodes-from-a-local-directory-isnt-working-anymore/5896
=> Fix missing delete item for local feeds

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Fix downloads sometimes running in notification only
=> Fix downloads sometimes running in notification only

ui/i18n/src/main/res/values/strings.xml
Consistently not use full stops. We recently did that for the global settings screen but not for the feed settings screen
=> Consistently not use full stops

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Do not collapse player when pressing more in bottom nav
Closes #7591
=> Do not collapse player when pressing more in bottom nav

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
Fix crash when intent is redelivered
=> Fix crash when intent is redelivered

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
Fix stop of local mediaSession immediately cancelling Cast playback
Closes #7276
=> Fix stop of local mediaSession immediately cancelling Cast playback

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java, ui/i18n/src/main/res/values/strings.xml, ui/notifications/src/main/java/de/danoeh/antennapod/ui/notifications/NotificationUtils.java
Closes #7079 
That is, I created a seperate refresh notification channel and updated the wording of the download notification channel
- ~[ ] If it is a core feature, I have added automated tests~
=> Split notification channel of downloading and refreshing

app/src/main/java/de/danoeh/antennapod/ui/screen/home/sections/SubscriptionsSection.java
Closes #7469 
There is still an issue with this PR. I think I've found the right spot, but somehow it still doesn't filter anything out. I even used "empty" time frames (filter between `now + 1` and `now +2`), but I still always get all podcasts.
Can someone please tell me if I made an issue, or if I have to debug the SQL-Statement a bit more? Thank you so much!
=> Limit "check your classics" to the last 3 years

app/src/main/java/de/danoeh/antennapod/ui/screen/download/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/PlaybackPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/UserInterfacePreferencesFragment.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/res/xml/preferences_downloads.xml, ui/preferences/src/main/res/xml/preferences_playback.xml, ui/preferences/src/main/res/xml/preferences_user_interface.xml
resolves #7012
This PR adds a setting to configure Delete button action.
Allows switching Delete button to Play/Pause.
Created Episode Lists group in User Interface settings
moved Swipe actions, Prefer Streaming and the Play/Pause button in Downloads list.
=> Add option to have Play/Pause button in Downloads

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Support closing miniplayer by swiping down. Closes #7360. This was easier to implement than I expected and works very well even on small screens. It works even better when bottom navigation is enabled.
=> Support closing miniplayer by swiping down

app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/UnsupportedFeedtypeException.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/util/TypeGetter.java
Show website title in 'server sent a website' error. Titles like "Log into this free WiFi", "Confirm that you are human", and similar should make it easier to see why the server returned a website.
See https://forum.antennapod.org/t/unsupported-feed-type-still-getting-new-episodes/6073
=> Show website title in 'server sent a website' error

ui/common/src/main/res/values/styles.xml
Fix system bar background in black theme
Closes #7630
=> Fix system bar background in black theme

app/src/main/java/de/danoeh/antennapod/actionbutton/DownloadActionButton.java, app/src/main/java/de/danoeh/antennapod/ui/StreamingConfirmationDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, ui/i18n/src/main/res/values/strings.xml
Tweak error messages related to feed types again, addition to #7629. If a user entered a url manually, show a different error message: "You entered a website address" instead of "Server returned a website". When showing the error message about trying to download on metered networks, also say something about non-VPN users (even though VPN users are the vast majority or users having this problem).
Closes #7632
=> Tweak error messages related to feed types again

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
This branch loads all episodes before doing anything in multiselect.. This solves the issue #7461 where not all episodes are loaded.
Fixes #7461 
- ~[ ] If it is a core feature, I have added automated tests~
=> Fix multiselect with lazy loading on podcast screen

model/src/main/java/de/danoeh/antennapod/model/feed/FeedItem.java
Fix transcript type not getting updated.
CC @Shaac @luleyleo
=> Fix transcript type not getting updated

app/src/main/res/layout-sw720dp/main.xml, app/src/main/res/layout/main.xml, ui/common/src/main/res/values/styles.xml
Reduce font size of bottom navigation.
See https://forum.antennapod.org/t/bottom-navigation-enhancements-improvements/5720/8
=> Reduce font size of bottom navigation

app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/main/java/de/danoeh/antennapod/ui/screen/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/RenameFeedDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/EditUrlSettingsDialog.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/edit_text_dialog.xml, ui/discovery/src/main/res/layout/quick_feed_discovery.xml, ui/i18n/src/main/res/values/strings.xml, ui/preferences/build.gradle
Increase touch target size of buttons. Google Play warns about these otherwise
=> Increase touch target size of buttons

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/FeedSettingsFragment.java, app/src/main/res/xml/feed_settings.xml
We migrated from a checkbox to a list preference.
The (unused) stored value causes a ClassCastException
Closes #7649
=> Fix crash on feed settings page

app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/HorizontalFeedListAdapter.java
Fixes #7609
This is just a small hotfix that checks if the activity is null before the crash happens due to the activity being null. If the bug should be fixed in a different way, just tell me :)
=> Fix multi-select staying enabled when leaving search

ui/i18n/src/main/res/values/strings.xml
Mention that 'new episode action' disables autodownload.
Workaround until we complete the rewrite of autodownload.
=> Mention that 'new episode action' disables autodownload

app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/FeedMultiSelectActionHandler.java
Enable 3-state auto-download setting in multi-select
Closes #7655
=> Enable 3-state auto-download setting in multi-select

ui/i18n/src/main/res/values/strings.xml, ui/preferences/src/main/res/layout/gpodnetauth_finish.xml, ui/preferences/src/main/res/values/arrays.xml
Remove duplicate strings. That's just unnecessary work for translators and might lead to inconsistencies
=> Remove duplicate strings

net/common/src/main/java/de/danoeh/antennapod/net/common/RedirectChecker.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/remote/HttpDownloader.java, net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SyncService.java
Connect to each newly added URL with a HEAD request. If there is a redirect to an existing URL, ignore the added feed.
This does not handle `itunes:new-feed-url` or other redirects. This will likely still cause problems with synchronization because the server still knows the old url. However, it makes the situation better than it was before by avoiding the duplicates. For a proper fix, we need a new protocol that can deal with redirects more elegantly (see #6506).
Closes #2214
=> Partially work around duplicated feeds when using sync

app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/DrawerPreferencesDialog.java, ui/i18n/src/main/res/values/strings.xml
Hide subscription list setting when using buttom navigation
See https://forum.antennapod.org/t/bottom-navigation-feedback/6277
=> Hide subscription list setting when using buttom navigation

app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java
Fixes: #7519
Hi,
This pull request changes the "date" and "smart shuffle" queue sorting criteria, both of which are sorted as descending by default at the moment, to ascending. This makes all queue sorting criteria now sort as ascending by default, which improves consistency.
- [x ] I have read the contribution guidelines: https://github.com/AntennaPod/AntennaPod/blob/develop/CONTRIBUTING.md#submit-a-pull-request
- [x ] I have performed a self-review of my code
- [x ] I have run the automated code checks using `./gradlew checkstyle spotbugsPlayDebug spotbugsDebug :app:lintPlayDebug`
- [x ] My code follows the style guidelines of the AntennaPod project: https://github.com/AntennaPod/AntennaPod/wiki/Code-style
- [x ] I have mentioned the corresponding issue and the relevant keyword (e.g., …
=> Ascending order for date-based sorting in queue

net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbReaderTest.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/episode/autodownload/DbTestUtils.java
Fix flaky test sorting by release date
=> Fix flaky test sorting by release date

app/src/main/res/layout/floating_select_menu.xml, app/src/main/res/layout/floating_select_menu_item.xml
Tweak padding of floating select menu
Fixes partially #7462
=> Tweak padding of floating select menu

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/SleepTimerDialog.java
When you first try to set a sleep timer with no media playing you get an error saying that no media is playing.
But if you start playing and then stop playing and try to set a sleep timer you're allowed.
This fixes the inconsistency and doesn't care if it first playback or subsequent playbacks, it will behave the same way - it will not let you create a sleep timer unless something is playing.
Fixes #7246
=> Consistently do not allow to set sleep timer if no media is playing

storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBUpgrader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
We check the feed id and the item id when removing from favorites. However, the item ids are unique, so there is no need to check the feed id. Actually, I have no idea why it was even added there in the first place.
Now that we have users who somehow ended up with a database where they cannot un-favorite some of the items, removed the check.
Also make sure to clear the favorites table when deleting a feed.
Closes #7718
=> Fix removing items from favorites

net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterface.java, net/download/service-interface/src/main/java/de/danoeh/antennapod/net/download/serviceinterface/DownloadServiceInterfaceStub.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/episode/autodownload/AutomaticDownloadAlgorithm.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/DownloadServiceInterfaceImpl.java
This prevents auto-download ending up downloading more episodes than intended.
Closes #7707
=> Count running downloads towards number of downloaded episodes

ui/common/src/main/res/drawable/scrollbar_thumb_default.xml, ui/common/src/main/res/drawable/scrollbar_thumb_pressed_dark.xml, ui/common/src/main/res/drawable/scrollbar_thumb_pressed_light.xml, ui/common/src/main/res/drawable/scrollbar_track.xml
Actually, the touchable area has the exact same size as before. Still, it feels easier to grab because it looks larger. It's just a psychological change but it does help a lot. We can't really make it larger because it would otherwise interfere with the buttons (we had that before, see #3400).
Closes #6864
=> Make scroll bar easier to grab

playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ShakeListener.java
Added a small vibration when the phone is shaken to reset the sleep timer so the user has feedback that the reset was applied.
Right now the user has no idea if the reset was applied or not, it's hard to tell when shake to reset is applied, a small vibration will give the user feedback.
=> Added a small vibration when the phone is shaken to reset the sleep timer

app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/ui/view/EmptyViewHandler.java, app/src/main/res/layout/empty_view_layout.xml, ui/i18n/src/main/res/values/strings.xml
If the queue is empty but there are new episodes in the inbox, a message informs the user of this and provides a button that redirects to the inbox. If the queue is either not empty or if the queue and inbox are both empty, then the messages are unchanged.
This commit changes the EmptyViewHandler to include a button field that is hidden by default. This is my first submission so please feel free to let me know if anything is askew.
Closes: #7538
=> Add button to inbox from queue

net/discovery/build.gradle
Switch dependency version on JitPack. Who knows what happened exactly, but JitPack changed something to the way they deliver dependencies. The version with the v prefix got rebuilt (files inside jar have a new time stamp, jar has a new hash, but contents are the same). Now it no longer has any dependencies attached to it. Switching to the version without v, which still works.
=> Switch dependency version on JitPack

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/preferences/FeedSettingsPreferenceFragment.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/FeedDatabaseWriter.java
Fix new episodes action for local feeds
Closes https://forum.antennapod.org/t/refresh-of-local-folder-no-longer-adds-new-episodes-to-queue/6490
=> Fix new episodes action for local feeds

app/src/main/res/layout/floating_select_menu.xml
Closes https://github.com/AntennaPod/AntennaPod/issues/7462
Tried to implement the fade out effect in the bottom multi-select menu, as discussed here.
> We discussed at the Needs decision meeting:
> We experimented a bit and added spacing on top, and made elements a bit narrower where possible (more word breaks, decrease size if there's short words) while increasing the padding both on top and between items.
> 
> The only thing that's left: fading - which we agree but needs to be implemented still. 
_Originally posted by @keunes in [#7462](https://github.com/AntennaPod/AntennaPod/issues/7462#issuecomment-2738121465)_
|Before|After|
|---|---|
I changed the clipping of the HorizontalScrollView in thie PR to `true`, I personally thought it looked better. But UI stuff is always highly …
=> Implement fading effect in multi-select bottom menu

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java, playback/service/src/main/java/de/danoeh/antennapod/playback/service/internal/ExoPlayerWrapper.java
Fix crash in PlaybackService. When service is quickly stopped again due to a playback error, background tasks might not have delivered their result yet. In this case, the service objects already get cleaned up. Now, if the result gets delivered, the service is in an invalid state.
This solves stack traces mentioned in #7135, #6549, #6772, #7182, #7664 and probably more. It probably does not fix these issues, but it at least solves the recorded crash. This is also one of the more common crashes reported through Google Play.
=> Fix crash in PlaybackService

net/discovery/src/main/java/de/danoeh/antennapod/net/discovery/PodcastSearcherRegistry.java
Faster search by removing fyyd from default providers
=> Faster search by removing fyyd from default providers

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/ui/SelectableAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/home/HomeFragment.java, app/src/main/java/de/danoeh/antennapod/ui/view/BottomSheetBackPressedCallback.java
This does not add animations between fragments, but it adds animations to UI elements like bottom sheets.
Replaces #7257
=> Add Predictive Back Gestures

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavDrawerFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java, ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/MainActivityStarter.java, ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/OnlineFeedviewActivityStarter.java, ui/discovery/src/main/java/de/danoeh/antennapod/ui/discovery/OnlineSearchFragment.java, ui/discovery/src/main/java/de/danoeh/antennapod/ui/discovery/QuickFeedDiscoveryFragment.java, ui/statistics/src/main/java/de/danoeh/antennapod/ui/statistics/feed/FeedStatisticsDialogFragment.java, ui/widget/src/main/java/de/danoeh/antennapod/ui/widget/WidgetUpdater.java
Fix back stack being cleared after searching
=> Fix back stack being cleared after searching

app/src/main/java/de/danoeh/antennapod/actionbutton/MarkAsPlayedActionButton.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/download/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/episode/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/ui/swipeactions/RemoveFromQueueSwipeAction.java, app/src/main/java/de/danoeh/antennapod/ui/view/LocalDeleteModal.java, app/src/main/res/layout/transcript_dialog.xml, app/src/main/res/menu/episodes_apply_action_speeddial.xml, app/src/main/res/menu/feeditem_options.xml, app/src/main/res/menu/feeditemlist_context.xml, ui/i18n/src/main/res/values/strings.xml
As discussed in https://github.com/AntennaPod/AntennaPod/pull/7696#discussion_r2019828358
The naming of strings is quite unorganized and inconsistent. This PR organizes the FeedItem Action section of strings.xml (as it was relevant to https://github.com/AntennaPod/AntennaPod/pull/7696) by renaming some items for consistency and grouping related items together.
This is the first part of an ongoing effort to improve strings.xml.
=> Organize FeedItem(s) action section of strings.xml

app/src/androidTest/java/de/test/antennapod/ui/FeedSettingsTest.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/SelectSubscriptionActivity.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/HorizontalItemViewHolder.java, app/src/main/java/de/danoeh/antennapod/ui/screen/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/InboxFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/download/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/download/DownloadLogAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/episode/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/episode/ItemPagerFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/AudioPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/playback/video/VideoplayerActivity.java, app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/queue/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/FeedMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionViewHolder.java, app/src/main/java/de/danoeh/antennapod/ui/swipeactions/RemoveFromHistorySwipeAction.java, app/src/main/java/de/danoeh/antennapod/ui/swipeactions/RemoveFromQueueSwipeAction.java, app/src/main/java/de/danoeh/antennapod/ui/view/ShownotesWebView.java, ui/app-start-intent/src/main/java/de/danoeh/antennapod/ui/appstartintent/MainActivityStarter.java
We can do that using an event.
This commit fixes one of the most prominent crashes on Google Play where we cast the OnlineFeedViewActivity to MainActivity.
=> Don't cast class to MainActivity to show message

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java
Fix crash when clicking buttons when feed is not loaded yet
Closes #7787
Closes #7786
=> Fix crash when clicking buttons when feed is not loaded yet

app/src/main/res/xml/feed_settings.xml, ui/i18n/src/main/res/values/strings.xml
Clarify that auto-download happens from inbox
See https://github.com/AntennaPod/AntennaPod/issues/7784
=> Clarify that auto-download happens from inbox

net/sync/gpoddernet/src/main/java/de/danoeh/antennapod/net/sync/HostnameParser.java
Don't crash when using invalid characters in host name
Closes #7783
=> Don't crash when using invalid characters in host name

ui/preferences/build.gradle
Upgrade SearchPreference library
Closes #7777
=> Upgrade SearchPreference library

storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/StatisticsItem.java, ui/echo/src/main/java/de/danoeh/antennapod/ui/echo/screen/HoarderScreen.java
Fixes #7547
This PR updates the Echo "check out again" recommendation logic.  
Now, only podcasts that have released at least one episode in the past 6 months and still have unplayed episodes are suggested.  
If a podcast title is empty, the feed identifier is used as a fallback.
Manually tested: The Echo screen now only suggests appropriate podcasts, and titles are displayed correctly.
=> Fix Echo "check out again" recommendation logic

app/src/main/java/de/danoeh/antennapod/ui/view/ShownotesWebView.java
Work around crashing WebView. I have only seen repeated WebView crashes on GrapheneOS, but maybe this also helps other systems.
=> Work around crashing WebView on GrapheneOS

net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SyncService.java, net/sync/service/src/main/java/de/danoeh/antennapod/net/sync/service/SynchronizationQueueStorage.java
When `queuedRemovedFeeds` and `queuedAddedFeeds` intersect when syncing subscriptins, remove the subscription from added or removed feeds to match the current local subscription status.
Closes #7570
=> Fix sync queue state if a feed is both added and removed

parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Atom.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Media.java, parser/feed/src/main/java/de/danoeh/antennapod/parser/feed/namespace/Rss20.java
If a feed has a broken mime type that is not audio or video, try to still use it as audio (if there is no audio yet). This might lead to AP trying to play random other files that are not media files, but it works around publishers messing up their mime types.
See https://forum.antennapod.org/t/episode-does-not-contain-a-media-file-on-private-podcast/6785/
=> Work around feeds with broken mime type

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, app/src/main/res/layout/feed_item_list_fragment.xml
When viewing episodes in what I think is the podcast preview screen / BottomSheet, the scroll position is now being remembered when viewing details of an episode and going back.
Closes #7767
| <img src="https://github.com/user-attachments/assets/8a78af44-8689-406d-aff7-16cbd22dbfc0" width="200"/> | <img src="https://github.com/user-attachments/assets/9d2e9938-a766-4d55-bc3f-65c54dc64e82" width="200"/> | <img src="https://github.com/user-attachments/assets/9b0dfada-27e9-4666-bbcc-bb992dc70580" width="200"/> |
|---|---|---|
=> Fix scroll position in episode list of podcast preview

app/proguard.cfg
Proguard removed some classes the app needed for the Fyyd search.
Closes #7866
=> Let proguard keep needed RxJava and fyydlin files for Fyyd search 

app/src/main/java/de/danoeh/antennapod/ui/screen/SearchFragment.java
Fix hiding playlist on search screen
Closes #7861
=> Fix hiding "add to queue" on search screen

storage/importexport/src/main/java/de/danoeh/antennapod/storage/importexport/AutomaticDatabaseExportWorker.java
One user reports that, when enabling automatic database export, files get created but not deleted. This is somewhat  hard to debug without direct access to that users phone.
Also, there is currently no code to check if deletion was actually successfull. Instead it is assumed that it always succeeds when a directory can be written to, which might be wrong for some devices.
This PR adds code to check if backup files could be deleted and show an error message to the user if not. This could be used as a starting point for further investigation.
Supports #7869
=> Communicate to user if db backup files could not be deleted

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
Fix 'all episodes' on Android Auto not respecting filter
Closes #7837
=> Fix 'all episodes' on Android Auto not respecting filter

playback/service/src/main/java/de/danoeh/antennapod/playback/service/PlaybackService.java
This reorganises the media tree for Android Auto so that subscriptions are in a dedicated section which is hinted to display as a grid layout ([originally suggested on the forum](https://forum.antennapod.org/t/android-auto-assorted-quirks/6846#p-19744-grid-view-for-subscriptions-2) -- seeing as I had the change prepared already, hopefully you won't mind me coming straight in with the PR; obviously happy to discuss alternatives).  Original context:
I’d find it a lot easier to scroll through the subscription list by thumbnail than by name. By making subscriptions a dedicated tab (instead of AA constructing the _More_ menu), its layout can be set to a grid, similar to the main Android app:
Note that the _A-Z_ button produces a list view after you pick a letter, so it’s technically possible …
=> Android Auto: Grid view for subscriptions

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeItemListAdapter.java
Toggle selection when pressing action button. I played around with graying it out, but that wasn't as clear as just toggling selection.
Closes #7877
=> Toggle selection when pressing action button

app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/NavListAdapter.java, app/src/main/res/layout/nav_listitem.xml
This PR fixes the UI issue where the title text and icons in the right group would overlap when both the error icon and inbox count were present. Previously, the layout did not properly space out these elements, leading to visual overlap.
In addition to fixing this, I’ve implemented a small UX improvement:
Rather than statically reserving space for the error icon (even when not shown), the layout now dynamically adjusts spacing. This avoids unnecessary truncation  of the title when there's no error icon, improving readability without affecting functionality.
Closes: #7571
=> Fix: Prevent error icon from overlapping title text (#7571)

parser/transcript/src/main/java/de/danoeh/antennapod/parser/transcript/VttTranscriptParser.java
I stumbled upon this podcast while testing transcript for another PR, called `Aaron Mahnke's Cabinet of Curiosities`.
You can add the podcast through [this url](https://omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/E062C374-9A39-42FA-888F-AE2C007B3C85/F0F95FE5-D5DE-4ABE-ADA4-AE2C007B3C8E/podcast.rss)
Transcript is supported, but it shows empty.
<details>
<summary>Screenshot</summary>
</details>
The root cause of the issue ? The hours in the timestamp, being 1 digit long (0 instead of 00).
Here's a comparison between [a standard transcript file](https://podnews.net/audio/podnews250804.mp3.vtt), and [the transcript file of an episode](https://api.omny.fm/orgs/e73c998e-6e60-432f-8610-ae210140c5b1/clips/79c22e66-010a-44a1-a7a4-b2fe0135e81a/transcript?format=WebVTT&t=175009985 …
=> Work around VTT files using single-digit hours

app/src/main/java/de/danoeh/antennapod/ui/screen/onlinefeedview/OnlineFeedViewActivity.java
Store podcast credentials in FeedPreferences after subscribing
Fix #7925
=> Fix not storing credentials after subscribing 

net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdater.java, net/download/service/src/test/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdaterTest.java
Remove file extensions from local files. Unfortunately, because of the metadata caching logic, this does not work for existing files, only new files.
https://forum.antennapod.org/t/hide-file-extensions-for-local-folder-files/7054
=> Remove file extensions from local files

app/src/main/java/de/danoeh/antennapod/ui/screen/playback/audio/ItemDescriptionFragment.java
Fix I/O on main thread in ItemDescriptionFragment. That's currently the top crash in Google Play Console.
=> Fix I/O on main thread in ItemDescriptionFragment

app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/ImportExportPreferencesFragment.java
Fix not taking persistable permissions for automatic export
Closes #7218
Closes #7869
=> Fix not taking persistable permissions for automatic export

app/src/main/java/de/danoeh/antennapod/ui/screen/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedInfoFragment.java
This is a follow up to the #6400. It appears deletion works after (re)connecting a folder, but then it stops working after a while. It appears the issue is the permissions - we did not specify the proper flags when requesting access, so Android revoked the access after a while.
From my testing, adding these extra flags seems to fix the issue.
=> Fix local feed delete stops working after some time

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/ui/screen/drawer/BottomNavigation.java
Refresh bottom nav counter even if app is not open
Closes #7677
=> Refresh bottom nav counter even if app is not open

app/src/main/java/de/danoeh/antennapod/ui/screen/feed/FeedItemlistFragment.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/local/LocalFeedUpdater.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, storage/database/src/main/java/de/danoeh/antennapod/storage/database/PodDBAdapter.java
Only load the download log entries we actually need
See #7664
=> Only load the download log entries we actually need

ui/preferences/src/main/java/de/danoeh/antennapod/ui/preferences/screen/synchronization/SynchronizationPreferencesFragment.java, ui/preferences/src/main/res/xml/preferences_synchronization.xml
Remove cloud icon on cloud screen, no other subscreen has icons
=> Remove cloud icon on cloud screen, no other subscreen has icons

storage/database/src/main/java/de/danoeh/antennapod/storage/database/DBReader.java, ui/i18n/src/main/res/values/strings.xml
Ignore 'show in main list' for subscriptions screen.
This no longer makes sense with tags always at the top, users can always create their own main list.
After we remove the side navigation, we can remove the tag setting.
=> Ignore 'show in main list' for subscriptions screen

app/src/main/java/de/danoeh/antennapod/ui/episodeslist/EpisodeMultiSelectActionHandler.java, app/src/main/java/de/danoeh/antennapod/ui/episodeslist/FeedItemMenuHandler.java
Support cancelling downloads using multi-select
Closes #7976
=> Support cancelling downloads using multi-select

app/src/androidTest/java/de/test/antennapod/EspressoTestUtils.java, app/src/main/java/de/danoeh/antennapod/PreferenceUpgrader.java, app/src/main/java/de/danoeh/antennapod/ui/screen/preferences/DownloadsPreferencesFragment.java, net/download/service/src/main/java/de/danoeh/antennapod/net/download/service/feed/FeedUpdateWorker.java, storage/preferences/src/main/java/de/danoeh/antennapod/storage/preferences/UserPreferences.java, ui/preferences/src/main/res/values/arrays.xml, ui/preferences/src/main/res/xml/preferences_downloads.xml
Migrate update interval from hours to minutes.
This is a bit of a hack so that we have "1" available for "global" (instead of 1 hour) because we cannot change sql default values.
This is a step towards #7902
=> Migrate update interval from hours to minutes

app/src/main/java/de/danoeh/antennapod/ui/screen/subscriptions/SubscriptionFragment.java
Actually show all subscriptions when selecting 'all'
Closes #8012
=> Actually show all subscriptions when selecting 'all'

.github/workflows/checks.yml, .github/workflows/close-if-no-reply.yml, .github/workflows/remove-labels-when-issue-gets-closed.yml
As [recommended](https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/#what-you-need-to-do) by GitHub, this PR ensures our workflows use the latest versions of actions (including using the [latest available Java version](https://github.com/actions/setup-java?tab=readme-ov-file#eclipse-temurin) for `setup-java`), preparing us for upcoming deprecations.
It also addresses the deprecation of [gradle/wrapper-validation-action](https://github.com/gradle/wrapper-validation-action).
=> Update actions and address a deprecation
