- CONTRIBUTORS
- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/java/de/danoeh/antennapod/receiver/PowerConnectionReceiver.java
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
- core/src/main/java/de/danoeh/antennapod/core/util/PowerUtils.java
- core/src/main/res/values/strings.xml
Resolves issue #104. The user now has the option of disabling auto-download when the device is running on battery. Like wifi-connected auto-dl, a change in charging status will either trigger auto-dl (if other conditions are met) or cancel auto-dl (if the device is no longer charging).
I tested this on my HTC One M7 running 4.4.3.
I added myself to CONTRIBUTORS (I submitted a couple of other patches previously). I hope that's OK, if not feel free to remove it.
Please let me know if any updates are needed.
> Download when charging issue 104

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/res/menu/queue.xml
- core/src/main/res/values/strings.xml
Clears the users queue, while first asking for confirmation from the user.
Note that the menu option is not disabled when the queue is empty. I think this is 'ok' as this doesn't harm anything.
For issue #593.
> Empty queue command 593

- app/src/main/java/de/danoeh/antennapod/activity/DirectoryChooserActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
- app/src/main/java/de/danoeh/antennapod/asynctask/OpmlExportWorker.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/layout/opml_import.xml
Instead of exporting a OPML file to a predefined folder the user can
choose the folder (but not the filename) the file will be exported
Resolves AntennaPod/AntennaPod#260
> Add ability to select OPML export folder

- app/src/main/java/de/danoeh/antennapod/activity/DirectoryChooserActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/layout/opml_import.xml
Instead of having a fixed path, the user can now choose the path to
import from via dialog. This made the rather bloated instruction text
superfluous. Some minor changes to the DirectoryChooserActivity and the
OMPL Import layout.
Resolves AntennaPod/AntennaPod#623
> Add ability to choose OMPL import path

- app/src/main/res/layout/cover_fragment.xml
The former scaling would scale the image so that width and height of
the cover would be at least as large as the view. Now, the covers
dimensions will be equal or less than the dimensions of the cover view.
Fixes AntennaPod/AntennaPod#621
> Correct audio player cover scaling

- core/src/main/java/de/danoeh/antennapod/core/syndication/handler/SyndHandler.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSDublinCore.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndDateUtils.java
I extended the SyncHandler to recognize the DublinCore namespace and it's date tag in particular
Date values are assumed to be in ISO8601 or RFC3339 format
Resolves AntennaPod/AntennaPod#610
> Can understand DublinCore publication date in RSS feed

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Problem: Deleting a queue list item causes the list to refresh. An old saved scroll position was getting restored.
Now, we restore the position only once and then forget the position.
> Fix for false restore where swipe to dismiss scrolls to the top of the list

- app/src/main/res/layout/queue_listitem.xml
Drag section reaches from left border to about half of the cover.
Before:
After:
Resolves AntennaPod/AntennaPod#670
> Queue: Drag handle area now 4x the size

- app/src/main/java/de/danoeh/antennapod/menuhandler/MenuItemUtils.java
- app/src/main/res/menu/feedlist.xml
- app/src/main/res/menu/new_episodes.xml
- app/src/main/res/menu/queue.xml
Now always displaying both search and refresh.  If we don't 'always' display each then the other won't be displayed. This is strange, since it appears there is plenty of room for both.  It would be interesting to know if anyone has a problem with this change in place.
resolves #633
> now always displaying both refresh and search. closes #633

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/res/values/strings.xml
Number of parallel downloads can be set in the preferences.
It is checked, that the input is reasonable (between 1 and 50 parallel downloads).
Sadly, NumberPicker is only available in API level 11 - EditText it is...
(Deleted "if (BuildConfig.DEBUG) Log.d(...)" in the download service, because it is stupid)
Resolves AntennaPod/AntennaPod#622
> Number of parallel downloads can be set in the preferences

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
Fixes AntennaPod/AntennaPod#684
media.compareWithOther(other) is always false:
* FeedItem extends FeedComponent
* compareWithOther(FeedItem/FeedComponent) is inherited from FeedComponent, always returns false
Tested on Android 4.2.2.
Not tested on an actual feed where the file's URL changes, but the code is pretty solid.
> Fix issue where feed media attributes did not get updated

- library/drag-sort-listview/build.gradle
Tested on emulator running 2.3.7, could not provoke a crash.
> Support library downgrade after crashes

- app/src/androidTest/java/de/test/antennapod/service/download/HttpDownloaderTest.java
- app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java
- app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
- app/src/androidTest/java/de/test/antennapod/util/service/download/HTTPBin.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedImage.java
GUI tests were not working properly.
Some tests still fail from time to time.
Most seem to be related to timing issues, e.g. some activity is still running while the test runner is already reseting the environment.
If this turns out to be a serious problem, adding Thread.sleep() here and there should fix them aswell
> Fixes non-working app tests, especially GUI tests

- app/src/main/java/de/danoeh/antennapod/adapter/ActionButtonUtils.java
- app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java
- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/NewEpisodesListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/feed/EventDistributor.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Direct play from the the list is now enabled. A pause button is no longer displayed in the list. It would need additional changes to get a pause button to work and to always be updated accordingly. Instead the
play button of the selected item changes to blank.
> Addresses #669 and #664: play buttons in the lists

- app/proguard.cfg
We shouldn't be logging any messages in release mode. Updated ProGuard config to remove any logging calls.
> don't log messages in release mode

- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
fixes small bug introduced in #709 that caused the icons for Queue and New Episodes to be swapped in the navigation list.
> show the correct icon for queue and new episodes

- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/res/layout/audioplayer_activity.xml
- app/src/main/res/xml/preferences.xml
- core/src/main/java/com/aocate/media/AndroidMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Users set fast forward and rewind time separately. This is set on the audio player activity by long pressing fast forward or rewind. Small numbers above the buttons show the current values.
The former preference setting has been removed.
FF/Rev seems to cause troubles on older devices. The seekbar is not updated properly when seeking while the audio is paused - the position is updated properly.
Until now, seeking was only possible when the audio was actually playing. On newer devices, the seekbar is not updated properly in very rare cases. Most of the time, it works as intended.
Closes AntennaPod/AntennaPod#642
(For easier review, I tried to add all tedious stuff into the first commit.)
> Separate fast forward and rewind times

- app/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
Fixes a bug where GPodnetSyncService was setting the wrong date when importing new feeds.  This result in feeds not being displayed since the system thought there was nothing new.
> gpodder now properly sets the initial data for feeds

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
For issues #741 and #742. Now restoring the last navigation fragment the user was viewing when AntennaPod was closed. This should give the user a more seamless experience where they don't see fragments they aren't expecting.
> now saving the last navigation fragment the user had loaded

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
These were happening on some handsets when onPrepareOptionsMenu was getting called.
It is sometimes called before the menu is actually loaded, causing us to not find the
MenuItem we're looking for.
This solves the symptom, if not the cause.
After making this change the number of failures reported on Apkudo dropped from 20 devices to just 6.
> Fixed some NullPointerExceptions

- core/src/main/java/de/danoeh/antennapod/core/feed/QueueEvent.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
After adding EventBus whenever you move an episode or attempt to swip to remove
(but don't actually remove) the undo toast for removing an episode would be
displayed.  This is now resolved.
> Fixes bug with undo toast.

- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- app/src/main/res/layout/downloadlog_item.xml
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
What it looks like:
What it does:
* Failed feed downloads (refresh) and media downloads have a retry button
* If there is a newer successful entry for a feed or feed media, the user cannot retry (because it is pointless, obviously)
* Successful feed refreshes now create a download log entry when the last refresh failed
* Wow, such layout, much fancy  [woof]
Resolves #541
> Retry failed downloads in the download log

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/res/values/strings.xml
A download report is only generated if at least one of the downloads (not including images, only feeds and media files) failed.
Before, this notification would show the refresh icon, ticker "Downloads completed", content title "Downloads completed".
Now: notification shows refresh icon with exclamation mark, ticker "Downloads completed with error(s)", content title "Download report"
> Download Report

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
These receivers weren't getting de-registered as they should have been.
> unregister recivers

- core/src/main/java/de/danoeh/antennapod/core/storage/APCleanupAlgorithm.java
Episodes that are not played yet (getPlaybackCompletionDate()==null) should be sorted in as now and not 1.1.1970
When sorted in as "now", these episodes are delete later in auto cleanup mode, than played once.
> Episodes with a PlaybackCompletionDate should be delete before those without.

- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
On 2.3 devices the text in the search box for adding a podcast via iTunes was barely visible.
This gives the text the correct color.
> fixed text field color in iTunes search for 2.3 devices

- app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java
- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetEpisodeAction.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/GpodnetPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
[Interesting stuff is in the second commit]
Changes 'n' Fixes:
* Episode actions are sent immediately (not only on feed refresh)
* Fixed episode identifier
* Local changes overwrite remote changes: If gpodder sends a podcast unsubscribe, but the local changes include subscribing to that podcast, we go with the local information.<br>Reasoning: Subscriptions are sync immediately after adding/removing, our local data is most likely more recent
> Gpodder synchronization fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromIntentActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
* When adding a feed via sharing the AntennaPod action now says 'Add Podcast' (hopefully this will make it more clear this isn't the activity to import OPML)
* Now supporting opening OPML files from Gmail and the Downloads folder
* Simplified processing of Intents in OpmlImportFromPathActivity
* We don't currently support importing OPML from just sharing a URL. We'll have to add that later. (issue #833)
> Fix sharing opml

- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
- app/src/main/res/layout/nav_feedlistitem.xml
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Forgot to make a screenshot of the layout errors. Hiding some of the elements led to elements overlapping.
Fixed:
> Fix for drawer layout and refreshing feeds that failed

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
Resolves #839
This is only used by the auto download algorithm. Auto download candidates are items in the queue and unplayed items. For the later, the removed criteria is always true.
Episodes in the queue should be auto downloaded regardless if they are played or not.
> Allow auto downloading of queued but played episodes

- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Resolves #854
I can only guess what exactly goes wrong here.
My guess is that okhttp either has a bug in its un-gzip and throws an error although the data was read correctly - or the server does not comply with some standard (e.g. there is no content-length field).
Catching the exception and just continuing as if nothing happened seems to work.
Not sure if additional checks would do any good. We could check the content length if it is sent by the server, but a lot of servers seem to get that wrong (sending the content length of the unzipped data)
> Fixes "gzip finished without exhausting source" error

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
Should resolve this crash seen in Google Play store reporting:
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=561 (# cursors opened by this proc=561)
at android.database.CursorWindow.<init>(CursorWindow.java:108)
at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at com.aocate.media.MediaPlayer$1.getQueueIDList(MediaPlayer.java:388)
at de.danoeh.antennapod.adapter.ActionButtonUtils.configureActionButton(ActionButtonUtils.java:67)
at de.danoeh.antennapod.adapter.FeedItemlistAdapter.getView(FeedItemlistAdapter.java:174)
at …
```
> now closing a lot of cursors that were otherwise staying open

- app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
- core/src/main/java/de/danoeh/antennapod/core/util/IntentUtils.java
New utility class IntentUtils that checks if there is actually an activity (app) that handles the intent. When a URL is malformed or has no target activity, it is no longer propose to open it.
The episode fragment now also got its own long click context menu.
Fixes #880
> Handle malformed URLs

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/res/layout/cover_fragment.xml
- app/src/main/res/layout/feedinfo.xml
I start with the tricky bit: When the main activity is restarted or resumed, we open the last fragment the user opened. Until now, this was read and deleted (set null). When coming back from another activity (audio player), the last fragment would else (when not nulled) be read (this would be the same as the current one) and the current fragment would be loaded again (my emulator shows some sort of short flashing).
Setting the last fragment to null had the following consequence: Coming back from the audio activity, the last fragment would be read and set to null. Opening the other activity and going back would query the last fragment again, this time the preference would be null and the default value Queue would be returned. The app now believes the current fragment to be the queue and …
> Fixes Queue not opening, small podcasts images not scaling up and long URL not wrapping

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Fixes #928
The PlaybackService was not using the right FeedMedia/Playable to determine if the file was present locally or the next item would be streamed
Also works with continuous playback
> Fixes Queue transition from playing local to streaming

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/config/StorageCallbacksImpl.java
- core/src/main/java/de/danoeh/antennapod/core/event/ProgressEvent.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/res/values/strings.xml
We now store in the database if a media file has an embedded picture. In principle, this makes any further checking superfluous.
Migration: Already downloaded files are checked and the database is updated accordingly. While the files are processed, we show a progress dialog to the user. (This dialog will be shown in future database migration)
This branch is based on the similar hotfix.
Resolves #898
> Store information if file has embedded picture in the database

- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/res/values/strings.xml
Give the use the option to disable the download report.
While it is useful to see the failed downloads, if a user is subscribed
to many podcasts, most of the times a few fail, which makes the notifications rather annonying.
> Download Report: introduce setting to disable

- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
testPauseForInterruptions was failing, looking for the Auto Delete string.
It should have been looking for the pause playback string.
> Fix testPauseForInterruptions

- core/src/main/java/de/danoeh/antennapod/core/asynctask/PicassoProvider.java
There are still cases where 'bitmap' could be null.
We shouldn't return a result when that's the case.
Returnning null appears to be supported by Picasso.
(see Picasso.NetworkRequestHandler)
Fixes AntennaPod/AntennaPod#947
> Return NULL instead of result when unable to load bitmap.

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Once an item has been downloaded once, we never really want to autodownload it again, whether or not it was downloaded this time.
Should resolve the problem in #936 related to episodes being re-downloaded once they've been deleted.
> set autodownload == false once an item is downloaded

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Fixes AntennaPod/AntennaPod#942
PlaybackServiceMediaPlayer.getPSMPInfo() groups PlayerStatus and the currently playing media (Playable) in a synchronized method so that you can get a consistent picture at any one point in time as to what was happening.  Unfortunately, it was getting called in other synchronized methods (of another class) and PlaybackServiceMediaPlayer has other synchronized methods that also get called.  This occasionally results in deadlock.
To fix it, I created a non-synchronized getPlayable() and now call either getPlayerStatus or getPlayable depending on which is needed except for the rare circumstances when they are both needed. When they're both needed we still call getPSMPInfo().  Luckily, the case where we need both aren't the cases that were causing this …
> Only call getPSMPInfo if you need both the status and the playable.

- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetEpisodeAction.java
**UNTESTED!  I don't have a working build setup.  Please verify before merging.**
According to [1] and my own episode actions feed, "action":"flattr" is a
valid action.  Future-proof the episode actions code by ignoring actions
that we don't know and care about.
This fixes the
java.lang.IllegalArgumentException: FLATTR is not a constant
exception when fetching the episode actions list.
[1]: https://gpoddernet.readthedocs.org/en/latest/api/reference/events.html
> gpoddernet: do not crash on unknown remote actions

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
This should prevent any IndexOutOfBounds errors.
The Downloads list that's provided via getDownloads shouldn't be pointing to the same instance as the one used by the DownloadService.
fixes AntennaPod/AntennaPod#968
> Return a copy of the downloads.

- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
It can be null in this class, so we should make sure it isn't accessed if it is.
fixes AntennaPod/AntennaPod#972
> Guard use of 'media'

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/RunningDownloadsFragment.java
- core/src/main/java/de/danoeh/antennapod/core/asynctask/DownloadObserver.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
In #969 we updated DownloadService to return a copy of the list of downloads. That prevented the views from referencing data that wasn't there anymore.
However, I didn't set it to send a copy of that list every time the data changed.  Previously there was 'onDownloadDataAvailable' which would get called when the initial list was created and 'onContentChanged' which would get called whenever anything changed.  Now, there is just 'onContentChanged' and it takes the content itself.
This solves the remaining problems from #968, but it does so at a cost. Now, any time the download list changes we'll create a copy of it. When we're downloading a lot of small items (feeds for example) the list might change rapidly.  That means we'll be creating a lot of these objects, just for them to be garbage …
> Must send download list when content changes

- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
- app/src/main/res/layout/episodes_apply_action_fragment.xml
- app/src/main/res/menu/episodes_apply_action_options.xml
- app/src/main/res/menu/feedlist.xml
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/res/values/strings.xml
Something to play with. Not very well tested yet.
Something to look at:
> Perform action on episodes

- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
- app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java
- app/src/main/res/layout/feedinfo.xml
- core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/res/values-iw-rIL/strings.xml
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Let me repeat this again:
DO NOT PULL THIS AS-IS. THIS IS FOR DISCUSSION ONLY.
One of the features I still miss in AntennaPod is the ability to control the Auto Delete option *per feed*.
Some feeds are throwaway - once I hear them, I want them to be automatically delete.
Other feeds are precious and I want to keep the chapters I've downloaded.
This pull request adds a new 'Delete After Playback' spinner to the FeedInfoActivity. It has 3 states:
Default - use the global setting
Yes - delete after playback, regardless of the global settings
No - Do not delete after playback, regardless of the global settings
This is my first Android work, and I have a VERY shallow understanding of Java (I come from C/C++), so this pull request is based on googling stackoverflow and the SDK documentation.
I …
> New feature: Add Feed-specific 'Delete After Playback' override option

- app/build.gradle
- app/src/main/templates/about.html
This change adds the information provided by "git describe" to the "About" screen.
This info includes the SHA1 of the commit on which this release is based, as well the the number of commits since the last release and the last release number.
Please note that AntennaPod release labels have been applies to the 'master' branch, therefore releasing snapshots from the 'develop' branch will not yield useful info other than the commit ID,
It is still useful in the sense that it provides the number of commits since the last label on the develop branch, and even if there are no more labels, the number of commit will increment for newer builds.
> Add git commit ID and version top the "About" screen

- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/receiver/AlarmUpdateReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java
Alarm was not being issued on devices running 5.1 (and perhaps older).
setRepeating is setInexactRepeating on API 19+, that means we can go as long as interval*2 before updates.
Switched to use 'set()' instead to get behavior that matches what users expect.  Otherwise we could go as long as 2 days between updates.
> Setting updates for a specific time of day didn't work on newer devices.

- app/src/androidTest/java/de/test/antennapod/handler/FeedHandlerTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- app/src/main/java/de/danoeh/antennapod/PodcastApp.java
- app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java
- core/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/event/FeedMediaEvent.java
- core/src/main/java/de/danoeh/antennapod/core/service/FeedMediaSizeService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
Obvious, visual change: When claimed media size is zero bytes, we no longer show "0 B", but nothing. I believe this is superior to showing "Unknown size" and alike, the user would not know why this is or what she can do to fix it.
For episodes, where the file size is unknown or suspiciously low (some feed seem to give the runtime in minutes...), we ask the server for the correct file size in a background service. This service is started when the app does the same (an old run may have been interrupted), but also when one or several feeds are refreshed.
This will fail if the server does not support the HEAD request method. As I have yet to encounter a server that does not, I was not able to find a workaround for this probably quite rare case.
Fixes #990
> Get filesize from server

- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
We don't dim items in playback history if they've been played anymore.
Also adds a space before the feed title when displaying the title.
fixes AntennaPod/AntennaPod#1007
> PlaybackHistory doesn't dim played items anymore.

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
Made some changes to the way the fragment of the last session is loaded. This fixes an issue where fragment saved to be the last one viewed would be opened unintentionally on notifying the main activity of an update.
This fix should be included in the next release - or else people will complain...
Fixes #1002
> Load fragment used in last session correctly

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/templates/about.html
Version code schema:
* "1.2.3-SNAPSHOT" -> 1020300
* "1.2.3-RC4" -> 1020304
* "1.2.3[-RELEASE] -> 1020399
The version name will include more information (RCx) - About no longer shows the version code, only the version name and the most current (short) commit hash.
> Proposal for new version code schema

- app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
- app/src/main/java/de/danoeh/antennapod/receiver/ConnectivityActionReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Fixes a couple of problems with Time of Day automatic refreshing:
* It was getting refreshed too many times. It was using .before() to determine if it should add a day, but it also needs to use .equals(), otherwise the alarm can trigger multiple times.
* It was using refreshExpiredFeeds() which was broken since it assumed getUpdateInterval() was the only game in town (it isn't since it doesn't handle time of day updates).   getExpiredFeeds() was also using the wrong units for getUpdateInterval() (it returns hours, but getExpiredFeeds() assumed it was millis) so it was just pretty much always refreshing all the feeds anyways.
I also fixed a test that was broken with some prior changes to Add Podcast.
> Fix Time of Day Refresh

- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Problem: Per default, auto downloading was enabled for all episodes when it was introduced. Now, some users complain that (older) episodes are downloaded twice (or again).
Solution: We disable auto downloading for all episodes that are marked as played, have a position > 0 (partially played) or are currently downloaded (all actions, that would disable auto downloading now).
We exclude episodes that are currently in the queue.
Possible new issues: There might be users that performed an action that automatically disabled auto downloading (like downloading or playing) and manually re-activated auto downloading. These users will lose their manual change.
Fixes #1009
Also changed: The DB version now reflects the app's code version. This will make it a lot easier to see when database migrations …
> Retro-actively disable auto download for older episodes

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrUtils.java
It turns out supporting 'flattring this app' is too complicated.
While we appreciate everyone that wants to support development, finding a way to properly and equitably manage the funds would take significant time away from actually working on AntennaPod.
We still support flattring feeds.
The best way people can support AntennaPod is by joining the alpha test and reporting bugs before the app goes to production.
> Remove Flattr this App button

- core/src/main/res/values/arrays.xml
At first, I tried 5,10,20,30,50,100,unlimited - tested it on a virtual Google Nexus One running 2.3.7, too many values to fit on one screen.
Went with 5,10,25,50,100,unlimited. Still has scroll bar, but at least all values appear without scrolling.
> Reorganize episode cache size values

- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
* Default value for the image cache size should be > 0
* If the image cache size is too small we force it back to default
* We should only have once instance of the HTTP client
fixes AntennaPod/AntennaPod/#1053
> Fixes pictures disappearing in some cases

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/dialog/TimeDialog.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
- core/src/main/res/values/strings.xml
Android can handle plurals and strings having the same names, but
Transifex can't.  Renamed the time_unit*'s to just time_ to make sure
we got the correct translations.
> Changed string names relating to time units.

- app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java
This following NullPointerException showed up from the play alpha channel.
What's interesting is that it came from within a 'Log.d()' line that should have been removed by ProGuard. I suspect it just removed the call to Log.d(), but that the computation that occurs in the call still occurs.
Is it ok to pass the .load() function of Glide a null pointer?  If so, awesome. If not we'll need to fix a couple of other places.
What do you think @mfietz?
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
at de.danoeh.antennapod.adapter.QueueListAdapter.getView(QueueListAdapter.java:158)
at com.mobeta.android.dslv.DragSortListView$AdapterWrapper.getView(DragSortListView.java:730)
at …
```
> resolves NPE in QueueListAdapter

- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/GpodnetPreferences.java
I noticed the following exception via Google Play
```
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at java.util.AbstractCollection.toString(AbstractCollection.java:372)
at java.util.Collections$UnmodifiableCollection.toString(Collections.java:994)
at java.lang.StringBuilder.append(StringBuilder.java:202)
at de.danoeh.antennapod.core.service.GpodnetSyncService.syncEpisodeActions(GpodnetSyncService.java:207)
at de.danoeh.antennapod.core.service.GpodnetSyncService.sync(GpodnetSyncService.java:120)
at de.danoeh.antennapod.core.service.GpodnetSyncService.access$100(GpodnetSyncService.java:45)
at de.danoeh.antennapod.core.service.GpodnetSyncService$1.onWaitCompleted(GpodnetSyncService.java:323)
at …
```
> Fix locking in GpodnetPreferences

- app/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
After some thought and use of autodownload as it stands now, auto-downloading all unplayed episodes is just not the expected behavior for anyone.  If we autodownload all unplayed episodes then if you subscribe to a new feed all of the episodes from that feed are candidates to be autodownloaded, and they may trump other 'new' episodes from other feeds.
So, this change makes it so that only queued and new items are autodownloaded. If you want to download something else you can still click the 'Download' button and it will still be downloaded and enqueued.
As a result, I think AntennaPod/AntennaPod#1060 will probably wind up focusing on the cleanup algorithm, favorites, etc...
This also fixes a small bug that occurs when upgrading the database to set the autodownload flag to false.
refs …
> Only autodownload queued and new items

- app/src/main/res/menu/feedinfo.xml
The FeedInfo display was missing a string when you clicked the ... action.  Turns out it never got switched over to share_feed_url_label.
> use correct string for action

- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
Attempting to resolve this crash that appeared in Google Play:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.danoeh.antennapod/de.danoeh.antennapod.activity.PreferenceActivity}: java.lang.NullPointerException: Attempt to read from field 'de.danoeh.antennapod.preferences.PreferenceController de.danoeh.antennapod.activity.PreferenceActivity.preferenceController' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.access$800(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
at android.os.Handler.dispatchMessage(Handler.java:102)
at …
```
> create PreferenceController before the main fragment

- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
iTunes search now works fine with non-ascii query strings.
Also checked the gpodder search, all queries I tried already worked fine.
Fixes #1075
> Encode non-ascii query strings for the iTunes search

- core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
> Display line breaks in shownotes correctly

- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
fixes AntennaPod/AntennaPod#1128
Using the same pattern we're using in our fragments.
> Protect use of menuInfo:

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Don't case the playable until we know it's actually a FeedMedia.
You can reproduce the error that was causing this by attempting to play a normal mp3 with AntennaPod and then trying to use the share options.
Fixes AntennaPod/AntennaPod#1111
> Properly check if we should show links share items.

- CHANGELOG.md
- core/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Also changed the changelog, mostly as a reminder to tell users why we need a new permission.
Side note: On Android 6, this has protection level normal - We won't have to ask the user for this permission.
Tested on a really, really cheap bluetooth speaker...
Fixes #1130
> Resume playback when bluetooth device is reconnected

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
Feed: http://echo.msk.ru/programs/speakrus/rss-audio.xml
Before
After
Fixes #1153
> Remove needless leading and trailing spaces in feed or episode title

- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
Fixes this NPE as reported on Google Play:
```
java.lang.NullPointerException
at java.util.Date.before(Date.java:178)
at de.danoeh.antennapod.core.service.GpodnetSyncService.processEpisodeActions(GpodnetSyncService.java:263)
at de.danoeh.antennapod.core.service.GpodnetSyncService.syncEpisodeActions(GpodnetSyncService.java:203)
at de.danoeh.antennapod.core.service.GpodnetSyncService.sync(GpodnetSyncService.java:120)
at de.danoeh.antennapod.core.service.GpodnetSyncService.access$100(GpodnetSyncService.java:45)
at de.danoeh.antennapod.core.service.GpodnetSyncService$1.onWaitCompleted(GpodnetSyncService.java:324)
at de.danoeh.antennapod.core.service.GpodnetSyncService$WaiterThread$1.run(GpodnetSyncService.java:360)
```
> fix NPE when action has no timestamp

- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java
- app/src/main/res/layout-v14/time_dialog.xml
- app/src/main/res/layout/time_dialog.xml
- core/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/ShakeListener.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
- core/src/main/res/values/strings.xml
The dialog will now remember the last settings.
I know, the layouts look redundant, but I found no other way to make the dialog look this way, e.g. if you remove the outer LinearLayout, the dialog will become very narrow.
10s before the timer is about to expire, users can choose to get a short 0.5s vibration, we need a new permission here. Not sure if this may have any implications on devices with no vibrator, maybe the Play Store will tell them APod is not compatible...
In any case, the audio's volume will be lower significantly. Lowering it to 10% may look much: I tried to find a balance between still being able to hear and detecting the actual volume change [1]. 10% turned out to be the best solution for me.
Shake to reset will only work in this 10 second timeframe. I took the …
> Sleep Timer: Shake to reset, lower volume, vibrate, remember preferences

- build.gradle
- circle.yml
Previously CircleCi was just doing ./gradlew test which doesn't actually try to build everything.
This will now run assembleDebug for us to give a better idea of if something works.
We still can't run tests (our tests fail on non-x86 hardware and CircleCi doesn't support x86 hardware) and we still can't assembleRelease (signing).
> disable predexing to get CircleCI doing a full build

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
Left: Button is cropped. On smaller displays, one of the buttons might not be shown at all.
Right: Stacked buttons according to https://www.google.com/design/spec/components/dialogs.html
The dialog will also have this material look on older devices.
I was going to use the library for some of the preference dialogs for material design, anyway.
There are one major and one minor newer versions of the library, but they already target v23.
An alternative would be to insert manual wrapping into the button labels ("Set*\n*Interval")
Downside: All of the strings would probably have to be revised. In some cases (German...), it might be pretty hard to find a good wrapping that works on all the different display sizes and resolutions
> Fix cropped dialog buttons

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/asynctask/OpmlExportWorker.java
- core/src/main/res/values/strings.xml
We had tried (but failed) to implement a robust folder selection dialog when exporting OPML (as mentioned in #314).  Here we give the option to share the exported OPML file with whatever application can support it.
If we think this is good enough we might think about closing #314.
> Add option to share OPML file when exporting it

- core/src/main/res/values-v21/styles.xml
- core/src/main/res/values/styles.xml
Before 'n' After
Tested on 2.3.7, 4.1.1, 4.4.4, 5.10
> Button text capitalized, not uppercase

- app/src/main/assets/LICENSE_MATERIAL_DIALOGS.txt
- app/src/main/java/de/danoeh/antennapod/activity/AboutActivity.java
- app/src/main/templates/about.html
Forgot the Material Dialogs license in the cropped buttons PR.
Seems like I messed up showing the licenses, so I fixed that.
Also works with dark theme nicely.
> Licenses: Material Dialogs, bug fix, nicer layout

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/MediaButtonIntentReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/res/values/strings.xml
(Cover of http://www.npr.org/sections/money/)
The next button doesn't actually mean there is another episode in the queue, it might end the playback altogether.
APod is now able to set the lockscreen background. It is a preference: There are probably a lot of people that prefer their own background image to the episode image on the lockscreen.
Maybe "lockscreen background" is a bit misleading: Basically, any other app/service that is "listening" (that receives MediaSession information) can read that image and show it. If enabled, watch apps will also be able to show the cover. "Cover art"? Not sure it this is any better, might only be more confusing.
Because of Glide, the meta data is updated in a background thread. Not sure if executing on the executor service is the best idea or if this …
> Lockscreen background, media session and playback state

- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
Resolves #1203
Instead of replacing a few special characters that we know are not allowed in filenames, only allow that few characters (alphanumeric, spaces and so on) that are unproblematic.
Also considered applying this the generation of the directory name, but I fear this could break backward compatibility. Current feeds with special characters in their title (that might create issues on some devices or file systems) could end up with a second directory for their media files.
While this would probably not be a problem I didn't want to risk fixing one issue and creating another.
All tests completed successfully.
> Allow only alphanumeric and a few other characters in media filenames

- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
NPE can occur when dialog is showing and the screen is rotated.
There probably still is an underlying problem, but I hope support lib v23 will make all of this obsolete.
This will at least keep the app from crashing.
Fixes #1220
> Fix PreferenceActivity NPE

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- build.gradle
- core/build.gradle
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/res/values/strings.xml
(Yep, on older devices, the content part is scrollable!)
* Fixed issue in Sonic player where switching would cause an unknown error (calling pause when in prepared state was considered an error)
* Variable Speed dialog: Thought it would be a good idea to mention sonic and allow the user to enable it instead of installing prestissimo.
* Now full dialog needed stacked buttons...
* Disable respective button when play store is not available or the android version is too low
* When switching to sonic, the media extractor doesn't give us the correct position after seeking. So, whenever the media player position doesn't seem to make sense, we have a look at the current playable
(I know, it's rather odd that enabling sonic is the negative action and closing the dialog is the neutral one. But that …
> Adapt variable speed preference dialog for sonic

- app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java
- app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBQueueCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/main/java/de/danoeh/antennapod/config/DBTasksCallbacksImpl.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APNullCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APQueueCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/EpisodeCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Here I am on my vacation submitting updates...
fixes #1234 and fixes #1060 
Preferences now has an 'Episode Cleanup' option that allows the user to specify how they want their episodes removed or deleted. The default is "if it isn't in the queue or favorites then it is eligible to be deleted if stuff needs to be downloaded".  However the user may override this and choose some other other setting.  They may choose "never' or any of 0, 1, 3, 5, and 7 days after the episode has completed playback.
I'm open to any suggestions on how/if things should be reworded.
I'm also willing to entertain some sort of indicator on an episode (perhaps in Completed Downloads) that shows it is eligible for deletion.  I have *no* idea what that indicator should look like though.
I also went through and fixed …
> Cleanup algorithm updates

- core/src/main/res/values/strings.xml
'Listening' doesn't make sense for video podcasts and we need to have some indication in the words that this only applies when you're done with the episode.
> listening -> finishing

- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
I think the logic we had previously might have been overly complicated.  If an item isn't played, you can now mark it played.  If it is played you can mark it unplayed.
fixes #1252
> Cleanup when we show the mark as played/unplayed menus.

- app/src/androidTest/java/de/test/antennapod/entities/ExternalMediaTest.java
- app/src/androidTest/java/de/test/antennapod/handler/FeedHandlerTest.java
- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java
- app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java
- app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
- app/src/androidTest/java/de/test/antennapod/util/RewindAfterPauseUtilTest.java
- app/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/util/RewindAfterPauseUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java
This pull request resolves #620 feature request.
The playback is rewinded X seconds after the pause and resume. The rewind duration depends on time that elapsed between the pause and resume. User is not able to customize the rewind duration right now.
I have chosen following constants (can be easily changed):
- podcast rewinds:
- 0 seconds - if pause < 3 minutes
- 2 seconds - if pause > 3 minutes
- 5 seconds - if pause > 1 hour
- 10 seconds - if pause > 1 day
I have chosen these constants based on my gut feelings and observation of the other apps such as Audible.
> Rewind after pause feature

- app/src/main/java/de/danoeh/antennapod/adapter/ChapterListAdapter.java
merging the fix from #1202 in to develop.  #1198 still needs to be merged in, but that's slightly more complicated since the problem file in question has been moved to a different library.  Perhaps @mfietz can deal with that?
refs #1225.
> prevent NPE when 'chapters' is null

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Fixes #1293
Checking menuInfo for null should be enough, but I wanted to make sure there isn't another NPE around the corner, so we now just check everything for null
> Prevent NPE in MainActivity.onContextItemSelected()

- app/build.gradle
material-dialogs:0.7.8.0 can't be downloaded but it seems that things work fine with 0.7.8.1. It seems simple enough to upgrade the dependency here.
> Fix "Could not find com.afollestad:material-dialogs:0.7.8.0" error.

- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Fixes #1301 
I figured, parsing is not that critical, so whenever the VM feels like throwing an exception, we should basically just ignore it.
Catching ``StringIndexOutOfBoundsException`` should actually be enough, but better safe than sorry. The app should not crash because some publication date might be displayed incorrectly.
> Fix datetime parsing StringIndexOutOfBoundsException

- core/src/main/java/de/danoeh/antennapod/core/asynctask/FeedRemover.java
Resolves #1304
Also considered using an IntentService or another background class.
Problem: At least two activities and one fragment react to the completed deletion in similar, but different ways. An IntentService could just send ProgressEvents, but the MainActivity would need some mechanism to find out what ("FeedRemover") actually completed.
This might not be the cleanest solution, but it should prevent the exception. One could also argue that changing only as little as possible to fix the issue is good ^^
> Feed Remover: Don't let the user cancel the ProgressDialog

- description/en.txt
Re-added accidentally removed Play Store tagline for mobile devices (the "Short description").
Added word 'player' in first sentence; most apps call themselves podcasting player. Hopefully improves Google Play Store listing a bit.
> Google Store description: Tagline + player

- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
StrictMode complained that there were two activities at one point.
Holding a "real" reference just seems like a very bad idea. Only using a weak reference might not solve any actual issues, but it is just a much cleaner approach.
> PreferenceActivity: weak reference

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
Problem: RSS feeds often have both an image tag and itunes:image tag. In my experience, the "normal" image tag often points nowhere or not to the image we want. The itunes tag is usually right.
Thus, we should prefer the itunes:image tag to the other tags and only use those as a fallback when the itunes tag is not present.
This is a partial solution to #1332, which might not even be a real problem after all.
> Prefer iTunes image over everything else

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
Fixes #1358
```
java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
at de.danoeh.antennapod.adapter.NavListAdapter.getLabel(NavListAdapter.java:86)
at de.danoeh.antennapod.activity.MainActivity.loadFragment(MainActivity.java:305)
at de.danoeh.antennapod.fragment.ItemlistFragment$3.onPostExecute(ItemlistFragment.java:277)
at de.danoeh.antennapod.fragment.ItemlistFragment$3.onPostExecute(ItemlistFragment.java:273)
at android.os.AsyncTask.finish(AsyncTask.java:636)
at android.os.AsyncTask.access$500(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5278)
at …
```
> ItemFragmentList: Exception when deleting current feed

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
Problem: The PlaybackServiceTaskManager would not reload its cached queue when the queue items are reordered.
Fixes #1386
> Play episodes in correct order after reordering

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/activity/DirectoryChooserActivity.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/values/strings.xml
Instead of the DirectoryChooser, we show:
As explained in #951, this will probably not solve the sd card issue on all devices (manufacturer dependent).
I choose not to show the whole path. Here, "Android/data/de.danoeh.antennapod[.debug]/files/" is truncated. Showing the available space should make it easier for users to identify the right folder.
Still not moving the data folder contents, this is a task for another day/PR.
> Replace DirectoryChooser with simple dialog listing all external directories

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
This NPE was reported on play. It seems to be an issue with Huawei devices. See http://stackoverflow.com/questions/31556679/android-huawei-mediassessioncompat and https://plus.google.com/+IanLake/posts/YgdTkKFxz7d
```
java.lang.RuntimeException: Unable to create service de.danoeh.antennapod.core.service.playback.PlaybackService: java.lang.NullPointerException
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2699)
at android.app.ActivityThread.access$2000(ActivityThread.java:143)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5291)
at java.lang.reflect.Method.invokeNative(Native Method)
at …
```
> Fix huawei npe

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
First commit can be ignored, just reformatting
The key event handling didn't handle some of the key events. This was especially bad on Lollipop or newer and in connection with Bluetooth devices.
Resolves #1407 ~~?~~ (~~Except that next is no longer fast-forward part~~ now it does)
> Skip media button (Bluetooth device) does fast-forward

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Makes #1413 right.
Basically, I thought those onPlay() etc methods would somehow get called by Android. Turns out, basically anytime onMediaButtonEvent() is called and there is a default implementation in MediaSession (non-support) that calls the appropriate method for a keycode.
Because we don't want the default and looking at the keycodes ourselves is no big fuzz, we can do all of this manually.
Really hope that settles it...
More information: https://github.com/android/platform_frameworks_base/blob/master/media/java/android/media/session/MediaSession.java#L728
> Also handle rewind/previous media buttons

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/dialog/RatingDialog.java
- core/src/main/res/values/strings.xml
7 days after the first app start (or 7 days after the upgrade):
If the user chooses remind me later, we wait another 7 days and show the dialog again.
> Rating Dialog

- core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
Frankly, inceptor is not the only solution, but the easiest.
Another would be the HttpDownloader, but it gets far more complicated. We would have to check prior requests, if one of those was redirected. Then, the DownloadRequest source (download url) would have to be non-final. Next, we would have to check any code that used the DownloadRequest if it assumes the source field to be final and so on (e.g. when removing the requests from the current downloads).
I think it is easier to update the field when we encounter a redirect. I don't think there is any other reason for a feed URL to change, so we actually don't need to update a saved feed's URL when refreshing the same.
> Update feed URL when redirected

- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
resolves crash on start that was happening in release versions. updates version to 1.4.1.1 for immediate release.
> apply the correct rxjava rules. version 1.4.1.1

- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
Resolves this error seen in the play store:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.danoeh.antennapod/de.danoeh.antennapod.activity.MainActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment de.danoeh.antennapod.dialog.EpisodesApplyActionFragment: make sure class name exists, is public, and has an empty constructor that is public
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at …
```
> resolve 'no empty constructor' error

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/util/FeedItemUtil.java
Resolves #1462 
Fixes feed refresh indicator in queue, episodes and feed overview.
Another optimization: When downloading, I chose to refresh the whole list because the change animation for a single list item looked pretty stupid. Just found out I can disable it... Now only items that are actually downloaded are refreshed.
I encountered an issue on my smartphone where dragging while downloading dropped the item at the current position (when the download progresses are updated). This change seems to fix it.
> Fix refresh indicator and (queue) dragging while downloading

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/res/layout/new_episodes_listitem.xml
- app/src/main/res/layout/queue_listitem.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Doesn't really fix #1464, but should have positive impact on memory. (At least it doesn't hurt)
→ http://stackoverflow.com/a/31062339/5369600
Basically, ``wrap_content `` is bad for images, because Glide would still has to load the full image. We should only use ``match_parent`` and fixed dp size.
> Lower memory usage

- app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
Resolves #1472
Still not really sure how this issue is caused. Probably when unsubscribing (deleting) from a feed.
At least the new code is more defensive, which makes it better.
> FeedMedia: item might be null

- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/RunningDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
Pretty much a no-brainer.
Prevents getting items with negative index (which throw ArrayIndexOutOfBoundsExceptions) from lists.
Resolves #1479
> ItemAccess: Prevent ArrayIndexOutOfBoundsException

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- core/src/main/java/de/danoeh/antennapod/core/util/StorageUtils.java
No idea how this can be reproduced... But showing an error message is still better than just crashing
Shows an error dialog when we cannot access external directories:
Also resolves another issue: The "free memory" information was not calculated for the specific choice for an external directory.
Resolves #1506
> PreferenceController: Prevent NPE in Data Folder Chooser

- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Only real changes is that the parameters are escaped before they are used in the query. Rest is reformatting.
Unfortunately, the RSS feed that caused this issue (The Onion Radio News) seems to not be available anymore, so I could not really test this.
Luckily, these are only minor changes and we should always escape Strings anyway.
Resolves #1510
> Escape SQL query parameters

- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Now, when a feed is removed, we also remove the corresponding entries from the download log. The user should not be able to retry refreshing a removed feed or to retry a failed download of one of its episodes.
Resolves #1522
> Prevent DownloadLog NPE

- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
Problem: When refreshing the current feed, the view would not refresh the list of episodes.
Tried to find out if this bug was introduced in a recent change. But even older commits did not include the feed list update event.
> Refresh feed view

- app/build.gradle
- build.gradle
- core/build.gradle
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
If Sonic fails (e.g. sample rate cannot be read), fall back to native mediaplayer.
If Sonic failed, we only reconsider using Sonic again when the playback service is restarted. Because we constantly reset audio players (and thereby forgetting we were in an error state), this seemed to be the easiest solution.
On Marshmallow, native pitch and playback speed work now. (Tested on N4 with Marshmallow)
Also includes downmixing (stereo to mono), which users will be able to enable in another PR.
Clone https://github.com/AntennaPod/AntennaPod-AudioPlayer/
See https://github.com/AntennaPod/AntennaPod-AudioPlayer/#local-testing
Call ``error()`` in ``SonicAudioPlayer.initStream()``
All tests passed on 4.4.4 virtual device.
> AudioPlayer v1.0.7

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/MenuItemUtils.java
- core/src/main/res/values/strings.xml
Icons should be indicative of buttons' actions. When the action of the button is to lock the queue, the icon should be a closed lock, not an open one, as the button's purpose is to perform an action and not act as a status indicator.
> Reverse (un)lock icons in queue

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java
When preferring the information from ``<itunes:image>``, check that the parser actually retrieved an URL from it.
> RSS: Check that image url is not empty

- app/src/androidTest/java/de/test/antennapod/ui/PlaybackSonicTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences.xml
After the episode cache limit makes only sense in connection with auto downloading, it should be in the corresponding sub menu.
Before
After
> Settings: Moved episode cache size to auto download sub-menu

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/res/layout/queue_listitem.xml
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
In the first step, I made the date wrap more nicely.
The second step follows the idea that the year is not really necessary if the podcast was published within the last year.
I also added some padding. Today is January 15,  2016. To not get confusing, on January 5, 2017, we will start showing the year of publication for a podcast published today.
[Before, intermediate, result]
> Pub date formatting

- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
Problem: ``DBReader.getFeed(ID)`` doesn't load the items' tags.
Other usages of ``TAG_QUEUE`` seem to be fine.
Resolves #1574
> Feed view: "Remove from Queue" context menu item when queued

- app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
- app/src/main/res/xml/preferences.xml
- core/src/main/res/values/strings.xml
Changes:
Sonic is now enabled by default. Instead of being in the experimental section of the settings, it is the first item in the playback section (above headphones disconnect/reconnect etc.).
See below: Also added a dialog that asks current users to switch to sonic (Android 4.1-5.1.1). Changing the dialog that is shown when variable playback speed is not available (native mediaplayer, pre-Marshmallow) also made sense to me.
[Download Plugin is greyed out because screenshot was taken on an emulator]
Resolves #1309
> Promote Sonic

- app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
Problem: FeedMedia's internal position is only updated every 5 seconds [1]. The widget would get updated about every 1.5s, but would read this often obsolete value. Now, we get the position directly from the playback service (and update every second).
Resolves #1278
--
[1] https://github.com/AntennaPod/AntennaPod/blob/f3758e33c28eae203bd6cfd0fee8cf3fb9c6b2d5/core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java#L38
> Widget: Update playback position every second

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/res/values/strings.xml
Uses `<plurals>` instead of just a normal string
Fixes #818
> Say '1 download left' instead of '1 downloads left'

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
Resolves #1529
Most debatable part is probably whether or not the status should be reset if we could assume the old URL was wrong (HTTP_NOT_FOUND etc.)
> Reset episode to new if media becomes available

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
~~Honestly no idea how to test this.~~~
If you can't make it, fake it. throw the exception in HttpDownloader, manually. Seems to work.
Basically, this piggybacks on the functionality for 404 HTTP errors.
Resolves #1296 
[Dang, based this on #1566. But now I'm to lazy to fix it...]
> Avoid download retry loop when storage is full

- app/proguard.cfg
I don't think we use it so we should be OK to ignore this.
@mfietz can correct me and suggest an alternative fix if he disagrees.
> LinePageIndicator uses MathFloat, which doesn't exist anymore.

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
Resolves #1603 
Changes in ``canSetPlaybackSpeed()`` go beyond the linked issue. Necessary because we often change the media player "on the fly". The current mp might not have playback speed capabilities, but we can switch to an implementation that does.
> Eliminate confusion from UI elements that change playback speed

- build.gradle
Resolves #1601 
Doesn't work perfectly, but as this seems to be a problem in Android, this might be the best workaround [1].
--
[1] see https://github.com/AntennaPod/AntennaPod-AudioPlayer/commit/a3d3967b0715905d8f13674f4bd5620a65c4e4ca
> Prevent native mediaplayer from unpausing when playback speed is changed

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
Resolves #1616 (Hopefully)
"if item.getAutoDownload() is false, the file has been downloaded before" is only correct for files downloaded recently.
Actually, checking ``getAutoDownload()`` should not really be necessary. Items with a former wrong URL (that 404'd) should still be new (if the user did not tamper with them).
> Only reset episode to new if feed item did not link to a file before

- app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
- app/src/main/res/layout/feedinfo.xml
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/res/values/strings.xml
Added a 'Global Refresh' option for feeds.  Defaults to true.
If you disable global refresh for a feed then if you refresh the feed list from the queue, from the episodes list or from a scheduled update then that feed will *not* be refreshed.  Further, any new episodes for the feed will *not* show up in 'New Episodes' though they will continue to show up under the Feed's episode view.
resolves #1182 and resolves #286
> Added 'Keep Updated' option for Feeds

- app/src/androidTest/java/de/test/antennapod/handler/FeedHandlerTest.java
- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java
- app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBQueueCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTestUtils.java
- app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java
- app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- app/src/main/java/de/danoeh/antennapod/asynctask/OpmlFeedQueuer.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
- app/src/main/java/de/danoeh/antennapod/receiver/SPAReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/backup/OpmlBackupAgent.java
- core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Instead of persisting the unix epoch time in the ``Feeds`` table's ``last_update`` property, we now persist the ``Last-Modified`` or ``ETag`` string returned from the server (SQLite doesn't care that the column type is integer).
This is to prevent issues where we would save a timestamp to the database even though the file has changed on the server (could be a caching or a simple race condition).
The other change is that refreshing the feed from its view now enforces the feed to be refreshed regardless of said column value.
> Improve If-Modified-Since/ETag

- circle.yml
circleci has been failing because it stopped trying to run 'gradle dependencies' and is instead running 'gradle compileTestJava' which doesn't exist.
We could probably also create a dummy gradle task to deal with that...
> try to fix circleci problem and speed up future builds

- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
Resolves #1658
gpodder escapes colons (``:``) which seems to be pretty unnecessary. See [1] and [2]
--
[1] http://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use/2053640#2053640
[2] https://www.w3.org/TR/html4/types.html#type-name
> Prevent gpodder sync duplicates

- app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java
- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
> Mobile Data: Do not show retrieving filesize spinner when download is not allowed

- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
Resolves #1714
~~(Did not even test this...)~~ Tested, works.
> Do not show full disk icon if cache size is unlimited

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- build.gradle
I know, branch name is a bit misleading...
Newest audio player should fix fallback to android's native player and catch all decoder thread exceptions (and fail gracefully).
When your locale is not us, the audio controls dialog saved the the playback speed from the slider in a wrong format. This leads to errors like this
```
E/PlaybackSvcMediaPlayer: java.lang.NumberFormatException: Invalid float: "1,70"
```
> Audioplayer v1.0.14 & Audio controls dialog fix

- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Resolves #1726 (Hopefully)
If different threads inconveniently call ``DateUtils.parse(String)`` at the same time, they might interfere with another using the same parser. Now, each caller gets its own parser.
(1.5.1, because this could only really harm performance, but I really doubt that)
> Give each pubdate thread its own parser

- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
Resolves #1747
Cause: The Observable would not be stopped on destroy due to it not being referenced.
> iTunes search: Prevent IllegalStateException

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
When rewind, play/pause or ff is pressed, the controls hiding is delayed.
Lowered the general delay for hiding from 5s to 2,5s. (In comparison, in VLC the default value is only 1s)
The position now also updates (e.g. when seeking) when playback is paused.
I noticed that often the current position is not updated because tryLock is false (race condition) and the position is not actually read.
So I added a timeout of 50ms. Really not sure if this is a good idea. 50ms should not be noticeable, but we are running on the main thread here...
Resolves #1687
> Video player: Delay controls hide on interaction

- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Resolves #1627
(Actually, probably not. If gzip is the problem, we should rather see a skip in the local audio, but not duplicate content. Well, it is an improvement, I guess...)
> Downloader: Disable gzip for media files

- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportBaseActivity.java
- core/src/main/res/values/strings.xml
``opml_import_error_dir_empty`` is not in use.
For testing: In ``OpmlImportFromPathActivity``, replace ``importUri(uri);`` with ``importUri(null);``
Resolves #1704
> OPML Import: Show dialog when no file has been selected

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
There was an inconsistency with the user set volumes, as the one experienced by the user when moving the seekbar isn't the same as the one later returned by UserPreferences.
This fixes that, and also moves the conversion formula into a new method on core.util.Converter
Also, I took the freedom to slightly alter the formula, since as it was it was giving the same output for 99 as for 100.
Besides, the volume bars progress were always initialized to 100, so I created methods on UserPreferences to read the saved values (different than returning a float between 0 and 1) and called them when initializing the seekbars.
> fix the volume conversion upon user interaction

- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
Resolves #1762
Biggest change is that AudioplayerPagerAdapter is static now (doesn't hold an implicit reference to the activity).
Because these changes are prone to error, I'd suggest to wait for 1.6 to test the changes thoroughly.
> Audioplayer: Prevent leak

- circle.yml
for some reason what worked before stopped working with 23.2.1, so now we'll grab more things.
> fix circle build

- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/res/layout/feeditem_fragment.xml
Resolves #1727
Also fixes an issue where the loading indicator is shown after an orientation change.
> Episode view: Show podcast title

- app/src/main/res/xml/preferences.xml
Sets the default episode cache size for new users to 10. Assuming that you have at least once a day access to a fast network and that 10 episodes is something like 3 hours of listening, 10 should be a reasonable default value.
To not make old users angry, the current default value of 20 (which is not actually any of the options) is bumped up to 25 if the user has not changed the default.
Resolves #1654
> Set default episode cache size to 25

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
It is becoming really hard to come up with meaningful titles...
Scenario: One episode ends, continuous playback is off. Next episode is loaded, position is 0. Until now, position 0 is regarded as invalid, the seekbar in audioplayer will not show the new position.
Resolves #1780
> When retrieving position of current episode, regard position 0 as valid

- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
Resolves #1529
Can be tested with http://test.mfietz.de/delay
(Basically, the feed contains 2 episodes. One is published just now, without a file. The other one minute ago with a file. The guid of an episode is the minute it was published. Subscribe, mark as played, wait little less than a minute, refresh. The just marked episode should be reset to new.)
> Reset episode to new if episode file is added later

- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromIntentActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
When Ghost Commander is used to open an OPML file *From local filesystem*, we would expect to receive a URI like ``file:///storage/emulated/0/FILE.opml``, but we receive ``/storage/emulated/0/FILE.opml``
Resolves #1502
> OPML Import: Fix URI containing absolute path

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
Yet, I'm not sure that the users understand that played duration != real time listened to podcasts (when playback speed != 1.00)
> Statistics: More accurate played duration

- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Addresses one of the issues from #1838 
Subscription List is now shown in the drawer options instead of having it's own thing.
> treat showing the subscriptions list like other drawer items.

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/view/OnSwipeGesture.java
- app/src/main/java/de/danoeh/antennapod/view/SwipeGestureDetector.java
Instead of having a single feeditem id, we now have a list of feeditem ids and a position.
When the user swipes left or right, the position is adapted accordingly and the UI is updated.
Works in all episodes, new episodes, favorites, queue, feed view...
As of now, it does not take into account that items that are represented in this list might be removed while in the episode view. Easiest solution would probably be to just finish the fragment when the next (or current) item is not found.
Resolves #662
> Episode view: Go to previous/next list item when swiping right/left

- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences.xml
- build.gradle
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Currently the lockscreen notification only contains play/pause and skip buttons. This PR makes the rewind and forward buttons appear on the lockscreen if the option `Expand Notification` is selected. The lockscreen then contains the rewind, play/pause and forward buttons, which in my opinion are the most useful buttons on the lockscreen. This has also been requested in #337 and #571.
> Optionally show rewind/forward buttons on the lockscreen

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/SearchlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Before & After
Even though the locale was US and the episode titles are in German, the hyphenation is actually pretty good
> Enable full hyphenation on Android 6

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
Resolves #1831
The problem: The apply actions dialog relied on the feed items tags being loaded
Solution: Load tags, use LongLists with ids less often
QueueEvent is mainly used by the queue fragment, FavoritesEvent by the favorites fragment. All other fragments get notified that feed items(' tags)  changed.
> Fix item tags

- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Always calls onFragmentLoaded() because updateAppearance() does not reload the description.
Resolves #1876
> Episode: Reload description on swipe

- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
For one, the sync was using the item identifier (UUID) to look for episodes which might not be the episode's download url.
Then, we can only sync the episode state when the feeds have been downloaded, parsed and persisted. before, chances were high that the feeds are still downloaded while we tried to find the not yet persisted episodes in the database and set their state according to gpodder.
Resolves #1872
> Fix initial gpodder sync

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/res/layout/new_episodes_listitem.xml
Before and after:
Resolves #1886
(I had to address the linearlayout. If we set the alpha of the container view, the list item dividers disappear)
> All Episodes/Favorites: Indicate played episodes

- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
Issue is: While playing an episode (locally), on the `MediaPlayerActivity`, and skipping to the next one, the new episode would pause some milliseconds after it started (at least when the media types change). Expected behavior would be, since the previous episode was playing, for the new one to keep playing.
This behavior, in part, was not present before the chromecast implementation, so a quick solution is to make the local PSMP behave exactly as before (so, on start playback, we're only asking to update the media session).
However, when switching from video to audio, this would also occur even before chromecast was implemented, being caused by the video surface being released and calling the media player to reset it. The method to reset the video surface is certainly not meant to be …
> avoid stopping playback after skipping (and changing media type)

- app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/CoverTarget.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/SearchlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- core/src/main/java/de/danoeh/antennapod/core/asynctask/ImageResource.java
- core/src/main/java/de/danoeh/antennapod/core/cast/RemoteMedia.java
- core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedImage.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java
- core/src/main/java/de/danoeh/antennapod/core/glide/AudioCoverFetcher.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
Re-enables embedded images.
Only tested with a few feeds that I know are using embedded images.
This is kind of a preparation for *virtual* podcasts aka local folders - We probably want embedded images if we ever implement them...
Possible drawbacks: Downloading files will take a bit longer as we check if the file has an embedded picture. Apart from that, hopefully none.
> Re-enable embedded images

- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Instead of returning something useful (audio/*, video/*), the ted talk servers return content type application/octet-stream.
The commit accepts this content type for media. Don't think there are any other mime types anyone would use.
This should probably go into 1.6
Resolves #1937
> Accept media content type application/octet-stream

- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
The scroll position on detail view is now being restored when you are switching back to it. 
On orientation change it doesn't restore on the exact position at the moment. 
But i think that could work with a scroll position relative to the webview height.
> Fix for restoring scroll position in detail view #1947

- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
A little strange that the NPE is occurring in ``PlaybackController`` and not when calling ``notifyVideoSurfaceAbandoned()`` on the same - maybe some VM optimization like inlining?
At least doesn't hurt to check for null.
Resolves #1972
> VideoplayerActivity: Prevent NPE

- app/src/main/java/de/danoeh/antennapod/activity/StorageErrorActivity.java
Maybe would be better to show the user a dialog message, but I have no idea what that would say. 
``getExternalFilesDir`` seems to return null which alone is pretty odd.
I say to wait for users complaining to get an idea under which conditions (steps to reproduce) this even happens.
Resolves #1971
> StorageErrorActivity: Prevent NPE

- app/src/main/res/values/strings.xml
- core/src/main/res/values/strings.xml
The app name would be shown as "library" after adding flavors.
> Fix app name (due to flavors)

- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
Left: Old behavior; subscription counter is set to none
Right: New behavior; subscription counter is set to number of unplayed episodes
Resolves #1914
> Subscriptions: Show indicator only when count > 0

- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
``importUri(@Nullable uri)``should not be an issue.
We only must not call ``toString()`` on a null object reference.
Resolves #1999
> OpmlImportFromPathActivity: Prevent onActivityResult NPE

- app/src/play/java/de/danoeh/antennapod/activity/CastEnabledActivity.java
- core/src/play/java/de/danoeh/antennapod/core/cast/CastManager.java
This fixes #1974.
I have no clue as what could have caused this problem.
If on one hand this PR prevents NPE to be thrown for this reason, it also prevents us from ever finding its cause as users will be more unlikely to report it in the future (who can tell if the cast button didn't show one particular time? more likely we assume it's some temporary connectivity issue).
> fixes CastManager.addMediaRouterButton NPE

- core/src/main/java/de/danoeh/antennapod/core/util/IntentUtils.java
Explanation: http://stackoverflow.com/a/11411881/5369600
Currently, ``IntentUtils.isCallable`` is true for an intent, even if none of the intent activities is exported, causing a ``SecurityException``.
Resolves #2004
> OPML Import: Check if there is an exported(!) activity for the intents/options

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
Formerly, the played duration was reset when the episode was added to the playback history, i.e. when it completed. Not really sure why that was the case, "so that it behaves correctly" is not really useful. Could have something to do with flattring, but I don't see why it would matter.
We also restore the played duration for episodes where the played duration was already reset. Of course, we have no way of knowing how often the episode was already reset. If the user played the episodes multiple times, most of the information is already lost.
Resolves #1961
> Fix statistics

- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
The subscription view had three issues: 
* When the former add tile holder was reused, we could end up with a cover in the add tile when the grid is reloaded, usually the cover of the top left feed
* Clicking the add tile did not work
* We need to unsubscribe, else rx could cause a "IllegalStateException: Activity has been destroyed" error
> Fix subscription view loading

- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1444 - “"static" fields should be constant”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1444
Soso Tughushi
> Code quality fix - "public static" fields should be constant.

- app/src/androidTest/java/de/test/antennapod/storage/DBTestUtils.java
- app/src/androidTest/java/de/test/antennapod/util/syndication/feedgenerator/GeneratorUtil.java
- app/src/main/java/de/danoeh/antennapod/activity/OpmlImportHolder.java
- app/src/main/java/de/danoeh/antennapod/config/ClientConfigurator.java
- app/src/main/java/de/danoeh/antennapod/dialog/GpodnetSetHostnameDialog.java
- app/src/main/java/de/danoeh/antennapod/dialog/RatingDialog.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
- core/src/main/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/main/java/de/danoeh/antennapod/core/UpdateManager.java
- core/src/main/java/de/danoeh/antennapod/core/cast/CastUtils.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideSettings.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/GpodnetPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
- core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/FeedItemUtil.java
- core/src/main/java/de/danoeh/antennapod/core/util/IntentUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/LangUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/RewindAfterPauseUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/StorageUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/ThemeUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrServiceCreator.java
- core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/MediaPlayerError.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
This pull request removes technical debt of 810 minutes.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Soso Tughushi
> squid:S1118 - Utility classes should not have public constructors

- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
This PR does two things.
Firstly, it resolves #2026 by reseting the holder counter, especially removing any listeners.
Now, we only keep a weak reference to the parent activity to prevent a leak.
> Fix full cache dialog and prevent leak

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Add exponential backoff for file type errors and check content length before assuming a file type error
I'm hopeful this resolves #2017
> Resolve file type errors

- core/src/main/java/de/danoeh/antennapod/core/feed/EventDistributor.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/ProxyConfig.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndTypeUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrServiceCreator.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:ModifiersOrderCheck - “Modifiers should be declared in the correct order”.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:ModifiersOrderCheck
Soso Tughushi.
> [squid:ModifiersOrderCheck] Modifiers should be declared in the correct order

- core/src/free/java/de/danoeh/antennapod/core/feed/FeedMediaFlavorHelper.java
- core/src/play/java/de/danoeh/antennapod/core/feed/FeedMediaFlavorHelper.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
This pull request removes technical debt of 60 minutes.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Soso Tughushi
> squid:S1118 - Utility classes should not have public constructors (part 2)

- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivityGingerbread.java
- app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/layout/gpodnetauth_credentials.xml
- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/GpodnetPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/res/values/strings.xml
on the gpodnet preferences, it adds an option that prevents sync error notifications from being shown. It does not apply to authentication errors.
It also includes another item that all it does is to show the result of the last sync attempt and when it occurred.
> Make gpodnet sync error notifications optional

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Fix binding issues by only using the MediaBrowserService onBind when the intent's action is MediaBrowserService and otherwise returning the LocalBinder. See issue introduced in https://github.com/AntennaPod/AntennaPod/pull/2053
> Fix issue where mini player doesn't show up

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
This resolves #2017 
https://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered()
See also:
http://stackoverflow.com/questions/23877476/android-why-connectivitymanager-isactivenetworkmetered-always-returning-true
http://blog.maxaller.name/2012/10/mobile-hotspots-conserving-data/
Overall, this seems like a good improvement. Should we change the strings as well and start calling metered, or keep calling it mobile connection even though it could be some weird wifi connection that charges by the transfer volume (I guess those still exist) and somehow android knows about it?
> change check for wifi connection to metered connection

- app/src/play/java/de/danoeh/antennapod/config/CastCallbackImpl.java
- app/src/play/java/de/danoeh/antennapod/dialog/CustomMRControllerDialog.java
- app/src/play/java/de/danoeh/antennapod/fragment/CustomMRControllerDialogFragment.java
- app/src/play/res/layout/media_router_controller.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/res/values-land/dimens.xml
- core/src/main/res/values/dimens.xml
- core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
This was really a pain. Horizontal LinearLayout's behavior is to first resolve the widths of its children and only then figure out any height restrictions. For a child view that imposes a certain aspect ratio, this means that once the height changes, its width is also going to change, but at that point the width is already fixed for all the other children, and LinearLayout doesn't ask them to update their dimensions.
Solution: override onMeasure on the LinearLayout to have a first pass through its children heights.
> fix horizontal layout (MediaRouteControllerDialog)

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
On Android 3+, the rotation also triggers a screen size change. For the activity (and with it dialogs, menus) not to be destroyed when the device is rotated, we have to add screen size to the things we handle ourselves.
Resolves #2023 
Resolves #2024
Resolves #2028
Resolves #2029
> Retain context menues and dialogs on rotation

- app/src/main/AndroidManifest.xml
Using an intent filter based on file extensions is unreliable: for example, K-9 Mail sends out intents with URI's like `content://com.fsck.k9.debug.attachmentprovider/75a212fa-2aa8-473c-ad4d-e4e86eff0bf7/5` when opening attachments, meaning any `intent-filter` relying on catching `*.opml` files will fail; also, extra dots in a file's path will break wildcard characters in `android:pathPattern`.
Using MIME types is currently the best option available. OPML files are often detected as `application/octet-stream` (a catch-all for unknown types) meaning the intent filter will catch files such as `.nomedia` etc., but I think that the amount of such files a user will come across is small enough that it won't really matter.
Fixes #1758
> Use MIME types in OPML import intent filter (fixes #1758)

- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java
- core/src/play/java/de/danoeh/antennapod/core/cast/CastManager.java
- core/src/play/java/de/danoeh/antennapod/core/cast/RemoteMedia.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
This PR changes some aspects of how the PlaybackService works and the way it communicates with the media players.
Main changes are:
* Playable types should now implement `onPlaybackStart()`, `onPlaybackPause()` and `onPlaybackCompleted()`, and before each call the current position should be properly updated (or more or less accurate), so that features such as played duration can work (only matters for `FeedMedia` type).
* Flattr and gpodder play action instructions were moved inside `FeedMedia`, to be executed when playback pauses or completes.
* As such, an item is flattr'd only when playback pauses/ends, as opposed to the previous behavior where it would be as soon as it reached the threshold (and we were checking every time we updated the position).
* This also introduces a distinction …
> Changes to media player protocol

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java
Add support for one mrss thumbnail, and description. Closes https://github.com/AntennaPod/AntennaPod/issues/1699
If an enclosure (content) is marked as default it can override an actual enclosure. For feeds that use mrss' content, they usually have the default one also be the enclosure, but if they don't this will still honor the default attribute.
> Improve MRSS support

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
Content is still preferred and used as default if both are present. But if it isn't it will use summary, usually a vague few sentences instead of show notes.
> Support Atom's summary tag

- build.gradle
On windows platform task :core:compileRetrolambdaPlayDebug often fails, generating error 
```
CreateProcess error=206, The filename or extension is too long
```
- See issue in the underlying retrolambda plugin: 
evant/gradle-retrolambda#206
> Fix build on windows with gradle-retrolambda plugin upgrade

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
It addresses #2105 . Behavior:
- if the user selects Rewind in Lockscreen Buttons settings, then the user can rewind in lockscreen 
- the button shown on lockscreen is previous button (Android's own limitation).
Discussion:
- overloading previous button as rewind should not confuse the user: AntennaPood does not support previous. The Lockscreen Buttons settings only provide rewind (no  previous). 
- the change (in `MediaSessionCompat` object) is consistent with the existing logic in the associated  `sessionCallback` object in [`onSkipToPrevious()`](https://github.com/AntennaPod/AntennaPod/blob/1.6.1.2/core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java#L1529) method's implementation is actually rewind.
- the fix in PR #2109 addresses hardware previous …
> Issue #2105 : support optional rewind in lockscreen 

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
When the user resumes the app, we now check if a feed refresh should be performed.
This is the case if the time since the last refresh is larger than the update interval or than 1 day in case of update time of day.
Also fixed documentation, which was plainly wrong.
Resolves #1942
> On resume, check if the feeds should be (automatically) refreshed.

- app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
I believe this issue hasn't been reported, but this is the way to reproduce it:
while using `MediaPlayerInfoActivity`, for instance while playing an audio episode, if the episode changes (either it ends or we skip) the next episode shows up. However, if go all the way to the chapters page and back to the cover page, the cover of the previous episode will show instead.
Here's my theory: 2 pages away the fragment gets destroyed, but when it is created again, it fetches the media that was passed to it as an argument on its instantiation, which won't be the same as the current media.
> fix cover fragment onMediaChanged

- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/res/values/strings.xml
If the user enables 'shouldHardwareButtonSkip' is likely there exist separate hardware buttons for 'Next' and 'Forward' functions. In this case, it's likely there exist also separate 'Previous' and 'Rewind' hardware buttons (as in my car stereo connected by bluetooth).  If that is the case, it is useless both buttons have the same function, it is more intuitive that the 'Previous' button restart the current track from its beginning as most players do. This patch does that.
> Set current position to the begining on 'Previous' button

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
I've changed the order in which the last played position is set to right after the media is loaded. This adds a delay (caused by user interaction) between seeking and playback start that should help to solve #1264. I've successfully tested it on my Fairphone 1, but no other phone.
> Prepare media on app start/resume and not on playback start

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndTypeUtils.java
[Alternative feeds](http://podlove.org/alternate-feeds/) is currently against spec, so I added support for it to be done through an archives link. Still supports alternate links as that's what's used and currently still recommended.
Adds images from media:content, if its medium, mime type or file extension indicates an image. I also cleaned up some of the mime type stuff when it is not present in RSS, MRSS or Atom. I've never seen this but it's presumably in their for a reason.
Also adds support for multiple authors.
> Parsing clean up

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
resolves #2181 
Unfortunately I was not able to test it because the build fails (dex 64K limit), so we should either take measures to get under that limit or else allow multidexing.
The free flavor has no issues with the build (but I'd rather not add even more instances to my phone).
This indicates that there could be a way to shrink, although it could be the google play services getting us over the limit.
> fix unskipped episodes being removed from queue

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
Fixes https://github.com/AntennaPod/AntennaPod/issues/2190
First checks the attribute, if that is invalid it will pull the mime type based of the file extension in the URL and then check that.
I don't know if this should be merged, because it is an issue with the feed not AntennaPod.
> Fallback to mime type from the URL when the defined is invalid

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
We now assume that the media type is audio when the mime type is unknown.
Resolves #2215
> Fix class cast exception on unknown mime type

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
This eases toggling an individual entry when one has many configured
wifi networks.
> Sort wifi names in automatic download preferences

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
User was listening to a podcast with headset, then get back home
and want to listen to the rest of the podcast on a chromecast.
If he unplug the headset while the audio is casting, we should not pause.
> don't pause while casting if headset is disconnected

- app/src/main/res/layout/nav_list.xml
- app/src/main/res/layout/subscription_item.xml
Hi,
I am developing a tool to automatically refactor Android applications with the goal of improving energy efficiency.
This pull request has the changes generated while applying the rule "ObsoleteLayoutParam".
While developing your application's views you might be specifying attributes in a view's artefact that are not necessary due to the nature of its parent. In this PR, those attributes were replaced by a comment.
I have made a previous validation of the changes and they seem correct.
Unfortunately, this tool is not able keep the original whitespace of the files, so comparison without ignoring whitespace might be confusing.
Please consider the changes and let me know if you agree with them.
Best,
Luis
> Android automatic refactor - ObsoleteLayoutParam

- core/src/androidTest/java/de/danoeh/antennapod/core/tests/util/DateUtilsTest.java
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Fixing of-by-one error, plus adding CET.
A can not reproduce #2269, suggest closing. Likely bogus data was fixed feed-side.
> Let me fix CET/CEST once again

- core/src/main/java/de/danoeh/antennapod/core/util/URLChecker.java
Fixes #2284 (subscribtion through podlove 'Let device decide')
`startFeedDownload` was called with 
pcast:logbuch-netzpolitik.de/feed/mp3
which was converted (using `URLChecker.prepareURL`) to
http://pcast:logbuch-netzpolitik.de/feed/mp3
Therefore, the invalid port error message
> Trimming 'pcast:' without '//'

- app/src/main/java/de/danoeh/antennapod/activity/StatisticsActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java
- app/src/main/res/layout/calculation_type.xml
- app/src/main/res/layout/statistics_mode_select_dialog.xml
- app/src/main/res/menu/statistics.xml
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/res/values/strings.xml
This new setting makes it easier to keep statistics even when switching podcast clients (by marking as played). It also respects podcasts you listened to before getPlayedDuration was introduced. 
Related discussion: http://www.github.com/AntennaPod/AntennaPod/pull/1841
Replaces #2111, I changed the branch
> Allow choosing between getDuration and getPlayedDuration

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N.
Try changing activity to activity.getApplicationContext()
[WifiManagerLeak]
> fix wifi service mem leak

- app/src/main/AndroidManifest.xml
Allows antennaPod to be movable, can be installed on SD card
Unfortunately, this does not move the podcast location to the card, just the app.
> set android:installLocation to auto

- build.gradle
- core/build.gradle
- core/src/free/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
This feature is only enabled for "play" build.
It is useful to skip advertisement during a podcast.
Note: I originaly tried to implement this in the "4 ways controller" managed by
the mediaSession (it contains vol up / vol down / skip). This object is linked
to the capabilities of the session and seems to be hard to customise without
changing the capabilities.
This patch simply add 2 new buttons
> add a "rewind" and "fast forward" button for android Wear

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
Fixes error when refreshing feeds:
```
10-15 16:21:34.157 885-893/de.danoeh.antennapod E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at android.database.CursorWindow.<init>(CursorWindow.java:111)
at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
at de.danoeh.antennapod.core.storage.DBReader.getFeedImages(DBReader.java:906)
at …
```
> Close cursor before returning

- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/res/values/strings.xml
This implements "keep episodes marked as favourite from being auto deleted after playback completes".
I find it a bit confusing that there are 2 "auto delete" functionalities:
1. after playback completes
2. Episode Cleanup's auto delete (at new episodes download time)
in case of no. 2, favourites were already kept (issue #1709),
however episodes marked as favourite were still deleted if "auto delete" was enabled, this was mentioned in issue #60.
> Skip favorite episodes during autodelete

- app/src/main/res/xml/preferences.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
- core/src/main/res/values/strings.xml
As I got "unlimited" data on my mobile I switched off wifi and found AntennaPod no longer did auto updates. I therefore downloaded the source, got android-studio and added the option to auto download even when you are not on wifi, even though I haven't done any android development before.
I've run with my changes for a few months without any problems and though it may be helpful for others.
I now see there is issue #2005 where this change is suggested already.
> Add auto download on mobile connection option

- core/src/androidTest/java/de/danoeh/antennapod/core/tests/util/DateUtilsTest.java
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
According to [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) the correct abbreviation is `Sep`. But [some](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521548) [generators](https://github.com/sparkle-project/Sparkle/issues/217) incorrectly use `Sept` instead. That causes the feed to be displayed out of order, and when logging is enabled, logcat shows `DateUtils: Could not parse date string`. The same feed works in Podcast Addict.
> Parse RSS pubDate fields containing "Sept"

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Changed the implementation of the 'Parcelable' to sync with what is written to the DB.
It could happen that if Android OS deserializes a FeedMedia, that a  playback position is set to the LocalPSMP which is quite old. As described in #2382 this is easily reproducable in Andoid O probably because of the aggressive Background Task management.
> Reload FeedMedia from DB to ensure correct playback position - fixes #2382

- app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/feed/Chapter.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java
Problem was that the chapters were read from the just downloaded file and persisted even if the database already contained chapters read from the feed.
Resolves #2397
> Avoid duplicate chapters

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
This should fix the issues with headset the button on Android 8.1+. The issue was that the media event was not properly consumed by AntennaPod (return true instead of false).
> Resolves #2475 (Headset button press not correctly handled)

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
This way, downloads get resumed even if the service crashes, instead of leaving dead files
Closes #2316, closes #1916
> Setting File_url when starting download

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/res/layout/downloaded_episodeslist_item.xml
- app/src/main/res/layout/downloadlist_item.xml
- app/src/main/res/layout/downloadlog_item.xml
- app/src/main/res/layout/feeditemlist_item.xml
- app/src/main/res/layout/mediaplayerinfo_activity.xml
- app/src/main/res/layout/new_episodes_listitem.xml
- app/src/main/res/layout/queue_listitem.xml
- app/src/main/res/layout/searchlist_item.xml
- app/src/main/res/layout/simplechapter_item.xml
- core/src/main/res/values/dimens.xml
> Improved list items when using a large font size

- app/src/main/res/layout/feedinfo.xml
This defined onClick callback does not exist, so we
don't need to specify it.
> remove reference to nonexisting onClick callback

- build.gradle
According to https://developer.android.com/about/dashboards/index.html
API levels of 14 and lower are only on less than 0.5% of the devices.
IMHO it is time to move on, and allow for some compat code cleanup.
Example cleanup included, but there is a lot to remove (extra resources,
various conditionals in the code)
> set minSdkVersion to 14

- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
Previously on first start of a video the aspect ratio
was not correct (annoying on a 18:9 phone as
it doesn't match the usual 16:9 aspect ratio). So extract
the code into a setupVideoAspectRatio() helper
and call it from surfaceCreated as well.
> Set video aspect on initial creation

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
- core/src/main/java/de/danoeh/antennapod/core/export/html/HtmlSymbols.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Adding final prohibits modification and allows initialization of
primitive and String fields at compile time instead of runtime in
clinit:
https://developer.android.com/training/articles/perf-tips.html#UseFinal
Found via error-prone.
> Make some static fields final

- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Because of #2339, the file always exists when starting a download.
There is still an issue with the server parsing "Range: bytes=0-"
incorrectly, but this commit should make the error appear less often.
Related to #2539
> Hotfix for servers not accepting the Range header

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
Simple fix for issue #2555 – when sorting the list of WiFi connections, handle the case that the SSID may be null.
> Fix for #2555 - handle null SSID in WiFi list

- core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java
May fix #2386. If so, thanks to @cyplo who provided the logcat output
which directed me to that code path.
> Fix possible NPE accessing image.download_url

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Closes #2541.
We do not need the same icon twice.
As the icon is displayed white-on-white, it is not visible anyways.
This also gives more space to the notification text
> Removed large icon from notification

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
This crash can be reproduced when exporting the database and importing it into
the debug version. Native crash.
> Fixed crash if media file exists but can not be read

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/res/layout/cover_fragment.xml
- app/src/main/res/layout/external_player_fragment.xml
- app/src/main/res/layout/feeditemlist_header.xml
- app/src/main/res/layout/main.xml
- core/src/main/res/values/colors.xml
This fixes that awful flickering when returning back to the queue:
Feed header background color:
Closes #2565
> Layout improvements

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- core/src/main/res/values/strings.xml
The same message is shown for HTML and OPML. Fixes #2462.
Additionally, using string formatting now instead of just "+"
> Use generic export message instead of OPML

- app/src/main/res/layout/nav_list.xml
Without this change, it seems like the sidebar is not usable
by using arrow keys only.
Related to #445.
> Allow to focus settings button

- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
This probably fixes all those "db deleted" issues and mysterious NPEs
Previously, the synchronized keyword on open() and close() was useless
because it was synchronizing on different objects in each thread.
Might fix various bugs like:
#1945 #2270 #2463 #2571
> Actually return instance in getInstance

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
When registering the receiver, it immediately receives
a headset unplugged event (broadcast is sticky) and pauses
playback again in some cases. We are only interested in status
changes, so we can just return.
Fixes #2635
> Don't pause directly after starting

- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
I forgot this one in #2644. Improvement can be observed when "deleting" the PictureInPicture dialog while having opened AntennaPod.
> Ignore more invalid positions

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
- core/src/main/java/de/danoeh/antennapod/core/util/FeedItemUtil.java
- core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java
For #2579 Provide share Link in episode playback screen even when there is no episode link. 
For the case that a feed item / podcast episode does not have a link (to episode website), the change will fallback to use feed / podcast website link in:
1. share link in FeedItem playback and FeedItem information screens (#2579)
2. visit website menu action for the above two screens (so that visit website and share link have consistent behavior)
It also fixes a (presumably) bug in share link with position, so that the share includes podcast and episode titles in the share text, to be on par with other share variations.
Closes #2579
> Share link improvement 2579

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
I think it's okay to prevent deletion of the current episode (#2674). When deleting the whole feed, there is already a warning dialog, so we can just stop the service to prevent "stuck" playback
Closes #2425
> Stop playback service when feed is deleted

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
It appears that Oreo has changed the behavior for Bluetooth KeyEvents.
Starting with Android 8.0, KeyEvent.getSource() returns 0 (unknown
source).
This change explicitly sets when a key press is sent from a
notification, or lockscreen event. Otherwise we use the
customer-defined skip behavior.
Fixes #2428
> Fix Bluetooth Forward Skip Button for Android 8

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
This PR closes issue #2680. It was suggested that the time remaining text read "n hours nn minutes left.", but there was already a String resource for "Time left:" so I used that instead.
> Display time left in queue info bar

- app/build.gradle
Speed up debug build by making `dexcount` plugin optional in debug build, configured with a new gradle property enableDexcountInDebug.
> Build tweak: Speed up debug build by making dexcount optional in debug build

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences_autodownload.xml
- app/src/main/res/xml/preferences_network.xml
Instead of displaying both the autodownload screen and the autodownload checkbox in search, ignore the screen and only display the checkbox (with a summary).
> Improve autodownload in search

- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
While working on the changes for https://github.com/AntennaPod/AntennaPod/pull/2697 I was reading over the `DownloadRequester.java` code and noticed the `context` parameter is unused in several places. This PR simply removes the unnecessary parameter, which cleans up the code a bit. I was able to unwrap some lines and still stay under the 100 char limit
> avoid unused context parameter

- app/src/main/java/de/danoeh/antennapod/activity/AboutActivity.java
- app/src/main/res/layout/about.xml
- create((Observable.OnSubscribe<String>) was deprecated, so replaced with fromCallable(())
- Navigating through the Links would latch the depth greater than 1, and so you couldn't leave the About page (replaced depth with webView.canGoBack())
- Code clean-up:
- Removed unnecessary version check
- Fixed spelling
- Removed unnecessary import
> About activity cleanup

- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
Most tests work now. Some fail because of Robotium is not seeing the text, even though it is clearly on screen (switch to Espresso in another PR?)
> Fixed most preference tests

- core/src/main/java/de/danoeh/antennapod/core/storage/DBUpgrader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
This has two advantages:
1) PodDbAdapter has 1724 instead of 1980 lines of code
2) Import/Export can use the code in the future
> Moved database upgrades to their own class

- app/sampledata/episodes.json
- app/sampledata/inplaylist
- app/sampledata/secondaryaction
- app/src/main/res/layout/all_episodes_fragment.xml
- app/src/main/res/layout/new_episodes_listitem.xml
- app/src/main/res/layout/secondary_action.xml
I make use of the [new sample data feature](https://developer.android.com/studio/write/tool-attributes#toolssample_resources) to render actual data in layouts. With that the background colors in preview mode are no longer needed.
I set the sample data up so that the individual items are rendered with **random** content.
> Render preview for all episodes layout with sample data.

- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/handler/TypeGetter.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/handler/UnsupportedFeedtypeException.java
Improves the error message in #2749.
Adds meaningful message and fixes a NPE that occurs if the feed is invalid (`e.getRootElement()` is null).
> Better feed parser errors

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
This could be a fix for #2752
In my case, the icon was not loaded because username and password were not `null`, but `""`. Looks like the server did not like empty credentials. I think it is safe to assume that an empty username is not a valid username (empty password could be).
Not sure how this single feed ended up with non-null credentials, but probably I played around with the feed settings screen.
> Do not authenticate image without user

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java
Closes #2538
`NSRSS20` uses a check if the parent element (`second`) is the feed or the feed item. This check is not present in `NSITunes`, so every parsed item overwrites the feed's description.
// NSRSS20.java
if (CHANNEL.equals(second) && state.getFeed() != null) {
state.getFeed().setDescription(content);
}
> https://github.com/AntennaPod/AntennaPod/issues/2538#issuecomment-357874512
> This doesn't happen for each and every feed, does it?
This does not happen for feeds that specify the description on the bottom of the feed (below all item descriptions). In this feeds, the last description that is overwritten is by accident the one we actually want.
> Do not overwrite feed description with item description

- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java
Could not reproduce this on the emulator, so I had to rely on documentation.
Resolves #2815 
As Job IDs must be unique per uid (https://commonsware.com/blog/2017/06/07/jobscheduler-job-ids-libraries.html), use IDs that no one else will use...
> Enqueue jobs with a unique job id per class

- app/src/main/java/de/danoeh/antennapod/preferences/NumberPickerPreference.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/layout/numberpicker.xml
- app/src/main/res/xml/preferences_network.xml
Closes #2818
Settings `inputType` does not seem to work. Android still presents the text keyboard. Therefore, this PR creates a new preference that can be used to enter numbers only.
<EditTextPreference
android:defaultValue="4"
android:inputType="number"
android:digits="0123456789"
android:key="prefParallelDownloads"
android:title="@string/pref_parallel_downloads_title"
app:useStockLayout="true"/>
> Implemented number picker preference

- core/src/androidTest/java/de/danoeh/antennapod/core/util/DateUtilsTest.java
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Added "EEE d MMM yyyy HH:mm:ss 'GMT'Z (z)"  time format to DateUtils class, so AntennaPod could parse dates like "Sun 01 Mar 2015 01:00:00 GMT-0400 (EDT)"  whish are for example used in "https://s3.us-east-2.amazonaws.com/podcast.intelligence.org/razmedia/razfeed.xml" 
Added new time format to the bottom, because it seems to be used rarely, so there is no sense to keep it higher in the array.
Closes #2801
> [#2801] (AntennaPod failing to parse date in "Sun 01 Mar 2015 01:00:00 GMT-0400 (EDT)" format)

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/res/menu/allepisodes_context.xml
- core/src/main/res/values/strings.xml
Closes #2580:
Expose "Mark as seen" as a context menu item in Episodes screen, in addition to the existing (somewhat hidden) swipe in Episode > New tab.
What it does not include:  it is not exposed to other type feedItem list UI, e.g., Queue, podcast, etc. (If desired, it can be done by changing `feeditemlist_context.xml` and `FeedItemMenuHandler.java` ( `onPrepareMenu()` and `onMenuItemClicked()`), ``
> Expose "Mark as seen" as a context menu item in Episodes screen

- core/src/main/res/values/colors.xml
Didn't see an issue for this minor issue, but found this while looking at the AMOLED theme.
On the standard AMOLED theme, you couldn't see which chapter was currently playing because the highlight color was the same color as the background:
Current `develop` branch:
So changed the color so that it was lighter, and recognizable as a highlight.
My PR:
> Fix AMOLED chapter currently playing highlight color

- app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
- app/src/main/res/xml/preferences_user_interface.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
This PR allows users to change how the back button functions. Closes #2196
Possible choices are following:
- **Default** - back button functions how it currently functions (closes the app if there is nowhere to go back to)
- **Go to page** - back button opens chosen page (Queue, Episodes or Subscriptions) and closes the app if you're already on that page
- **Open navigation drawer** - back button always opens the navigation drawer instead of closing the app
- **Double tap to exit** - like default, but requires two taps to close the app
- **Confirm to exit** - like default, but prompts user if they really want to exit
---
> Add configurable behavior of the back button

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
It partially addresses #2947, preventing app crash.
The PR does not address the root cause of #2947, on why the player intermittently got stuck to begin with.
> Fix app crash in some error cases with ExoPlayer

- core/src/main/res/values-v23/styles.xml
- core/src/main/res/values/colors.xml
- core/src/main/res/values/styles.xml
The status bar now has the same color as the toolbar, like most Google apps do it. In my opinion, this looks a bit more modern. I am open to hear other opinions. Looks better on a real device than on the screenshots :)
Before:
After:
> Expanding toolbar

- app/src/main/AndroidManifest.xml
Closes #2948 - Make AntennaPod go to last activity when launched again [*], per standard Android App behavior.
[*] If AntennaPod has been used recently (approximately last 30 minutes), and has not been explicitly removed by users.
Discussion:
- removing `singleTask` from `SplashActivity` will not cause unwanted side effects in navigation (the task stack), given `SplashActivity` always quickly go away anyway. The actual purpose for `singleTask` is preserved in `MainActivity`.
See [AndroidManifest.xml's history](https://github.com/AntennaPod/AntennaPod/blame/1.7.1/app/src/main/AndroidManifest.xml#L51) for reference.
- `android:alwaysRetainTaskState="true"` could have been set so that AntennaPod *always* go to last activity (e.g., even if users removes it from recent app list), but such …
> make AntennaPod go to last activity (rather than MainActivity) when launched again

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
this is a solution to fix the issue of media data disappearing on screen rotation. I had to move the setupGUI method to the onCreate() because there is the issue that the oncreate method is called everytime you rotate. In order to save the fragment data, the ID has to be initialized and if the setupGUI is in onStart() method it throws a null pointer exeption.
An easier solution to this would have been to stop the activity for getting recreated on rotate in the AndroidManifest, but the problem is that MediaplayerActivity isn't a valid activity because it is declared as an abstract class. Also setting it to MediaplayerinfoActivity had no effect and onCreate() was still called.
closes #2992
> Fixed losing media data on rotation

- app/src/androidTest/java/de/test/antennapod/util/ConverterTest.java
- app/src/androidTest/java/de/test/antennapod/util/playback/TimelineTest.java
- core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
Fixes #3031.
This changes the definition of 'short' and 'long' timecode when parsing the shownotes. A  'short' timecode has the format of MM:SS instead of HH:MM. A long timecode is HH:MM:SS. In addition the first part of a timecode can contain one or two digits.
Tests were updated to reflect this new definition and some new ones were added as well.
If there is anything else that needs to be done or changed please let me know.
> Change Timecode Regex

- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
It seems clear to me that the intent was to use encodedQuery, which avoids issues related to illegal characters by encoding them (so % gets changed into %25, space into +, etc...). The explicit replacement of space with +  is also not needed anymore.
This also makes the `encodedQuery = query; // failsafe` line make sense
This fixes #3028 and maybe other issues
> Fix #3028: actually use encodedQuery from URLEncoder to avoid encoding issues

- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
I'm not sure this is the best way to go about this, especially since I had to import the charset library, so please do take a look at it.
> Fix #3054: use UTF-8 to encode password and username for gpodder auth 

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
It fixes the issue https://github.com/AntennaPod/AntennaPod/issues/2162#issuecomment-473173597 raised by @sbadux
- It should also address the inflated played duration reports in 2018 raised in the issue.
- It is unclear if it addresses the original 2016 issue in #2162 . The statistics logic that is fixed was introduced in 2017 (PR #2294) released in `v1.6.1.4` .
> bugfix - statistics - inflated actual played duration

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
If an item has already been played, downloading its media will not
reset that "played" flag.
Fixes: #3067
> Do not reset item "played" flag on media download

- core/build.gradle
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/test/java/de/danoeh/antennapod/core/feed/FeedItemTest.java
- core/src/test/java/de/danoeh/antennapod/core/feed/FeedMediaMother.java
- core/src/test/java/de/danoeh/antennapod/core/feed/FeedMediaTest.java
A follow-up to PR #3068 that adds tests for issue #3067.
As discussed previously in PR #3068, the condition on which the `FeedItem` state is changed has been updated to be clearer (use `FeedItem.isNew()` instead of `!FeedItem.isPlayed()`). *This is a bonus from the explicit tests added by this commit which would otherwise fail.*
> Validate that the item state is only changed when needed

- app/src/main/res/xml/preferences_network.xml
- core/src/main/java/de/danoeh/antennapod/core/UpdateManager.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
- core/src/main/res/values/arrays.xml
- core/src/main/res/values/strings.xml
Makes mobile updates setting tri-state (nothing/images/everything). Defaults to `images` to prevent issues like #3079 and #2752
Also fixes some crashes related to image loading on mobile networks.
Closes #2918
> Mobile updates: Allow images

- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java
- core/src/main/java/de/danoeh/antennapod/core/receiver/MediaButtonReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/util/Optional.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackServiceStarter.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
Closes #2716. The code is complete, pending reviews requested and testing of cast scenario.
This first cut check-ins definitely solves the phantom service notification in #2716, as it eliminates the source of it (the workaround dummy notification). It is tested with
- existing test suite (note: `VideoPlayerActivityTest` failed, but it has been failing even before the check-in)
- manual testing for typical audio playback: in app, notification controls, lockscreen controls, widgets.
- devices covered: Android 7 devices, Android 9 and Android 4.4 simulators,
fc0f49f523fd350f4cef9eaa40fa38a476dc59b5 is the crux. It follows the pattern in Google Sample App as explained in https://github.com/AntennaPod/AntennaPod/issues/2716#issuecomment-444282899
Plan:
Out of scope:
- Potentially replacing …
> Fix phantom service notification

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Fixes #3084
Only created the adapter when it is actually necessary and throws it away if not. Not sure why the first item after an undo is not rendered correctly, seems to have something to do with stable ids...
> Create new adapter to show single item after undo

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
I have another suggestion for fixing the media player screen, just as #3072 and #3095.
> @orionlee: https://github.com/AntennaPod/AntennaPod/pull/3072#issuecomment-480531425
> The current MediaplayerInfoPagerAdapter that tries to keep states are bound to fail in some cases, as Android does its own thing outside the adapter.
I have removed all state from the fragments and the adapter. The fragments create their own connection to the PlaybackService and can be created and restored by the Android system without any problems. The fragments even are no longer dependent on the Activity they are shown in - this makes it easier to implement something like #2353 in the future.
Possible problems: The fragments create their own connection to the PlaybackService. This might be a bit of an overhead …
> Do not hold state in fragments

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
After much noise in #3087 (sorry), I finally managed to get a responsive ExoPlayer in the main thread!. Apparently, ExoPlayer does not call `onSeekProcessed` and therefore, AntennaPod waited until the 3 seconds timeout every time a seek happened. When calling `audioSeekCompleteListener` directly, everything is fine.
Closes #3025
> Executing all ExoPlayer methods on main thread

- core/src/main/java/de/danoeh/antennapod/core/util/FeedUpdateUtils.java
Closes #2956 
- The fix should also remove some occasional unresponsive UI, as the UI also occasional call automatic feed update.
See: https://github.com/AntennaPod/AntennaPod/search?q=checkShouldRefreshFeeds&unscoped_q=checkShouldRefreshFeeds
- a side effect is for scheduled automatic feed update on Android 7+ devices, it now
spawns an additional thread to check for network availability. It is already being run in a background `JobService` so the additional thread is not necessary.
It can be eliminated with additional logic branching, but I feel the added complexity is not worth the once-in-a-while additional thread.
> Prevent app crash during some automatic feed update

- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
If the playback is finished in background, the fragmentLayout is not hidden.
Steps to reproduce (without this commit):
- Start last item in queue
- Leave app using home button
- Finish playback by using notification skip button
- Resume to AntennaPod
- ExternalPlayerFragment is shown (in invalid state) but should be hidden
> Hiding ExternalPlayerFragment onStart

- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
When adding certain podcasts, a `LeakedClosableViolation` is thrown
due to the fact that we can make multiple requests with the same `OkHttpClient`.
Also, when removing podcasts, another exception is thrown since RxJava no longer accepts `null` values.
This PR fixes both issues. More details can be found in the individual commit messages.
> Fix thrown exceptions when adding/removing podcasts

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Because #3093 set the adapter to null, the eventbus changes are no longer handled. This PR just reloads the whole list if the list is empty and an event occurs.
Closes #3144
> Fixed empty list not receiving updates

- app/src/main/res/layout/nav_feedlistitem.xml
When we're not able to get the episode count for a podcast and updating
the feed fails, the error icon shown in the navbar is too close to the
right/end border of the nav drawer.
This fixes this padding.
Closes: #2982
> Fix padding when count is zero and error happened

- app/src/main/java/de/danoeh/antennapod/activity/AboutActivity.java
The Google Play pre-launch-report starts using AntennaPod as a web browser...
> About screen: Open web links in browser

- app/build.gradle
- app/src/main/res/layout/cover_fragment.xml
- core/build.gradle
The cover fragment would hide both podcast and episode names in small
screen devices or multi-window mode.
This replaces the deprecated PercentRelativeLayout in favor of a regular
LinearLayout with weights to make sure that each section of the fragment
(podcast title, image, episode name) will have the necessary space in
the screen.
Since PercentRelativeLayout was only being used here, it also removes
the dependencies from the gradle files.
Closes: #3169
> Fix cover fragment in small screens

- core/src/main/res/values/styles.xml
@orionlee, you added the `type="attr"` attribute. In my opinion, this is not needed and it even causes errors to be displayed. I suggest removing the `type` attribute. When removing, the app still compiles fine. I have never seen an app which does use the attribute. They all do it like in this PR [k9](https://github.com/k9mail/k-9/blob/master/app/ui/src/main/res/values/themes.xml), [Transportr](https://github.com/grote/Transportr/blob/master/app/src/main/res/values/themes.xml), [Owncloud](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/values/styles.xml)
> Fixed attr redeclaration

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/parsers/DurationParser.java
- core/src/test/java/de/danoeh/antennapod/core/syndication/parsers/DurationParserTest.java
Apple says [this][1] about the `<itunes:duration>` tag:
If you specify a single number as a value (without colons), Apple
Podcasts displays the value as seconds.
This PR handles this single-number format.
Closes: #3024
[1]: https://help.apple.com/itc/podcasts_connect/#/itcb54353390
> Handle iTunes single-number duration format

- app/src/main/res/menu/episodes.xml
Previously, when the user clicked the search button, the context menu
would be hidden and the refresh button would move way too close to the
edge of the screen.
This makes sure that when a user clicks the search button on the
episodes screen, the remaining actionbar items (refresh and context
menu) stay where they are.
> Prevent actionbar items from moving when searching for episodes

- app/src/main/java/de/danoeh/antennapod/adapter/DataFolderAdapter.java
- app/src/main/java/de/danoeh/antennapod/dialog/ChooseDataFolderDialog.java
- app/src/main/res/layout/choose_data_folder_dialog_entry.xml
- core/src/main/java/de/danoeh/antennapod/core/util/StorageUtils.java
- core/src/main/res/values/strings.xml
This displays a progress bar with the amount of used/free space in each
storage location to make it easier to identify storage devices. This is
particularly useful for devices that use non-standard names as mentioned in #3049.
**Yet to be implemented**: identify whether a location is internal/external.
Comments and feedback are welcome. =)
> Add progress bar with space information to data folder selection dialog

- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
According to the stack trace provided by @ByteHamster on #3197, the `ScheduleThreadPoolExecutor` is rejecting the task to start the widget updater. I'm guessing the executor was shut down based on the stack trace and [OpenJDK's source](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ScheduledThreadPoolExecutor.java) for `ScheduledThreadPoolExecutor`.
What I'm guessing is happening is a race between the `PlaybackService` initiating shutdown after being destroyed by the system, and a media playback event that starts the widget updater back up. I've added a failing test as a first commit to confirm this, and the fix commit also makes the test pass.
Fixes #3197.
> Fix scheduling tasks on shutdown executor

- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
If the iTunes fragment is disposed (e.g. if the user navigated away) while the iTunes list is still loading, or while the metadata for a particular podcast is loading, an `InterruptedIOException` will be thrown and delivered to an error handling lambda. However, said lambda is part of a `Disposable` belonging to the fragment which, at the point of delivering this error, will have been cleaned up. This causes RxJava framework to throw an uncaught `UndeliverableException`, which terminates the app.
Thanks @ByteHamster for the stack trace :)
Fixes #3196.
> Avoid error delivery to disposed Disposable

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Without this change, http images in shownotes are not displayed.
Mixed content should be ok because we do not load scripts.
Closes #3189
> Clear text traffic in shownotes

- app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java
- core/src/main/res/values/strings.xml
Fixes #3148 
Provides warning when one attempts to log in to GPodder but enters unaccepted characters in the username field e.g When user enters email in username field, a warning will be provided to show that the user has entered unaccepted characters.
> Validate username for characters not accepted.

- core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java
`URLDecoder.decode` throws an `IllegalArgumentException` if a URL is malformed. Specifically in #3247, the ID3 chapter frame contains a malformed user-defined URL (WXXX) frame where a percent sign isn't encoded as `%25` like it should be.
Instead of crashing, let's drop the URL and continue along.
Fixes #3247.
> Gracefully handle bad ID3 chapter URLs

- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Previously this method considered a date within the last 365 days to
be in the same year as today.  Instead compare the actual years to
avoid confusion.  Fixes #3255.
> Fix within last year check in formatAbbrev

- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
- app/src/main/res/layout/cover_fragment.xml
Works on #3220
Extend the play/pause functionality to `image cover`. When the user taps the `image cover`  This performs the same actions as `play/pause` in the bottom control area.
> Extend play/pause functionality to Image Cover

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/activity/FeedSettingsActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
- app/src/main/java/de/danoeh/antennapod/viewmodel/FeedSettingsViewModel.java
- build.gradle
Currently, we're relying on the settings activity being created before the settings fragment. However, the latter will be recreated automatically on config changes, e.g. rotating the screen, at the `super.onCreate(savedInstanceState)` call.
This PR creates a new `ViewModel` for keeping Feed data around for the settings activity and fragment throughout their lifecycles, including config changes e.g. screen rotations. This effectively removes the assumption that the Activity will always control the creation of the Fragment.
Bonus: using the `ViewModel` means we don't re-read the Feed from the DB on every screen rotation. ;)
Fixes #3245.
> New ViewModel for loading feed preferences across lifecycle

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
Fixes #3209
Fixes the issue when that happens when long-pressing a favourite episode, selects "Remove from favourites" and it removes the wrong episode on some occasions.
> Fix removing wrong favourite message

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/RunningDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
- core/src/main/java/de/danoeh/antennapod/core/event/DownloaderUpdate.java
Unregistering from the EventDistributor on stop will prevent the screen
from updating when coming back from the off screen (#2747 and #3203),
so this registers/unregisters on start/stop while also making sure that
the screen is reloaded on start.
Therefore, we need to also call `loadItems()` (or the equivalent method
of the fragment) to make sure that when we come back from an off screen
it is updated appropriately.
It also makes sure we take advantage of the native fragment lifecycle [[1]]
instead of storing state about whether views have been created and attributes
have been assigned.
[1]: https://developer.android.com/guide/components/fragments
Closes: #2747
Closes: #3203
> Reorganize fragment lifecycle

- app/src/main/res/layout/mediaplayerinfo_activity.xml
- core/src/main/res/values-h768dp/dimens.xml
- core/src/main/res/values/dimens.xml
Extracts the scrub bar to a separate layout and adds vertical padding to the scrub bar on large devices.
**NOTE**: this PR is based on #3232 .
Fixes #3201.
> Pad scrubber on large devices

- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
This allows the user to better search through an episode, by allowing
them to rewind less than what was just forwarded. It is also aligned
with how other apps out there behave.
Closes: #3262
> Change default rewind time to 10s

- core/src/main/res/layout/player_widget.xml
Reduced space between title and timestamp. Also, fixed some RTL layout problems.
Closes #3251
> Reduced widget spacing

- .circleci/config.yml
- app/src/main/AndroidManifest.xml
- build.gradle
Starting in November, app updates must target API 28. I went through the list of [Behavior changes](https://developer.android.com/about/versions/pie/android-9.0-changes-all) to verify that nothing is broken. Extensive testing is still needed.
> Targeting Android API 28

- core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
When #3284 (Make ExoPlayer the default player) was merged [1],
`UpdateManager` was removed but a reference to it was left behind in
`ClientConfig`, which causes the project not to build.
Since its contents were integrated into `app/PreferenceUpgrader`, we no
longer need this entry here.
[1]: https://github.com/AntennaPod/AntennaPod/pull/3284
> Remove non-existing class from ClientConfig

- app/src/main/java/de/danoeh/antennapod/fragment/preferences/AutoDownloadPreferencesFragment.java
When a user has many wifi networks it can be difficult to remember if
a given network has upper- or lower-case.
> Sort automatic download wifi names ignoring case

- .circleci/config.yml
- app/src/androidTest/java/de/test/antennapod/ui/PlaybackSonicTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java
Fixed androidTest compilation errors introduced in #3322
> AndroidTest fixes due to PR #3322

- app/src/main/res/values-w300dp/dimens-fabspeeddial.xml
make the incorrect :app:lintVitalRelease error go away.
(The base named dimen comes from fab speeddial library, thus it is not actually missing)
> Make the incorrect :app:lintVitalRelease error go away.

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java
Hopefully fixes some unreproducible cases where clicking the notification buttons just does nothing.
> Executing notification actions in foreground

- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
Closes #3373, #3374 (bundle together as both are small enough fixes to lump in the same set of files).
For #3374, arguably, a better UX will be when fab is open, the user should not be able to change the items selected, i.e., hiding all the action menu items. In such UX, the UI will prevent users from deselect all when fab is open.
> fix batch edit: deselect all label and FAB overlay remains when deselect all

- app/src/main/java/de/danoeh/antennapod/discovery/CombinedSearcher.java
This needs more work but for now, we can just skip gpodnet results. Gpodder returns many outdated results which is worse for most users than not finding everything. Related to #3376.
> Disabled gpodnet in combined search

- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
Android stops the PlaybackService but we still have the audio focus callbacks in place. When the service is stopped, we stop the executors in `PlaybackService.onDestroy`. If the callback is then executed, the app crashes because the executors are stopped.
After this PR, `PlaybackService.onDestroy` removes the audio listeners. Therefore, after an interruption that is long enough so that Android kills the service, the listeners are not called to a destroyed service. A side effect is that the user has to press *play* manually after leaving playback for too long but I think this behavior is okay.
Closes #3186
```
// Playing
2019-09-09 18:27:53.006 16336-16336/de.danoeh.antennapod.debug D/PlaybackService: Saving current position to 16770
2019-09-09 18:27:58.008 …
```
> Fixed receiving audio events after service shutdown

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
Sonic also leads to crashes. Setting to ExoPlayer on upgrade for all users, regardless of their selected player. I don't think many users care about the media player and by switching the player, we can get rid of all kinds of playback issues.
> Ensure that ExoPlayer is set

- core/src/main/AndroidManifest.xml
minimal fix for #3387 to be included in v1.7.3 release (no UI changes)
> #3387 short-term (v1.7.3) fix for Auto Downoad WiFi filter UI on Android 10+

- app/src/main/res/menu/feedinfo.xml
- app/src/main/res/menu/feedlist.xml
- core/src/main/res/values/strings.xml
Closes #2977 .
The fix is trivial with the new label "Share Podcast URL" on Podcast screen menu.
The text "Share Podcast URL" is a new resource that requires translation.
> Fix incorrect "share podcast url" label

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
- app/src/main/res/menu/mediaplayer.xml
It addresses a point of #2929 .
(I personally would be happy to close the issue with this PR, but there are still requests about the opening podcast from Episode (feedItem) Screen.)
Added a new action menu item "Open Podcast" to go to the podcast from Player Screen directly.
> add Open Podcast to player screen

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Steps to reproduce:
- Send STOP key two times
- Service starts foreground but does not stop again because stateManager does not know about foreground state
> Fixed another phantom service is running notification

- app/src/play/java/de/danoeh/antennapod/activity/CastEnabledActivity.java
- app/src/play/java/de/danoeh/antennapod/preferences/PreferenceControllerFlavorHelper.java
- core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/play/java/de/danoeh/antennapod/core/cast/CastManager.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
Closes #3069 - It fixes an issue that for Google Play store version, AntennaPod will invoke Cast-related Google Play Service even when an user disables Chromecast support.
TODOs:
> Avoid Cast initialization unless it is enabled

- app/src/main/java/de/danoeh/antennapod/PodcastApp.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
The amount of messages that AntennaPod produces is quite high. Especially the position update every second during playback produced a ton of messages. Removed those messages. Additionally, removed messages that contain the cover urls.
> Reduced logcat output

- app/src/androidTest/java/de/danoeh/antennapod/core/service/download/StubDownloader.java
- app/src/androidTest/java/de/test/antennapod/service/download/DownloadServiceTest.java
- app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java
- app/src/androidTest/java/de/test/antennapod/util/event/FeedItemEventListener.java
- app/src/androidTest/java/de/test/antennapod/util/feed/FeedItemEventListener.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
A follow-up on #3471 . 
The test spells out the expected behavior for `DownloadService` upon media download success, to guard against regression.
> Test download service event posting

- app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
Steps to reproduce:
- Open feed screen, observe that item does not have a progress bar
- Play that exact item from the queue
- Switch back to feed screen
- Progress bar is updated but invisible
> Fixed missing progress bar on position update

- gradle.properties
Explicitly set max gradle jvm memory - otherwise, release build fails on some machines after AndroidX migration.
On my box setting it to `-Xmx=1536m` would work. I chose to set it to a higher `-Xmx=4096m` so that for developers with better machine, the explicit settings wouldn't hamper them.
> Explicitly set max gradle jvm memory

- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
Users on Google Play seem to be confused that they can not select a
playback speed lower than 1x anymore. The reason is that they just
use the preference dialog and that dialog only displays the range
that is selected for the button.
> Added 0.75 to default playback speed list

- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/ItemActionButton.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java
- app/src/main/res/xml/preferences_playback.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/values/strings.xml
Implementation of option to display `Stream` button in place of `Download` (closes #3019 )
* Added user preference to favor streams
* Added StreamAction to provide Stream button in feed/queue listitems
> Show stream button rather than download (in queue, podcast views)

- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayActionButton.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
We can't resume because PlaybackService is stopped after finishing playback (because it's a foreground service). Just call the service directly.
Closes #3540
> Removed resume intent

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
Closes #2945
If the feed explicitly specifies an episode image, use that instead of the embedded image in the media file. This fixes the problem that media files change their icons if there is a mismatch between embedded and feed-specified image. In most feeds I tried, this change even improved the resolution of the image (embedded often seem to have lower resolution). In opus files, this speeds up loading the image.
I don't think that there are publishers who add an episode-specific cover to the media file but not to the feed. One side effect could be that users start to notice more episode-specific covers. #3505 adds an option to not show episode-specific covers if someone is not happy with that.
> Prefer image that is specified in feed over embedded image

- core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java
If option "pref_followQueue_title" is disabled, when played episode #1 is ended and next episode #2 is loaded, progress string on widget show incorrect information about position and duration of episode, because it show (position / duration) of ended episode #1 instead of (position / duration) of loaded episode #2.
> Fix incorrect progress string on widget

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceStateManager.java
When pausing, we stop the foreground service. This prevented re-entering
foreground state later, which lead to Android killing the service after a
few seconds.
Closes #3570
> Fixed pressing play from headset button

- app/src/androidTest/java/de/test/antennapod/service/download/DownloadServiceTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DownloadActionButton.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/MobileDownloadHelper.java
- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
- core/src/androidTest/java/de/danoeh/antennapod/core/service/download/DownloadRequestTest.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
Follow up on PR #2714 . 
Handle #2448 for the case user cancels a download. With the PR, the episode will be dequeued if it was auto-enqueued as part of the download.
Closes #2448
> More respect download order - handle cancel

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
We tried to prioritize feed downloads over media downloads but that never worked because the `downloadExecutor` executes requests in the order they were added in. This fix adds the downloads to our list in the same order.
Changing the priority in a `ThreadPoolExecutor` with custom queue is possible but we currently use a `ExecutorCompletionService` that wraps a `ThreadPoolExecutor`. The `ExecutorCompletionService` handles `Callable<Downloader>` while a normal `ThreadPoolExecutor` only handles `Runnable`.
If someone finds the time to implement the prioritization, I would be happy to merge a PR. For now, this PR fixes the bug of showing a wrong download list without changing the actual download order.
Closes #2894
> Fix download order list

- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
Hotfix for #3560. Auto cleanup needs to be re-organized in the future (see #3560) but for now, this fixes disappearing episodes that some users experience.
> Hotfix: Do not delete episodes

- core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
You can't modify playback params on the ExoPlayer while paused (see
https://github.com/google/ExoPlayer/issues/4064) so added a member
object which *can* be modified while playback is paused. These
parameters are always applied on start of playback.
Fixes #3651
> Added playback params to wrapper so speed can be changed while paused

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
downloadExecutor.take() clears the interrupted state of the thread when throwing an
InterruptedException. When getting this exception, we need to return instead of relying
on the loop to get cancelled.
> Fix DownloadService deadlock

- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
- core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
This fixes a crash when starting services without starting the main activity. Also it fixes crashes when users upgrade their phone to Android 8+. Might also be related to #2817
```
11:48:06 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: numtests=219
11:48:06 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: stack=android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=downloading pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PUBLIC)
11:48:06 V/InstrumentationResultParser: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
11:48:06 V/InstrumentationResultParser: at …
```
> Make sure to create notification channels

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Otherwise, the notification can stay while the service is actually stopped
> Cancel notification after cancelling notification updater

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
This fixes a ConcurrentModificationException if the thread that queues downloads (database IO)
adds the item to the downloads list and the notification updater queries the downloads list at
the same time.
> Only modify and query downloads array in main thread

- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
We sometimes get an ArrayIndexOutOfBoundsException when trying to create the ItemPagerFragment. After trying quite a few things already, Google Play still reports the crash. Previous experiments showed that the index is not larger than the array length. Because it is an AIOOB Exception and not a NPE, the array must be created correctly. Maybe it is a negative index. Might be caused by getAdapterPosition() returning NO_POSITION (-1).
> Try to fix ArrayIndexOutOfBoundsException

- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
This patch makes sure that an episode actually contains a media file before being added to the download batch. 
Right now AntennaPod crashes when an user attempts to batch download text-only feeds.
This commit will prevent AntennaPod from crashing, however the app will tell the user it is downloading the text-only entries when in fact it is just ignoring them. The user facing message should obviously be changed to make this behavior transparent to the user.
I would appreciate any suggestions.
Edit: My idea is to pass size of toDownload to close() instead of size of checkedIds. This way the number displayed should match the number of episodes actually being downloaded. In case only text-only entries have been selected no snackbar is being displayed. So the user tells the app to go download …
> Check if an episode has media before adding it to download batch

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
This PR introduces initial support for subscribeonandroid.com URLs.
Fixes #2297 
However, I'm not really happy with the way URLs are parsed now. In particular the RegEx I hacked together.
Other than that I'm not sure how to handle the http(s) part of the URL. If an user tries to subscribe to an subscribeonandroid.com URL served via https while the original only being available via plan http the subscription is probably going to fail.
Let me know your thoughts.
> Support for "Subscribe on Android" 

- app/src/androidTest/java/de/test/antennapod/ui/TextOnlyFeedsTest.java
- app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/MarkAsPlayedActionButton.java
- app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
- core/src/main/res/values/strings.xml
I started toying around with #2682
AntennaPod now shows "mark as read" instead of "mark as played" when viewing an item, however there are many more places where this should be changed in order to be fully consistent.
In particular FeedItemMenuHandler.java comes to mind in this regard. I will probably have to extend feeditem_options.xml in case we really want that. I'm not sure if we do. Do we?
> Show "mark as read" rather than "mark as play" in case item has no media

- core/src/main/res/values/strings.xml
Adapted mentions of 'feed' to 'podcast' where plausible; fixes #3747.
Exceptions:
- Line 255 (always strings.xml): download_type_feed: It is the technical type of the download. Mentioning Podcast here might be confusing.
- Line 119: feedurl label: In this case some podcasts mention their feed url so it might help to say "Podcast feed URL" instead of "Podcast URL".
- Line 233: download_error_unsupported_type: The error should be technical. "Unsupported Podcast Type" might sound nice, but what would you think as a podcast provider if your user reports an "Unsupported Podcast Type"? (It think "Unsupported Feed Type" the better error message in this case.)
> changed mentions of 'feed' to 'podcast'

- app/src/androidTest/java/de/test/antennapod/util/URLCheckerTest.java
- core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
- core/src/main/java/de/danoeh/antennapod/core/util/URLChecker.java
I just looked at `GpodnetSyncService.processSubscriptionChanges`. There are several reasons for duplicate subscriptions after a gpodder full sync.
- The URLs do not match exactly (`https://www.example.com/feed` vs `https://example.com/feed/` vs `http://example.com/feed/`). Actually, those URLs are different. Servers could return a different reply. Because I think that this is unlikely, this PR changes the behavior.
- The feed moved to a new page. For example, `https://www.example.com/feed` could redirect to `https://www.example.com/newFeed`. AntennaPod updates the URL but if Gpodder still has the old url, AntennaPod does not know that it is the same feed. Actually, we can not really fix this, only suppress it. Gpodder will still have the old url on their server and it is a **full** sync. …
> More forgiving duplicate detection

- app/src/androidTest/java/de/test/antennapod/ui/SpeedChangeTest.java
- app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
- app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
When setting the speed to a value that is not available for the button using the audio controls dialog, we no longer jump to the lowest value. Instead, we jump to the next bigger one.
Steps to reproduce:
- Play
- Pause
- Close AudioPlayerActivity
- Open AudioPlayerActivity
- Tap speed button
- Always sets to the one after 1.0
> Convert speed to float

- app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java
- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
If you had an episode in the queue without a cover, it first showed the placeholder text.
After scrolling, the placeholder text was hidden and then there was just nothing at all.
This was inconsistent and confusing.
Now, always shows the placeholder (while loading and on error), making sure to update visibility.
> Fix weird behavior in CoverLoader

- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
Stacktrace:
```
Feed parser exception: java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
at android.widget.ListView.addHeaderView(ListView.java:258)
at android.widget.ListView.addHeaderView(ListView.java:287)
at de.danoeh.antennapod.activity.OnlineFeedViewActivity.showFeedInformation(OnlineFeedViewActivity.java:380)
at de.danoeh.antennapod.activity.OnlineFeedViewActivity.lambda$parseFeed$5$OnlineFeedViewActivity(OnlineFeedViewActivity.java:304)
at de.danoeh.antennapod.activity.-$$Lambda$OnlineFeedViewActivity$CXzj4SjBL5FAn6jkIj9XbyiCeF8.accept(lambda)
at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableOb …
```
> Fixed adding feeds on Android 4.1

- app/src/main/java/de/danoeh/antennapod/CrashReportWriter.java
- app/src/main/java/de/danoeh/antennapod/activity/BugReportActivity.java
Otherwise, users report bugs with old stack traces and therefore
old system info. Display a big system info block of the current
version and a simple line of the crash version.
> Always print current version of AntennaPod

- core/src/main/res/drawable/ic_notification_cast_off.xml
- core/src/main/res/drawable/ic_notification_fast_forward.xml
- core/src/main/res/drawable/ic_notification_fast_rewind.xml
- core/src/main/res/drawable/ic_notification_pause.xml
- core/src/main/res/drawable/ic_notification_play.xml
- core/src/main/res/drawable/ic_notification_skip.xml
A simple change to make the buttons 25% larger.  I've seen a few users complaining.
Screen shot to compare before (blue) and after (white)
Removing the 36dp one, way too big (from the reviewers)
New proposal is the 30dp
> 30dp buttons for notification / lock screen (play, fwd, rewind) buttons

- core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java
Today's screens have a much better resolution than a few years ago when this code was created.
Use 1/3 of the target size of the image instead of a fixed size. The transformed image
is cached by Glide, so the transformation does not need to be done multiple times.
This way, the images look a lot better (because they are not stretched to be displayed).
Before/After:
> Increase blurred image size

- app/src/androidTest/java/de/test/antennapod/storage/DBTestUtils.java
- app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
- app/src/main/res/layout/simplechapter_item.xml
- core/src/main/java/de/danoeh/antennapod/core/feed/Chapter.java
- core/src/main/java/de/danoeh/antennapod/core/feed/ID3Chapter.java
- core/src/main/java/de/danoeh/antennapod/core/feed/SimpleChapter.java
- core/src/main/java/de/danoeh/antennapod/core/feed/VorbisCommentChapter.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideModule.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ChapterImageModelLoader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBUpgrader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSSimpleChapters.java
- core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/EmbeddedChapterImage.java
- core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java
- core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3Reader.java
- core/src/main/java/de/danoeh/antennapod/core/util/vorbiscommentreader/VorbisCommentChapterReader.java
- core/src/main/java/de/danoeh/antennapod/core/util/vorbiscommentreader/VorbisCommentReader.java
- Supports [Podlove Simple Chapters](https://podlove.org/simple-chapters/) and mp3. Vorbis [does not support chapter images](http://lists.xiph.org/pipermail/vorbis-dev/2012-April/020272.html).
- Chapter images are only supported for new episodes. Otherwise, we would need to fetch chapters for every item on feed refresh, what is really slow.
- While I was trying to understand the code, I added support for parsing opus files. The old Vorbis reader only supported ogg.
Closes #2102
> Support for chapter images

- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
Sometimes, `media` does not know the duration. `getDuration()` loads directly from the `PlaybackService`.
> Fixed seeking when streaming

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
I do not know why showing the notification makes it disappear earlier but even if it does not
disappear earlier, the number will now be updated to show "0 downloads left" instead of
incorrectly sticking with 1 download until dismissed.
> Hide downloading notification earlier

- app/src/main/res/xml/preferences_user_interface.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
instead of new+unplayed
In my studies, new users were regularly confused about what those numbers mean.
> Change default drawer counter to 'new episodes'

- app/src/main/java/de/danoeh/antennapod/dialog/IntraFeedSortDialog.java
When a new feed is added their sort values are set to `null`. Added a check to default sort method to select "Date (New -> Old)" and show it is selected.
closes: #3918
> Fixed default sort method not showing up as selected

- app/src/main/java/de/danoeh/antennapod/discovery/ItunesTopListLoader.java
- core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
- core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
This makes feed updates faster and reduces the server load. Does not cache media files. Cached iTunes toplist at least one day.
> Enable caching for web responses

- app/src/main/java/de/danoeh/antennapod/discovery/ItunesPodcastSearcher.java
- app/src/main/java/de/danoeh/antennapod/discovery/ItunesTopListLoader.java
- core/src/main/java/de/danoeh/antennapod/core/glide/ChapterImageModelLoader.java
- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
- core/src/main/java/de/danoeh/antennapod/core/service/UserAgentInterceptor.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Apparently, AntennaPod talked to fyyd with the UserAgent "OkHttp/x.y.z" instead of "AntennaPod/x.y.z". This should now be fixed.
> Always add UserAgent to requests

- core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java
```
03-16 13:40:00.424 3096-3132/de.danoeh.antennapod.debug E/GlideExecutor: Request threw uncaught throwable
java.lang.ArrayIndexOutOfBoundsException: length=9216; index=9427
at de.danoeh.antennapod.core.glide.FastBlurTransformation.fastBlur(FastBlurTransformation.java:235)
at de.danoeh.antennapod.core.glide.FastBlurTransformation.transform(FastBlurTransformation.java:26)
at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:81)
at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:540)
at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:604)
at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:46)
at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(Load …
```
> Fixed blurring images on Android 4.4

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/adapter/gpodnet/PodcastListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java
- app/src/main/java/de/danoeh/antennapod/discovery/PodcastSearchResult.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
- app/src/main/res/layout/gpodnet_podcast_listitem.xml
- app/src/main/res/layout/itunes_podcast_listitem.xml
- app/src/main/res/layout/searchlist_item.xml
- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
- core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetPodcast.java
fix #3754
1) In the iTunes search feed use artistName
2) In the RSS feed from iTunes, use summary
3) In GpodnetPodcast, and Fyyd - use description
Gpodder.net search
Fyyd
Browsing on iTunes
Advance search on iTunes
> show artistName in place of podcast url when it is availble

- app/src/main/java/de/danoeh/antennapod/activity/SplashActivity.java
- app/src/main/res/layout/splash.xml
- core/src/main/res/values-v26/styles.xml
The progress bar is only shown if there are long database migrations
> Fixed jumping icon on splash screen

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
The first call to installSslProvider may take quite long.
Already report the started download.
> Fixed downloads taking long before being shown as started

- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/main/java/de/danoeh/antennapod/fragment/preferences/AutoDownloadPreferencesFragment.java
- core/src/main/AndroidManifest.xml
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/drawable/ic_warning_red.xml
- core/src/main/res/values/strings.xml
We implemented a workaround requiring location permissions. Quite a few users complained about the permission in Google Play comments. As soon as we target Android 10 (and we need to do that, rather sooner than later, to keep uploading updates), even the workaround stops to work. The system then always returns an empty list of known WiFi networks.
This change in Android is actually a privacy feature. The list of known networks allows to track your location. Unfortunately, this breaks legitimate uses like ours.
Closes #3387
> Removed WiFi filter on Android 10

- app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
fix #3956
add YYYY-MM_DD to the filenames for database, opml and html exports
> put a date with the filename being exported

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
- core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
- core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Closes #3971
Before:
After:
You can see that before the change, `extractItemlistFromCursor` needs 65% of the total `getRecentlyPublishedEpisodes` method duration. Afterwards, it needs 55%. This does not have a noticeable impact on the app's perceived speed, unfortunately.
`EpisodeItemViewHolder/LayoutInflater.inflate` takes way more time and is even executed on the UI Thread. Around 30% of layouting is spent inflating `EpisodeItemViewHolder`. We should probably configure RecyclerView to re-use our ViewHolders throughout the whole app instead of per fragment instance (all lists use the same items, so this could get us quite a bit of performance impact).
> Always join FeedMedia instead of doing two queries

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndTypeUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
According to my Profiling session, we spend around a third of our UI thread time during download building Strings:
Even though parsing the feeds is done only in one thread, it still has enough time to sleep. So this is not a bottle-neck:
Of the actual feed parsing, handling the date parsing takes by far the most time. We might want to think about that to make the app more efficient. As a first step, do not create a `SimpleDateFormat` instance for every single `parse` method call.
Parsing the MIME types in `SyndTypeUtils` takes surprisingly long. Not anywhere near critical but considering this can be done with `startsWith` [much more efficiently](https://stackoverflow.com/questions/19807253/java-string-parsing-what-is-faster-regex-or-string-methods), do that instead.
> Performance improvements

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
- app/src/main/java/de/danoeh/antennapod/view/EpisodeItemListRecyclerView.java
- app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
- app/src/main/res/layout/all_episodes_fragment.xml
- app/src/main/res/layout/feed_item_list_fragment.xml
- app/src/main/res/layout/queue_fragment.xml
- app/src/main/res/layout/search_fragment.xml
- app/src/main/res/layout/simple_list_fragment.xml
- core/src/main/res/values/ids.xml
`EpisodeItemViewHolder/LayoutInflater.inflate` takes a lot of time and is even executed on the UI Thread. Around 30% of layouting is spent inflating `EpisodeItemViewHolder`. Configured RecyclerView to re-use our ViewHolders throughout the whole app instead of per fragment instance. All lists use the same items, so this gives a noticeable performance impact. Especially noticeable on the "Episodes" page when swiping between the 3 tabs. Logging output shows that `EpisodeItemViewHolder.<init>` is called significantly less frequently (after some initial calls, you can navigate the app without any additional call).
> Recycle ViewHolders throughout the whole app

- app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
- app/src/main/res/layout/audio_controls.xml
- core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/IPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/VideoPlayer.java
- core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
This feature is probably only used by 1% of the users. Because the button is only shown when the items have more than one audio track, I do not consider this a problem. Most users will never see this.
You can try this with https://media.ccc.de/c/36c3/podcast/mp4-hq.xml. With this PR, you can select the live translation language in AntennaPod.
> Allow to select audio track

- app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java
- app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
- app/src/androidTest/java/de/test/antennapod/util/service/download/HTTPBin.java
- app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/APQueueCleanupAlgorithm.java
- core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
- core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- core/src/main/java/de/danoeh/antennapod/core/sync/gpoddernet/GpodnetService.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
- core/src/play/java/de/danoeh/antennapod/core/cast/CastManager.java
Split from #4020, searched `%d`, `%.1f`, `%.2f` entire the project to see if locale `String.format` has correct locale, which includes fixes on some SQL query fixes on locales don't use 123 digits (۱۲۳), URL builders that should've used 123 in any locale, improvements on logs.
Rule of thumb, use Locale.getDefault() everywhere string goes directly to view and use Locale.US (or Locale.ENGLISH, the former was used by the project already) every other place like building a SQL query or URL (and maybe logs as they are in English anyway)
> Fix locale of every String.format number formatter

- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java
Ideally %d%s should be moved into the message itself this however is
a temporal fix before apply that to the messages themselves.
> Localize digits in queue episodes and parallel downloads numbers

- app/build.gradle
- app/proguard.cfg
- app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
- app/src/androidTest/java/de/test/antennapod/storage/AutoDownloadTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java
- app/src/androidTest/java/de/test/antennapod/ui/NavigationDrawerTest.java
- app/src/androidTest/java/de/test/antennapod/ui/SpeedChangeTest.java
- app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java
- app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
This reduces the method count from 64k to 44k and the apk size from 8MB to 7MB.
This means we do not need to enable MultiDex, yet.
> Allow Proguard to optimize androidx packages

- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
Turns
(note the new episodes triangle indicator)
To
And keeps LTR intact:
> Fix TriangleLabelView corner in RTL languages

- app/src/main/res/layout/feeditemlist_item.xml
Android Studio was also giving hint about this
Went for other layouts to find similar issues but didn't find this hint on them.
I was seeing this particular issue as an user initially…
This change keeps LTR UI intact:
But turns:
To:
which now matches with LTR UI.
> Fix symmetry issues of feed item list

- app/src/main/java/de/danoeh/antennapod/adapter/DataFolderAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadStatisticsListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/DownloadlistAdapter.java
- app/src/main/java/de/danoeh/antennapod/view/viewholder/EpisodeItemViewHolder.java
- core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
No change in English locale:
But turns:
to:
> Use Android's own file size formatter

- core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
When items were written to the database, their RSS specified image was set to the podcast's image.
This prevented displaying the embedded picture because the image specified in RSS has a higher
priority than the image that is embedded.
Closes #4056
> Fixed not displaying embedded pictures

- app/build.gradle
- app/src/main/java/com/google/android/material/bottomsheet/ViewPagerBottomSheetBehavior.java
- app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/DownloadsFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/GpodnetMainFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/preferences/StatisticsFragment.java
- app/src/main/java/de/danoeh/antennapod/view/NestedScrollableHost.java
- app/src/main/java/de/danoeh/antennapod/view/PagerIndicatorView.java
- app/src/main/res/layout/audioplayer_fragment.xml
- app/src/main/res/layout/feeditem_fragment.xml
- app/src/main/res/layout/feeditem_pager_fragment.xml
- app/src/main/res/layout/item_description_fragment.xml
- app/src/main/res/layout/pager_fragment.xml
- app/src/main/res/layout/statistics_fragment.xml
[ViewPager2](https://developer.android.com/jetpack/androidx/releases/viewpager2) is a recently added component to fix different issues of ViewPager which is itself built upon RecyclerView (though we haven't used this property of it here).
The specific thing that has motivated me to adopt the project with ViewPager2 is lack of RTL languages support on ViewPager which now is supported by ViewPager2, most annoying thing for me when I use the app with a device that uses Persian for its UI, see this for example,
This patch turns it into: (which is the correct scrolling for touch screens)
So the scrolling won't be confusing for RTL languages users anymore. I've fixed minor things which will explain as comment for the patch.
Thanks!
> Adopt the project with ViewPager2 

- app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
- app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
- app/src/main/java/de/danoeh/antennapod/dialog/SkipPreferenceDialog.java
- app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
Turns 
to 
How to reproduce? Use Persian فارسی as your phone's language.
Note the used digits. Am carefully fixing places should use locale's digits, and found out there is `NumberFormat.getInstance().format` which should be used for number that has sole visual purpose so normalized `String.format(Locale.getDefault(), "%d",` with this that should be a bit lighter also.
> Use locale's digits in more places

- app/src/main/res/layout/pager_fragment.xml
- app/src/main/res/layout/statistics_fragment.xml
- core/src/main/res/values/styles.xml
Only tabBackground is not enough on big screens.
Follow-up for #4108. Thanks @ebraminio for noticing.
> Fixed tab background

- app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/values/strings.xml
I just tried to play an opus file and received errors. Wondered what is wrong until I read in the stack trace that I had selected Sonic, which can not play opus files. Error dialog now shows a button that allows to switch to ExoPlayer.
> Offer to switch to ExoPlayer on media player error

- app/src/main/res/layout/feeditemlist_item.xml
- app/src/main/res/layout/subscription_item.xml
- core/src/main/res/values/colors.xml
If you have many non-square images, they look somehow unaligned. This change adds clear boundaries.
> Make subscriptions view more consistent when showing non-square images

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Partial fix for #3878. The fragments are shown but the toolbar menus are messed up (other fragment still has setSupportActionbar). Setting the ActionBar in onResume does not work because resume order is not deterministic.
Commit 2 fixes my way to reproduce the problem but there are probably more cases where the activity is recreated, so the issue is not fixed yet (but a messed up toolbar is better than an empty screen).
> Fix fragment state on restart

- app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
- app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java
If the description is really short, the WebView shrinks. When touching
below the WebView, one needs to slide pretty precisely to swipe horizontally.
If there is a little bit of slope, the player closes (completely, without following
the finger). This change resizes the WebView, so that one can not touch below it.
> Reduced probability for closing player accidentally

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/preferences/UserInterfacePreferencesFragment.java
Users might want to try all themes to see how they look. Having to re-open the settings screen every time is cumbersome.
> Switch theme without user obstruction

- app/build.gradle
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DownloadActionButton.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/ItemActionButton.java
- app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java
- app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
- core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UsageStatistics.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/res/layout/popup_bubble_view.xml
- core/src/main/res/values/strings.xml
- core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
- settings.gradle
I think most users stream rather than download. We do not have analytics, so just ask the users when they press the stream button significantly more often than the download button.
Related: #3593
> Added on-demand configuration for stream vs download

- core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
Some feeds specify both `itunes:image` and `image`. Looks like many publishers don't know what they are doing and specify different icons for the two tags... The guardian feeds are messed up, too (cc @keunes). Also requested on Google Groups: https://groups.google.com/forum/#!topic/antennapod/YlZND4mz2SM
New guardian icon:
> Prefer itunes:image

- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Apparently, recreate() brings RxJava in a strange state where errors are directly
thrown instead of relaying them to the error callback. Because of a race condition
in ItemDescriptionFragment.loadData, this throws a NPE.
Closes #4144
> Fixed crash when changing theme

- app/src/androidTest/java/de/test/antennapod/util/FilenameGeneratorTest.java
- core/src/main/java/de/danoeh/antennapod/core/util/FileNameGenerator.java
This change makes the situation in #1688 better for languages that use letters with accents (`Äàáâãå`). It does not change the situation when using languages like Farsi.
> Stripping accents before generating file name

- build.gradle
- core/src/main/java/de/danoeh/antennapod/core/util/ChapterUtils.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java
- ExoPlayer already used the AntennaPod user agent
- Sonic and Device internal have now been changed to use the AntennaPod user agent
- Something I did not think about earlier: The chapter loader (that is used to load embedded chapters of the media file in case the feed does not support chapter marks) has now been changed to use the AntennaPod user agent
Closes #4240
> Fix useragent

- app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
- core/src/main/res/values/strings.xml
Show a different warning message if a local feed is about to be deleted.
Introduce a new message key `feed_delete_confirmation_local_msg` that needs to be translated.
Contributes to #4287.
> Do not warn that all files are deleted when removing a local feed

- app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
Simple modification that enables swiping actions in queue lists when "keep sorted" option is checked.
Fixes #4235
> Fixed #4235 by enabling swiping actions on locked queue list

- app/build.gradle
This was originally added because the task was also responsible for copying the current git commit hash to the "about" screen. The commit was later moved to a `buildConfigField`, so this can now be removed again.
Closes #4317
> Removed upToDateWhen of copyLicense task

- app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
Hi @ByteHamster because you said in #3675 that the icon in the filtered message looks a bit old, I changed it to the material icon, which I think looks better and I use the same icon in the subscription filter.
Screenshot (md-info-outline):
Of course there is also an outfilled icon (md-info):
> Use material info icon in filter messages

- app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java
**Steps to reproduce:**
1. Start fresh AntennaPod instance (in virtual device)
2. Subscribe any podcast
3. Go to Subscriptions, click on the podcast to see the subscription episodes list (`FeedItemlistFragment`)
4. Click on menu icon, click on "Remove podcast", and click on "Confirm"
5. The podcast is removed, but a NullPointerException occurs and can be seen in Logcat, see excerpt below
```
2020-08-02 21:48:00.881 26457-26457/de.danoeh.antennapod.debug D/MainActivity: loadFragment(tag: EpisodesFragment, args: null)
2020-08-02 21:48:00.882 26457-26457/de.danoeh.antennapod.debug D/NavDrawerFragment: saveLastNavFragment(tag: EpisodesFragment)
2020-08-02 21:48:00.883 26457-26457/de.danoeh.antennapod.debug D/NavDrawerFragment: getLastNavFragment() -> EpisodesFragment
2020-08-02 21:48:00.902 …
```
> Fix NullPointerException in FeedItemlistFragment when deleting a podcast

- app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
- core/src/main/java/de/danoeh/antennapod/core/syndication/handler/UnsupportedFeedtypeException.java
In the last few hours, 2 people contacted me because they inserted a website address instead of a podcast feed address. Make error message more easy to understand: "The server returned a website, not a podcast feed" instead of just "Invalid type".
> Be more verbose about invalid type errors

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
- app/src/main/res/layout/main.xml
- app/src/main/res/values/integers.xml
- core/src/main/res/values/dimens.xml
While adding support for samsung's DeX (#4343 ), the issue appeared that the navigation drawer is too large on wide screens.
This could be solved by a screen-size-dynamical drawer size or a maximum width.
> WIP: Dynamical navigation drawer size

- core/build.gradle
- core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
This mimics an update I did for Slide [here](https://github.com/ccrama/Slide/commit/f3e402d24ded46fa5a290ad5c1dc903749e8e1e8).
This update won't cause any problems. I've thoroughly tested (this and [other](https://github.com/ccrama/Slide/pull/3233/commits/f61d3bd6b84ed9413637c2a4c34a804eba274498)) ExoPlayer updates and deprecation fixes in Slide debug builds, and there have been zero problems (if anything, better performance).
Of course, you can wait until after 2.0.0 is released to merge this if you wish.
> Update ExoPlayer to 2.11.8

- app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
- app/src/main/res/xml/preferences.xml
Copycat applications regularly forget to update the about screen.
They then still claim to be AntennaPod, linking our developers
and our support channels. This change simply hides the about screen
when detecting an app that is not official.
> Hide about screen in copycat applications

- app/src/androidTest/java/de/test/antennapod/entities/ExternalMediaTest.java
- app/src/androidTest/java/de/test/antennapod/playback/PlaybackTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java
- app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java
- app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java
- app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java
- app/src/androidTest/java/de/test/antennapod/ui/SpeedChangeTest.java
- app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
- app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java
- app/src/main/java/de/danoeh/antennapod/preferences/MasterSwitchPreference.java
- app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java
- app/src/main/java/de/danoeh/antennapod/spa/SPAUtil.java
- app/src/main/res/xml/feed_settings.xml
- app/src/main/res/xml/preferences_autodownload.xml
- app/src/main/res/xml/preferences_gpodder.xml
- app/src/main/res/xml/preferences_network.xml
- app/src/main/res/xml/preferences_playback.xml
- app/src/main/res/xml/preferences_storage.xml
- app/src/main/res/xml/preferences_user_interface.xml
- app/src/play/java/de/danoeh/antennapod/activity/CastEnabledActivity.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java
- core/src/main/java/de/danoeh/antennapod/core/util/playback/Playable.java
Nothing really changed here either.
If you are curious, here is the code difference between SwitchPreference and SwitchPreferenceCompat (generated using WinMerge).
[SwitchPreference diff.zip](https://github.com/AntennaPod/AntennaPod/files/5144769/SwitchPreference.diff.zip)
> Move remaining preference to AndroidX preference

- core/src/main/java/de/danoeh/antennapod/core/receiver/MediaButtonReceiver.java
- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
This should solve #1560 for some platforms where it still was a problem. Instead of assuming all calls to onReceiver() for MediaButtonReceiver are made by "software" buttons (like the playback controls on lockscreen), it now checks if the intent has a non-zero eventTime or downTime, which seems to be a good indicator that it's actually caused by a real button.
I've tested this on Android 4.4, 5.1 and 10. The controls on the lockscreen still function correctly and it solves #1560 on the device I had that was still affected (the problem of a long press on volume up/down with the screen of would skip track instead of jumping forwards/backwards).
Note: I don't have a blutooth music controller so I've not been able to check if the functionality remains as expected. This should probably be …
> Fix hardware buttons registered as lockscreen/notification taps

- core/src/main/res/color/filter_dialog_background_dark.xml
- core/src/main/res/color/filter_dialog_background_light.xml
- core/src/main/res/drawable/filter_dialog_background_dark.xml
- core/src/main/res/drawable/filter_dialog_background_light.xml
- core/src/main/res/values/styles.xml
This fixes defect 4430. It converts the filter dialog's color state lists to state list drawables for filter background colors. This eliminates an incompatibility on earlier Android OS versions (https://stackoverflow.com/questions/3953606/how-to-specify-background-color-in-color-state-list-resources)
Closes #4430
> Fix error inflating class RadioButton when opening Subscriptions filter dialog

- core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
Apparently, there are ways to end up with items that have no feed.
This hotfix prevents the app from crashing but it does not solve the
reason for items without feeds.
> Fixed crash when item has no feed

- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
- app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
Fixes: "Share episode url" does not work
- Class `FeedMenuHandler`: Hide complete submenu "Share..." as both sub menu items are not visible for local feeds.
- Class `FeedItemMenuHandler`: Hide "Share..." menu item for local feeds.
Contributes to #4287.
> Local feeds: Hide "Share..." menu item

- app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java
- app/src/main/res/layout/quick_feed_discovery.xml
This adds a retry button to the `QuickFeedDiscoveryFragment` if there is any kind of error.
Closes #4227
> Show retry button if QuickFeedDiscovery failed

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
fix #3803
fix #3447
fix #4336 
Added rewind and fast forward buttons
With Android auto, by default, the space that is allocated is for the skip to previous button.  If we  wanted a rewind button that has to be added as custom function.
Even though the rewind function works, in order for the button to appear in Android auto, we have add a customer function.  ([reference](https://developer.android.com/training/cars/media))
I've tested this on a HUD debugging 
My setup ([ref](https://tonytam.org/2020/02/17/debugging-android-autos/))
> add custom rewind for android auto

- app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java
- app/src/main/java/de/danoeh/antennapod/fragment/AudioPlayerFragment.java
We currently have no method to actively query the buffering state.
Remove indicator if we can no longer receive updates.
Closes #4148
> Fix buffering indicator sometimes sticking

- app/build.gradle
If @edwinhere deleted their API key, AntennaPod would lose the feature.
Now using two keys, one that is public (for F-Droid) and one that is not public (for Google Play). This reduces the probability for being blocked when someone takes the public key and spams the API.
> Updated podcastindex api key

- core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Local feeds: Do not display streaming confirmation when playing local file without network connection
Modifies the method `PlaybackService.onStartCommand()` to suppress the streaming confirmation.
Uses this logic to check if the feed is a local feed:
`boolean localFeed = URLUtil.isContentUrl(playable.getStreamUrl());`
Works fine for all use cases I have tested. But I'm not sure if this is the best way to solve the problem.
Contributes to #4287.
> Local feeds: Do not display streaming confirmation

- .circleci/config.yml
- build.gradle
- core/build.gradle
- core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java
- core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
For instance, this solves #2814 for people not using Google services. It also solved other protocol errors I was starting to get on an old device (running android 4.4.4, without Google services installed). I have tested these changes on both 1.8.1 and the current develop branch without any problems (in fact, some episodes seem to download faster but that's probably just placebo). I hope this is acceptable to be included officially in AntennaPod.
This does not change the Play builds (it's primarily meant for the F-Droid releases). On Play builds Conscrypt does not get bundled and they get no changes to what protocols and cipher suites are enabled. But I'm almost tempted to suggest dropping the dependency on the Google GMS Provider Installer... By knowing that a modern security provider is …
> Bundle a modern Security Provider (Conscrypt) in the Free builds.

- core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadServiceNotification.java
- core/src/main/res/values/strings.xml
Closes #4487 
This PR adds the ability for translators to add plural variants to the `download_report_content` resource string.
> Add plural default resource for download_report_content string.
