AntennaPod/AntennaPod

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml
I believe this resolves issue #595.
It works exactly the same as the 'All Episodes' refresh. If we'd likely slightly different behavior that would need to be explained further.
=> Add refresh button to queue view 595

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/util/QueueSorter.java, core/src/main/res/values/strings.xml
relates to #166
This add a sub menu to sort queue by alpha, date and duration.
=> Options to sort queue

app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, core/src/main/res/values/strings.xml
Added confirmation when marking all as read both in the all episodes view and the feed view. For issue #596.
=> Confirm mark all read

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Resolves AntennaPod/AntennaPod#551
=> Persist scroll position in Queue view

app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Resolves AntennaPod/AntennaPod#506
=> Add ability to clear the download log

core/src/main/res/values-zh-rCN/strings.xml
"博客" replace to "播客"
"单集" better than "曲目" (reference Podcast app for iOS)
"畸形" replace to "错误的"
=> fix Chinese translation

app/src/main/java/de/danoeh/antennapod/activity/DirectoryChooserActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlExportWorker.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/layout/opml_import.xml
Reverts AntennaPod/AntennaPod#643
=> Revert "Add ability to select OPML export folder"

app/src/main/res/layout/cover_fragment.xml
Reverts AntennaPod/AntennaPod#639
=> Revert "Correct audio player cover scaling"

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Reverts AntennaPod/AntennaPod#644
=> Revert "Persist scroll position in Queue view"

app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Reverts AntennaPod/AntennaPod#641
=> Revert "Add ability to clear the download log"

core/src/main/res/values-zh-rCN/strings.xml
Reverts AntennaPod/AntennaPod#635
=> Revert "fix Chinese translation"

.gitignore
we don't want to accidentally check in any keys...
=> updated .gitignore to ignore keystores

core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
=> make gpodder service usable for older devices again

app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/fragment_itunes_search.xml, app/src/main/res/layout/itunes_podcast_listitem.xml, core/src/main/res/values/strings.xml
=> Add ability to search iTunes for podcasts

app/src/main/java/de/danoeh/antennapod/preferences/CustomEditTextPreference.java, app/src/main/res/xml/preferences.xml
Stolen from https://stackoverflow.com/a/28287972
=> Inverse background of EditTextPreference for older android versions

app/src/main/java/de/danoeh/antennapod/adapter/gpodnet/TagListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagListFragment.java, app/src/main/res/layout/gpodnet_podcast_listitem.xml, app/src/main/res/layout/gpodnet_tag_listitem.xml, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetTag.java
Makes Gpodder tags prettier. Shows title and usage.
Fixes ActionBar title issue
Also fixes issue introduced in AntennaPod/AntennaPod#679
=> Gpodder tags show title and usage

app/src/main/java/de/danoeh/antennapod/activity/DefaultOnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlFeedQueuer.java, app/src/main/java/de/danoeh/antennapod/receiver/SPAReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
Resolves AntennaPod/AntennaPod#671
Tested with a list of 103 podcasts. Nearly half could use the header.
=> Downloader use If-Modified-Since HTTP header

app/src/main/java/de/danoeh/antennapod/activity/DefaultOnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlFeedQueuer.java, app/src/main/java/de/danoeh/antennapod/receiver/SPAReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
Reverts AntennaPod/AntennaPod#681
After testing a couple of other things (unrelated to this) I noticed that this change actually prevented certain feeds from being updated when they should have been.
Specifically: http://feeds.podtrac.com/eL1krEll7iB4 and http://feeds.soundcloud.com/users/soundcloud:users:20170457/sounds.rss
=> Revert "Downloader use If-Modified-Since HTTP header"

app/src/main/AndroidManifest.xml
just updated the version information
=> update manifest to have different versions so that we can alpha test

app/src/main/java/de/danoeh/antennapod/activity/DefaultOnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlFeedQueuer.java, app/src/main/java/de/danoeh/antennapod/receiver/SPAReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadRequest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
Refresh feeds at least every x:
1 day seemed a little bit short, 1 week to long. Chose 3 days for the time being.
=> Downloader use If-Modified-Since HTTP header (Take 2)

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/opml_import.xml, core/src/main/res/values/strings.xml, core/src/main/res/values/styles.xml
If one of the options is not available, the corresponding description, button and divider are hidden.
Texts are adjusted accordingly.
Some minor adjustments on the add feed fragment to look prettier...
=> OPML import with better explanations and usage of external apps, "Add feed" facelift

CONTRIBUTING.md, README.md, core/src/main/res/values-zh-rCN/strings.xml
This will help get us ready for the release when we need to merge develop back in to master.
=> Merge master changes

app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
closes #628
New Episodes will no longer scroll back to the top when after you view an episode.
(with many thanks to @mfietz for showing me the way)
=> now persisting the scroll position for New Episodes

app/src/main/AndroidManifest.xml, app/src/main/assets/about.html, core/src/main/res/values-az/strings.xml, core/src/main/res/values-ca/strings.xml, core/src/main/res/values-cs-rCZ/strings.xml, core/src/main/res/values-da/strings.xml, core/src/main/res/values-de/strings.xml, core/src/main/res/values-es-rES/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-hi-rIN/strings.xml, core/src/main/res/values-it-rIT/strings.xml, core/src/main/res/values-iw-rIL/strings.xml, core/src/main/res/values-ja/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-nl/strings.xml, core/src/main/res/values-pl-rPL/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-pt/strings.xml, core/src/main/res/values-ro-rRO/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sv-rSE/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-uk-rUA/strings.xml, core/src/main/res/values-zh-rCN/strings.xml
Updated strings and version in prep for release.  Will wait and update strings again before final release. No more code changes expected except to fix bugs.
refs #708
=> Update strings and version

.gitignore, core/src/main/res/values-es/strings.xml, core/src/main/res/values-it-rIT/strings.xml, core/src/main/res/values-iw-rIL/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-uk-rUA/strings.xml
closes AntennaPod/AntennaPod#708
=> update strings for release 1.1

app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/NewEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/res/layout/all_episodes_fragment.xml, app/src/main/res/menu/new_episodes.xml, core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Version 1.1.1 is now in production, so it should be in master.
=> Version 1.1.1

app/build.gradle, app/proguard.cfg, app/src/main/assets/LICENSE_ANDROID_ICONIFY.txt, app/src/main/assets/about.html, app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/res/layout/feedinfo.xml, core/src/main/res/values/strings.xml
Show URL in feed info. Also made the layout look nicer.
Closes AntennaPod/AntennaPod#722
Before & after:
=> Show URL in feed info

library/drag-sort-listview/src/main/java/com/mobeta/android/dslv/DragSortController.java
There is probably a better fix (as mentioned here http://stackoverflow.com/a/4582899/6839)
But this will work in the short term and doesn't require anything too drastic.
closes AntennaPod/AntennaPod#765
=> Fixes NullPointerException in DragSortController.onScroll.

app/proguard.cfg
Will make for saner crash reports in Google Play.
closes AntennaPod/AntennaPod#758
=> don't obfuscate

app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java
fixes a null pointer exception that can sometimes occur when the Playbac...kWidgetService is shutdown
=> Fixes NPE in PlaybackWidgetService

CONTRIBUTORS, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/assets/.gitignore, app/src/main/templates/about.html
* Automatically updates the version in about.html automatically at build time.
* Includes the version code in about.html (to make tracking alpha/beta releases easier).
* Updated copyright to reflect the fact that there are many contributors now
closes AntennaPod/AntennaPod#701
=> Update about.html version automatically

app/src/main/java/de/danoeh/antennapod/adapter/ActionButtonUtils.java, app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java, core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java, core/src/main/res/values/strings.xml
=> Confirm download on mobile data connection

app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java, core/src/main/res/values/strings.xml
Defaults to true.
fixes AntennaPod/AntennaPod#753
Also fixed warning due to TAG being too long for log statements.
=> Optionally resume playback after call

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/GpodnetMainFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/SearchListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagListFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/MenuItemUtils.java, app/src/main/res/menu/feedlist.xml, app/src/main/res/menu/gpodder_podcasts.xml, app/src/main/res/menu/new_episodes.xml, app/src/main/res/menu/queue.xml
Tested on 2.3 and 4.2.
Both Light and Dark theme work (correct icon, text color etc.)
=> Fix ActionBar SearchView

app/src/main/res/menu/queue.xml
=> Use localization for clear queue

app/src/main/java/de/danoeh/antennapod/adapter/NewEpisodesListAdapter.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
=> Fix NPE and hide progress bar without media

app/build.gradle, app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java, app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java, app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java, app/src/main/templates/about.html, build.gradle, core/src/androidTest/java/de/danoeh/antennapod/core/test/ApplicationTest.java, core/src/androidTest/java/de/danoeh/antennapod/core/util/DateUtilsTest.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/gui/UndoBarController.java
Resolves #731
Additionally, fixes bug in datetime parsing (negative timezones) and refactors UserPreferences (constants, variables, reloading variables etc. in same order as the Preferences fragment)
All 184 tests succeeded on emulated Moto X 4.4.4
Branch is rebased on #808
=> Tests fixed

app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java
=> Widget: Show correct played and total when current episode ends

core/src/main/java/com/aocate/media/AndroidMediaPlayer.java
Closes AntennaPod/AntennaPod#612
Needs testing. I assumed 6dB would be a good value for the maximum loudness amplification, might be too much.
Did not have any test files, but it should work...
=> LoudnessEnhancer for Android 4.4+

core/src/main/java/com/aocate/media/AndroidMediaPlayer.java
Reverts AntennaPod/AntennaPod#726
Turns out this causes media to not play on my HTC One M7.
=> Revert "LoudnessEnhancer for Android 4.4+"

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesListAdapter.java, app/src/main/res/layout/new_episodes_listitem.xml
=> Download and playback progress now displayed in All/New Episodes

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
=> Fixed import Google Drive

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Fixes AntennaPod/AntennaPod#829
We'll have to live with this for a bit to ensure it actually fixes the problem.
=> reverting to tryLock for getPosition

app/src/main/res/layout/opml_import.xml
put the LinearView in a ScrollView. fixes AntennaPod/AntennaPod#841
=> Let Opml import scroll on smaller screens

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Fixes some NullPointerExceptions that were reported against build 54.
=> Fix NullPointerExceptions

app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, core/src/main/res/values/strings.xml
=> Fix 'Confirm Mobile Download' dialog clipping

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
commitAllowingStateLoss should do this for us. As noted in the TODO there is probably a better
way, but now is not time.
Fixes #846
=> Avoid IllegalStateExceptions

core/src/main/res/values-pt/strings.xml
=> updating pt strings

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java
Updated to build 56 and fixed #868.
=> Build 56 and fix for 868

core/src/main/java/de/danoeh/antennapod/core/asynctask/PicassoProvider.java
Fixes AntennaPod/AntennaPod#887
=> fix for NullPointerException in bitmap configs.  

app/build.gradle
Fixes AntennaPod/AntennaPod#883
=> Fix gradle build from app dir

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Still need feedback from folks to see if this actually works.
=> Attempt to fix AntennaPod/AntennaPod#884 by removing StringUtils.join

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
=> Disable embedded images

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, app/src/main/res/menu/allepisodes_context.xml, app/src/main/res/menu/feedinfo.xml, app/src/main/res/menu/feeditem_options.xml, app/src/main/res/menu/feeditemlist_context.xml, app/src/main/res/menu/feedlist.xml, app/src/main/res/menu/mediaplayer.xml, app/src/main/res/menu/queue_context.xml, core/src/main/java/de/danoeh/antennapod/core/util/ShareUtils.java, core/src/main/res/values/strings.xml
Share feed:
Share episode, context menu:
Share episode, action bar:
"... with position" is only available, if position > 0
I also took the liberty to capitalize some of the GUI strings, e.g. "New episodes" became "New Episodes". IMHO the later looks a lot nicer. (The idea is to capitalize fragment and dialog titles and alike.)
Resolves #120
=> Share feeds and episodes

core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Not really sure if this actually solves the problem: None of the Android OSes at hand shows the described behavior. Still, I'm rather optimistic...
Hopefully
Resolves #946
=> Cache DateTime parser

app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
fixes AntennaPod/AntennaPod#970
=> Make sure controller isn't null

app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
Fixes AntennaPod/AntennaPod#964
=> Don't send Gpodder actions for items that don't have media.

app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java
Fixes AntennaPod/AntennaPod#979
=> Don't assume the activity is non-null within the callback.

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/res/layout/feeditem_fragment_header.xml, core/src/main/res/values/strings.xml
(Not perfect, still an improvement)
Resolves #991
=> Fix button moving and icon being cut

app/src/main/res/layout-v14/authentication_dialog.xml, app/src/main/res/layout-v14/download_authentication_activity.xml, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/authentication_dialog.xml, app/src/main/res/layout/download_authentication_activity.xml, app/src/main/res/layout/feedinfo.xml, app/src/main/res/layout/gpodnetauth_credentials.xml
Added the magic EditText properties to every EditText where it made sense to me.
Fixes #992
=> Fix edittext pasting issues on some devices

app/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
=> Do not send If-Modified-Since header if feed is paged

app/src/main/AndroidManifest.xml
Forgot to merge this PR previously, just updates the build number to 61, to match what is currently in alpha.
=> update to build 61

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java, core/src/main/java/de/danoeh/antennapod/core/service/FeedMediaSizeService.java
because I forgot to actually push this before committing #1027.  Renames methods and variables to be more descriptive.
=> renamed checkedonSize

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/layout/queue_fragment.xml, core/src/main/java/de/danoeh/antennapod/core/util/Converter.java
Shows the queue's current number of episodes and the total duration
**Update**:
=> Queue shows number of episodes and total duration

.tx/config, core/src/main/res/values-it-rIT/strings.xml, core/src/main/res/values-no/strings.xml, core/src/main/res/values-tr/strings.xml
Also updated some other strings.
fixes AntennaPod/AntennaPod#1038
=> Added Norweign

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, core/src/main/java/de/danoeh/antennapod/core/dialog/ConfirmationDialog.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
When the user changes a podcast's auto download setting, ask if this new setting should be applied to the podcast's episodes.
Fixes #1044
**Upgrade** [new screenshot]
=> Apply podcast's auto download preference to its episodes

core/src/main/res/values/strings.xml
fixes AntennaPod/AntennaPod#1050
@mfietz if you want to do this some other way, that's fine, let me know.
=> we can have both strings and plurals with the same name.

app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
I noticed this NPE when I was testing something else.
```
08-05 01:28:27.587: E/AndroidRuntime(1293): java.lang.NullPointerException
08-05 01:28:27.587: E/AndroidRuntime(1293): 	at de.danoeh.antennapod.fragment.ItemlistFragment.refreshHeaderView(ItemlistFragment.java:453)
08-05 01:28:27.587: E/AndroidRuntime(1293): 	at de.danoeh.antennapod.fragment.ItemlistFragment.onFragmentLoaded(ItemlistFragment.java:438)
08-05 01:28:27.587: E/AndroidRuntime(1293): 	at de.danoeh.antennapod.fragment.ItemlistFragment.access$900(ItemlistFragment.java:79)
08-05 01:28:27.587: E/AndroidRuntime(1293): 	at de.danoeh.antennapod.fragment.ItemlistFragment$ItemLoader.onPostExecute(ItemlistFragment.java:647)
08-05 01:28:27.587: E/AndroidRuntime(1293): 	at de.danoeh.antennapod.fragment.ItemlistFragment$ItemLoader.onP …
```
=> Feeds can be null in ItemListFragment

core/src/main/res/values/strings.xml
@LatinSuD reported an extra " in this string on Transifex.
=> removed extra quote

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/DefaultOnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/SearchlistAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/gpodnet/PodcastListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, core/src/main/java/de/danoeh/antennapod/core/glide/ApGlideSettings.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Cache strategy is now set in ApGlideSettings and referenced everywhere else from there.
=> Cache all images (should reduce lag displaying lists of episodes)

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/AboutActivity.java
fix issue #1073. crash on oneplus two(Android 5.1.1, Oxygen 2.0.0).
https://github.com/AntennaPod/AntennaPod/issues/1073
=> fix issue #1073. crash on oneplus two(Android 5.1.1, Oxygen 2.0.0).

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
Fixes #1092 
(Ignore the branch name ^^)
=> Fix smark values

app/src/main/java/de/danoeh/antennapod/PodcastApp.java, core/src/main/java/de/danoeh/antennapod/core/service/FeedMediaSizeService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
=> Disable feed media file size service

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
preferences.xml and UserPreferences used different strings m(
Rest is refactoring
Fixes #1106
=> Read feed counter setting correctly

core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
fixes AntennaPod/AntennaPod#1102
=> not every action has a timestamp

app/proguard.cfg
ProGuard was throwing a fit, this gets it to quiet down and doesn't actually cause any problems.
Fixes #1117
=> Fixes use of RxJava and Lambdas

core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetService.java
=> gpodder.net: POST empty string instead of null

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
and just let auto-download do it's thing.
refs AntennaPod/AntennaPod#1009
MAYBE for 1.3.2, still needs some testing I think.
=> Remove selective downloading of new things 

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
fixes a NullPointerException in MediaPlayerActivity that I added with an earlier commit :(
=> fix npe in media player

app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java
Re-ordered initialization so 'instance' is populated as soon as possible.
fixes AntennaPod/AntennaPod#1136
=> reorder intialization

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java, core/src/main/res/values/strings.xml
=> Localize option label

app/build.gradle, app/src/main/java/de/danoeh/antennapod/PodcastApp.java, app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/res/layout/feeditemlist_header.xml, app/src/main/res/layout/nav_feedlistitem.xml
=> Upgrade Iconify to v2

core/src/main/res/values/strings.xml
Reverts AntennaPod/AntennaPod#1156
They didn't want to make this change just yet. They had another idea in mind.
=> Revert "Update strings.xml"

app/src/main/java/de/danoeh/antennapod/activity/AboutActivity.java, app/src/main/templates/about.html
Behold!
(Left: 4.4.4; Right: 2.3.7)
Fixes #1154
=> Dark About view

app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
=> Check that URL is not null (or empty) when retrieving file size

app/build.gradle, app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java, core/build.gradle, core/src/main/java/de/danoeh/antennapod/core/service/playback/MediaButtonIntentReceiver.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
We now target API 22 and use the corresponding support libraries.
Note that most of this work was care of @mfietz.
=> Update to API 22

core/src/main/res/values/arrays.xml
[Idea for v1.3](https://github.com/AntennaPod/AntennaPod/issues/882). Useful when one can't listen to podcasts every *single* day, and even only on weekends.
=> add 3 & 7 day update interval

app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, core/src/main/res/values/attrs.xml, core/src/main/res/values/colors.xml, core/src/main/res/values/styles.xml
=> Fix gears color

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/res/layout/audioplayer_activity.xml, app/src/main/res/layout/choose_speed_dialog.xml
No changes to the normal click behavior. When long clicked, get a dialog where you can choose the new playback speed directly.
When clicked outside of the popup, it is dismissed.
Resolves #1123
=> Choose playback speed directly

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
Applying pr #1161 to version 1.3 for quicker release.
=> Fix url error for version 1.3.3

core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/AutomaticDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Simplified autodownloading and hopefully fixes (finally) our autodownloading of old episodes.
fixes #1009.
=> Fix new episodes

app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java, core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
markItemRead -> markItemPlayed and now requires the desired state instead of boolean.
fixes AntennaPod/AntennaPod#1173
=> Set episode back to 'New' when undo remove from new episodes.

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Well, I watched https://www.youtube.com/watch?v=x8Hddx1eOZo
The only place where we really can free up some memory is Glide
So I looked into it and found https://github.com/bumptech/glide/blob/master/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrSearchActivity.java
Actually, I don't think I ever ran into memory problems on my phone, but this seems like a good idea to do
=> Glide memory management

core/src/main/java/com/aocate/media/ServiceBackedMediaPlayer.java
Code changes inspired by https://github.com/android/platform_frameworks_base/blob/master/media/java/android/media/MediaPlayer.java
What was happening here?
When a ServiceBackedMediaPlayer was created on startup but the current episode is paused (we played an episode and restarted the app; external player is at the bottom, but paused), the media player already acquired a wakelock without needing it. This would only get justified when the user actually started playing.
So, now the wakelock is only acquired if it was held when the method was called.
Resolves #1110
=> Do not acquire wakelock when Prestissimo backed mediaplayer is created

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/adapter/ChapterListAdapter.java
=> Resolves NullPointerException when dealing with chapters

app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java
* user the view and not the text
* clear preferences earlier in setup
=> Fix playback tests that don't always work.

app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueListAdapter.java
=> Error handling for getMediaSize observable

app/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
We really need to create this on upgrade or else people will have a bad time.
=> create the favorites table on upgrade

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
AutoCloseable isn't available on all APIs
=> Fix force close on 2.3.7

core/src/main/res/values/arrays.xml
Resolves #1240 
I did only some very basic UI tests. Didn't seem worth firing up the test framework.
=> Additional playback speed steps

core/src/main/java/de/danoeh/antennapod/core/opml/OpmlSymbols.java, core/src/main/java/de/danoeh/antennapod/core/opml/OpmlWriter.java
Adds indentation, line breaks and when the file was created
Resolves #1238
=> Format exported OPML file

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
=> Drawer: Sort feeds by publication date

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Make notification text readable (fixes #1233)
=> Make Text Readable On Download Notification 

app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/res/values/strings.xml
Change language related to skipping episodes.
Also now keep the episode media if we're going to keep it in the queue.
fixes #1228
=> Keep episode media if we're supposed to keep skipped episodes

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Resolves #1259
OkHttp seems to have problems with SPDY and/or HTTP/2 (the later is just a guess)
When using such a protocol fails, we simply resort to good ol' HTTP/1.1
This PR might even be hotfix-worthy
To my knowledge, at least 5.1.0 ad 5.1.1 are affected; if you believe the OkHttp issue, 5.0.x also has this issue
=> Use HTTP/1.1 when new fancy protocols fail

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Solves #1264 
(I hope...)
More information at the bottom of the issue.
=> Seeking: wait for completion where appropriate

circle.yml
This should make it *very* easy for people to test each PR. The circle build will provide a debug apk.  This won't interfere with people's normally installed release apk.  As a result, they should be able to install and test the feature without any problems.
=> archive the build output

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
fixes AntennaPod/AntennaPod#1274
Now a question about flattr, if we're keeping it when skipping, should we flattr it now (if auto flattr is enabled)? or if it's ever played to completion?
=> if we're skipping an epsiode and keeping it, don't mark it played.

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/java/de/danoeh/antennapod/core/event/QueueEvent.java
Fixes #1290 
Mostly replaced the Loader with an Observable.
Also changed the order of some of the functions (I like to have the methods in order of the lifecycle), replaced some anonymous classes with lambdas.
EventDistributor and EventBus are register and unregistered in onResume and onPause.
=> NPE: ItemFragment Loader.loadInBackground

description/en.txt
- functionality- rather than technology-centred feature list
- more story-like description (from adding, via managing, to listening and thanking the creators)
Closes #1276
=> Updated description

README.md
And put a reference to the wiki.
Also updated some links to use AntennaPod rather than danieloeh in them, plus updated description to be a bit more in line with Google Play Short description.
=> Readme.md: Merge 'Alpha & Beta testing'

core/src/main/res/values-de/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-nl/strings.xml
=> updated strings

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/res/values/strings.xml
Vibrate when starting playback due to bluetooth reconnect.
fixes AntennaPod/AntennaPod#1305
=> Have a different option for bluetooth reconnect.

core/src/main/java/de/danoeh/antennapod/core/syndication/handler/TypeGetter.java
Fixes #1314 
Important part is in the first commit, the second one is just for fun
=> Close TypeGetter InputStreamReader

app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
Some small refactorings.
Don't think I broke anything, all tests passed on my machine.
=> Refactoring: User preferences

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
=> Drawer: Sort feeds case-insensitive

app/src/main/java/de/danoeh/antennapod/PodcastApp.java
Just seems like a good idea...
=> Strict mode for debugging

app/build.gradle, build.gradle, core/build.gradle, library/drag-sort-listview/build.gradle
For this $version thing to work, I had to replace those single quotes with double quotes, so I just went ahead and replaced them everywhere...
=> Gradle: external version variables, lombok AST

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> Sleep timer: Fix sleeping when shake to reset is not enabled

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Sort them by publication date, newest first, we might offer other options in the future.
=> sort favorites by publication date

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, core/src/main/java/de/danoeh/antennapod/core/asynctask/FeedRemover.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Well, cannot be really any worse than what we currently do...
=> If removing currently playing episode, (pause and) skip the same

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
FF and Rewind are now available on the large notification.
Putting them in the compact notification poses too many problems at this point. Eventually we'll add a setting to let people choose.
refs AntennaPod/AntennaPod#1268
=> put ff and rewind buttons on the large notification. 

core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetTag.java
The other two classes that implement Parcelable are fine, btw.
=> Provide Parcelable.Creator object called CREATOR

app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
ViewHolders (listeners) should not use position as a fixed value, because due to drag'n'drop said can change.
=> Fix queue ordering/duplicate issues

core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
Resolves #1374 
Resolves #1382 
Sure, let's water those crops with Brawndo's...
=> Allow TLSv1

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
=> Queue: Restore scroll position, don't glitch

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
Some method reordering, one comment and new ``onSkipToPrevious()``
=> Rewind when skip to previous is pressed

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/res/layout/feeditemlist_item.xml, app/src/main/res/layout/new_episodes_listitem.xml, app/src/main/res/layout/queue_listitem.xml, core/src/main/res/values/colors.xml
wow, such shiny ;)
Resolves #1366
=> Highlight currently playing

app/src/main/java/de/danoeh/antennapod/CrashReportWriter.java, app/src/main/java/de/danoeh/antennapod/PodcastApp.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlExportWorker.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java, core/src/main/java/de/danoeh/antennapod/core/util/StorageUtils.java, core/src/main/res/values/strings.xml
For those poor souls than either don't have Google Play, don't trust Google Play and/or close the crash dialog too quickly.
CrashReportWriter writes a crash report to a file and then lets the app crash as usual.
There is a new "preference" in settings below About that lets the user send that crash report to me.
(Greyed when there is no crash report, yet)
Rest is refactoring or AS deciding to add spaces, replace tabs or other shenanigans.
=> Log Crash Report

app/src/main/res/layout/all_episodes_fragment.xml, project.properties
+ Follow up to commit e63e0a4f1c5fb83048bee06916ec001f858626e3.
=> Removed references to former "app/dslv" submodule.

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Otherwise there can sometimes be some unexpected scroll position changes.
=> only restore scoll position if we're starting or resuming

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
wow, even a comment explaining things /o\
=> *EpisodesFragment: Fix context menu sharing

core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java
For testing:
Relative redirect: http://test.mfietz.de/redirect/path (sends "Location: /redirect/foo")
Path-relative redirect: http://test.mfietz.de/redirect/rel-path (sends "Location: foo")
Both should redirect to http://test.mfietz.de/redirect/foo
Resolves #1445
=> Handle redirects with relative URL correctly

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Fix episode filter

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
=> Drawer: If open, back button closes it

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
Again, not really sure how this is caused. Maybe the user is downloading episodes from a feed and while AP is still downloading deletes that feed? When deleting a feed, downloads of that feed are canceled, but this could still be a timing issue.
Changes in this PR and #1474 should fix the issue.
``chaptersRead`` is not used, so I removed the corresponding code.
=> DownloadService: media item might be null

app/src/main/java/de/danoeh/antennapod/CrashReportWriter.java, app/src/main/java/de/danoeh/antennapod/PodcastApp.java
Most important part is the OS version. I hope to be able to tell if someone is running CyanogenMod or another custom rom.
=> Crash Report: More environment information

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
=> GpodnetEpisodeAction.<init>: Media mustn't be null

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Reference: This should close #1456 
I made the changes discussed on https://github.com/AntennaPod/AntennaPod/pull/1470 this should be correct now
=>  Player: Toggle "time left" and "total time" #1456 

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Should fix sqlite IllegalStateExceptions where AP accesses the already closed database.
(Basically this just reverts to a former state)
=> Fix sqlite IllegalStateException

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
=> Consider theme when highlighting

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Not sure how the NPE is exactly caused, but more checks are never really a bad idea...
Resolves #1504
=> MediaPlayerActivity: Prevent onPrepareOptionsMenu NPE

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Fix "Escape SQL query parameters"

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/res/values/arrays.xml
Removed 45 seconds and added 2 and 5 minutes.
Resolves #1421
=> More smark options

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/res/values/strings.xml
Now, the interval dialog checks the current setting.
The preference view also shows the current value below the actual summary:
(In time, I think most of the preferences that are more than a checkbox/switch should get that "current value" information)
Resolves #1488
=> Give feedback about current update setting

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Disable auto download when HTTP_NOT_FOUND (404)

app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java
=> ItemListFragment: Prevent onListItemClick() NPE 

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
=> Prevent IllegalStateException when fragment is detached

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
=> Refresh queue when item playback position is reset

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
Resolves #1487
Didn't run a single test. It does compile and does what it is supposed to...
=> Default update interval for fresh installations

core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
=> Atom: If multiple enclosures, use first one

core/src/main/res/values/strings.xml
Include in description what triggers Episode Cleanup (ie Auto Downloads)
=> Update Episode Cleanup description

core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java
=> Parse <itunes:summary> and <itunes:subtitle>

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
Was broken in f6d5c780e59687509fd0d96c3a31e5ca69697fba
Should work now.
=> autodownload should be the default

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/res/menu/feeditemlist_context.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
=> Feed view: Add "Add/Remove to/from Favorites" to context menu

changelog/de.md, changelog/it.md, changelog/nb_NO.md, changelog/nl.md, changelog/ru_RU.md, changelog/sv_SE.md, changelog/tr.md, core/src/main/res/values-de/strings.xml, core/src/main/res/values-es-rES/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-nb/strings.xml, core/src/main/res/values-nl/strings.xml, core/src/main/res/values-pl-rPL/strings.xml, core/src/main/res/values-pt/strings.xml, core/src/main/res/values-ru/strings.xml, description/de.txt, description/fr.txt, description/pt.txt
=> Update translations 2016 01 24

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java
See http://stackoverflow.com/questions/18230752/no-view-found-for-id-0x-for-fragment-after-rotation
Resolves #1599
=> Audio Player: Don't retain cover fragment

app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/res/layout/fragment_itunes_search.xml, app/src/main/res/layout/gpodnet_podcast_listitem.xml, app/src/main/res/layout/itunes_podcast_listitem.xml, app/src/main/res/menu/itunes_search.xml, core/src/main/res/values/styles.xml
* SearchView is in the action bar (just like gpodder search)
* Progress bar
* Message is nothing was found
* On error, show error message and retry button
* Layout improvements: General niceness, also shows feed URL (gpodder got a little nicer layout, too)
Resolves #1553
=> iTunes Search improvement

app/build.gradle, app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/res/layout/cover_fragment.xml
Shownotes now also has the same background color as cover and chapters.
Resolves #1602
=> Audio Player: Themed background Color

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, app/src/main/res/menu/feedlist.xml, core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/arrays.xml
Fixes #1500 (see the issue for details)
=> Use positive/reverse filtering

changelog/de.md, changelog/fr.md, changelog/pt.md, core/src/main/res/values-az/strings.xml, core/src/main/res/values-ca/strings.xml, core/src/main/res/values-cs-rCZ/strings.xml, core/src/main/res/values-da/strings.xml, core/src/main/res/values-de/strings.xml, core/src/main/res/values-es-rES/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-hi-rIN/strings.xml, core/src/main/res/values-it-rIT/strings.xml, core/src/main/res/values-iw-rIL/strings.xml, core/src/main/res/values-ja/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-nb/strings.xml, core/src/main/res/values-nl/strings.xml, core/src/main/res/values-pl-rPL/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-pt/strings.xml, core/src/main/res/values-ro-rRO/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sv-rSE/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-uk-rUA/strings.xml, core/src/main/res/values-zh-rCN/strings.xml, description/pt.txt
It looks like some people are getting confused about the '&#8230;' business. I guess I shouldn't be surprised.
Not sure the best way to get everyone back on track.
Any thoughts @mfietz or @recalculated?
=> updated translations

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
=> Audioplayer: Prevent onMediaChanged() NPE

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java, app/src/main/res/layout/itemdescription_listitem.xml
=> Subscription view: Show publication dates and look better

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportBaseActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromIntentActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java, core/src/main/res/values/strings.xml
=> Import OPML: Ask for permission to access external storage on Marshmallow

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
wasn't setting boolean properly when loading data, resulted in filter switching to 'include'
=> Set 'filterInclude' properly

app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, build.gradle
Made some optimizations...
(Luckily we are still in alpha, so we have enough time to check that I did not fuck up ^^)
=> Upgrade AntennaPod-AudioPlayer to v1.0.11

app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/res/layout/downloaded_episodeslist_item.xml, app/src/main/res/layout/episodes_apply_action_fragment.xml, app/src/main/res/menu/downloads_completed.xml, app/src/main/res/menu/episodes_apply_action_options.xml, core/src/main/res/values/strings.xml
This is also a preparation to use the dialog in other places by making the provided actions configurable.
I'd recommend checking the commits one by one...
Resolves #1222
=> Completed Downloads: Gears Dialog

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
=> Apply Actions: Get Add to Queue back

description/en.txt
Functionality introduced per  #1612. Should probably wait with merging until 1.5 is out on Google Play.
=> add 'episode filtering' & other updates

build.gradle
see https://publicobject.com/2016/02/11/okhttp-certificate-pinning-vulnerability/
(Didn't run the test suite, but a manual test seemed fine)
=> Upgrade OkHttp to 2.7.4

build.gradle
Resolves #837
(See https://github.com/AntennaPod/AntennaPod-AudioPlayer/commit/66faaa4bdd907638c7549d498442e6f0f6c41dfd)
=> Upgrade AudioPlayer to v1.0.12

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/res/layout/audio_controls.xml
=> Audio controls dialog scrollable

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java
=> Prevent FeedMedia.getFeedTitle() NPE

app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java
=> StringUtils: Xiaomi NoSuchMethodError

core/src/main/java/de/danoeh/antennapod/core/feed/FeedMedia.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
~~More of a hotfix.
Probably not the smartest idea to load the chapters and write them to the database on the main thread...~~
Resolves #1680
=> Load embedded chapters from local files

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
=> Video player: Do not NPE when rewind or fast-forward time is changed

core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
=> Prevent NPE in DateUtils.abbrev()

app/src/main/res/layout/external_player_fragment.xml, app/src/main/res/layout/nav_feedlistitem.xml
Queue appearance has not changed.
Resolves #1675
=> Improve scaling of cover in external player and navbar

core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
=> Set notification visibility to public

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Trying to prevent as many NPEs as possible. Might not even be possible in some cases that a variable is null, but checking does not harm.
Resolves #1710
=> AudioPlayer NPEs

app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
No idea how to actually test this...
Resolves #1706
=> Audio player fragments: Do not refresh when not attached

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Fixes #1724
This should be a hotfix...
=> Fix play-pause after re-opening audioplayer

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Only change is the ``error -> {...` part, the rest is reformating.
=> MediaplayerActivity: checkFavorites() implement OnError

app/build.gradle, build.gradle, core/src/main/res/values/styles.xml
=> Upgrade support libraries to version 23.2.0

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/layout/queue_fragment.xml
Hopefully resolves some phones crashing when an item in the queue is dragged.
=> Fix RecyclerView reorder crash

app/src/main/java/de/danoeh/antennapod/activity/OpmlFeedChooserActivity.java, app/src/main/res/menu/opml_selection_options.xml
=> OPML Import: Select/deselect toggle

core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java, core/src/main/res/values/strings.xml
=> Show message if shownotes are empty

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
=> Duck and raise audio volume back

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/model/GpodnetEpisodeAction.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java, core/src/main/java/de/danoeh/antennapod/core/util/Converter.java, core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
=> Avoid unneeded boxing

app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/ProxyDialog.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/layout/downloadlog_item.xml, app/src/main/res/layout/proxy_settings.xml, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java, core/src/main/java/de/danoeh/antennapod/core/service/download/ProxyConfig.java, core/src/main/res/values/strings.xml
Resolves #447
**Testing:**
Install [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android&hl=de)
Host: 127.0.0.1 / localhost
Port: 8118
**Testing authorization:**
I installed Polipo on a RasPi for that. My config is this:
```
logSyslog = false
logFile = /dev/null
proxyAddress = "::0" 
authCredentials = <username>:<password>
allowedClients = 127.0.0.1, <local-ip-range>
diskCacheRoot = ""
```
**No Socks 4 or 5?**
The problem is described in https://github.com/square/okhttp/issues/2315
If someone actually asks for SOCKS support, we could have a look at jsocks
This PR also contains a minor fix for cut off icons in the Downloads Log.
=> Proxy support

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/util/DownloadError.java, core/src/main/res/values/strings.xml
Resolves #1503
Could probably add some lengthy explanation, but the user probably only wants that HTML is not mistaken for an episode.
=> Downloader: Check content type for media

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
The summary might have space for improvement...
Resolves #359
=> Gpodder: Enable manual syncing

app/src/main/java/de/danoeh/antennapod/PodcastApp.java, app/src/main/java/de/danoeh/antennapod/receiver/ConnectivityActionReceiver.java, app/src/main/java/de/danoeh/antennapod/receiver/PowerConnectionReceiver.java, app/src/main/java/de/danoeh/antennapod/receiver/SPAReceiver.java, core/src/main/java/de/danoeh/antennapod/core/ClientConfig.java, core/src/main/java/de/danoeh/antennapod/core/UpdateManager.java, core/src/main/java/de/danoeh/antennapod/core/receiver/AlarmUpdateReceiver.java, core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java, core/src/main/java/de/danoeh/antennapod/core/receiver/MediaButtonReceiver.java
Make sure that DB helpers, preferences and so on are initialized on each of the various entry points, especially BroadcastReceivers.
Resolves #1695
~~**Edit** Tests failing. Something about feed preferences. Trying to figure out if I caused this.~~
=> Ensure initialization

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, build.gradle
=> Master to 1.5.2.0

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java
=> Try to handle all external media controls

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/main/res/values/strings.xml
Resolves #775
(Just to be clear, the right screenshot shows the screen after the podcast has been added to the database.)
=> Add ability to open feed after subscribing

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
Resolves #1718
(Didn't run any tests, just opened the dialog in the app)
=> Pre-select playback speeds 1.00, 1.25, 1.50, 1.75 and 2.00

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
=> Only have one cursor open at the same time

app/src/main/AndroidManifest.xml
Resolves #965
Video just keeps running, we don't even have to do any resuming or restoring \o/
=> Enable counter-clockwise orientation in video player

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSContent.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSDublinCore.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSSimpleChapters.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java, core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndTypeUtils.java
Make as little assumptions as possible about the current parsing ``state`` (current item, feed etc.)
(I'd rather have too many checks than having to dig deep into the code to find out if a variable can be null at that particular moment)
Resolves #1686
(Yes, I forgot to create a new branch. Luckily, the branch was already merged and the new branch would be based on this anyway)
=> Prevent parsing errors

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
Opens https://github.com/AntennaPod/AntennaPod/labels/bug with any installed browser
=> Link to known issues/bugs in Settings

core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedFile.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedPreferences.java
=> Fix feed refresh issue

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java
Seems like an obvious typo to me...
=> fix double if on FeedItemlistAdapter

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java, app/src/main/java/de/danoeh/antennapod/menuhandler/MenuItemUtils.java
As per http://developer.android.com/reference/android/content/res/TypedArray.html
=> recycle typedArrays

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
Just wondering if those toasts were supposed to be shown...
=> show potential Toasts

core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSITunes.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSMedia.java
=> Parse iTunes duration seconds as float

core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrServiceCreator.java
I was wondering if FlattrServiceCreator should be changed...
If not, then just dismiss this pull request.
=> FlattrServiceCreator

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/res/values/strings.xml
No idea how well ``<![CDATA[...]]>`` will work with Transifex. It's an adventure!
Resolves #358
=> Show gpodder information

app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java, app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Should improve the performance of the SQLite database
Might resolve #1749
=> Enable WAL and use non-exclusive transactions

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/StatisticsActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/layout/statistics_activity.xml, app/src/main/res/layout/statistics_listitem.xml, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/util/Converter.java, core/src/main/res/values/strings.xml
=> Added statistics function

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
Did some minor refactoring and changed the AsyncTask to an Observable.
Changes to visibility or modifiers were suggested by the IDE (Inspect code).
Resolves #1812
=> PlaybackController.bindService() with Observable

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java
Handles feed removal a bit different, but I think this is much better.
Resolves #1817
=> Handling removing feed that is playing or paused

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
=> Fix navbar counter highlighting

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceMediaPlayerTest.java, app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBNullCleanupAlgorithmTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java, app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, build.gradle, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/AudioPlayer.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
Resolves #1793
Audio player upgrade fixes issues with streaming and makes android mediaplayer more stable.
=> Switch audio player implementation immediately

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
Re-arranged settings some and add the FAQ.
=> Settings cleanup

app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java, core/src/main/res/values/strings.xml
=> better device id generation

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/res/menu/feeditem_options.xml
=> Episode view: Open podcast

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
Props to @mfietz for discovering this bizarre fix.
=> fixes AntennaPod/AntennaPod#1848

CONTRIBUTING.md
=> Devide --> Device in CONTRIBUTING.md

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, core/src/main/java/de/danoeh/antennapod/core/util/LongIntMap.java
=> Subscription counter

app/src/main/java/de/danoeh/antennapod/adapter/DownloadLogAdapter.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/util/DownloadError.java, core/src/main/res/values/strings.xml
=> Delay auto download when receiving 403 Forbidden HTTP error

build.gradle
=> Make Flattr work again

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
=> AudioPlayerActivity: Prevent onStop() NPE

app/src/main/java/de/danoeh/antennapod/activity/StorageErrorActivity.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
Resolves #1893
I'm not able to trigger the issue, but this hopefully prevents it.
=> Prevent permission denied when determining free space

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
Resolves #1887
Only my best guess what the issue is: Episodes having the same pubDate but not appearing in the feed at the same time.
=> Episodes with same pubDate

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java
Resolves #1888
Could not check gpodder (500), but feed info works fine
=> Resolve potential AsyncTask performance issue

app/proguard.cfg
Resolves #1883 
Not checked, just hoping it makes sense...
=> Prevent potential crash on Samsung devices

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java
=> fix NPE on log

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
=> fix NPE when media is 'uncastable'

README.md
See Issue #1965, adds to pullrequest #14
References:
- [F-droid badge](https://gitlab.com/fdroid/artwork/blob/master/badge/README.md)
- [Google Play badge](https://play.google.com/intl/en_us/badges/)
=> Updated Badges in README

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java
=> Fix slow loading of filtered feeds

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Resolves #1937
Based on 1.6 devel, should probably not wait 2-3 months until 1.7 ...
=> Downloader: Fix invalid media mime type

app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
At least this will prevent exceptions.
Probably does not fix the underlying issue which is unknown.
=> Prevent onServiceConnected ClassCastException

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
Reasoning: You can swipe it off, removal via context menu should also be allowed.
Resolves #1969
=> Queue: Allow removal of playing/paused episode via context menu

app/src/free/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/adapter/ActionButtonCallback.java, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/play/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/play/java/de/danoeh/antennapod/fragment/ItemFragment.java
=> Prevent possible hang-bugs

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml, core/src/main/java/de/danoeh/antennapod/core/util/QueueSorter.java, core/src/main/res/values/strings.xml
Implements #1835 
- Add menu entries to sort feed  by title ("Feed title")
- Rename the "Alphabetically" sort option by "Episode title"
=> Add option to sort queue by feed title

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/res/menu/episodes.xml, core/src/main/res/values/strings.xml
First image: New episodes: Mark all as seen instead of played
Second image: (No changes, don't show marked as seen here)
Third image: Fixed snackbar
Resolves #1929 
Could be in 1.6, but introduces a new string...
=> New episodes: Mark (all) as seen

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java
Replaces AsyncTask with RxObservable
Resolves #1997
=> FeedInfoActivity: Prevent IllegalStateException

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java
=> Subscriptions: Move add tile to end

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/res/values/strings.xml
Introduces a new string to enforce translation.
Resolves #1970
=> Item view: Make remove/delete less ambiguous

app/src/androidTest/java/de/test/antennapod/gpodnet/GPodnetServiceTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java, app/src/androidTest/java/de/test/antennapod/storage/DBTasksTest.java, app/src/androidTest/java/de/test/antennapod/storage/DBWriterTest.java, app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java, app/src/androidTest/java/de/test/antennapod/util/service/download/HTTPBin.java, app/src/androidTest/java/de/test/antennapod/util/service/download/NanoHTTPD.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlFeedChooserActivity.java, core/src/main/java/de/danoeh/antennapod/core/util/flattr/FlattrUtils.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S2293 - The diamond operator ("<>") should be used
This pull request removes 62 minutes of technical debt.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2293
Soso Tughushi
=> squid:S2293 - The diamond operator ("<>") should be used

core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java
=> Prevent crash when image url is empty string

app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java
=> Completed Downloads: Add transparency to played episodes

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Fix mark as seen and improve mark all X [of feed Z] as Y

app/src/main/AndroidManifest.xml
Skipping 1.6.1.1, because I'm not a smart man...
=> Prepare 1.6.1.2

build.gradle
Resolves #1909
This issue was resolved in the support library ver. 23.3.0.
https://developer.android.com/topic/libraries/support-library/revisions.html (mediarouter)
=> update support library

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
Resolves #2017 (Really, this time)
=> Downloader: Check content-type for null

app/src/free/java/de/danoeh/antennapod/config/CastCallbackImpl.java, app/src/main/java/de/danoeh/antennapod/config/ClientConfigurator.java, app/src/play/java/de/danoeh/antennapod/cast/CustomMRControllerDialog.java, app/src/play/java/de/danoeh/antennapod/config/CastCallbackImpl.java, app/src/play/java/de/danoeh/antennapod/dialog/CustomMRControllerDialog.java, app/src/play/res/layout/media_router_controller.xml, core/src/free/java/de/danoeh/antennapod/core/CastCallbacks.java, core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/play/java/de/danoeh/antennapod/core/CastCallbacks.java, core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java, core/src/play/java/de/danoeh/antennapod/core/cast/CastManager.java
Resolves #1910 
This selects the background color based on the most predominant color in the image (for not landscape enough ones). For some reason the choice isn't the obvious one sometimes (we'd usually just want to extend the background from the image).
=> Fix Cast Dialog image

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
=> OnlineFeedViewActivity: Add onError and refactor

app/src/main/java/de/danoeh/antennapod/adapter/SearchlistAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java, core/src/main/res/values/strings.xml
I have improved some of the search features.
1) Added a TextView that informs the user that the search came up empty.
2) Prevent duplicate search episode results.
3) Add transparency to episodes that have been played.
=> Improve search results: "no results" view, no duplicates, transparent played episodes

core/src/main/java/de/danoeh/antennapod/core/syndication/handler/TypeGetter.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
Fixes https://github.com/AntennaPod/AntennaPod/issues/1949
Parses Author and Language
=> Improve Atom support

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> On shake, reset timer to the current waiting time

core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
This pull-request adds a check for Amazon AWS S3 pre-signed urls so that authentication headers are not set. This is because S3 does not allow both an authentication header and a pre-signed url at the same time ([Amazon documentation](
http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html)).
This will resolve the issue discussed in [Google Groups](https://groups.google.com/forum/#!topic/antennapod/C89LMPtUqpg).
=> Prevent authentication header to be set for s3 presigned-urls

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/res/menu/episodes_apply_action_options.xml, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
Episode filter
Gears dialog
Resolves #2079
=> Add "has media" filter

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, core/src/main/res/values/strings.xml
=> Show "mark all as seen" confirmation dialog

core/src/main/java/de/danoeh/antennapod/core/syndication/handler/SyndHandler.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
=> Feed media is only valid when download url is not empty

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
=> Add full sync with gpodder

core/src/main/java/de/danoeh/antennapod/core/asynctask/FeedRemover.java
=> FeedRemover: When closing dialog, check if it is still attached

app/src/main/java/de/danoeh/antennapod/activity/OpmlFeedChooserActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportBaseActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportHolder.java, app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivity.java, app/src/main/java/de/danoeh/antennapod/activity/PreferenceActivityGingerbread.java, app/src/main/java/de/danoeh/antennapod/asynctask/ExportWorker.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlExportWorker.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlFeedQueuer.java, app/src/main/java/de/danoeh/antennapod/asynctask/OpmlImportWorker.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/backup/OpmlBackupAgent.java, core/src/main/java/de/danoeh/antennapod/core/export/CommonSymbols.java, core/src/main/java/de/danoeh/antennapod/core/export/ExportWriter.java, core/src/main/java/de/danoeh/antennapod/core/export/html/HtmlSymbols.java, core/src/main/java/de/danoeh/antennapod/core/export/html/HtmlWriter.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlElement.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlReader.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlSymbols.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlWriter.java, core/src/main/res/values/strings.xml
=> Export subscriptions as HTML

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
=> Add option to show number of downloaded episodes in subscription counter

core/src/main/java/de/danoeh/antennapod/core/export/CommonSymbols.java, core/src/main/java/de/danoeh/antennapod/core/export/html/HtmlWriter.java, core/src/main/java/de/danoeh/antennapod/core/export/opml/OpmlWriter.java
Format exported OPML and HTML files
=> Indent exported files

app/build.gradle, app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FyydSearchFragment.java, app/src/main/res/layout/addfeed.xml, core/src/main/res/values/strings.xml, core/src/main/res/values/styles.xml
=> Integrate fyyd podcast search engine

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/AdapterUtils.java, core/src/main/java/de/danoeh/antennapod/core/util/syndication/HtmlToPlainText.java
=> Sanitize HTML from Atom feed descriptions/subtitles

core/src/main/java/de/danoeh/antennapod/core/syndication/util/SyndTypeUtils.java
=> Accept 'application/octet-stream' as valid media mime type

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportBaseActivity.java
=> Do not check permissions for OPML import on pre-M Android versions

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/NSAtom.java
YouTube doesn't provide a feed description, and an error is thrown when trying to trim the HTML from the null string.
=> Youtube fix

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Catch out of memory exception

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Resolves #2134 
Borrowed from @BigPet's 65577cfa74c978cecd4da902bd665bcd376e01df
=> Prevent ClassCastException

app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceMediaPlayer.java, core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java
=> Do not auto-enable sleep timer after skipping

app/build.gradle, app/src/main/java/de/danoeh/antennapod/PodcastApp.java, build.gradle, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/NSRSS20.java
#2200 asks a feature of a [launch screen](https://material.google.com/patterns/launch-screens.html).
This PR implements a same thing using [this guide](https://www.bignerdranch.com/blog/splash-screens-the-right-way/).
=> Add launch screen.

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
=> Remove cached feed file after parsing

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromIntentActivity.java
=> Share OPML [Fixed]

core/src/androidTest/java/de/danoeh/antennapod/core/tests/util/DateUtilsTest.java, core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
Hopefully resolves issues #2243 and #2250.
=> Additional date format and a hack for CEST

app/src/main/AndroidManifest.xml, app/src/main/res/xml/automotive_app_desc.xml, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
I also added the ability to search for feed items by feed identifier and feed author since I think that would make the most sense when searching by voice.
=> Enable support for Android Auto with support for OnPlayFromSearch

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, core/src/main/java/de/danoeh/antennapod/core/dialog/ConfirmationDialog.java, core/src/main/res/values/strings.xml
=> Added feed title to delete confirmation

core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
This way, your most-loved feeds are on top of the list
=> Sort feeds by number of played episodes

app/src/main/java/de/danoeh/antennapod/adapter/ChaptersListAdapter.java, app/src/main/res/layout/simplechapter_item.xml, core/src/main/res/values/strings.xml
Closes #2174
I'm not sure if it's the best idea to fix this in the UI. Unfortunately, adding a `getDuration()` method to `Chapter` requires a lot of changes in various parser classes, like `VorbisCommentChapter` or `ID3Chapter`.
=> Added duration to chapters list

core/src/androidTest/java/de/danoeh/antennapod/core/tests/util/DateUtilsTest.java, core/src/main/java/de/danoeh/antennapod/core/util/DateUtils.java
=> When date string parsing failed, try parsing the string without the weekday

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java
=> Only allow menu invalidations from active fragment

core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
- Taking more care of closing adapter and cursors.
- Dropping unneeded MoveToFirst where we manage the cursor.
- Better feed association implementation.
- Dropping one of getFeedItems() methods that looks unused.
=> Some cleanup on DBReader:

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> Fixed playback progress bar position after start

core/src/main/java/de/danoeh/antennapod/core/receiver/FeedUpdateReceiver.java
=> When automatically updating feeds, check if a network connection is available first

app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java, app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedImageMother.java, core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedItemMother.java, core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedItemTest.java, core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedMother.java, core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedTest.java, core/src/main/java/de/danoeh/antennapod/core/feed/Feed.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Update feed and item images

ISSUE_TEMPLATE.md
=> F-Store → F-Droid

app/src/main/java/de/danoeh/antennapod/activity/StorageErrorActivity.java
I'm not sure but did you mean ">=" ?
=> request permissions in api > 23 (Android N etc.)

circle.yml
=> Update circle.yml to currently used build tools version

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
While I could not reproduce the issue, I hope this resolves #2413
=> Cast according to mediaplayer instance type, not media type

app/src/androidTest/java/de/test/antennapod/util/FilenameGeneratorTest.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java, core/src/main/java/de/danoeh/antennapod/core/util/FileNameGenerator.java
=> Only allow very limited set of characters in file names

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/main/res/values/strings.xml
=> Merged add_feed_label and add_new_feed_label

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/res/values/strings.xml
=> Check successful file deletion

app/src/main/java/de/danoeh/antennapod/service/PlayerWidgetService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Also check keep favorites preference in player widget service

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java
=> Avoid FileUriExposedException on OPML Import

app/src/main/res/layout/player_widget.xml
The time text was hard to read
=> Adjust text color in widget

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/res/layout/cover_fragment.xml, app/src/main/res/layout/external_player_fragment.xml, core/src/main/res/values-v21/styles.xml, core/src/main/res/values/styles.xml
Well, I am having trouble with the bottom sheet. But here is at least a nice animation ;)
=> Shared element transition

app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
Bug was introduced in #2457, shared element does not exist in video view
=> Fixed video view

core/src/main/AndroidManifest.xml, core/src/main/java/de/danoeh/antennapod/core/service/GpodnetSyncService.java
The _FLAG_ variant is the input enum, replace it
with the value-equivalent properly typed enum.
=> Return START_STICKY from onStartCommand()

build.gradle
jsoup 1.11.1 features a 30% lower DOM memory footprint, streaming
network HTML parsing, faster HTML generation, and a bunch of other
improvements and bug fixes.
See https://jsoup.org/news/release-1.11.1 and
https://jsoup.org/news/release-1.11.2 (with the followup bugfixes)
for details.
=> Update jsoup to 1.11.2

app/src/main/java/de/danoeh/antennapod/activity/FeedInfoActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadsFragment.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/util/syndication/HtmlToPlainText.java
This avoids an implicit this field and can help GC.  Found via
error-prone.
=> Make some inner classes static

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/ImportExportActivity.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/layout/import_export_activity.xml, app/src/main/res/xml/preferences.xml, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
Still needs some cleanup and testing.
Fixes #377
=> Database import/export

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
This prevents large numbers of db writes in quick succession. This is a particular problem for large queue lengths. Fixes #2562 and potentially fixes #2573
Feedback and suggestions for improvement welcome.
=> Only write queue order to database on drag release for podcast queue.

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
This might allow some forensics if #2463 happens. Maybe it also
allows to recover some of the files manually.
=> Backup corrupted db

app/src/androidTest/java/de/test/antennapod/feed/FeedItemTest.java, core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java
This PR correctly handles empty `content:encoded` tags. I am not sure if this should rather be solved on the publisher's end, but it's a very small change :)
> **TextUtils.isEmpty**
> Returns true if the string is null or 0-length.
I am listening to "Hello Internet": http://www.hellointernet.fm/podcast?format=rss. Starting with HI92, there are no shownotes anymore. Before HI92, all shownotes are displayed correctly.
Working shownotes:
```
<item>
<title>H.I. #91: Last Man to Die?</title>
<dc:creator>Hello Internet</dc:creator>
<pubDate>Tue, 31 Oct 2017 22:05:11 +0000</pubDate>
<link>http://www.hellointernet.fm/podcast/91</link>
<guid isPermaLink="false">52d66949e4b0a8cec3bcdd46:52d67282e4b0cca8969714fa:59f8f3572774d1b8507f6e72</guid>
<description>
<![CDATA[<p>Grey and Brady discuss: …
```
=> Fixes empty contentEncoded

app/src/main/res/layout/import_export_activity.xml
=> Added scrolling to Import/Export

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
=> Even use expired cache if there is no network

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences.xml
=> Added OPML import option next to the export option

app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, app/src/main/res/layout/downloadlog_item.xml, core/src/main/res/values/strings.xml
=> Showing URL for failed downloads

app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
=> Ignore invalid position updates

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java, core/src/main/res/values/strings.xml
=> Split up two different uses of the string 'New'

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java
=> Added warning to 'Mark all played'

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/util/Permutor.java, core/src/main/java/de/danoeh/antennapod/core/util/QueueSorter.java, core/src/main/res/values/strings.xml
Added "Random" and "Smart Shuffle" items at the bottom of the Queue|Sort menu.
Added "Permutor" interface to allow specification of reordering logic to be specified in QueueSorter (vs. DBWriter), similar to the existing sort logic.
Added "Random" and "Smart Shuffle" strings to core/src/main/res/values (did not add translations for non-English languages)
JavaDoc was added, but no new tests (didn't see tests for existing UI-level stuff like Queue|Sort, so I left it out)
Closes #2366, Closes #2602
=> Added "Random" and "Smart Shuffle"

core/src/main/AndroidManifest.xml, core/src/main/res/values/strings.xml
=> Allow feeds update to be triggered by external apps.

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/DefaultActionButtonCallback.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java, app/src/main/java/de/danoeh/antennapod/spa/SPAUtil.java, core/src/main/java/de/danoeh/antennapod/core/asynctask/FeedRemover.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java, core/src/main/java/de/danoeh/antennapod/core/util/IntentUtils.java
=> Limit broadcasts to current app

core/src/main/java/de/danoeh/antennapod/core/syndication/handler/TypeGetter.java
=> Assume version 2.0 for RSS if property is missing

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
=> Requesting audio focus on Android O

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java, core/src/main/res/values/strings.xml
I was just wondering why playing external files does not work. Looks like the permission was not set manually in settings. This PR makes AP ask for the permission.
=> Requesting storage permissions for external files

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Closes #2819
I do not own a Chromecast, so I can not test this one
=> Allow mediaPlayer to be null

core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Do not crash if mediaPlayer is null

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
=> Ensure that during feeds update, automatic (episodes) download the latest ones

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItemFilter.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
=> Add feed filter criteria 'is favorite'

build.gradle, core/build.gradle, core/src/main/java/de/danoeh/antennapod/core/util/FeedUpdateUtils.java
=> When auto refreshing feeds, give network some time to get available

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
I have verified this change on the emulator.
=> Resolves #2829 - Make queue remaining time sensitive to playback speed

app/build.gradle, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java
=> 2855 Cancel UI media info update when fragment is destroyed

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/res/values/strings.xml
Closes #2810
For details, see #2810
=> Hiding expand notification preference on API 26

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml
=> Allow to select all above/below in batch editor

core/src/main/res/drawable/overlay_drawable_dark_trueblack.xml, core/src/main/res/values/styles.xml
See photo example below. This PR closes issue #2873.
=> Change show notes background and scrubber background to black on AMOLED theme

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Resolves #2882
I wasn't able to reproduce this issue, but the changes should at least prevent the app from crashing. We'll see if it remains in a proper state...
=> Prevent NPE

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
closes #2878
The fix uses the pattern in the similar `QueueRecyclerAdapter.java`
=> Fix episode screen context menu is applied on wrong feed item during refresh

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, core/src/main/res/values/arrays.xml
=> Fix NPE when selecting Go to page for the first time

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
Fixes #2925, fix suggested by ByteHamster.
=> Fix bug preventing database import on Android 9.

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
=> #2950 - fix app crash in OPML Export > Send flow

app/src/main/play/en-US/listing/shortdescription
AntennaPod doesn't manage radio stations. Related to #2968.
=> Remove radio mention

core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
=> Only delete from queue if deletion of media succeeds

app/src/main/res/layout/feeditemlist_item.xml, app/src/main/res/layout/nav_feedlistitem.xml, app/src/main/res/layout/nav_listitem.xml
fixed the ripple effect issue that was caused by my previous pull request, closes #2999
=> Reimplemented the ripple effect when choosing a nav item

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle
removed implementation was some Eclipse/ant style, now it's Gradle style
=> simplify versionCode

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
Fix #2633 
* set min/max playback speeds for seekbar using user preferences
* 0.05x stepping playback speed for increment/decrement button
=> Set min/max playback speeds from preferences

core/src/test/java/de/danoeh/antennapod/core/util/ConverterTest.java, core/src/test/java/de/danoeh/antennapod/core/util/RewindAfterPauseUtilTest.java, core/src/test/java/de/danoeh/antennapod/core/util/URIUtilTest.java
This allows to execute them on CircleCI automatically.
=> Moved some implementation tests to unit tests

app/build.gradle, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences_storage.xml, core/src/main/res/values/strings.xml
As suggested by @keunes in #2899
=> Add backup keyword to search

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
This is now more or less the same code as in the parent class. Might need some cleanup instead of just adding more code.
Closes #3022
=> Fixed download status update in NewEpisodesFragment

app/build.gradle
Related to #3004
Fixed upstream in https://github.com/mfietz/fyydlin/pull/1
=> Fixed fyyd feed search

core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
=> Respect 'keep updated' for new items counter

app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Fixes `<a href="//example.com">` links
Closes #3036
=> Specifying base url

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/java/de/danoeh/antennapod/asynctask/ExportWorker.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java, app/src/play/java/de/danoeh/antennapod/dialog/CustomMRControllerDialog.java, core/src/main/java/de/danoeh/antennapod/core/service/download/Downloader.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
closes #2966. The PR is *incomplete*, pending #2954 merge.
Two correctness issues identified. 
1. `OnlineFeedViewActivity.parseFeed()` : fixes pending `Optional` in #2954 
2. `PlaybackController.bindToService()` : fixed already in #2954
The rest are annotating nullness and make it explicit in observer codes that they expect `@NonNull` result ( removing null check in observers).
=> Fix rxjava2 null returns

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
=> bugfix - add podcast by URL - show error dialog when URL points to no feed

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
=> bugfix - bulk actions - make UI survive upon split screen

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Entering multiwindow caused a spinner that did not go away.
=> Fix displaying progress indicator in multi window

core/src/main/res/values/styles.xml
=> Reduced repetition in styles.xml

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/menu/subscriptions.xml, core/src/main/res/values/strings.xml
=> Set number of subscription columns

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java
Introduced in #3097
Closes #3110
=> Fixed crash when re-using released controller

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/play/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceFlavorHelper.java, core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
=> Fixed cast related bugs

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> Fixed NetworkOnMainThreadException

app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
This is a minor fix to remove redundant casts and add generic type to avoid compiler warnings.
=> Cleanup compiler warnings

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
So it is easier to identify problems in bug reports
=> Added names for threads

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
The method is called again with a valid listAdapter automatically
Closes #3154
=> Fixed NPE when selected item is null

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/view/EmptyViewHandler.java, app/src/main/java/de/danoeh/antennapod/view/SimpleAdapterDataObserver.java, app/src/main/res/layout/all_episodes_fragment.xml, app/src/main/res/layout/empty_view_layout.xml, app/src/main/res/layout/queue_fragment.xml
=> Simplify empty view handling on recycler views

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> Fixed threading bugs in Sonic

core/src/main/java/de/danoeh/antennapod/core/util/NetworkUtils.java
=> Enable autodownload over Ethernet

app/src/main/java/de/danoeh/antennapod/fragment/ChaptersFragment.java
This is especially helpful for episodes that have a large number of
chapters.
Closes: #2853
=> Scroll to chapter currently being played

app/src/main/java/de/danoeh/antennapod/activity/OpmlImportFromPathActivity.java, app/src/main/res/layout/opml_import.xml
Action does not show useful options anyways. Buttons might feel mismatched, so I removed the unneeded one.
Closes #2581
=> Removed opml pick action

app/proguard.cfg
=> No longer try to remove log

app/src/main/java/de/danoeh/antennapod/activity/ImportExportActivity.java, core/src/main/res/values/strings.xml
Does some basic validation before importing + overwriting the local SQLite3 DB.
Fixes #3163.
=> Check SQLite3 magic bytes before import

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/res/xml/preferences_playback.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java, core/src/main/java/de/danoeh/antennapod/core/util/TimeSpeedConverter.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/res/values/strings.xml
This is a simple implementation proposal to fix https://github.com/AntennaPod/AntennaPod/issues/2197
IMHO remaining time should always consider the playback speed, no UI changes are needed.
=> Fixes #2197: Remaining time playback speed

core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java, core/src/main/java/de/danoeh/antennapod/core/util/comparator/InReverseChronologicalOrder.java, core/src/main/java/de/danoeh/antennapod/core/util/comparator/SearchResultDateComparator.java
=> bugfix #3009 - Podcast's feed search results listed in an odd order

core/src/main/java/de/danoeh/antennapod/core/util/QueueSorter.java
This reworks the sort algorithm used in smart shuffle so that episodes
are spread out evenly, which avoids episodes bunching up at the bottom
of the queue when one feed has more episodes than others, and avoids
running through feeds with few episodes very quickly.
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Smart shuffle: spread episodes evenly

app/build.gradle, app/src/main/java/de/danoeh/antennapod/PodcastApp.java, core/build.gradle
This should make registering subscribers a bit faster.
http://greenrobot.org/eventbus/documentation/subscriber-index/
=> Use annotation processor for EventBus

core/src/main/res/values/strings.xml
=> Clarified mobile updates setting

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java, app/src/main/res/xml/preferences_autodownload.xml, core/src/main/res/values-de/strings.xml, core/src/main/res/values/strings.xml
As suggested in https://github.com/AntennaPod/AntennaPod/issues/3053#issuecomment-477224413. Unfortunately, I don't have the Android tool-chain installed and I'm not an Android developer. So it would be good if someone could test it.
=> add pref_episode_cache_summary

app/src/main/AndroidManifest.xml
=> Removed deleted receiver from manifest

app/build.gradle
=> Updated SearchPreference

app/src/main/java/de/danoeh/antennapod/adapter/DataFolderAdapter.java, core/src/main/res/values/strings.xml
=> Added total space to storage select dialog

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
=> Fixed batch edit items grayed out on API 23 and 24

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/gpoddernet/GpodnetAuthenticationActivity.java, app/src/main/res/layout/gpodnetauth_credentials.xml, app/src/main/res/layout/gpodnetauth_device.xml
Refer to the changes.
- Remove android:screenOrientation="portrait" for rotating.
- Remove override onConfigurationChanged function that does nothing.
Resolves #3235
=> Removed screenOrientation attributes in manifest

app/src/main/java/de/danoeh/antennapod/adapter/itunes/ItunesAdapter.java, app/src/main/java/de/danoeh/antennapod/discovery/CombinedSearcher.java, app/src/main/java/de/danoeh/antennapod/discovery/FyydPodcastSearcher.java, app/src/main/java/de/danoeh/antennapod/discovery/GpodnetPodcastSearcher.java, app/src/main/java/de/danoeh/antennapod/discovery/ItunesPodcastSearcher.java, app/src/main/java/de/danoeh/antennapod/discovery/PodcastSearchResult.java, app/src/main/java/de/danoeh/antennapod/discovery/PodcastSearcher.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/CombinedSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FyydSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/res/layout/addfeed.xml
Allows to search using all providers at once.
Working towards #3178
=> WIP: Combined podcast search

app/build.gradle, app/src/main/java/de/danoeh/antennapod/adapter/FeedDiscoverAdapter.java, app/src/main/java/de/danoeh/antennapod/discovery/ItunesTopListLoader.java, app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/CombinedSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java, app/src/main/java/de/danoeh/antennapod/view/WrappingGridView.java, app/src/main/res/layout/addfeed.xml, app/src/main/res/layout/quick_feed_discovery.xml, app/src/main/res/layout/quick_feed_discovery_item.xml, app/src/main/res/menu/advanced_search.xml, core/src/main/res/values/strings.xml
=> Add feed page redesign

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
=> Fixed some crashes

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/menu/queue.xml
=> Added batch edit to queue

app/src/androidTest/java/de/test/antennapod/util/service/download/NanoHTTPD.java, build.gradle, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetServiceAuthenticationException.java, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetServiceBadStatusCodeException.java, core/src/main/java/de/danoeh/antennapod/core/gpoddernet/GpodnetServiceException.java, core/src/main/java/de/danoeh/antennapod/core/menuhandler/MenuItemUtils.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequestException.java, core/src/main/java/de/danoeh/antennapod/core/syndication/handler/UnsupportedFeedtypeException.java, core/src/main/java/de/danoeh/antennapod/core/util/InvalidFeedException.java, core/src/main/java/de/danoeh/antennapod/core/util/exception/MediaFileNotFoundException.java, core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3ReaderException.java, core/src/main/java/de/danoeh/antennapod/core/util/syndication/HtmlToPlainText.java, core/src/main/java/de/danoeh/antennapod/core/util/vorbiscommentreader/VorbisCommentReaderException.java
This re-enables both linting options, according to https://github.com/AntennaPod/AntennaPod/issues/3273
=> Re-enable deprecation and serial linting

core/src/main/res/values/arrays.xml
=> Added 500 episodes limit

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Stop service if playing from preferences does not work

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/res/layout/onlinefeedview_header.xml
What bugged me most was the fact that the list items showed a ripple effect on touch but did not do anything. While I was looking at the layout, I added some bigger images.
=> Updated OnlineFeedView layout

app/src/main/java/de/danoeh/antennapod/adapter/CoverLoader.java, app/src/main/java/de/danoeh/antennapod/adapter/DataFolderAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
=> Make classes static where possible

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceStateManager.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> PlaybackService bug fixes

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/util/TimeSpeedConverter.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> Allow to adjust video playback speed

app/build.gradle, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
=> Extracted preference search string resources

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceStateManager.java, core/src/main/res/drawable/ic_stream_white.xml, core/src/main/res/values/strings.xml
No longer remove the notification on audio focus loss
Closes #1417
Closes #2812
=> Playback service notification improvements

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
=> Disabled long-press drag

app/src/main/java/de/danoeh/antennapod/discovery/ItunesTopListLoader.java, core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java, core/src/main/java/de/danoeh/antennapod/core/util/exception/RxJavaErrorHandlerSetup.java, core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
Closes #3344
For details, see https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling
=> Do not crash on undeliverable InterruptedException

app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
Makes sure that playback service is always stopped if currently playing media is deleted
Closes #3336
Closes #2210
=> Allow to delete currently playing media

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/res/menu/episodes.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java
This is a squashed version of #3322
Closes #3308
=> More episodes on all episodes

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/res/layout/all_episodes_fragment.xml, core/src/main/res/drawable/line.xml, core/src/main/res/drawable/line_drawable.xml, core/src/main/res/drawable/thumb.xml, core/src/main/res/drawable/thumb_drawable.xml
=> Fast scroll

app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/res/menu/feedlist.xml
Collapses the menu items instead of moving them partially out of the screen. Also fixes #2560
=> Collapse search view

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
=> Fixed deleting currently playing feed

app/src/main/templates/about.html
Add attribution for FAB SpeedDial library.
=> FAB SpeedDial - add attribution in about screen

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java
=> Fixed playback speed button not cycling through options

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/res/layout/episodes_apply_action_fragment.xml
=> Batch edit screen FAB

app/src/main/java/de/danoeh/antennapod/fragment/AddFeedFragment.java, app/src/main/res/layout/addfeed.xml, core/src/main/java/de/danoeh/antennapod/core/util/exception/RxJavaErrorHandlerSetup.java
=> Add feed improvements

app/src/main/templates/about.html
=> Add link to Privacy Policy

app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java
=> update FAQ link to https

core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java
Follow-up to #3397
@sbadux I changed the behavior again, so that the service is actively restarted when gaining audio focus again. Then the setting is still there and we don't change any behavior to the previous version.
=> Restart service when re-gaining audio focus

app/src/main/java/de/danoeh/antennapod/adapter/DownloadlistAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java, core/src/main/java/de/danoeh/antennapod/core/util/ThemeUtils.java, core/src/main/res/values/colors.xml
`selection_background_color_*` are never displayed because the selected position is never set.
=> Removed unused color resource

app/src/main/res/layout/feeditem_fragment.xml
Maybe this makes it easier to discover the feature.
=> Cover and text are selectable. Show this on click

core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java
=> Fixed widget if playbackservice is not running

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> Allow to set playback speed while service is not running

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java
=> Showing full description when clicking item on podcast preview screen

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/CrashReportWriter.java, app/src/main/java/de/danoeh/antennapod/activity/CrashReportActivity.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/MainPreferencesFragment.java, app/src/main/res/layout/crash_report.xml, core/src/main/res/values/strings.xml
No longer send bug reports to @mfietz via email. Instead, display the recorded stack trace and show a button to create an issue on GitHub.
=> Added screen that shows crash info

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
=> Fixed HTTP redirects in ExoPlayer

app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/menu/subscriptions.xml, core/src/main/java/de/danoeh/antennapod/core/event/DownloadEvent.java
=> Added refresh item to subscriptions view

config/checkstyle/checkstyle.xml, core/src/main/java/de/danoeh/antennapod/core/util/Optional.java, core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ChapterReader.java
All copied from the Google checks
=> Enabled more checkstyle rules

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
=> Do not notify cancelled downloads

app/src/main/java/de/danoeh/antennapod/fragment/preferences/AutoDownloadPreferencesFragment.java, core/src/main/AndroidManifest.xml, core/src/main/res/drawable/ic_warning_red.xml, core/src/main/res/values/strings.xml
Short term fix for #3387 
The initial commit is the bare minimum. I intend to add the UI change to prompt users to grant permission when necessary in the next few days.
=> Make Automatic Download WiFi filter UI work on Android 10+

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Do not reinit on pause

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
Allows to skip back one time without re-fetching data.
Closes #3463
=> Keep 30 seconds of back buffer

core/src/main/java/de/danoeh/antennapod/core/preferences/PlaybackPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
This makes the giant `PlaybackService` 75 lines shorter. Still 1819 lines left to restructure :D
=> Moved storing PlaybackPreferences to PlaybackPreferences.java

app/src/androidTest/java/de/test/antennapod/service/playback/PlaybackServiceTaskManagerTest.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> New fix player stuck due to streaming rather than using downloaded media

core/src/main/java/de/danoeh/antennapod/core/feed/FeedItem.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
=> Fixed feed without any identifying value

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
=> Added logging to ExoPlayer

app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/StatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/view/PieChartView.java, app/src/main/res/layout/statistics_activity.xml, app/src/main/res/layout/statistics_listitem.xml, app/src/main/res/layout/statistics_listitem_total_time.xml
=> Added pie chart to statistics

app/build.gradle
When building, the app would sometimes end up with a wrong commit. This is fixed by forcing Gradle to execute the task every build.
=> Fix about screen update

config/checkstyle/checkstyle-best-practice.xml
This are the style guidelines I want to enforce throughout the project in the future.
Currently, huge parts of the app do not pass these checks but when developing something new,
we should add those checks to our IDEs.
They are basically the Google checks but with an increased line length from 100 to 120
characters and using 4 instead of 2 spaces for indentation.
=> Added best-practice checkstyle checks

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/ExternalMedia.java
- Start playing after granting permission
- Showing file name instead of blank space if there is no title
=> Local playable improvements

core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> Fixed downmixing if service is not bound

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java
=> Showing progress in notification

app/src/main/java/de/danoeh/antennapod/adapter/SubscriptionsAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/layout/fragment_subscriptions.xml
=> Implement a FAB to add podcast on the Subscriptions screen

app/src/androidTest/java/de/test/antennapod/ui/PlaybackTest.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
Close #3383.
I am fairly confident that the fix is complete, but would like a second opinion.
=> Bugfix skip last episode in queue - episode status

app/build.gradle
Migrated to androidx, aligned text with list items
Before / After
=> Updated preference search

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
Fixes #3503.
Reset playback position when an item is marked as played.
=> Issue #3503 - reset playback position when marking as played

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/ShakeListener.java
I was able to get a "play" action to reset the sleep timer if it hasn't yet expired with these code changes.
FIxes #2381
=> Issue #2381 - restart sleep timer on play

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java, core/src/main/java/de/danoeh/antennapod/core/util/FeedItemUtil.java, core/src/test/java/de/danoeh/antennapod/core/util/FeedItemUtilTest.java
Closes #3527. 
I plan to do a bit more review to ensure there is no other codepaths that have similar problems.
=> bugfix: Share Episode URL - handle empty link

app/src/main/java/de/danoeh/antennapod/activity/AudioplayerActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/DownloadedEpisodesListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/CoverFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/res/xml/preferences_user_interface.xml, core/src/main/java/de/danoeh/antennapod/core/feed/util/ImageResourceUtils.java, core/src/main/java/de/danoeh/antennapod/core/feed/util/PlaybackSpeedUtils.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/java/de/danoeh/antennapod/core/service/PlayerWidgetJobService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceNotificationBuilder.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/res/values/strings.xml
The default is to use the episode cover (keep the previous behavior).
Fixes #3070
=> Add an option to replace Episode cover with Podcast cover

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java, build.gradle, config/checkstyle/checkstyle-best-practice.xml, config/checkstyle/checkstyle.xml, core/src/main/java/de/danoeh/antennapod/core/event/DownloaderUpdate.java, core/src/main/java/de/danoeh/antennapod/core/glide/FastBlurTransformation.java, core/src/main/java/de/danoeh/antennapod/core/util/id3reader/ID3Reader.java
- Do not enforce Google checkstlye import order
The IntelliJ/AS default is different, so this would be a problem for most new developers.
Additionally, there definitely are more important things to enforce.
- Enforce rules that we already fulfill
- Enforce MultipleVariableDeclarations checkstyle
- Enforce NoWhitespaceBefore checkstyle
=> Checkstyle change

app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/DownloadLogFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java, core/src/main/java/de/danoeh/antennapod/core/event/DownloadLogEvent.java, core/src/main/java/de/danoeh/antennapod/core/event/PlaybackHistoryEvent.java, core/src/main/java/de/danoeh/antennapod/core/feed/EventDistributor.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
We currently have two ways to broadcast events. Working to retire our own EventDistributor.
=> Migrated some events from EventDistributor to EventBus

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java
Refactor after PR #3528 . Reuse the now common FeedItem sorting logic in batch edit screen.
=> Refactor batch edit - use the common FeedItem sorting logic

gradle/wrapper/gradle-wrapper.properties
=> new gradle version

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/res/layout/onlinefeedview_activity.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java, core/src/main/res/values/styles.xml
User study showed that new users do not get the difference between the actual
feed list and the preview. If the preview is a dialog, this is a lot easier to see.
Additionally, the "dialog" now closes after the subscription succeeded.
=> Style OnlineFeedViewActivity like a dialog

app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
- Allow queue swiping in both directions
- Do not allow swiping on tabbed screens where it interferes with tab switching
=> Modified episode swipe directions

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/java/de/danoeh/antennapod/view/EmptyViewHandler.java, core/src/main/res/values/strings.xml
=> Added empty view to subscription list

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Do not display streaming notification if continuous playback is disabled

core/build.gradle
=> Moved robotium dependency to test flavour

build.gradle, core/build.gradle, core/src/androidTest/java/de/danoeh/antennapod/core/syndication/namespace/atom/AtomTextTest.java, core/src/main/java/de/danoeh/antennapod/core/syndication/namespace/atom/AtomText.java, core/src/main/java/de/danoeh/antennapod/core/util/FileNameGenerator.java
Also, reformatted the touched files according to checkstyle
=> Removed commons text library that was just used 2 times

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/OpmlImportBaseActivity.java, app/src/main/java/de/danoeh/antennapod/activity/StorageErrorActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/DataFolderAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/MobileDownloadHelper.java, app/src/main/java/de/danoeh/antennapod/dialog/ChooseDataFolderDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/ProxyDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/RatingDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/RenameFeedDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java, app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QuickFeedDiscoveryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/NetworkPreferencesFragment.java, app/src/main/res/layout/audio_controls.xml, app/src/main/res/layout/choose_data_folder_dialog.xml, app/src/main/res/layout/choose_data_folder_dialog_entry.xml, app/src/main/res/layout/edit_text_dialog.xml, app/src/main/res/layout/proxy_settings.xml, app/src/main/res/layout/quick_feed_discovery.xml, app/src/main/res/layout/time_dialog.xml, app/src/main/res/layout/videoplayer_activity.xml, app/src/main/res/xml/preferences_autodownload.xml, app/src/main/res/xml/preferences_playback.xml, app/src/main/res/xml/preferences_user_interface.xml, build.gradle
The AlertDialogs from Androidx are material, too. We do not need to add an additional dependency.
=> Removed MaterialDialog dependency

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, app/src/main/res/layout/onlinefeedview_activity.xml, app/src/main/res/layout/onlinefeedview_header.xml, app/src/main/res/layout/quick_feed_discovery.xml, app/src/main/res/layout/quick_feed_discovery_item.xml, core/src/main/res/values-v21/styles.xml, core/src/main/res/values/styles.xml
It's now blue and stays on the top when scrolling
=> Even more prominent subscribe button

app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
Problem was that a float 5.99999 was casted to an int and therefore was 5.
=> Fixed playback speed button

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
=> Fixed info bar ignoring 'time respects playback speed' setting

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/res/layout/feeditem_pager_fragment.xml, core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java
Now using real swipe gestures.
Old / new:
=> Switched from gestures to ViewPager

app/src/main/res/menu/episodes.xml
=> Fix refresh icon sometimes not displayed

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
This mankes it easier to change the default later without affecting existing installs
=> Explicitly set default download/streaming value for existing users

app/src/main/play/listings/en-US/full-description.txt
The description was a huge, badly formatted wall of text.
- Fixed typo reported by translator @meskobalazs
- Removed unnecessary line breaks
- Removed some technical details most users don't understand (paged feeds etc)
=> Updated Google Play description

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java
=> Stop listening to shake events and reset volume if sleep timer is reset

app/src/main/java/de/danoeh/antennapod/PodcastApp.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/activity/VideoplayerActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/CombinedSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ExternalPlayerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FyydSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/PodcastListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/SearchListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/gpodnet/TagListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/MenuItemUtils.java, build.gradle, core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/arrays.xml
Of our 130.000 active installs, currently 100 users still have Android 4.0. I think it is reasonable to bump the minimum API version to 16 (Android 4.1).
=> Bumped minimum API version to 16

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
=> Show update failed badge on parse errors

CONTRIBUTING.md, app/proguard.cfg, app/src/main/assets/licenses.xml, app/src/main/java/de/danoeh/antennapod/dialog/VariableSpeedDialog.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/res/values/strings.xml
The prestissimo plugin was last updated in 2013
=> Removed prestissimo

build.gradle
A specific bug that is fixed that we might also face: https://github.com/google/ExoPlayer/issues/6238
Maybe this even helps with #3574 
AntennaPod now uses 65040 out of 65536 methods. Pretty sure we need to enable multidex soon :(
=> Upgraded ExoPlayer

core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DownloadRequester.java
=> Do not start download service if there is nothing to download

app/src/androidTest/java/de/test/antennapod/storage/DBCleanupTests.java
Cleanup is currently just enabled if autodownload is enabled
=> Fixed db cleanup tests

core/src/main/java/de/danoeh/antennapod/core/service/download/handler/MediaDownloadedHandler.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBWriter.java
=> Mark as seen after download completed

app/src/main/java/de/danoeh/antennapod/menuhandler/FeedItemMenuHandler.java
=> Stop playback when resetting position of currently playing item

core/src/main/java/de/danoeh/antennapod/core/service/download/handler/MediaDownloadedHandler.java
=> Signal unread items update after downloading

core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java
=> Fixed ArrayIndexOutOfBoundsException when updating feeds

app/src/main/java/de/danoeh/antennapod/fragment/ItemPagerFragment.java
I hope this fixes the following crash on Google Play:
```
java.lang.ArrayIndexOutOfBoundsException: 
at de.danoeh.antennapod.fragment.ItemPagerFragment.onCreateView (ItemPagerFragment.java:93)
```
=> Initialize variable directly before using

app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackPreferencesFragment.java
=> Update lists after changing 'prefer streaming' preference

app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
Fixes #3662 
This is my very first contribution so bear with me.
Please let me know if anything needs to be changed in order to have this merged.
=> Add download button to queue batch processing

core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
Fixes https downloads on really old devices (Android 4.4)
Closes #3735
Closes #3672
=> Use Google Trust provider

app/src/main/java/de/danoeh/antennapod/adapter/SearchlistAdapter.java, core/src/main/java/de/danoeh/antennapod/core/feed/SearchResult.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBTasks.java, core/src/main/java/de/danoeh/antennapod/core/storage/FeedSearcher.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/java/de/danoeh/antennapod/core/storage/SearchLocation.java
**All in all, this PR allows to search around 30 times faster!**
- Instead of making 6 database lookups, make a single one with `OR` statements. This reduces the time for searching 25k items from 15 seconds to 5 seconds.
- Limit to 500 search results. This reduces the time from 5 seconds to around .5 seconds.
=> Increased search performance

app/src/androidTest/java/de/test/antennapod/ui/UITestUtils.java, app/src/main/java/de/danoeh/antennapod/dialog/EpisodesApplyActionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/AutoDownloadPreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/FeedMenuHandler.java
Those arrays are just there for the type system. Creating them with a big size
is not necessary and uses unnecessary resources.
=> Do not allocate space for arrays that do not need to be allocated

app/src/androidTest/java/de/test/antennapod/storage/DBReaderTest.java, app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FavoriteEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java, app/src/main/res/layout/all_episodes_fragment.xml, core/src/main/java/de/danoeh/antennapod/core/storage/APDownloadAlgorithm.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
This improves the usability for users with tons of subscriptions who don't mark new episodes as seen
=> Added paged loading to 'new episodes' list

app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java, app/src/main/res/xml/preferences.xml, core/src/main/res/values/strings.xml
fix #3744 by adding summary to main preference screen.  This will let users find the preferences easier.
=> add summary to main settings/preferences screen

core/src/main/java/de/danoeh/antennapod/core/glide/ApOkHttpUrlLoader.java, core/src/main/java/de/danoeh/antennapod/core/service/BasicAuthorizationInterceptor.java, core/src/main/java/de/danoeh/antennapod/core/service/download/AntennapodHttpClient.java, core/src/main/java/de/danoeh/antennapod/core/service/download/HttpDownloader.java
This is a memory leak and can cause crashes on some devices
=> Do not create new httpclient for each download

app/src/main/java/de/danoeh/antennapod/adapter/DownloadStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/PlaybackStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/DownloadStatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackStatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/StatisticsFragment.java, app/src/main/res/layout/statistics_fragment.xml, app/src/main/res/layout/statistics_listitem.xml, app/src/main/res/layout/statistics_listitem_total.xml, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/util/comparator/CompareCompat.java, core/src/main/res/values/strings.xml
Here's what I came up with for this feature. Let me know what you think!
Closes #3484
=> Show storage size of downloaded episodes

app/src/main/java/de/danoeh/antennapod/adapter/DownloadStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/PlaybackStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/view/PieChartView.java, app/src/main/res/layout/statistics_listitem.xml
This way, it's easier to know what podcast matches what part of the chart.
Suggested here: https://github.com/AntennaPod/AntennaPod/pull/3485#issuecomment-541055521
=> Added colorful dots to statistics

app/src/main/java/de/danoeh/antennapod/activity/ImportExportActivity.java
Force full restart to trigger the upgrade methods again.
=> Fixed importing old database models

app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java
fix #3768 double check the item is still in the queue, bugfix or 1.8.0
see https://github.com/AntennaPod/AntennaPod/pull/3769
/cc @ByteHamster
=> Double check the item is still in the queue

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java
=> Make seeking more reliable

app/src/main/java/de/danoeh/antennapod/fragment/SubscriptionFragment.java, app/src/main/res/layout/opml_selection.xml
=> Fix subscription screen not updating

app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java
Users are confused that the slider does not have all speed options anymore
This basically reverts 6a56260
Closes #3758
=> Do not link playback speed settings

app/src/main/java/de/danoeh/antennapod/adapter/AllEpisodesRecycleAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/QueueRecyclerAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/ItemActionButton.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
=> Fix download button when 'prefer streaming' is active

app/src/main/java/de/danoeh/antennapod/preferences/PreferenceUpgrader.java, app/src/main/res/xml/preferences_playback.xml, core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
This makes it easier for users to discover the feature
=> Enable PiP by default

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/res/layout/feeditem_fragment.xml
=> Fixed multi-line buttons

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Do not restart sleep timer when automatically playing next episode

app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java, app/src/main/java/de/danoeh/antennapod/dialog/SleepTimerDialog.java, app/src/main/res/layout/time_dialog.xml, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackServiceTaskManager.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java, core/src/main/res/values/strings.xml
To me, it was quite confusing that the sleep timer dialog has two different layouts. Additionally, as requested on Google Groups, the time is now updated every second.
Before:
After:
=> Updated sleep timer UI

app/src/androidTest/java/de/test/antennapod/util/playback/TimelineTest.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemDescriptionFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/java/de/danoeh/antennapod/view/ShownotesWebView.java, app/src/main/res/layout/feeditem_fragment.xml, core/src/main/java/de/danoeh/antennapod/core/util/playback/Timeline.java, core/src/main/res/values/strings.xml
- Created ShownotesWebView instead of having the same code in multiple locations
- Allow to click timecodes in item fragment, not just on the player screen
=> ShownotesWebView improvements

app/src/main/java/de/danoeh/antennapod/adapter/DownloadStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/PlaybackStatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/adapter/StatisticsListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/DownloadStatisticsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/PlaybackStatisticsFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DBReader.java, core/src/main/java/de/danoeh/antennapod/core/storage/StatisticsItem.java
Removed unused `StatisticsData` wrapper class and extracted `StatisticsItem` to new class
=> Clean up statistics

app/build.gradle, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/view/PagerIndicatorView.java, app/src/main/res/layout/mediaplayerinfo_activity.xml
=> Added Viewpager indicator that shows if chapters are present

app/src/main/java/de/danoeh/antennapod/fragment/FeedSettingsFragment.java, core/src/main/java/de/danoeh/antennapod/core/event/settings/SpeedPresetChangedEvent.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Update speed when changing feed defaults

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, core/src/main/java/de/danoeh/antennapod/core/storage/DatabaseExporter.java, core/src/main/java/de/danoeh/antennapod/core/storage/PodDBAdapter.java, core/src/main/res/values/strings.xml
=> Verify database version before import

app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java
This is the same as 72a8e0f3b622641f9e6e9ff6001f12db87d9c948
but that commit got lost when merging master into develop
=> Fixed not restarting correctly after import

core/src/main/java/de/danoeh/antennapod/core/service/download/handler/MediaDownloadedHandler.java
Fixes media size being unknown even if item is downloaded
=> Set file size after downlaod

core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java
fix #3834
fix #2907
This seems to fix it for this [test scenario](https://github.com/AntennaPod/AntennaPod/issues/3834#issuecomment-583796775), I know @ByteHamster said it's likely another section of code.  I will NOT be offended if you close this PR and fix it elsewhere.  I see how frustrating and endless infinite loop and alerts/notification is.
=> do not infinite download on 410, 400

app/src/main/res/layout/subscription_item.xml
=> Fixed subscription screen overflowing when having 5 columns and broken images

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, app/src/main/res/layout/feeditem_fragment.xml
- Bigger image
- Everything left-aligned
- Reduced line thickness
Before/After:
=> Updated item details page

app/src/main/res/layout/statistics_listitem_total.xml
fix #3872
min and max width of pie chart
=> min and max width of piechart

app/src/main/AndroidManifest.xml
WTF, Google...
https://developer.android.com/guide/webapps/managing-webview#metrics
=> Opt out of WebView metrics collection

app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/NewEpisodesFragment.java
=> Fixed flashing refresh button

app/src/main/java/de/danoeh/antennapod/dialog/PlaybackControlsDialog.java, app/src/main/res/layout/audio_controls.xml
=> Fixed overlapping audio controls

core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java
=> Fixed resuming when episode was streamed

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/CancelDownloadActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DeleteActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/DownloadActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PauseActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/VisitWebsiteActionButton.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
Much more readable to have decision for action and action itself in one place.
=> Refactor action button in ItemFragment

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java, app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java, app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackServiceStarter.java
Easier to see than a notification
Closes #3487
=> Add allow streaming dialog

app/src/main/java/de/danoeh/antennapod/adapter/DownloadlistAdapter.java, core/src/main/res/values/strings.xml
Changed the variable used to display the downloadstring to download pending string. Bonus fix of fixing the misspelled comment word. :)
Closes: #3915
=> Change display of text from Download queued to Download pending

app/src/main/res/menu/downloads_completed.xml, app/src/main/res/menu/feedlist.xml, app/src/main/res/menu/queue.xml, core/src/main/res/values/strings.xml
Changed the string to "Multi Select" and change variable name to better match new meaning. Updated usages to new variable name.
closes: #3909
=> Change batch edit text to Multi select

app/src/main/res/layout/feeditemlist_item.xml
or images with strange aspect ratio
=> Do not display white on white for transparent images

core/src/main/java/de/danoeh/antennapod/core/service/download/handler/FeedParserTask.java
=> Fixed showing feed title in download log

app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/view/PagerIndicatorView.java, app/src/main/res/layout/audio_controls.xml, app/src/main/res/layout/mediaplayerinfo_activity.xml, app/src/main/res/layout/nav_list.xml, core/src/main/res/values/attrs.xml, core/src/main/res/values/colors.xml, core/src/main/res/values/styles.xml
=> Removed ActionBar background on player page

app/src/main/java/de/danoeh/antennapod/adapter/FeedItemlistDescriptionAdapter.java, app/src/main/java/de/danoeh/antennapod/dialog/StreamingConfirmationDialog.java, app/src/main/res/layout/itemdescription_listitem.xml, core/src/main/java/de/danoeh/antennapod/core/util/playback/RemoteMedia.java, core/src/main/res/values/strings.xml, core/src/play/java/de/danoeh/antennapod/core/cast/CastUtils.java, core/src/play/java/de/danoeh/antennapod/core/cast/MediaInfoCreator.java, core/src/play/java/de/danoeh/antennapod/core/feed/FeedMediaFlavorHelper.java, core/src/play/java/de/danoeh/antennapod/core/service/playback/RemotePSMP.java
Draft. Needs a UI before merging. Probably something like long-press -> play without subscribing. I do not think a prominent play button is a good idea here.
Closes #3618
=> Allow to stream episodes from unsubscribed podcast

app/src/androidTest/java/de/test/antennapod/EspressoTestUtils.java, app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java, app/src/androidTest/java/de/test/antennapod/ui/NavigationDrawerTest.java, app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/java/de/danoeh/antennapod/activity/MediaplayerInfoActivity.java, app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java, app/src/main/java/de/danoeh/antennapod/config/DownloadServiceCallbacksImpl.java, app/src/main/java/de/danoeh/antennapod/fragment/NavDrawerFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/preferences/UserInterfacePreferencesFragment.java, app/src/main/java/de/danoeh/antennapod/menuhandler/NavDrawerActivity.java, app/src/main/res/layout/main.xml, app/src/main/res/layout/mediaplayerinfo_activity.xml, app/src/main/res/layout/nav_list.xml
This allows getting MainActivity from 800 lines to 400 lines.
=> Nav list fragment

app/src/main/java/de/danoeh/antennapod/activity/DownloadAuthenticationActivity.java, app/src/main/res/layout/download_authentication_activity.xml
Also, made it look less like Android 4.4
Closes #3870
=> Fixed white on white text

app/src/androidTest/java/de/test/antennapod/service/download/DownloadServiceTest.java, app/src/androidTest/java/de/test/antennapod/util/event/DownloadEventListener.java, app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java, core/src/free/java/de/danoeh/antennapod/core/ClientConfig.java, core/src/main/java/de/danoeh/antennapod/core/service/download/DownloadService.java, core/src/play/java/de/danoeh/antennapod/core/ClientConfig.java
This makes starting the app around 1.2 seconds faster
=> Install ssl provider asynchronously

app/src/main/java/de/danoeh/antennapod/adapter/EpisodeItemListAdapter.java, app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/EpisodesListFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/FeedItemlistFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/PlaybackHistoryFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/QueueFragment.java, app/src/main/java/de/danoeh/antennapod/fragment/SearchFragment.java
- Fixed header not updating
- Fixed items flickering during download
=> Feedinfo page improvements

core/src/main/java/de/danoeh/antennapod/core/service/playback/ExoPlayerWrapper.java, core/src/main/java/de/danoeh/antennapod/core/service/playback/LocalPSMP.java, core/src/main/java/de/danoeh/antennapod/core/util/playback/PlaybackController.java
=> Show buffering indicator on ExoPlayer

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java, app/src/main/res/layout/audioplayer_fragment.xml, app/src/main/res/layout/external_player_fragment.xml
=> Fixed description overlapping mini player

.circleci/config.yml, config/checkstyle/checkstyle-new-code.xml
=> Added diff-checkstyle

app/src/main/java/de/danoeh/antennapod/dialog/EpisodeFilterDialog.java, app/src/main/res/layout/episode_filter_dialog.xml
fix #3977, just don't use custom background
=> use default colors for button background

app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/PlayActionButton.java, app/src/main/java/de/danoeh/antennapod/adapter/actionbutton/StreamActionButton.java
This makes it easier to discover the difference between audio and video ;)
=> Open video player when playing video

app/src/main/AndroidManifest.xml
hide the keyboard to start
Fixes #3364
=> soft keyboard

app/src/main/AndroidManifest.xml, app/src/main/java/de/danoeh/antennapod/fragment/preferences/ImportExportPreferencesFragment.java, core/src/main/res/values/strings.xml
=> show a warning dialog when importing a database

app/src/main/res/menu/queue.xml, core/src/main/res/values/strings.xml
=> easy to read sorting options

app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
=> Fixed 'Open podcast' menu item in media player

app/src/main/java/de/danoeh/antennapod/activity/OnlineFeedViewActivity.java
=> Fixed error dialog not closing activity sometimes

app/src/main/java/de/danoeh/antennapod/fragment/ItemFragment.java
=> Fix crash when clicking timecode

app/src/main/java/de/danoeh/antennapod/CrashReportWriter.java
Seems to be posted to GitHub a lot. So give it a better formatting :)
=> Write crash info in Markdown
